[[priv-cfi]]
== 控制流完整性 (CFI)

控制流完整性 (CFI) 功能有助于防御面向返回编程 (ROP) 和调用/跳转面向编程 (COP/JOP) 风格的控制流颠覆攻击。Zicfiss 和 Zicfilp 扩展分别提供后向边和前向边控制流完整性。有关这些 CFI 功能和相关的非特权 ISA 的更多详细信息，请参阅非特权 ISA 规范的控制流完整性章节。

[[priv-forward]]
=== 着陆垫 (Zicfilp)

本节指定了 Zicfilp 扩展的特权 ISA。

[[FCFIACT]]
==== 着陆垫启用 (LPE) 状态

术语 `xLPE` 用于确定 Zicfilp 扩展提供的使用着陆垫的前向边 CFI 是否在特权模式下启用。

当实现 S 模式时，确定如下：

.S 模式实现时 `xLPE` 的确定
[width=100%]
[%header, cols="^4,^12"]
|===
|特权模式| xLPE
|  M           | `mseccfg.MLPE`
|  S 或 HS     | `menvcfg.LPE`
|  VS          | `henvcfg.LPE`
|  U 或 VU     | `senvcfg.LPE`
|===

当未实现 S 模式时，确定如下：

.S 模式未实现时 `xLPE` 的确定
[width=100%]
[%header, cols="^4,^12"]
|===
|特权模式| xLPE
|  M           | `mseccfg.MLPE`
|  U           | `menvcfg.LPE`
|===

[NOTE]
====
Zicfilp 必须在每个特权模式下显式启用才能使用。

使用 `LPAD` 指令编译的程序在未实现或未启用 Zicfilp 扩展时，仍能正常运行，但没有前向边 CFI 保护。
====

<<<

[[ZICFILP_FORWARD_TRAPS]]
==== 陷阱时保留预期着陆垫状态

`JALR`/`C.JALR`/`C.JR` 完成后，但在间接调用/跳转目标处的指令解码之前，可能需要将陷阱传递到相同或更高特权模式，原因如下：

* 异步中断。
* 优先级高于软件检查异常的同步异常，其中 `__x__tval` 设置为"着陆垫故障 (code=2)"（参见特权规范的 <<exception-priority>>）。

Zicfilp 引起的软件检查异常优先级高于非法指令异常，但低于指令访问故障。

由于指令不是 `LPAD` 指令（当 `ELP` 为 `LP_EXPECTED` 时）或 `LPAD` 指令本身引起的软件检查异常（参见 <<LP_INST>>）会导致陷阱传递到相同或更高特权模式。

在这种情况下，陷阱之前的 `ELP`（即先前的 `ELP`）必须通过陷阱传递保留，以便在从陷阱返回时可以恢复。为了在陷阱传递到 M 模式时存储先前的 `ELP` 状态，`mstatus` CSR 中提供了 `MPELP` 位。为了在陷阱传递到 S/HS 模式时存储先前的 `ELP` 状态，`mstatus` CSR 中提供了 `SPELP` 位。`mstatus` 中的 `SPELP` 位可以通过 `sstatus` CSR 访问。为了在陷阱传递到 VS 模式时存储先前的 `ELP` 状态，`vsstatus`（`sstatus` 的 VS 模式版本）中定义了 `SPELP` 位。为了在转换为调试模式时存储先前的 `ELP` 状态，`dcsr` 寄存器中定义了 `pelp` 位。

当陷阱进入特权模式 `x` 时，`__x__PELP` 设置为 `ELP`，`ELP` 设置为 `NO_LP_EXPECTED`。

`MRET` 或 `SRET` 指令分别用于从 M 模式或 S 模式的陷阱返回。执行 `__x__RET` 指令时，如果新特权模式是 `y`，则如果 `__y__LPE`（参见 <<FCFIACT>>）为 1，则 `ELP` 设置为 `__x__PELP` 的值；否则，它设置为 `NO_LP_EXPECTED`；`__x__PELP` 设置为 `NO_LP_EXPECTED`。

进入调试模式后，`dcsr` 中的 `pelp` 位会更新为 hart 先前所处特权级别的 `ELP`，并且 `ELP` 设置为 `NO_LP_EXPECTED`。当 hart 从调试模式恢复时，如果新特权模式是 `y`，则如果 `__y__LPE`（参见 <<FCFIACT>>）为 1，则 `ELP` 设置为 `pelp` 的值；否则，它设置为 `NO_LP_EXPECTED`。

另请参阅 <<rnmi>>，了解实现此扩展时添加到 RNMI 陷阱和 MNRET 指令的语义。

[NOTE]
====
特权模式 `x` 中的陷阱处理程序在执行间接调用/跳转之前，如果 `xLPE=1`，则必须保存 `__x__PELP` 位和 `x7` 寄存器。如果特权模式 `x` 可以响应中断且 `xLPE=1`，则陷阱处理程序在启用中断之前也应保存这些值。

特权模式 `x` 中的陷阱处理程序在执行 `__x__RET` 指令从陷阱返回之前，必须恢复保存的 `__x__PELP` 位和 `x7` 寄存器。
====

<<<

[[priv-backward]]
=== 影子栈 (Zicfiss)

本节指定了 Zicfiss 扩展的特权 ISA。

==== 影子栈指针 (`ssp`) CSR 访问控制

访问 `ssp` CSR 可能会导致非法指令异常或虚拟指令异常，具体取决于 *__x__*`envcfg.SSE` 字段的状态。条件如下：

* 如果特权模式低于 M 且 `menvcfg.SSE` 为 0，则引发非法指令异常。
* 否则，如果在 U 模式下且 `senvcfg.SSE` 为 0，则引发非法指令异常。
* 否则，如果在 VS 模式下且 `henvcfg.SSE` 为 0，则引发虚拟指令异常。
* 否则，如果在 VU 模式下且 `henvcfg.SSE` 或 `senvcfg.SSE` 为 0，则引发虚拟指令异常。
* 否则，允许访问。

==== 影子栈启用 (SSE) 状态

术语 `xSSE` 用于确定 Zicfiss 扩展提供的使用影子栈的后向边 CFI 是否在特权模式下启用。

当实现 S 模式时，确定如下：

.S 模式实现时 `xSSE` 的确定
[width=100%]
[%header, cols="^4,^12"]
|===
|特权模式| `xSSE`
|  M           | `0`
|  S 或 HS     | `menvcfg.SSE`
|  VS          | `henvcfg.SSE`
|  U 或 VU     | `senvcfg.SSE`
|===

当未实现 S 模式时，M 和 U 特权模式下的 `xSSE` 均为 0。

[NOTE]
====
在 U 模式下激活 Zicfiss 必须针对每个进程显式完成。当应用程序未编译 Zicfiss 且未在 U 模式下激活 Zicfiss 时，它允许调用可能包含 Zicfiss 指令的共享库。在这种情况下，共享库中的 Zicfiss 指令将恢复其 Zimop/Zcmop 定义的行为。

当在 S 模式下启用 Zicfiss 时，使用未编译 Zicfiss 指令的操作系统是无害的。此类不使用后向边 CFI 进行 S 模式执行的操作系统仍可以为 U 模式应用程序激活 Zicfiss。

当使用 Zicfiss 指令的程序安装在支持 Zicfiss 扩展但未在程序执行的特权模式下启用该扩展的处理器上时，程序仍能正常运行，但没有后向边 CFI 保护，因为 Zicfiss 指令将恢复其 Zimop/Zcmop 定义的行为。

当使用 Zicfiss 指令的程序安装在不支持 Zicfiss 扩展但支持 Zimop 和 Zcmop 扩展的处理器上时，程序仍能正常运行，但没有后向边 CFI 保护，因为 Zicfiss 指令将恢复其 Zimop/Zcmop 定义的行为。

在不支持 Zimop/Zcmop 扩展的处理器上，所有 Zimop/Zcmop 代码点（包括用于 Zicfiss 指令的代码点）都可能导致非法指令异常。不支持在此类机器上执行使用这些指令的程序。

目前不支持在 M 模式下激活 Zicfiss。此外，当未实现 S 模式时，也不支持在 U 模式下激活。这些功能可能会在未来的标准扩展中引入。
====

NOTE: `xSSE` 的更改立即生效；地址转换缓存无需与 SFENCE.VMA、HFENCE.GVMA 或 HFENCE.VVMA 指令同步。


[[SSMP]]
==== 影子栈内存保护

为了保护影子栈内存，在单阶段和 VS 阶段页表中，内存与一种新的页面类型——影子栈 (SS) 页面——相关联。编码 `R=0`、`W=1` 和 `X=0` 被定义为表示 SS 页面。当 `menvcfg.SSE=0` 时，此编码保持保留。同样，当 `V=1` 且 `henvcfg.SSE=0` 时，此编码在 `VS` 和 `VU` 级别保持保留。

如果 `satp.MODE`（或当 `V=1` 时的 `vsatp.MODE`）设置为 `Bare` 且有效特权模式低于 M，则禁止影子栈内存访问，并且影子栈指令将引发存储/AMO 访问故障异常。当有效特权模式为 M 时，`SSAMOSWAP.W/D` 指令的任何内存访问都将导致存储/AMO 访问故障异常。

映射为 SS 页面的内存不能被 `SSAMOSWAP.W/D`、`SSPUSH` 和 `C.SSPUSH` 以外的指令写入。尝试写入将引发存储/AMO 访问故障异常。使用 _缓存块操作_ (`CBO.*`) 指令访问 SS 页面是不允许的。此类访问将引发存储/AMO 访问故障异常。隐式访问，包括对 SS 页面的指令获取，是不允许的。此类访问将引发适合访问类型的访问故障异常。然而，影子栈可由所有仅从内存加载的指令读取。

[NOTE]
====
除 `SSAMOSWAP`、`SSPUSH` 和 `C.SSPUSH` 以外的指令对影子栈页面的存储将触发存储/AMO 访问故障异常，而不是存储/AMO 页故障异常，表示致命错误。存储/AMO 页故障表明操作系统可以处理和纠正故障，这在这种情况下是不可行的。因此，页故障处理程序必须解码故障指令的操作码，以辨别故障是由非影子栈指令写入 SS 页面（致命条件）还是由影子栈指令写入非驻留页面（可恢复条件）引起的。操作系统页故障处理程序的性能关键性质要求触发访问故障而不是页故障，从而允许明确区分致命条件和可恢复故障。

操作系统必须确保不存在可写、非影子栈别名虚拟地址映射，用于支持影子栈的物理内存。此外，在地址未对齐异常取代访问故障异常的系统中，模拟未对齐存储的处理程序必须设计为在存储指向影子栈页面时引发访问故障异常。

所有执行加载操作的指令都允许从影子栈读取。此功能通过允许检查影子栈中备份的链接寄存器值来促进调试和性能分析。
====

[NOTE]
====
截至本规范起草时，指令获取是唯一一种受单阶段或 VS 阶段地址转换影响的隐式访问类型。
====

如果影子栈 (SS) 指令引发访问故障、页故障或客户机页故障异常，该异常旨在指示原始指令类型（加载或存储/AMO），则报告的异常原因分别是存储/AMO 访问故障（代码 7）、存储/AMO 页故障（代码 15）或存储/AMO 客户机页故障（代码 23）。对于影子栈指令，报告的指令类型始终如同它是存储或 AMO，即使对于仅从内存读取而不写入内存的指令 `SSPOPCHK` 和 `C.SSPOPCHK` 也是如此。

[NOTE]
====
当实现 Zicfiss 时，现有的"存储/AMO"异常可以被认为是"存储/AMO/SS"异常，表示陷阱指令是存储、AMO 或影子栈指令。
====

影子栈指令仅限于访问影子栈 (`pte.xwr=010b`) 页面。如果影子栈指令访问的页面未指定为影子栈页面且未标记为只读 (`pte.xwr=001`)，则将调用存储/AMO 访问故障异常。相反，如果影子栈指令访问的页面是只读页面，则将触发存储/AMO 页故障异常。


[NOTE]
====
影子栈加载和存储将触发存储/AMO 页故障，如果访问的页面是只读的，以支持影子栈页面的写时复制 (COW)。如果页面已标记为只读以进行 COW 跟踪，则页故障处理程序通过创建页面副本并更新 `pte.xwr` 为 `010b` 来响应，从而将每个副本指定为影子栈页面。相反，如果访问目标是真正的只读页面，则报告为存储/AMO 页故障的故障会向操作系统发出信号，表明该故障是致命且不可恢复的。报告故障为存储/AMO 页故障，即使对于 `SSPOPCHK` 启动的内存访问，也有助于确定致命性；如果这些报告为加载页故障，则对真正只读页面的访问可能会被错误地视为可恢复故障，导致故障指令无限期重试。PTE 不提供只读影子栈编码。

影子栈指令尝试访问标记为读写、读写执行、读执行或只执行的页面会导致存储/AMO 访问故障异常，同样表示致命条件。

影子栈应在两端由保护页边界，以防止一个影子栈意外下溢或溢出到另一个影子栈。通常，栈的保护页是进程无法访问的页面，该进程拥有该栈。
====

<<<

如果 `ssp` 中的虚拟地址未对齐 `XLEN`，则 `SSPUSH`/`C.SSPUSH`/`SSPOPCHK`/`C.SSPOPCHK` 指令会导致存储/AMO 访问故障异常。

[NOTE]
====
不需要对影子栈进行未对齐访问，强制对齐更安全，可以检测程序中的错误。在这种情况下，会引发访问故障异常而不是地址未对齐异常，以指示致命性，并且指令不得由陷阱处理程序模拟。
====

访问内存的影子栈指令的正确执行要求访问的内存是幂等的。如果 `SSPUSH`/`C.SSPUSH`/`SSPOPCHK`/`C.SSPOPCHK`/`SSAMOSWAP.W/D` 指令引用的内存不是幂等的，则指令会导致存储/AMO 访问故障异常。

[NOTE]
====
`SSPOPCHK` 指令执行加载，然后检查加载的数据值与链接寄存器作为源。如果与链接寄存器的检查失败，并且指令被陷阱处理程序重新启动，则指令将再次执行加载。如果执行加载的内存不是幂等的，则第二次加载可能会导致意外的副作用。访问影子栈的影子栈指令要求 `ssp` 引用的内存是幂等的，以避免此类问题。将影子栈放置在非幂等内存中，例如非幂等设备内存中，不是预期的用法，并且要求引用的内存是幂等的不会造成重大限制。
====

`U` 和 `SUM` 位强制执行正常进行，用于影子栈指令启动的内存访问。`MXR` 位的状态不影响对影子栈页面的读取访问，因为影子栈页面始终可由所有从内存加载的指令读取。

G 阶段地址转换和保护不受 Zicfiss 扩展的影响。G 阶段 PTE 中的 `xwr == 010b` 编码保持保留。当 G 阶段页表处于活动状态时，访问内存的影子栈指令要求 G 阶段页表对访问的内存具有读写权限；否则会引发存储/AMO 客户机页故障异常。

[NOTE]
====
未来的扩展可能会在 G 阶段页表中定义影子栈编码，以支持诸如管理程序为其客户机强制执行影子栈保护之类的用例。
====

Svpbmt 和 Svnapot 扩展支持影子栈页面。

PMA 检查已扩展，要求影子栈指令引用的内存是幂等的。PMP 检查已扩展，要求影子栈指令访问的内存具有读写权限。如果 PMP 不提供读写权限或访问的内存不是幂等的，则会引发存储/AMO 访问故障异常。

`SSAMOSWAP.W/D` 指令要求访问的内存范围的 PMA 提供 AMOSwap 级别支持。