[[atomics]]
== "A" 扩展：原子指令, 2.1 版本

原子指令扩展，名为 "A"，包含一系列原子性地“读-改-写”内存的指令，用于支持在同一内存空间中运行的多个 RISC-V hart 之间的同步。它提供了两种形式的原子指令：预留加载/条件存储（load-reserved/store-conditional）指令和原子性“读取并操作”（fetch-and-op）内存指令。这两种原子指令都支持多种内存一致性顺序，包括无序（unordered）、获取（acquire）、释放（release）和顺序一致（sequentially consistent）语义。这些指令使 RISC-V 能够支持 RCsc 内存一致性模型。 cite:[Gharachorloo90memoryconsistency]

[NOTE]
====
经过大量辩论，语言社区和架构社区似乎最终将释放一致性（release consistency）确定为标准的内存一致性模型，因此 RISC-V 的原子指令支持也是围绕此模型构建的。
====

A 扩展包含由 Zaamo 和 Zalrsc 扩展提供的指令。

=== 指定原子指令的顺序

基本的 RISC-V ISA 采用宽松的内存模型，使用 FENCE 指令来施加额外的顺序约束。执行环境将地址空间划分为内存域和 I/O 域，FENCE 指令提供了对这两个地址域之一或两者的访问进行排序的选项。

为了更有效地支持释放一致性 cite:[Gharachorloo90memoryconsistency]，每条原子指令都有两个位：_aq_ 和 _rl_，用于指定从其他 RISC-V hart 观察到的额外内存排序约束。这些位对原子指令正在访问的地址域（内存或 I/O）的访问进行排序。对于另一个域的访问，则没有隐含的排序约束，应使用 FENCE 指令来跨两个域进行排序。

如果 _aq_ 和 _rl_ 位都为 0，则不会对原子内存操作施加额外的排序约束。如果只设置了 _aq_ 位，该原子内存操作被视为一个 _acquire_ 访问，即在该 RISC-V hart 上，任何后续的内存操作都不能被观察到发生在该 acquire 内存操作之前。如果只设置了 _rl_ 位，该原子内存操作被视为一个 _release_ 访问，即该 release 内存操作不能被观察到发生在该 RISC-V hart 上任何先前的内存操作之前。如果 _aq_ 和 _rl_ 位都被设置，该原子内存操作是 _顺序一致的_，不能被观察到发生在同一 RISC-V hart 上、同一地址域内的任何先前内存操作之前或任何后续内存操作之后。

[[sec:lrsc]]
=== "Zalrsc" 扩展：预留加载/条件存储指令

include::images/wavedrom/load-reserve-st-conditional.edn[]

对单个内存字或双字的复杂原子内存操作是通过预留加载（LR）和条件存储（SC）指令完成的。LR.W 从 _rs1_ 中的地址加载一个字，将符号扩展后的值放入 _rd_，并注册一个 _预留集_——一个包含被寻址字中所有字节的字节集合。SC.W 有条件地将 _rs2_ 中的一个字写入 _rs1_ 中的地址：只有当预留仍然有效且预留集包含正在写入的字节时，SC.W 才会成功。如果 SC.W 成功，指令将 _rs2_ 中的字写入内存，并将 0 写入 _rd_。如果 SC.W 失败，指令不写入内存，并将一个非零值写入 _rd_。
任何 SC.W 指令都不能在未通过内存权限检查的情况下退役（retire），但在失败的 SC.W 上是否会发生隐式地址转换和保护内存访问的任何副作用（例如设置页表项的 D 位）是未指定的（UNSPECIFIED）。
出于内存保护的目的，失败的 SC.W 可以被视为一次存储操作。
无论成功与否，执行 SC.W 指令都会使该 hart 持有的任何预留失效。LR.D 和 SC.D 对双字进行类似的操作，仅在 RV64 上可用。对于 RV64，LR.W 和 SC.W 会对放入 _rd_ 的值进行符号扩展。

[NOTE]
====
比较并交换（CAS）和 LR/SC 都可以用来构建无锁数据结构。经过广泛讨论，我们选择了 LR/SC，原因有几点：1）CAS 存在 ABA 问题，而 LR/SC 避免了这个问题，因为它监视对该地址的所有写入，而不仅仅是检查数据值的变化；2）CAS 还需要一种新的整数指令格式来支持三个源操作数（地址、比较值、交换值），以及一种不同的内存系统消息格式，这会使微架构复杂化；3）此外，为了避免 ABA 问题，其他系统提供了双宽 CAS（DW-CAS），允许在测试和递增计数器的同时处理一个数据字。这需要在一个指令中读取五个寄存器并写入两个，还需要一种新的更大的内存系统消息类型，进一步使实现复杂化；4）LR/SC 提供了许多原语的更高效实现，因为它只需要一次加载，而 CAS 需要两次（在 CAS 指令前一次加载以获取用于推测计算的值，然后在 CAS 指令中第二次加载以在更新前检查值是否未变）。

LR/SC 相对于 CAS 的主要缺点是活锁（livelock），我们在某些情况下通过下面描述的架构保证最终前进的机制来避免。另一个担忧是当前 x86 架构（及其 DW-CAS）的影响是否会使同步库和其他假定 DW-CAS 是基本机器原语的软件的移植复杂化。一个可能的缓解因素是 x86 最近增加了事务性内存指令，这可能导致人们不再使用 DW-CAS。

更普遍地说，多字原子原语是可取的，但关于它应该采取何种形式仍有相当大的争议，并且保证前进性会增加系统的复杂性。
====

值为 1 的失败代码表示一个未指明的失败。其他失败代码目前保留。可移植的软件应该只假设失败代码为非零。

[NOTE]
====
我们保留失败代码 1 表示“未指明”，这样简单的实现可以使用为 SLT/SLTU 指令所需的现有复用器返回此值。更具体的失败代码可能会在未来的 ISA 版本或扩展中定义。
====

对于 LR 和 SC，Zalrsc 扩展要求 _rs1_ 中保存的地址必须与操作数的大小自然对齐（即，双字为八字节对齐，字为四字节对齐）。如果地址未自然对齐，将生成地址未对齐异常或访问故障异常。如果未对齐的访问本可以完成，但不应被模拟，则可以为该内存访问生成访问故障异常。
[NOTE]
====
在大多数系统中，模拟未对齐的 LR/SC 序列是不切实际的。

未对齐的 LR/SC 序列还可能导致同时访问多个预留集，目前的定义没有为此提供规定。
====

一个实现可以在每次 LR 时注册一个任意大的预留集，只要该预留集包含了被寻址数据字或双字的所有字节。一个 SC 只能与程序顺序中最近的 LR 配对。只有当在 LR 和 SC 之间没有观察到来自另一个 hart 对预留集的存储，并且在程序顺序中 LR 和它本身之间没有其他 SC 时，SC 才可能成功。只有当在 LR 和 SC 之间没有观察到来自 hart 以外的设备对 LR 指令访问的字节的写入时，SC 才可能成功。请注意，这个 LR 可能有不同的有效地址和数据大小，但将 SC 的地址作为预留集的一部分进行了预留。

[NOTE]
====
遵循此模型，在具有内存转换的系统中，如果较早的 LR 使用具有不同虚拟地址的别名预留了相同的位置，则允许 SC 成功，但如果虚拟地址不同，也允许其失败。

为了兼容旧式设备和总线，只有当来自 RISC-V hart 以外的设备的写入与 LR 访问的字节重叠时，才需要使预留失效。当这些写入访问预留集中的其他字节时，则不需要使预留失效。
====

如果地址不在程序顺序中最近的 LR 的预留集内，SC 必须失败。如果在 LR 和 SC 之间可以观察到来自另一个 hart 对预留集的存储，SC 必须失败。如果在 LR 和 SC 之间可以观察到来自某个其他设备对 LR 访问的字节的写入，SC 必须失败。（如果这样的设备写入了预留集但没有写入 LR 访问的字节，SC 可能失败也可能不失败。）如果在程序顺序中 LR 和 SC 之间有另一个 SC（到任何地址），SC 必须失败。成功的 LR/SC 序列的原子性要求的精确陈述由 <<rvwmo>> 中的原子性公理定义。

[NOTE]
====
平台应提供一种方法来确定预留集的大小和形状。

平台规范可以限制预留集的大小和形状。

应使用对内存暂存字的条件存储指令来强制使任何现有的加载预留失效：

* 在抢占式上下文切换期间，以及
* 在必要时更改虚拟到物理地址映射时，例如在迁移可能包含活动预留的页面时。

当 hart 执行 LR 或 SC 时其预留失效，这意味着一个 hart 一次只能持有一个预留，并且一个 SC 只能与程序顺序中最近的 LR 配对，而 LR 只能与紧随其后的 SC 配对。这是对 <<rvwmo>> 中原子性公理的一个限制，以确保软件在按此方式操作的常见预期实现上正确运行。
====

一个 SC 指令永远不能被另一个 RISC-V hart 在建立预留的 LR 指令之前观察到。

[NOTE]
====
通过在 LR 指令上设置 _aq_ 位，可以为 LR/SC 序列赋予 acquire 语义。通过在 SC 指令上设置 _rl_ 位，可以为 LR/SC 序列赋予 release 语义。假设对其他原子操作有适当的映射，在 LR 指令上设置 _aq_ 位，并在 SC 指令上设置 _rl_ 位，可以使 LR/SC 序列在 C++ `memory_order_seq_cst` 意义上是顺序一致的。这样的序列不会充当对序列之前和之后的普通加载和存储指令进行排序的栅栏（fence）。对其他 C++ 原子操作的特定指令映射，或更强的“顺序一致性”概念，可能要求在 LR 或 SC 指令之一或两者上都设置这两个位。

如果在 LR 或 SC 上都没有设置任何位，则可以观察到 LR/SC 序列发生在来自同一 RISC-V hart 的周围内存操作之前或之后。当 LR/SC 序列用于实现并行归约操作时，这可能是合适的。
====

软件不应在 LR 指令上设置 _rl_ 位，除非 _aq_ 位也被设置；软件也不应在 SC 指令上设置 _aq_ 位，除非 _rl_ 位也被设置。不保证 LR._rl_ 和 SC._aq_ 指令提供比两个位都清除时更强的排序，但可能会导致性能下降。

[NOTE]
====
[[cas]]
[source,asm]
.使用 LR/SC 实现比较并交换功能的示例代码。
        # a0 保存内存位置的地址
        # a1 保存期望值
        # a2 保存期望写入的值
        # a0 保存返回值，如果成功则为 0，否则为非 0
    cas:
        lr.w t0, (a0)        # 加载原始值。
        bne t0, a1, fail     # 不匹配，则失败。
        sc.w t0, a2, (a0)    # 尝试更新。
        bnez t0, cas         # 如果条件存储失败，则重试。
        li a0, 0             # 设置返回值为成功。
        jr ra                # 返回。
    fail:
        li a0, 1             # 设置返回值为失败。
        jr ra                # 返回。

LR/SC 可用于构建无锁数据结构。<<cas>> 中显示了使用 LR/SC 实现比较并交换功能的示例。如果内联，比较并交换功能仅需四条指令。
====

[[sec:lrscseq]]
=== 条件存储指令的最终成功性

Zalrsc 扩展定义了 _受限 LR/SC 循环_，具有以下属性：

* 循环仅包含一个 LR/SC 序列和在失败时重试该序列的代码，并且必须包含最多 16 条连续存放在内存中的指令。
* LR/SC 序列以 LR 指令开始，以 SC 指令结束。在 LR 和 SC 指令之间执行的动态代码只能包含来自基本“I”指令集的指令，不包括加载、存储、后向跳转、采用的后向分支、JALR、FENCE 和 SYSTEM 指令。
也允许使用 Zca 和 Zcb 扩展中上述“I”指令的压缩形式。
* 重试失败的 LR/SC 序列的代码可以包含后向跳转和/或分支以重复 LR/SC 序列，但其他方面与 LR 和 SC 之间的代码具有相同的约束。
* LR 和 SC 地址必须位于具有 _LR/SC 最终性_ 属性的内存区域内。执行环境负责传达哪些区域具有此属性。
* SC 必须指向与同一 hart 执行的最新 LR 相同的有效地址，并且具有相同的数据大小。

不属于受限 LR/SC 循环的 LR/SC 序列是 _不受限的_。不受限的 LR/SC 序列在某些实现上可能会在某些尝试中成功，但在其他实现上可能永远不会成功。

[NOTE]
====
我们将 LR/SC 循环的长度限制在基本 ISA 中 64 个连续指令字节内，以避免对指令缓存和 TLB 大小及关联性造成不当限制。同样，我们不允许在循环内进行其他加载和存储，以避免在简单实现中对数据缓存关联性的限制，这些实现在私有缓存中跟踪预留。对分支和跳转的限制限制了可以在序列中花费的时间。不允许浮点运算和整数乘法/除法，以简化操作系统在缺乏适当硬件支持的实现上对这些指令的模拟。

不禁止软件使用不受限的 LR/SC 序列，但可移植软件必须检测序列重复失败的情况，然后回退到不依赖于不受限 LR/SC 序列的备用代码序列。允许实现无条件地使任何不受限的 LR/SC 序列失败。
====

如果一个 hart _H_ 进入一个受限 LR/SC 循环，执行环境必须保证以下事件之一最终会发生：

* _H_ 或某个其他 hart 对 _H_ 的受限 LR/SC 循环中的 LR 指令的预留集执行了成功的 SC。
* 某个其他 hart 对 _H_ 的受限 LR/SC 循环中的 LR 指令的预留集执行了无条件存储或 AMO 指令，或者系统中的某个其他设备写入了该预留集。
* _H_ 执行了一个退出受限 LR/SC 循环的分支或跳转。
* _H_ 发生陷阱。

[NOTE]
====
请注意，这些定义允许实现偶尔因任何原因使 SC 指令失败，只要不违反上述保证即可。

作为最终性保证的结果，如果执行环境中的某些 hart 正在执行受限 LR/SC 循环，并且执行环境中的没有其他 hart 或设备对该预留集执行无条件存储或 AMO，那么至少有一个 hart 最终会退出其受限 LR/SC 循环。相比之下，如果其他 hart 或设备继续写入该预留集，则不保证任何 hart 会退出其 LR/SC 循环。

加载和预留加载指令本身不会阻碍其他 hart 的 LR/SC 序列的进展。我们注意到此约束意味着，除其他外，由其他 hart（可能在同一核心内）执行的加载和预留加载指令不能无限期地阻碍 LR/SC 的进展。例如，由共享缓存的另一个 hart 引起的缓存驱逐不能无限期地阻碍 LR/SC 的进展。通常，这意味着预留的跟踪与任何共享缓存的驱逐无关。同样，由 hart 内的推测执行引起的缓存未命中不能无限期地阻碍 LR/SC 的进展。

这些定义承认 SC 指令可能由于实现原因而虚假失败的可能性，只要最终取得进展即可。

CAS 的一个优点是它保证某个 hart 最终会取得进展，而 LR/SC 原子序列在某些系统上可能会无限期地活锁。为了避免这个问题，我们为某些 LR/SC 序列添加了架构上的无活锁保证。

本规范的早期版本强加了更强的无饥饿保证。然而，较弱的无活锁保证足以实现 C11 和 C++11 语言，并且在某些微架构风格中提供起来要容易得多。
====

[[sec:amo]]
=== "Zaamo" 扩展：原子内存操作

include::images/wavedrom/atomic-mem.edn[]

原子内存操作（AMO）指令执行“读-改-写”操作，用于多处理器同步，并使用 R 型指令格式编码。这些 AMO 指令原子性地从 _rs1_ 中的地址加载一个数据值，将该值放入寄存器 _rd_，将一个二元运算符应用于加载的值和 _rs2_ 中的原始值，然后将结果存回 _rs1_ 中的原始地址。AMO 可以操作内存中的 _双字_（仅限 RV64）或 _字_。对于 RV64，32 位 AMO 总是对放入 _rd_ 的值进行符号扩展，并忽略 _rs2_ 原始值的高 32 位。

对于 AMO，Zaamo 扩展要求 _rs1_ 中保存的地址必须与操作数的大小自然对齐（即，双字为八字节对齐，字为四字节对齐）。如果地址未自然对齐，将生成地址未对齐异常或访问故障异常。如果未对齐的访问本可以完成，但不应被模拟，则可以为该内存访问生成访问故障异常。

本手册第二卷中定义的未对齐原子性粒度 PMA，可选地放宽了此对齐要求。
如果存在，未对齐原子性粒度 PMA 指定了未对齐原子性粒度的大小，即 2 的幂次方的字节数。
未对齐原子性粒度 PMA 仅适用于 AMO、基本 ISA 中定义的加载和存储，以及 F、D 和 Q 扩展中定义的不超过 XLEN 位的加载和存储。
对于该集合中的指令，如果所有访问的字节都位于同一个未对齐原子性粒度内，则该指令不会因地址对齐原因而引发异常，并且就 RVWMO 而言，该指令只会产生一次内存操作——即，它将原子地执行。

支持的操作包括交换、整数加法、按位与、按位或、按位异或，以及有符号和无符号整数的最大值和最小值。
在没有排序约束的情况下，这些 AMO 可用于实现并行归约操作，其中返回值通常通过写入 `x0` 来丢弃。

[NOTE]
====
我们提供了“读取并操作”风格的原子原语，因为它们比 LR/SC 或 CAS 更能扩展到高度并行的系统。简单的微架构可以使用 LR/SC 原语实现 AMO，只要该实现能保证 AMO 最终完成。更复杂的实现也可能在内存控制器上实现 AMO，并且可以在目标是 `x0` 时优化掉获取原始值的操作。

选择 AMO 的集合是为了有效地支持 C11/C++11 的原子内存操作，并支持内存中的并行归约。AMO 的另一个用途是为内存映射的设备寄存器（例如，设置、清除或切换位）在 I/O 空间中提供原子更新。

Zaamo 扩展使微控制器级别的实现能够利用 A 扩展的 AMO 子集中的原子原语。通常，此类实现没有缓存，因此可能无法自然支持 Zalrsc 扩展提供的 LR/SC 指令。
====

为了帮助实现多处理器同步，AMO 可选地提供释放一致性语义。如果设置了 _aq_ 位，则该 RISC-V hart 中任何后续的内存操作都不能被观察到在 AMO 之前发生。相反，如果设置了 _rl_ 位，则其他 RISC-V hart 不会在该 RISC-V hart 中先于 AMO 的内存访问之前观察到 AMO。在 AMO 上同时设置 _aq_ 和 _rl_ 位会使序列顺序一致，这意味着它不能与来自同一 hart 的早期或晚期内存操作重新排序。

[NOTE]
====
AMO 旨在高效地实现 C11 和 C++11 内存模型。虽然 FENCE R, RW 指令足以实现 _acquire_ 操作，FENCE RW, W 足以实现 _release_，但与设置了相应 _aq_ 或 _rl_ 位的 AMO 相比，两者都意味着不必要的额外排序。
====

[NOTE]
====
一个由“测试-再测试-并设置”自旋锁保护的临界区的示例代码序列如示例 <<critical>> 所示。请注意，第一个 AMO 标记为 _aq_ 以在临界区之前对锁的获取进行排序，第二个 AMO 标记为 _rl_ 以在锁的释放之前对临界区进行排序。

[[critical]]
[source,asm]
.互斥示例代码。`a0` 包含锁的地址。
        li           t0, 1        # 初始化交换值。
    again:
        lw           t1, (a0)     # 检查锁是否被持有。
        bnez         t1, again    # 如果被持有则重试。
        amoswap.w.aq t1, t0, (a0) # 尝试获取锁。
        bnez         t1, again    # 如果被持有则重试。
        # ...
        # 临界区。
        # ...
        amoswap.w.rl x0, x0, (a0) # 通过存储 0 释放锁。

我们建议对锁的获取和释放都使用 <<critical>> 中显示的 AMO Swap 习语，以简化推测性锁消除的实现。 cite:[Rajwar:2001:SLE]
====

[NOTE]
====
“A”扩展中的指令可用于提供顺序一致的加载和存储，但这比必要地更多地限制了硬件对内存访问的重新排序。
一个 C++ 顺序一致的加载可以实现为设置了 _aq_ 的 LR。然而，LR/SC 的最终成功保证可能会减慢来自相同有效地址的并发加载。一个顺序一致的存储可以实现为一个 AMOSWAP，它将旧值写入 `x0` 并设置了 _rl_。然而，多余的加载可能会施加对于此用例不必要的排序约束。
特定的编译约定可能要求在 LR 和 AMOSWAP 指令之一或两者中都设置 _aq_ 和 _rl_ 位。
====
