[[bits]]
== “B”扩展：位操作，版本 1.0.0

B 标准扩展包含由 Zba、Zbb 和 Zbs 扩展提供的指令。

[[preface]]
=== Zb* 概述

位操作（bitmanip）扩展集由基础 RISC-V 架构的几个组件扩展组成，旨在提供代码大小缩减、性能改进和能耗降低的某种组合。
虽然这些指令旨在通用，但某些指令在某些领域比其他领域更有用。
因此，提供了几个较小的位操作扩展。这些较小的扩展中的每一个都按共同的功能和用例分组，并且每个都有自己的 Zb* 扩展名。

每个位操作扩展都包含一组具有相似目的并且通常可以共享相同逻辑的位操作指令。有些指令仅在一个扩展中可用，而其他指令在多个扩展中可用。
指令的助记符和编码与它们出现的扩展无关。
因此，在实现具有重叠指令的扩展时，逻辑或编码上没有冗余。

位操作扩展是为 RV32 和 RV64 定义的。

=== 字指令

位操作扩展遵循 RV64 中的约定，即带有 _w_ 后缀的指令（在 _w_ 之前没有点）会忽略其输入的上半部分 32 位，将最低有效 32 位作为有符号值进行操作，并生成一个符号扩展到 XLEN 的 32 位有符号结果。

带有 _.uw_ 后缀的位操作指令有一个操作数，该操作数是从指定寄存器的最低有效 32 位中提取的无符号 32 位值。除此之外，这些指令执行完整的 XLEN 操作。

带有 _.b_、_.h_ 和 _.w_ 后缀的位操作指令分别只查看输入的最低有效 8 位、16 位和 32 位，并根据具体指令生成一个符号扩展或零扩展的 XLEN 宽度的结果。

=== 指令语义的伪代码

<<#insns-b>> 中每条指令的语义都用类似 SAIL 的语法表示。

=== 扩展

第一批公开发布审查的位操作扩展是：

* <<#zba>>
* <<#zbb>>
* <<#zbc>>
* <<#zbs>>

以下是这些扩展中包含的所有指令及其具体映射的列表：

[%header,cols="^3,^3,10,16,^2,^2,^2,^2"]
|====
|RV32
|RV64
|助记符
|指令
|Zba
|Zbb
|Zbc
|Zbs

|
|&#10003;
|add.uw _rd_, _rs1_, _rs2_
|<<#insns-add_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|andn _rd_, _rs1_, _rs2_
|<<#insns-andn>>
|
|&#10003;
|
|


|&#10003;
|&#10003;
|clmul _rd_, _rs1_, _rs2_
|<<#insns-clmul>>
|
|
|&#10003;
|

|&#10003;
|&#10003;
|clmulh _rd_, _rs1_, _rs2_
|<<#insns-clmulh>>
|
|
|&#10003;
|

|&#10003;
|&#10003;
|clmulr _rd_, _rs1_, _rs2_
|<<#insns-clmulr>>
|
|
|&#10003;
|

|&#10003;
|&#10003;
|clz _rd_, _rs_
|<<#insns-clz>>
|
|&#10003;
|
|

|
|&#10003;
|clzw _rd_, _rs_
|<<#insns-clzw>>
|
|&#10003;
|
|
|&#10003;
|&#10003;
|cpop _rd_, _rs_
|<<#insns-cpop>>
|
|&#10003;
|
|

|
|&#10003;
|cpopw _rd_, _rs_
|<<#insns-cpopw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|ctz _rd_, _rs_
|<<#insns-ctz>>
|
|&#10003;
|
|

|
|&#10003;
|ctzw _rd_, _rs_
|<<#insns-ctzw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|max _rd_, _rs1_, _rs2_
|<<#insns-max>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|maxu _rd_, _rs1_, _rs2_
|<<#insns-maxu>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|min _rd_, _rs1_, _rs2_
|<<#insns-min>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|minu _rd_, _rs1_, _rs2_
|<<#insns-minu>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|orc.b _rd_, _rs_
|<<#insns-orc_b>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|orn _rd_, _rs1_, _rs2_
|<<#insns-orn>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|rev8 _rd_, _rs_
|<<#insns-rev8>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|rol _rd_, _rs1_, _rs2_
|<<#insns-rol>>
|
|&#10003;
|
|

|
|&#10003;
|rolw _rd_, _rs1_, _rs2_
|<<#insns-rolw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|ror _rd_, _rs1_, _rs2_
|<<#insns-ror>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|rori _rd_, _rs1_, _shamt_
|<<#insns-rori>>
|
|&#10003;
|
|

|
|&#10003;
|roriw _rd_, _rs1_, _shamt_
|<<#insns-roriw>>
|
|&#10003;
|
|

|
|&#10003;
|rorw _rd_, _rs1_, _rs2_
|<<#insns-rorw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|bclr _rd_, _rs1_, _rs2_
|<<#insns-bclr>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bclri _rd_, _rs1_, _imm_
|<<#insns-bclri>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bext _rd_, _rs1_, _rs2_
|<<#insns-bext>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bexti _rd_, _rs1_, _imm_
|<<#insns-bexti>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|binv _rd_, _rs1_, _rs2_
|<<#insns-binv>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|binvi _rd_, _rs1_, _imm_
|<<#insns-binvi>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bset _rd_, _rs1_, _rs2_
|<<#insns-bset>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bseti _rd_, _rs1_, _imm_
|<<#insns-bseti>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|sext.b _rd_, _rs_
|<<#insns-sext_b>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|sext.h _rd_, _rs_
|<<#insns-sext_h>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|sh1add _rd_, _rs1_, _rs2_
|<<#insns-sh1add>>
|&#10003;
|
|
|

|
|&#10003;
|sh1add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh1add_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|sh2add _rd_, _rs1_, _rs2_
|<<#insns-sh2add>>
|&#10003;
|
|
|

|
|&#10003;
|sh2add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh2add_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|sh3add _rd_, _rs1_, _rs2_
|<<#insns-sh3add>>
|&#10003;
|
|
|

|
|&#10003;
|sh3add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh3add_uw>>
|&#10003;
|
|
|

|
|&#10003;
|slli.uw _rd_, _rs1_, _imm_
|<<#insns-slli_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|xnor _rd_, _rs1_, _rs2_
|<<#insns-xnor>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|zext.h _rd_, _rs_
|<<#insns-zext_h>>
|
|&#10003;
|
|

|====

[#zba,reftext=地址生成指令]
==== Zba: 地址生成

Zba 指令可用于加速生成地址，这些地址使用无符号字大小和 XLEN 大小的索引来索引基本类型（半字、字、双字）的数组：将移位的索引添加到基地址。

移位和加法指令执行 1、2 或 3 位的左移，因为这些在实际代码中很常见，并且因为它们可以用最少的额外硬件（超出简单加法器的硬件）来实现。这避免了在实现中加长关键路径。

虽然移位和加法指令的最大左移量限制为 3，但 slli 指令（来自基本 ISA）可用于执行类似的移位，以索引到更宽元素的数组中。此扩展中添加的 slli.uw 可在索引要解释为无符号字时使用。

以下指令构成了 Zba 扩展：

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|
|&#10003;
|add.uw _rd_, _rs1_, _rs2_
|<<#insns-add_uw>>

|&#10003;
|&#10003;
|sh1add _rd_, _rs1_, _rs2_
|<<#insns-sh1add>>

|
|&#10003;
|sh1add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh1add_uw>>

|&#10003;
|&#10003;
|sh2add _rd_, _rs1_, _rs2_
|<<#insns-sh2add>>

|
|&#10003;
|sh2add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh2add_uw>>

|&#10003;
|&#10003;
|sh3add _rd_, _rs1_, _rs2_
|<<#insns-sh3add>>

|
|&#10003;
|sh3add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh3add_uw>>

|
|&#10003;
|slli.uw _rd_, _rs1_, _imm_
|<<#insns-slli_uw>>

|===

[#zbb,reftext="基本位操作"]
==== Zbb: 基本位操作

===== 带否定的逻辑运算

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|andn _rd_, _rs1_, _rs2_
|<<#insns-andn>>

|&#10003;
|&#10003;
|orn _rd_, _rs1_, _rs2_
|<<#insns-orn>>

|&#10003;
|&#10003;
|xnor _rd_, _rs1_, _rs2_
|<<#insns-xnor>>
|===

.实现提示
[NOTE, caption="Imp" ]
===============================================================
带否定的逻辑指令可以通过反转 _rs2_ 输入到基本所需的 AND、OR 和 XOR 逻辑指令来实现。
在某些实现中，用于减法的 rs2 上的反相器可以为此目的重用。
===============================================================

===== 计算前导/后导零位

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|clz _rd_, _rs_
|<<#insns-clz>>

|
|&#10003;
|clzw _rd_, _rs_
|<<#insns-clzw>>

|&#10003;
|&#10003;
|ctz _rd_, _rs_
|<<#insns-ctz>>

|
|&#10003;
|ctzw _rd_, _rs_
|<<#insns-ctzw>>
|===

===== 计算置位数

这些指令计算置位（1位）的数量。这通常也称为 population count。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|cpop _rd_, _rs_
|<<#insns-cpop>>

|
|&#10003;
|cpopw _rd_, _rs_
|<<#insns-cpopw>>
|===

===== 整数最小/最大值

整数最小/最大值指令是算术 R 型指令，返回两个操作数中较小/较大的一个。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|max _rd_, _rs1_, _rs2_
|<<#insns-max>>

|&#10003;
|&#10003;
|maxu _rd_, _rs1_, _rs2_
|<<#insns-maxu>>

|&#10003;
|&#10003;
|min _rd_, _rs1_, _rs2_
|<<#insns-min>>

|&#10003;
|&#10003;
|minu _rd_, _rs1_, _rs2_
|<<#insns-minu>>
|===

===== 符号扩展和零扩展

这些指令执行源寄存器最低有效 8 位或 16 位的符号扩展或零扩展。

这些指令取代了通用的惯用语 `slli rd,rs,(XLEN-<size>) + srai`（用于 8 位和 16 位数量的符号扩展）和 `slli + srli`（用于 16 位数量的零扩展）。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|sext.b _rd_, _rs_
|<<#insns-sext_b>>

|&#10003;
|&#10003;
|sext.h _rd_, _rs_
|<<#insns-sext_h>>

|&#10003;
|&#10003;
|zext.h _rd_, _rs_
|<<#insns-zext_h>>
|===

===== 按位旋转

按位旋转指令类似于基本规范中的逻辑移位操作。然而，逻辑移位指令移入零，而旋转指令则移入从值的另一侧移出的位。
这种操作也称为“循环移位”。



[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|rol _rd_, _rs1_, _rs2_
|<<#insns-rol>>

|
|&#10003;
|rolw _rd_, _rs1_, _rs2_
|<<#insns-rolw>>

|&#10003;
|&#10003;
|ror _rd_, _rs1_, _rs2_
|<<#insns-ror>>

|&#10003;
|&#10003;
|rori _rd_, _rs1_, _shamt_
|<<#insns-rori>>

|
|&#10003;
|roriw _rd_, _rs1_, _shamt_
|<<#insns-roriw>>

|
|&#10003;
|rorw _rd_, _rs1_, _rs2_
|<<#insns-rorw>>
|===

.架构说明
[NOTE, caption="AE" ]
===============================================================
包含旋转指令是为了取代一个常见的四指令序列以达到相同的效果（neg; sll/srl; srl/sll; or）。
===============================================================

===== 或组合

如果 _rs_ 的相应字节内没有置位，*orc.b* 将结果 _rd_ 中每个字节的位设置为全零；如果 _rs_ 的相应字节内有任何位置位，则设置为全一。

一个用例是字符串处理函数，例如 *strlen* 和 *strcpy*，它们可以使用 *orc.b* 通过计算字中前导非零字节中的置位数来测试终止零字节。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|orc.b _rd_, _rs_
|<<#insns-orc_b>>
|===

===== 字节反转

*rev8* 反转 _rs_ 的字节顺序。

[%header,cols="^1,^1,4,8"]
|====
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|rev8 _rd_, _rs_
|<<#insns-rev8>>

|====

[#zbc,reftext="无进位乘法"]
==== Zbc: 无进位乘法

无进位乘法是 GF(2) 上多项式环中的乘法。

*clmul* 产生 2×XLEN 无进位乘积的下半部分，*clmulh* 产生上半部分。

*clmulr* 产生 2×XLEN 无进位乘积的第 2×XLEN−2:XLEN-1 位。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|clmul _rd_, _rs1_, _rs2_
|<<#insns-clmul>>

|&#10003;
|&#10003;
|clmulh _rd_, _rs1_, _rs2_
|<<#insns-clmulh>>

|&#10003;
|&#10003;
|clmulr _rd_, _rs1_, _rs2_
|<<#insns-clmulr>>

|===

[#zbs,reftext="单位指令"]
==== Zbs: 单位指令

单位指令提供了一种在寄存器中设置、清除、反转或提取单个位的机制。该位由其索引指定。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|bclr _rd_, _rs1_, _rs2_
|<<#insns-bclr>>

|&#10003;
|&#10003;
|bclri _rd_, _rs1_, _imm_
|<<#insns-bclri>>

|&#10003;
|&#10003;
|bext _rd_, _rs1_, _rs2_
|<<#insns-bext>>

|&#10003;
|&#10003;
|bexti _rd_, _rs1_, _imm_
|<<#insns-bexti>>

|&#10003;
|&#10003;
|binv _rd_, _rs1_, _rs2_
|<<#insns-binv>>

|&#10003;
|&#10003;
|binvi _rd_, _rs1_, _imm_
|<<#insns-binvi>>

|&#10003;
|&#10003;
|bset _rd_, _rs1_, _rs2_
|<<#insns-bset>>

|&#10003;
|&#10003;
|bseti _rd_, _rs1_, _imm_
|<<#insns-bseti>>

|===

[[zbkb,用于密码学的位操作]]
==== Zbkb: 用于密码学的位操作

该扩展包含实现密码学工作负载中常见操作所必需的指令。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令


| &#10003;
| &#10003;
|  rol
| <<insns-rol>>

|
| &#10003;
|  rolw
| <<insns-rolw>>

| &#10003;
| &#10003;
|  ror
| <<insns-ror>>

| &#10003;
| &#10003;
|  rori
| <<insns-rori>>

|
| &#10003;
|  roriw
| <<insns-roriw>>

|
| &#10003;
|  rorw
| <<insns-rorw>>

| &#10003;
| &#10003;
|  andn
| <<insns-andn>>

| &#10003;
| &#10003;
|  orn
| <<insns-orn>>

| &#10003;
| &#10003;
|  xnor
| <<insns-xnor>>

| &#10003;
| &#10003;
|  pack
| <<insns-pack>>

| &#10003;
| &#10003;
|  packh
| <<insns-packh>>

|
| &#10003;
|  packw
| <<insns-packw>>

| &#10003;
| &#10003;
|  brev8
| <<insns-brev8>>

| &#10003;
| &#10003;
|  rev8
| <<insns-rev8>>

| &#10003;
|
|  zip
| <<insns-zip>>

| &#10003;
|
|  unzip
| <<insns-unzip>>

|===

[[zbkc,用于密码学的无进位乘法]]
==== Zbkc: 用于密码学的无进位乘法

无进位乘法是 GF(2) 上多项式环中的乘法。这是某些密码学工作负载中的关键操作，特别是 AES-GCM 认证加密方案。
该扩展仅提供有效实现 GHASH 操作所需的指令，该操作是此工作负载的一部分。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|clmul _rd_, _rs1_, _rs2_
|<<#insns-clmul>>

|&#10003;
|&#10003;
|clmulh _rd_, _rs1_, _rs2_
|<<#insns-clmulh>>

|===

[[zbkx,交叉开关排列]]
==== Zbkx: 交叉开关排列

这些指令在通用寄存器内部为 4 位和 8 位元素实现了一个“查找表”。
_rs1_ 用作 N 位字的向量，_rs2_ 用作 _rs1_ 中 N 位索引的向量。
_rs1_ 中的元素被 _rs2_ 中的索引元素替换，如果 _rs2_ 中的索引越界，则为零。

这些指令对于表示 N 位到 N 位的布尔运算以及实现具有秘密相关内存访问（特别是 SBox）的密码学代码很有用，这样执行延迟不依赖于正在操作的（秘密）数据。

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|xperm4 _rd_, _rs1_, _rs2_
|<<#insns-xperm4>>

|&#10003;
|&#10003;
|xperm8 _rd_, _rs1_, _rs2_
|<<#insns-xperm8>>

|===

<<<

[#insns-b,reftext="指令（按字母顺序）"]
=== 指令（按字母顺序）

[#insns-add_uw,reftext=无符号字加法]
==== add.uw

概要::
无符号字加法

助记符::
add.uw _rd_, _rs1_, _rs2_

伪指令::
zext.w _rd_, _rs1_ → add.uw _rd_, _rs1_, zero

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x0, attr: ['ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x04, attr: ['ADD.UW'] },
]}
....

描述::
该指令在 _rs2_ 和 _rs1_ 的零扩展最低有效字之间执行 XLEN 宽度的加法。

操作::
[source,sail]
--
let base = X(rs2);
let index = EXTZ(X(rs1)[31..0]);

X(rd) = base + index;
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zba (<<zba>>)
|0.93
|已批准
|===

<<<
[#insns-andn,reftext="带反向操作数的与运算"]
==== andn

概要::
带反向操作数的与运算

助记符::
andn _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x7, attr: ['ANDN']},
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x20, attr: ['ANDN'] },
]}
....

描述::
该指令执行 _rs1_ 和 _rs2_ 的按位取反之间的按位逻辑与操作。

操作::
[source,sail]
--
X(rd) = X(rs1) & ~X(rs2);
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbb (<<#zbb>>)
|v1.0
|已批准

|Zbkb (<<#zbkb>>)
|v1.0
|已批准
|===

<<<
[#insns-bclr,reftext="单位清除（寄存器）"]
==== bclr

概要::
单位清除（寄存器）

助记符::
bclr _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BCLR'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x24, attr: ['BCLR/BEXT'] },
]}
....

描述::
该指令返回 _rs1_，其中在 _rs2_ 中指定的索引处清除了一个单位。
索引从 _rs2_ 的低 log2(XLEN) 位读取。

操作::
[source,sail]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = X(rs1) & ~(1 << index)
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-bclri,reftext="单位清除（立即数）"]
==== bclri

概要::
单位清除（立即数）

助记符::
bclri _rd_, _rs1_, _shamt_

编码 (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BCLRI'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x24, attr: ['BCLRI'] },
]}
....

编码 (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BCLRI'] },
    { bits:  5, name: 'rs1' },
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x12, attr: ['BCLRI'] },
]}
....

描述::
该指令返回 _rs1_，其中在 _shamt_ 中指定的索引处清除了一个单位。
索引从 _shamt_ 的低 log2(XLEN) 位读取。
对于 RV32，对应于 shamt[5]=1 的编码是保留的。

操作::
[source,sail]
--
let index = shamt & (XLEN - 1);
X(rd) = X(rs1) & ~(1 << index)
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-bext,reftext="单位提取（寄存器）"]
==== bext

概要::
单位提取（寄存器）
// 我们应该将其描述为“如果位已设置则设置”吗？

助记符::
bext _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x5, attr: ['BEXT'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x24, attr: ['BCLR/BEXT'] },
]}
....

描述::
该指令返回从 _rs1_ 中在 _rs2_ 中指定的索引处提取的单个位。
索引从 _rs2_ 的低 log2(XLEN) 位读取。

操作::
[source,sail]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = (X(rs1) >> index) & 1;
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-bexti,reftext="单位提取（立即数）"]
==== bexti

概要::
单位提取（立即数）

助记符::
bexti _rd_, _rs1_, _shamt_

编码 (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x5, attr: ['BEXTI'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x24, attr: ['BEXTI/BCLRI'] },
]}
....

编码 (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x5, attr: ['BEXTI'] },
    { bits:  5, name: 'rs1' },
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x12, attr: ['BEXTI/BCLRI'] },
]}
....

描述::
该指令返回从 _rs1_ 中在 _shamt_ 中指定的索引处提取的单个位。
索引从 _shamt_ 的低 log2(XLEN) 位读取。
对于 RV32，对应于 shamt[5]=1 的编码是保留的。

操作::
[source,sail]
--
let index = shamt & (XLEN - 1);
X(rd) = (X(rs1) >> index) & 1;
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-binv,reftext="单位反转（寄存器）"]
==== binv

概要::
单位反转（寄存器）

助记符::
binv _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BINV'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x34, attr: ['BINV'] },
]}
....

描述::
该指令返回 _rs1_，其中在 _rs2_ 中指定的索引处反转了一个单位。
索引从 _rs2_ 的低 log2(XLEN) 位读取。

操作::
[source,sail]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = X(rs1) ^ (1 << index)
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-binvi,reftext="单位反转（立即数）"]
==== binvi

概要::
单位反转（立即数）

助记符::
binvi _rd_, _rs1_, _shamt_

编码 (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BINV'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x34, attr: ['BINVI'] },
]}
....

编码 (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BINV'] },
    { bits:  5, name: 'rs1' },
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x1a, attr: ['BINVI'] },
]}
....

描述::
该指令返回 _rs1_，其中在 _shamt_ 中指定的索引处反转了一个单位。
索引从 _shamt_ 的低 log2(XLEN) 位读取。
对于 RV32，对应于 shamt[5]=1 的编码是保留的。

操作::
[source,sail]
--
let index = shamt & (XLEN - 1);
X(rd) = X(rs1) ^ (1 << index)
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-bset,reftext="单位设置（寄存器）"]
==== bset

概要::
单位设置（寄存器）

助记符::
bset _rd_, _rs1_,_rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BSET'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x14, attr: ['BSET'] },
]}
....

描述::
该指令返回 _rs1_，其中在 _rs2_ 中指定的索引处设置了一个单位。
索引从 _rs2_ 的低 log2(XLEN) 位读取。

操作::
[source,sail]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = X(rs1) | (1 << index)
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-bseti,reftext="单位设置（立即数）"]
==== bseti

概要::
单位设置（立即数）

助记符::
bseti _rd_, _rs1_,_shamt_

编码 (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BSETI'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x14, attr: ['BSETI'] },
]}
....

编码 (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['BSETI'] },
    { bits:  5, name: 'rs1' },
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x0a, attr: ['BSETI'] },
]}
....

描述::
该指令返回 _rs1_，其中在 _shamt_ 中指定的索引处设置了一个单位。
索引从 _shamt_ 的低 log2(XLEN) 位读取。
对于 RV32，对应于 shamt[5]=1 的编码是保留的。

操作::
[source,sail]
--
let index = shamt & (XLEN - 1);
X(rd) = X(rs1) | (1 << index)
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbs (<<#zbs>>)
|v1.0
|已批准
|===

<<<
[#insns-clmul,reftext="无进位乘法（低位部分）"]
==== clmul

概要::
无进位乘法（低位部分）

助记符::
clmul _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CLMUL'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x5, attr: ['MINMAX/CLMUL'] },
]}
....

描述::
clmul 产生 2·XLEN 无进位乘积的下半部分。

操作::
[source,sail]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);
let output : xlenbits = 0;

foreach (i from 0 to (xlen - 1) by 1) {
   output = if   ((rs2_val >> i) & 1)
            then output ^ (rs1_val << i);
            else output;
}

X[rd] = output
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbc (<<#zbc>>)
|v1.0
|已批准

|Zbkc (<<#zbkc>>)
|v1.0
|已批准
|===

<<<
[#insns-clmulh,reftext="无进位乘法（高位部分）"]
==== clmulh

概要::
无进位乘法（高位部分）

助记符::
clmulh _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x3, attr: ['CLMULH'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x5, attr: ['MINMAX/CLMUL'] },
]}
....

描述::
clmulh 产生 2·XLEN 无进位乘积的上半部分。

操作::
[source,sail]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);
let output : xlenbits = 0;

foreach (i from 1 to xlen by 1) {
   output = if   ((rs2_val >> i) & 1)
            then output ^ (rs1_val >> (xlen - i));
            else output;
}

X[rd] = output
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbc (<<#zbc>>)
|v1.0
|已批准

|Zbkc (<<#zbkc>>)
|v1.0
|已批准
|===


<<<
[#insns-clmulr,reftext="无进位乘法（反转）"]
==== clmulr

概要::
无进位乘法（反转）

助记符::
clmulr _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x2, attr: ['CLMULR'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x5, attr: ['MINMAX/CLMUL'] },
]}
....

描述::
*clmulr* 产生 2·XLEN 无进位乘积的第 2·XLEN−2:XLEN-1 位。

操作::
[source,sail]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);
let output : xlenbits = 0;

foreach (i from 0 to (xlen - 1) by 1) {
   output = if   ((rs2_val >> i) & 1)
            then output ^ (rs1_val >> (xlen - i - 1));
            else output;
}

X[rd] = output
--

.注意
[NOTE, caption="A" ]
===============================================================
*clmulr* 指令用于加速 CRC 计算。
指令助记符中的 *r* 代表 _反转_，因为该指令等效于对比特输入进行比特反转，执行 *clmul*，然后对比特输出进行比特反转。
===============================================================

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbc (<<#zbc>>)
|v1.0
|已批准
|===

<<<
[#insns-clz,reftext="计算前导零位"]
==== clz

概要::
计算前导零位

助记符::
clz _rd_, _rs_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CLZ']  },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x0, attr: ['CLZ'] },
    { bits:  7, name: 0x30, attr: ['CLZ']  },
]}
....

描述::
该指令计算从最高有效位（即 XLEN-1）开始到第 0 位为止，第一个 1 之前的 0 的数量。因此，如果输入为 0，则输出为 XLEN；如果输入的最高有效位为 1，则输出为 0。

操作::
[source,sail]
--
val HighestSetBit : forall ('N : Int), 'N >= 0. bits('N) -> int

function HighestSetBit x = {
  foreach (i from (xlen - 1) to 0 by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return -1;
}

let rs = X(rs);
X[rd] = (xlen - 1) - HighestSetBit(rs);
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbb (<<#zbb>>)
|v1.0
|已批准
|===

<<<
[#insns-clzw,reftext="计算字中的前导零位"]
==== clzw

概要::
计算字中的前导零位

助记符::
clzw _rd_, _rs_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CLZW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x0, attr: ['CLZW'] },
    { bits:  7, name: 0x30, attr: ['CLZW'] },
]}
....

描述::
该指令计算从第 31 位开始到第 0 位为止，第一个 1 之前的 0 的数量。
因此，如果最低有效字为 0，则输出为 32；如果字的最高有效位（即第 31 位）为 1，则输出为 0。

操作::
[source,sail]
--
val HighestSetBit32 : forall ('N : Int), 'N >= 0. bits('N) -> int

function HighestSetBit32 x = {
  foreach (i from 31 to 0 by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return -1;
}

let rs = X(rs);
X[rd] = 31 - HighestSetBit(rs);
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbb (<<#zbb>>)
|v1.0
|已批准
|===

<<<
[#insns-cpop,reftext="计算置位数"]
==== cpop

概要::
计算置位数

助记符::
cpop _rd_, _rs_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CPOP'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x2, attr: ['CPOP'] },
    { bits:  7, name: 0x30, attr: ['CPOP'] },
]}
....
描述::
该指令计算源寄存器中 1 的数量（即置位数）。

操作::
[source,sail]
--
let bitcount = 0;
let rs = X(rs);

foreach (i from 0 to (xlen - 1) in inc)
    if rs[i] == 0b1 then bitcount = bitcount + 1 else ();

X[rd] = bitcount
--

.软件提示
[NOTE, caption="SH" ]
===============================================================
此操作称为 population count、popcount、sideways sum、bit summation 或 Hamming weight。

GCC 内置函数 `+__builtin_popcount (unsigned int x)+` 在 RV32 上由 cpop 实现，在 RV64 上由 *cpopw* 实现。
LP64 的 GCC 内置函数 `+__builtin_popcountl (unsigned long x)+` 在 RV64 上由 *cpop* 实现。
===============================================================

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbb (<<#zbb>>)
|v1.0
|已批准
|===

<<<
[#insns-cpopw,reftext="计算字中的置位数"]
==== cpopw

概要::
计算字中的置位数

助记符::
cpopw _rd_, _rs_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CPOPW'] },
    { bits:  5, name: 'rs' },
    { bits:  5, name: 0x2, attr: ['CPOPW'] },
    { bits:  7, name: 0x30, attr: ['CPOPW'] },
]}
....
描述::
该指令计算源寄存器最低有效字中 1 的数量（即置位数）。

操作::
[source,sail]
--
let bitcount = 0;
let val = X(rs);

foreach (i from 0 to 31 in inc)
    if val[i] == 0b1 then bitcount = bitcount + 1 else ();

X[rd] = bitcount
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbb (<<#zbb>>)
|v1.0
|已批准
|===

<<<
[#insns-ctz,reftext="计算后导零位"]
==== ctz

概要::
计算后导零位

助记符::
ctz _rd_, _rs_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  7, name: 0x30, attr: ['CTZ/CTZW'] },
]}
....

描述::
该指令计算从最低有效位（即 0）开始到最高有效位（即 XLEN-1）为止，第一个 1 之前的 0 的数量。
因此，如果输入为 0，则输出为 XLEN；如果输入的最低有效位为 1，则输出为 0。

操作::
[source,sail]
--
val LowestSetBit : forall ('N : Int), 'N >= 0. bits('N) -> int

function LowestSetBit x = {
  foreach (i from 0 to (xlen - 1) by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return xlen;
}

let rs = X(rs);
X[rd] = LowestSetBit(rs);
--

包含于::
[%header,cols="4,2,2"]
|===
|扩展
|最低版本
|生命周期状态

|Zbb (<<#zbb>>)
|v1.0
|已批准
|===

<<<
[#insns-ctzw,reftext="计算字中的后导零位"]
==== ctzw

概要::
计算字中的后导零位

助记符::
ctzw _rd_, _rs_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  7, name: 0x30, attr: ['CTZ/CTZW'] },
]}
....

描述::
该指令计算从最低有效位（即 0）开始到最低有效字的最高有效位（即 31）为止，第一个 1 之前的 0 的数量。因此，如果最低有效字为 0，则输出为 32；如果输入的最低有效位为 1，则输出为 0。

操作::
[source,sail]
--
val LowestSetBit32 : forall ('N : Int), 'N >= 0. bits('N) -> int

function LowestSetBit32 x = {
  foreach (i from 0 to 31 by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();