[[compressed]]
== "C"扩展：压缩指令，版本 2.0

本章描述了 RISC-V 标准压缩指令集扩展，名为"C"，它通过为常用操作添加简短的 16 位指令编码来减少静态和动态代码大小。C 扩展可以添加到任何基本 ISA（RV32I、RV32E、RV64I、RV64E）中，我们使用通用术语"RVC"来涵盖其中任何一个。通常，程序中 50%-60% 的 RISC-V 指令可以替换为 RVC 指令，从而使代码大小减少 25%-30%。

=== 概述

RVC 使用简单的压缩方案，当满足以下条件时，为常见的 32 位 RISC-V 指令提供更短的 16 位版本：

* 立即数或地址偏移量很小，或者
* 其中一个寄存器是零寄存器 (`x0`)、ABI 链接寄存器 (`x1`) 或 ABI 栈指针 (`x2`)，或者
* 目标寄存器和第一个源寄存器相同，或者
* 使用的寄存器是 8 个最常用的寄存器。

C 扩展与所有其他标准指令扩展兼容。C 扩展允许 16 位指令与 32 位指令自由混合，后者现在可以在任何 16 位边界开始，即 IALIGN=16。添加 C 扩展后，任何指令都不会引发指令地址未对齐异常。

[NOTE]
====
取消原始 32 位指令的 32 位对齐约束可以显著提高代码密度。
====

压缩指令编码在 RV32C 和 RV64C 中大部分是通用的，但如 <<rvc-instr-table0, 表 34>> 所示，少数操作码根据基本 ISA 用于不同的目的。例如，更宽地址空间的 RV64C 变体需要额外的操作码来压缩 64 位整数值的加载和存储，而 RV32C 使用相同的操作码来压缩单精度浮点值的加载和存储。
如果实现了 C 扩展，则只要同时实现了相关的标准浮点扩展（F 和/或 D），就必须提供相应的压缩浮点加载和存储指令。此外，RV32C 包含一个压缩的跳转和链接指令，用于压缩短距离子程序调用，而 RV64C 使用相同的操作码来压缩 ADDIW。

[NOTE]
====
双精度加载和存储在静态和动态指令中占很大比例，因此有动机将其包含在 RV32C 和 RV64C 编码中。

尽管单精度加载和存储对于为当前支持的 ABI 编译的基准测试来说，不是静态或动态压缩的主要来源，但对于仅提供硬件单精度浮点单元且 ABI 仅支持单精度浮点数的微控制器，单精度加载和存储的使用频率至少与测量基准测试中的双精度加载和存储一样高。因此，有动机在 RV32C 中提供对这些指令的压缩支持。

短距离子程序调用在微控制器的小型二进制文件中更常见，因此有动机将其包含在 RV32C 中。

尽管为不同的基本 ISA 重用操作码用于不同的目的会增加文档的复杂性，但即使对于支持多个基本 ISA 的设计，对实现复杂性的影响也很小。压缩浮点加载和存储变体使用相同的指令格式和相同的寄存器说明符，与更宽的整数加载和存储相同。
====

RVC 的设计约束是，每个 RVC 指令都扩展为基本 ISA（RV32I/E 或 RV64I/E）或 F 和 D 标准扩展（如果存在）中的单个 32 位指令。采用此约束有两个主要优点：

* 硬件设计可以在解码期间简单地扩展 RVC 指令，从而简化验证并最大限度地减少对现有微架构的修改。

* 编译器可以不了解 RVC 扩展，并将代码压缩留给汇编器和链接器，尽管支持压缩的编译器通常能够产生更好的结果。

[NOTE]
====
我们认为 C 和基本 IFD 指令之间简单的一对一映射的多种复杂性降低，远远超过了稍微更密集的编码可能带来的潜在收益，这种编码增加了仅在 C 扩展中支持的额外指令，或者允许在一个 C 指令中编码多个 IFD 指令。
====

需要注意的是，C 扩展并非设计为独立的 ISA，而是旨在与基本 ISA 一起使用。

[NOTE]
====
可变长度指令集长期以来一直用于提高代码密度。例如，1950 年代后期开发的 IBM Stretch cite:[stretch] 具有 32 位和 64 位指令的 ISA，其中一些 32 位指令是完整 64 位指令的压缩版本。
Stretch 还采用了限制在某些较短指令格式中可寻址的寄存器集的概念，其中短分支指令只能引用其中一个索引寄存器。
后来的 IBM 360 架构 cite:[ibm360] 支持简单的可变长度指令编码，具有 16 位、32 位或 48 位指令格式。

1963 年，CDC 推出了 Cray 设计的 CDC 6600 cite:[cdc6600]，它是 RISC 架构的先驱，引入了寄存器丰富的加载-存储架构，指令长度为 15 位和 30 位。后来的 Cray-1 设计使用了非常相似的指令格式，指令长度为 16 位和 32 位。

1980 年代最初的 RISC ISA 都选择了性能而非代码大小，这对于工作站环境来说是合理的，但对于嵌入式系统则不然。因此，ARM 和 MIPS 随后都推出了 ISA 版本，通过提供替代的 16 位宽指令集而不是标准的 32 位宽指令来提供更小的代码大小。压缩的 RISC ISA 相对于其起点将代码大小减少了约 25-30%，产生的代码比 80x86 小得多。这个结果让一些人感到惊讶，因为他们的直觉是可变长度的 CISC ISA 应该比只提供 16 位和 32 位格式的 RISC ISA 小。

由于原始 RISC ISA 没有留下足够的 opcode 空间来包含这些计划外的压缩指令，因此它们被开发为全新的 ISA。这意味着编译器需要为单独的压缩 ISA 提供不同的代码生成器。第一代压缩 RISC ISA 扩展（例如 ARM Thumb 和 MIPS16）仅使用固定的 16 位指令大小，这在静态代码大小方面取得了良好的减少，但导致动态指令计数增加，从而导致性能低于原始固定宽度 32 位指令大小。这导致了第二代压缩 RISC ISA 设计的开发，具有混合的 16 位和 32 位指令长度（例如 ARM Thumb2、microMIPS、PowerPC VLE），因此性能与纯 32 位指令相似，但代码大小节省显著。不幸的是，这些不同代的压缩 ISA 彼此不兼容，也与原始未压缩 ISA 不兼容，导致文档、实现和软件工具支持方面的显著复杂性。

在常用的 64 位 ISA 中，目前只有 PowerPC 和 microMIPS 支持压缩指令格式。令人惊讶的是，移动平台最流行的 64 位 ISA（ARM v8）不包含压缩指令格式，考虑到静态代码大小和动态指令获取带宽是重要的指标。尽管静态代码大小在大型系统中不是主要问题，但指令获取带宽可能是运行商业工作负载的服务器中的主要瓶颈，这些服务器通常具有大型指令工作集。

受益于 25 年的经验，RISC-V 从一开始就设计为支持压缩指令，为 RVC 留下了足够的 opcode 空间，使其可以作为基本 ISA 的简单扩展（以及许多其他扩展）添加。RVC 的理念是减少嵌入式应用程序的代码大小，并由于指令缓存中的未命中更少而提高所有应用程序的性能和能效。Waterman 表明 RVC 获取的指令位数减少了 25%-30%，这使指令缓存未命中减少了 20%-25%，或者大致与指令缓存大小加倍的性能影响相同。 cite:[waterman-ms]
====

=== 压缩指令格式
((((compressed, formats))))

<<rvc-form>> 显示了九种压缩指令格式。CR、CI 和 CSS 可以使用 32 个 RVI 寄存器中的任何一个，但 CIW、CL、CS、CA 和 CB 仅限于其中 8 个。
<<registers>> 列出了这些常用寄存器，它们对应于寄存器 `x8` 到 `x15`。请注意，加载和存储指令有单独的版本，它们使用栈指针作为基地址寄存器，因为保存到栈和从栈恢复非常普遍，并且它们使用 CI 和 CSS 格式以允许访问所有 32 个数据寄存器。CIW 为 ADDI4SPN 指令提供了一个 8 位立即数。

[NOTE]
====
RISC-V ABI 已更改，使常用寄存器映射到寄存器"x8-x15"。这通过拥有连续的自然对齐的寄存器编号集来简化解压缩解码器，并且还与只有 16 个整数寄存器的 RV32E 和 RV64E 基本 ISA 兼容。
====
压缩的基于寄存器的浮点加载和存储也分别使用 CL 和 CS 格式，八个寄存器映射到 `f8` 到 `f15`。
((((calling convention, standard))))
[NOTE]
====
_标准 RISC-V 调用约定将最常用的浮点寄存器映射到寄存器 `f8` 到 `f15`，这允许与整数寄存器编号相同的寄存器解压缩解码。_
====
((((register source specifiers, c-ext))))
这些格式旨在将两个寄存器源说明符的位放在所有指令中的相同位置，而目标寄存器字段可以移动。当存在完整的 5 位目标寄存器说明符时，它与 32 位 RISC-V 编码中的位置相同。当立即数进行符号扩展时，符号扩展始终从第 12 位开始。立即数字段已打乱，与基本规范中一样，以减少所需的立即数多路复用器数量。
[NOTE]
====
立即数字段在指令格式中被打乱而不是按顺序排列，以便尽可能多的位在每条指令中处于相同的位置，从而简化实现。
====

对于许多 RVC 指令，不允许零值立即数，并且 `x0` 不是有效的 5 位寄存器说明符。这些限制释放了编码空间，用于需要更少操作数位的其他指令。

//[[cr-register]]
//include::images/wavedrom/cr-register.edn[]
//.Compressed 16-bit RVC instructions
//(((compressed, 16-bit)))

[[rvc-form]]
.压缩的 16 位 RVC 指令格式
//[%header]
[float="center",align="center",cols="1a, 2a",frame="none",grid="none"]
|===
|
[%autowidth,float="right",align="right",cols="^,^",frame="none",grid="none",options="noheader"]
!===
!格式 ! 含义
!CR ! 寄存器
!CI ! 立即数
!CSS ! 栈相对存储
!CIW ! 宽立即数
!CL ! 加载
!CS ! 存储
!CA ! 算术
!CB ! 分支/算术
!CJ ! 跳转
!===
|
[float="left",align="left",cols="1,1,1,1,1,1,1",options="noheader"]
!===
^!15 14 13 ^!12 ^!11 10 ^!9 8 7 ^!6 5 ^!4 3 2 ^!1 0
2+^!funct4 2+^!rd/rs1 2+^!rs2 ^!  op
^!funct3 ^!imm 2+^!rd/rs1  2+^!imm ^!  op
^!funct3 3+^!imm  2+^!rs2 ^!  op
^!funct3 4+^!imm ^!rd&#x2032; ^! op
^!funct3 2+^!imm ^!rs1&#x2032; ^!imm ^!rd&#x2032; ^! op
^!funct3 2+^!imm ^!rs1&#x2032; ^! imm ^!rs2&#x2032; ^! op
3+^!funct6 ^!rd&#x2032;/rs1&#x2032; ^!funct2 ^!rs2&#x2032; ^! op
^!funct3 2+^!offset ^!rd&#x2032;/rs1&#x2032; 2+^!offset ^! op
^!funct3 5+^!jump target ^! op
!===
|===

[[registers]]
.CIW、CL、CS、CA 和 CB 格式的三位 _rs1_′、_rs2_′ 和 _rd_′ 字段指定的寄存器。
//[cols="20%,10%,10%,10%,10%,10%,10%,10%,10%"]
[float="center",align="center",cols="1a, 1a",frame="none",grid="none"]
|===
|
[%autowidth,cols="<",frame="none",grid="none",options="noheader"]
!===
!RVC 寄存器编号
!整数寄存器编号
!整数寄存器 ABI 名称
!浮点寄存器编号
!浮点寄存器 ABI 名称
!===
|

[%autowidth,cols="^,^,^,^,^,^,^,^",options="noheader"]
!===
!`000` !`001` !`010` !`011` !`100` !`101` !`110` !`111`
!`x8` !`x9` !`x10` !`x11` !`x12` !`x13` !`x14`!`x15`
!`s0` !`s1` !`a0` !`a1` !`a2` !`a3` !`a4`!`a5`
!`f8` !`f9` !`f10` !`f11` !`f12` !`f13`!`f14` !`f15`
!`fs0` !`fs1` !`fa0` !`fa1` !`fa2`!`fa3` !`fa4` !`fa5`
!===
|===


=== 加载和存储指令

为了增加 16 位指令的覆盖范围，数据传输指令使用零扩展立即数，这些立即数按数据大小（字节）进行缩放：字为 ×4，双字为 ×8，四字为 ×16。

RVC 提供两种加载和存储变体。一种使用 ABI 栈指针 `x2` 作为基地址，并且可以指向任何数据寄存器。另一种可以引用 8 个基地址寄存器中的一个和 8 个数据寄存器中的一个。

==== 基于栈指针的加载和存储

include::images/wavedrom/c-sp-load-store.edn[]
[[c-sp-load-store]]
//.基于栈指针的加载和存储——这些指令使用 CI 格式。

这些指令使用 CI 格式。

C.LWSP 将 32 位值从内存加载到寄存器 _rd_ 中。它通过将零扩展偏移量（按 4 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `lw rd, offset(x2)`。C.LWSP 仅在 _rd_≠`x0` 时有效；_rd_=`x0` 的代码点是保留的。

C.LDSP 是 RV64C 独有的指令，它将 64 位值从内存加载到寄存器 _rd_ 中。它通过将零扩展偏移量（按 8 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `ld rd, offset(x2)`。C.LDSP 仅在 _rd_≠`x0` 时有效；_rd_=`x0` 的代码点是保留的。

C.FLWSP 是 RV32FC 独有的指令，它将单精度浮点值从内存加载到浮点寄存器 _rd_ 中。它通过将零扩展偏移量（按 4 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `flw rd, offset(x2)`。

C.FLDSP 是 RV32DC/RV64DC 独有的指令，它将双精度浮点值从内存加载到浮点寄存器 _rd_ 中。它通过将零扩展偏移量（按 8 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `fld rd, offset(x2)`。

include::images/wavedrom/c-sp-load-store-css.edn[]
[[c-sp-load-store-css]]
//.基于栈指针的加载和存储——这些指令使用 CSS 格式。

这些指令使用 CSS 格式。

C.SWSP 将寄存器 _rs2_ 中的 32 位值存储到内存中。它通过将零扩展偏移量（按 4 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `sw rs2, offset(x2)`。

C.SDSP 是 RV64C 独有的指令，它将寄存器 _rs2_ 中的 64 位值存储到内存中。它通过将零扩展偏移量（按 8 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `sd rs2, offset(x2)`。

C.FSWSP 是 RV32FC 独有的指令，它将浮点寄存器 _rs2_ 中的单精度浮点值存储到内存中。它通过将零扩展偏移量（按 4 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `fsw rs2, offset(x2)`。

C.FSDSP 是 RV32DC/RV64DC 独有的指令，它将浮点寄存器 _rs2_ 中的双精度浮点值存储到内存中。它通过将零扩展偏移量（按 8 缩放）添加到栈指针 `x2` 来计算有效地址。它扩展为 `fsd rs2, offset(x2)`。

[NOTE]
====
函数入口/出口处的寄存器保存/恢复代码在静态代码大小中占很大一部分。RVC 中基于栈指针的压缩加载和存储有效地将保存/恢复的静态代码大小减少了 2 倍，同时通过减少动态指令带宽提高了性能。

其他 ISA 中用于进一步减少保存/恢复代码大小的常见机制是多重加载和多重存储指令。我们考虑为 RISC-V 采用这些指令，但注意到这些指令存在以下缺点：

* 这些指令使处理器实现复杂化。
* 对于虚拟内存系统，一些数据访问可能驻留在物理内存中，而另一些则可能不驻留，这需要为部分执行的指令提供新的重启机制。
* 与 RVC 的其余指令不同，没有与多重加载和多重存储等效的 IFD 指令。
* 与 RVC 的其余指令不同，编译器必须了解这些多重加载和多重存储指令，才能以预期的顺序分配寄存器，并连续且以正确的顺序调度加载和存储，以最大限度地提高它们被汇编器或链接器检测并替换为等效的多重加载或多重存储压缩指令的机会。
* 简单的微架构实现将限制其他指令如何围绕多重加载和存储指令进行调度，从而导致潜在的性能损失。
* 对顺序寄存器分配的渴望可能与为 CIW、CL、CS、CA 和 CB 格式选择的特色寄存器冲突。

此外，通过用对通用序言和尾声代码的子程序调用替换序言和尾声代码，可以在软件中实现大部分收益，这是一种在 cite:[waterman-phd] 的 5.6 节中描述的技术。

尽管合理的架构师可能会得出不同的结论，但我们决定省略多重加载和存储，而是使用仅软件的方法调用保存/恢复微代码例程，以实现最大的代码大小减少。
====

==== 基于寄存器的加载和存储

[[reg-based-ldnstr]]
include::images/wavedrom/reg-based-ldnstr.edn[]
//.压缩的、基于寄存器的加载和存储——这些指令使用 CL 格式。
(((compressed, register-based load and store)))
这些指令使用 CL 格式。

C.LW 将 32 位值从内存加载到寄存器 `_rd′_` 中。它通过将零扩展偏移量（按 4 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `lw rd′, offset(rs1′)`。

C.LD 是 RV64C 独有的指令，它将 64 位值从内存加载到寄存器 `_rd′_` 中。它通过将零扩展偏移量（按 8 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `ld rd′, offset(rs1′)`。

C.FLW 是 RV32FC 独有的指令，它将单精度浮点值从内存加载到浮点寄存器 `_rd′_` 中。它通过将零扩展偏移量（按 4 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `flw rd′, offset(rs1′)`。

C.FLD 是 RV32DC/RV64DC 独有的指令，它将双精度浮点值从内存加载到浮点寄存器 `_rd′_` 中。它通过将零扩展偏移量（按 8 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `fld rd′, offset(rs1′)`。

[[c-cs-format-ls]]
include::images/wavedrom/c-cs-format-ls.edn[]
//.压缩的、CS 格式加载和存储——这些指令使用 CS 格式。
(((compressed, cs-format load and store)))

这些指令使用 CS 格式。

C.SW 将寄存器 `_rs2′_` 中的 32 位值存储到内存中。它通过将零扩展偏移量（按 4 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `sw rs2′, offset(rs1′)`。

C.SD 是 RV64C 独有的指令，它将寄存器 `_rs2′_` 中的 64 位值存储到内存中。它通过将零扩展偏移量（按 8 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `sd rs2′, offset(rs1′)`。

C.FSW 是 RV32FC 独有的指令，它将浮点寄存器 `_rs2′_` 中的单精度浮点值存储到内存中。它通过将零扩展偏移量（按 4 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `fsw rs2′, offset(rs1′)`。

C.FSD 是 RV32DC/RV64DC 独有的指令，它将浮点寄存器 `_rs2′_` 中的双精度浮点值存储到内存中。它通过将零扩展偏移量（按 8 缩放）添加到寄存器 `_rs1′_` 中的基地址来计算有效地址。它扩展为 `fsd rs2′, offset(rs1′)`。

=== 控制转移指令

RVC 提供无条件跳转指令和条件分支指令。与基本 RVI 指令一样，所有 RVC 控制转移指令的偏移量都是 2 字节的倍数。

[[c-cj-format-ls]]
include::images/wavedrom/c-cj-format-ls.edn[]
//.压缩的、CJ 格式加载和存储——这些指令使用 CJ 格式。
(((compressed, cj-format load and store)))

这些指令使用 CJ 格式。

C.J 执行无条件控制转移。偏移量进行符号扩展并添加到 `pc` 以形成跳转目标地址。因此，C.J 可以指向 ±2 KiB 范围。C.J 扩展为 `jal x0, offset`。

C.JAL 是 RV32C 独有的指令，它执行与 C.J 相同的操作，但额外将跳转后指令的地址 (`pc+2`) 写入链接寄存器 `x1`。C.JAL 扩展为 `jal x1, offset`。

[[c-cr-format-ls]]
include::images/wavedrom/c-cr-format-ls.edn[]
//.压缩的、CR 格式加载和存储——这些指令使用 CR 格式。
(((compressed, cr-format load and store)))

这些指令使用 CR 格式。

C.JR（跳转寄存器）执行到寄存器 _rs1_ 中地址的无条件控制转移。C.JR 扩展为 `jalr x0, 0(rs1)`。C.JR 仅在 _rs1_≠`x0` 时有效；_rs1_=`x0` 的代码点是保留的。

C.JALR（跳转并链接寄存器）执行与 C.JR 相同的操作，但额外将跳转后指令的地址 (`pc`+2) 写入链接寄存器 `x1`。C.JALR 扩展为 `jalr x1, 0(rs1)`。C.JALR 仅在 _rs1_≠`x0` 时有效；_rs1_=`x0` 的代码点对应于 C.EBREAK 指令。

[NOTE]
====
严格来说，C.JALR 并不完全扩展为基本 RVI 指令，因为添加到 PC 以形成链接地址的值是 2 而不是基本 ISA 中的 4，但支持 2 字节和 4 字节的偏移量对基本微架构来说只是一个非常小的改动。
====

[[c-cb-format-ls]]
include::images/wavedrom/c-cb-format-ls.edn[]
//.压缩的、CB 格式加载和存储——这些指令使用 CB 格式。
(((compressed, cb-format load and store)))

这些指令使用 CB 格式。

C.BEQZ 执行条件控制转移。偏移量进行符号扩展并添加到 `pc` 以形成分支目标地址。因此，它可以指向 ±256 B 范围。如果寄存器 _rs1′_ 中的值为零，C.BEQZ 则进行分支。它扩展为 `beq rs1′, x0, offset`。

C.BNEZ 的定义类似，但如果 _rs1′_ 包含非零值，它则进行分支。它扩展为 `bne rs1′, x0, offset`。

=== 整数计算指令

RVC 提供了一些用于整数算术和常量生成的指令。

==== 整数常量生成指令

两个常量生成指令都使用 CI 指令格式，并且可以指向任何整数寄存器。

[[c-integer-const-gen]]
include::images/wavedrom/c-integer-const-gen.edn[]
//.整数常量生成格式。
(((compressed, integer constant generation)))


C.LI 将符号扩展的 6 位立即数 _imm_ 加载到寄存器 _rd_ 中。C.LI 扩展为 `addi rd, x0, imm`。
_rd_=`x0` 的 C.LI 代码点是 HINT。

C.LUI 将非零的 6 位立即数字段加载到目标寄存器的 17-12 位中，清除低 12 位，并将第 17 位符号扩展到目标寄存器的所有更高位。C.LUI 扩展为 `lui rd, imm`。C.LUI 仅在 _rd_≠`x2` 且立即数不等于零时有效。_imm_=0 的代码点是保留的。
_rd_=`x2` 且 _imm_≠0 的代码点对应于 C.ADDI16SP 指令。
_rd_=`x0` 且 _imm_≠0 的代码点是 HINT。

==== 整数寄存器-立即数操作

这些整数寄存器-立即数操作以 CI 格式编码，并对整数寄存器和 6 位立即数执行操作。

[[c-integer-register-immediate]]
include::images/wavedrom/c-int-reg-immed.edn[]
//.整数寄存器-立即数格式。
(((compressed, integer register-immediate)))

C.ADDI 将非零符号扩展的 6 位立即数添加到寄存器 _rd_ 中的值，然后将结果写入 _rd_。C.ADDI 扩展为 `addi rd, rd, imm`。
_rd_≠0 且 _imm_=0 的代码点是 HINT。
_rd_=`x0` 的代码点编码 C.NOP 指令，其中 _imm_≠0 的代码点是 HINT。


C.ADDIW 是 RV64C 独有的指令，它执行相同的计算，但产生一个 32 位结果，然后将结果符号扩展到 64 位。C.ADDIW 扩展为 `addiw rd, rd, imm`。C.ADDIW 的立即数可以为零，此时对应于 `sext.w rd`。C.ADDIW 仅在 _rd_≠`x0` 时有效；_rd_=`x0` 的代码点是保留的。

C.ADDI16SP（立即数加到栈指针）与 C.LUI 共享操作码，但目标字段为 `x2`。C.ADDI16SP 将非零符号扩展的 6 位立即数添加到栈指针 (`sp=x2`) 中的值，其中立即数按 16 的倍数缩放，范围为 [-512, 496]。C.ADDI16SP 用于在过程序言和尾声中调整栈指针。它扩展为 `addi x2, x2, nzimm[9:4]`。C.ADDI16SP 仅在 _nzimm_≠0 时有效；_nzimm_=0 的代码点是保留的。

[NOTE]
====
在标准 RISC-V 调用约定中，栈指针 `sp` 始终是 16 字节对齐的。
====

[[c-ciw]]
include::images/wavedrom/c-ciw.edn[]
//.CIW 格式。
(((compressed, CIW)))
C.ADDI4SPN（立即数加到栈指针，非破坏性）是 CIW 格式指令，它将零扩展的非零立即数（按 4 缩放）添加到栈指针 `x2`，并将结果写入 `rd′`。该指令用于生成指向栈分配变量的指针，并扩展为 `addi rd′, x2, nzuimm[9:2]`。C.ADDI4SPN 仅在 _nzuimm_≠0 时有效；_nzuimm_=0 的代码点是保留的。

[[c-ci]]
include::images/wavedrom/c-ci.edn[]
//.CI 格式。
(((compressed, CI)))

C.SLLI 是 CI 格式指令，它对寄存器 _rd_ 中的值执行逻辑左移，然后将结果写入 _rd_。移位量编码在 _shamt_ 字段中。
C.SLLI 扩展为 `slli rd, rd, shamt[5:0]`。

_shamt_=0 或 _rd_=`x0` 的 C.SLLI 代码点是 HINT。

对于 RV32C，_shamt[5]_ 必须为零；_shamt[5]_=1 的代码点指定用于自定义扩展。

[[c-srli-srai]]

include::images/wavedrom/c-srli-srai.edn[]
//.C-SRLI-SRAI 格式。
(((compressed, C.SRLI, C.SRAI)))

C.SRLI 是 CB 格式指令，它对寄存器 _rd′_ 中的值执行逻辑右移，然后将结果写入 _rd′_。移位量编码在 _shamt_ 字段中。
C.SRLI 扩展为 `srli rd′, rd′, shamt`。

_shamt_=0 的 C.SRLI 代码点是 HINT。

对于 RV32C，_shamt[5]_ 必须为零；_shamt[5]_=1 的代码点指定用于自定义扩展。

C.SRAI 的定义与 C.SRLI 类似，但执行算术右移。C.SRAI 扩展为 `srai rd′, rd′, shamt`。

[NOTE]
====
左移通常比右移更频繁，因为左移经常用于缩放地址值。因此，右移获得了较少的编码空间，并放置在所有其他立即数都进行符号扩展的编码象限中。
====
[[c-andi]]
include::images/wavedrom/c-andi.edn[]
//.C.ANDI 格式
(((compressed, C.ANDI)))

C.ANDI 是 CB 格式指令，它计算寄存器 _rd′_ 中的值与符号扩展的 6 位立即数之间的按位 AND，然后将结果写入 _rd′_。C.ANDI 扩展为 `andi rd′, rd′, imm`。

==== 整数寄存器-寄存器操作

[[c-cr]]
include::images/wavedrom/c-int-reg-to-reg-cr-format.edn[]
//C.CR 格式
((((compressed. C.CR))))
这些指令使用 CR 格式。

C.MV 将寄存器 _rs2_ 中的值复制到寄存器 _rd_ 中。C.MV 扩展为 `add rd, x0, rs2`。C.MV 仅在 _rs2_≠`x0` 时有效；_rs2_=`x0` 的代码点对应于 C.JR 指令。_rs2_≠`x0` 且 _rd_=`x0` 的代码点是 HINT。

[NOTE]
====
_C.MV 扩展为与规范 MV 伪指令不同的指令，后者使用 ADDI。处理 MV 特殊的实现，例如使用寄存器重命名硬件的实现，可能会发现将 C.MV 扩展为 MV 而不是 ADD 更方便，尽管会增加少量硬件成本。_
====

C.ADD 将寄存器 _rd_ 和 _rs2_ 中的值相加，并将结果写入寄存器 _rd_。C.ADD 扩展为 `add rd, rd, rs2`。C.ADD 仅在 _rs2_≠`x0` 时有效；_rs2_=`x0` 的代码点对应于 C.JALR 和 C.EBREAK 指令。_rs2_≠`x0` 且 _rd_=`x0` 的代码点是 HINT。

[[c-ca]]
include::images/wavedrom/c-int-reg-to-reg-ca-format.edn[]
//C.CA 格式
((((compressed. C.CA))))

这些指令使用 CA 格式。

`C.AND` 计算寄存器 _rd′_ 和 _rs2′_ 中的值之间的按位 `AND`，然后将结果写入寄存器 _rd′_。`C.AND` 扩展为 `and rd′, rd′, rs2′`。

`C.OR` 计算寄存器 _rd′_ 和 _rs2′_ 中的值之间的按位 `OR`，然后将结果写入寄存器 _rd′_。`C.OR` 扩展为 `or rd′, rd′, rs2′`。

`C.XOR` 计算寄存器 _rd′_ 和 _rs2′_ 中的值之间的按位 `XOR`，然后将结果写入寄存器 _rd′_。`C.XOR` 扩展为 `xor rd′, rd′, rs2′`。

`C.SUB` 从寄存器 _rd′_ 中的值中减去寄存器 _rs2′_ 中的值，然后将结果写入寄存器 _rd′_。`C.SUB` 扩展为 `sub rd′, rd′, rs2′`。

`C.ADDW` 是 RV64C 独有的指令，它将寄存器 _rd′_ 和 _rs2′_ 中的值相加，然后将和的低 32 位符号扩展，再将结果写入寄存器 _rd′_。`C.ADDW` 扩展为 `addw rd′, rd′, rs2′`。

`C.SUBW` 是 RV64C 独有的指令，它从寄存器 _rd′_ 中的值中减去寄存器 _rs2′_ 中的值，然后将差的低 32 位符号扩展，再将结果写入寄存器 _rd′_。`C.SUBW` 扩展为 `subw rd′, rd′, rs2′`。

[NOTE]
====
这组六条指令单独来看节省不大，但它们不占用太多编码空间，并且易于实现，作为一个整体，它们在静态和动态压缩方面提供了可观的改进。
====

==== 定义的非法指令

[[c-def-illegal-inst]]
include::images/wavedrom/c-def-illegal-inst.edn[]
((((compressed. C.DIINST))))

所有位均为零的 16 位指令被永久保留为非法指令。

[NOTE]
====
我们将全零指令保留为非法指令，以帮助捕获执行内存空间中全零或不存在部分的尝试。全零值不应在任何非标准扩展中重新定义。同样，我们将所有位都设置为 1 的指令（对应于 RISC-V 可变长度编码方案中的超长指令）保留为非法指令，以捕获在不存在的内存区域中看到的另一个常见值。
====

==== NOP 指令

[[c-nop-instr]]
include::images/wavedrom/c-nop-instr.edn[]
((((compressed. C.NOPINSTR))))

`C.NOP` 是 CI 格式指令，除了推进 `pc` 和增加任何适用的性能计数器外，不改变任何用户可见状态。`C.NOP` 扩展为 `nop`。_imm_≠0 的 `C.NOP` 代码点编码 HINT。

==== 断点指令

[[c-breakpoint-instr]]
include::images/wavedrom/c-breakpoint-instr.edn[]
((((compressed. C.BREAKPOINTINSTR))))

调试器可以使用 `C.EBREAK` 指令（扩展为 `ebreak`）将控制权转移回调试环境。
`C.EBREAK` 与 `C.ADD` 指令共享操作码，但 _rd_ 和 _rs2_ 都为零，因此也可以使用 `CR` 格式。

=== C 指令在 LR/SC 序列中的使用

在支持 C 扩展的实现上，<<sec:lrscseq>> 中描述的受限 LR/SC 序列中允许的 I 指令的压缩形式，也允许在受限 LR/SC 序列中使用。

[NOTE]
====
这意味着任何声称支持 A 和 C 扩展的实现都必须确保包含有效 C 指令的 LR/SC 序列最终会完成。
====

[[rvc-hints]]
=== HINT 指令

RVC 编码空间的一部分保留用于微架构 HINT。与 RV32I 基本 ISA 中的 HINT（参见 <<rv32i-hints>>）一样，这些指令不修改任何架构状态，除了推进 `pc` 和任何适用的性能计数器。HINT 在忽略它们的实现上作为空操作执行。

RVC HINT 编码为不修改架构状态的计算指令，要么是因为 _rd_=`x0`（例如 `C.ADD _x0_, _t0_`），要么是因为 _rd_ 被其自身的副本覆盖（例如 `C.ADDI _t0_, 0`）。

[NOTE]
====
选择此 HINT 编码是为了让简单的实现可以完全忽略 HINT，而是将 HINT 作为常规计算指令执行，该指令恰好不改变架构状态。
====

RVC HINT 不一定扩展为它们的 RVI HINT 对应物。例如，`C.ADD` _x0_, _a0_ 可能不会编码与 `ADD` _x0_, _x0_, _a0_ 相同的 HINT。

[NOTE]
====
不要求 RVC HINT 扩展为 RVI HINT 的主要原因是 HINT 不太可能以与底层计算指令相同的方式进行压缩。此外，解耦 RVC 和 RVI HINT 映射允许将稀缺的 RVC HINT 空间分配给最流行的 HINT，特别是那些适合宏操作融合的 HINT。
====

<<rvc-t-hints, 表 32>> 列出了所有 RVC HINT 代码点。对于 RV32C，78% 的 HINT 空间保留用于标准 HINT。HINT 空间的其余部分指定用于自定义 HINT；在此子空间中永远不会定义标准 HINT。

[[rvc-t-hints]]
.RVC HINT 指令。
[cols="<,<,>,<",options="header",]
|===
|指令 |约束 |代码点 |目的

|C.NOP |_imm_≠0 |63 .6+.^|_指定用于未来的标准用途_

|C.ADDI | _rd_≠`x0`, _imm_=0 |31

|C.LI | _rd_=`x0` |64

|C.LUI | _rd_=`x0`, _imm_≠0 |63

|C.MV | _rd_=`x0`, _rs2_≠`x0` |31

|C.ADD | _rd_=`x0`, _rs2_≠`x0`, _rs2_≠`x2-x5` | 27

|C.ADD | _rd_=`x0`, _rs2_=`x2-x5` |4|(rs2=x2) C.NTL.P1 (rs2=x3) C.NTL.PALL (rs2=x4) C.NTL.S1 (rs2=x5) C.NTL.ALL

|C.SLLI |_rd_=`x0` or _imm_=0 |63 (RV32), 95 (RV64)  .3+.^|_指定用于自定义用途_

|C.SRLI | _imm_=0 |8

|C.SRAI | _imm_=0 |8
|===

=== RVC 指令集列表

<<rvcopcodemap>> 显示了 RVC 主要操作码的映射。表的每一行对应于编码空间的一个象限。最后一个象限，其两个最低有效位已设置，对应于宽度大于 16 位的指令，包括基本 ISA 中的指令。一些指令仅对某些操作数有效；当无效时，它们被标记为 _RES_ 表示操作码保留用于未来的标准扩展；_Custom_ 表示操作码指定用于自定义扩展；或 _HINT_ 表示操作码保留用于微架构提示（参见 <<rvc-hints>>）。

<<<

[[rvcopcodemap]]
.RVC 操作码映射指令。
[%autowidth,float="center",align="center",cols=">,^,^,^,^,^,^,^,^,^,<]
|===
2+>|inst[15:13] +
inst[1:0] ^.^s|000 ^.^s|001 ^.^s|010 ^.^s|011 ^.^s|100 ^.^s|101 ^.^s|110 ^.^s|111 |

2+>.^|00 .^|ADDI4SPN ^.^|FLD +
FLD ^.^| LW ^.^| FLW +
LD ^.^| _Reserved_ ^.^| FSD +
FSD ^.^| SW ^.^| FSW +
SD
^.^| RV32 +
RV64

2+>.^|01 ^.^|ADDI ^.^|JAL +
ADDIW ^.^|LI ^.^|LUI/ADDI16SP ^.^|MISC-ALU ^.^|J ^.^|BEQZ ^.^|BNEZ ^.^|RV32 +
RV64

2+>.^|10 ^.^|SLLI ^.^|FLDSP +
FLDSP ^.^|LWSP ^.^|FLWSP +
LDSP ^.^|J[AL]R/MV/ADD ^.^|FSDSP +
FSDSP ^.^|SWSP ^.^|FSWSP +
SDSP ^.^|RV32 +
RV64

2+>.^|11 9+^|>16b
|===

<<rvc-instr-table0>>、<<rvc-instr-table1>> 和 <<rvc-instr-table2>> 列出了 RVC 指令。

[[rvc-instr-table0]]
.RVC 指令列表，象限 0
include::images/bytefield/rvc-instr-quad0.edn[]
//include::images/bytefield/rvc-instr-quad0.png[]

[[rvc-instr-table1]]
.RVC 指令列表，象限 1
include::images/bytefield/rvc-instr-quad1.edn[]
//include::images/bytefield/rvc-instr-quad1.png[]

[[rvc-instr-table2]]
.RVC 指令列表，象限 2
include::images/bytefield/rvc-instr-quad2.edn[]
//include::images/bytefield/rvc-instr-quad2.png[]