[[cmo]]
== “CMO”扩展：基本缓存管理操作 ISA，版本 1.0.0

=== 指令语义的伪代码

<<#insns>> 章中每条指令的语义都用类似 SAIL 的语法表示。

[#intro-cmo,reftext="引言"]
=== 引言

_缓存管理操作_（或 _CMO_）指令对内存层次结构中数据副本执行操作。通常，CMO 指令对缓存的数据副本进行操作，但在某些情况下，CMO 指令可以直接对内存位置进行操作。此外，CMO 指令按操作分组为以下类别：

* _管理_ 指令操作数据缓存副本，相对于可以访问数据的一组代理
* _清零_ 指令将一系列内存位置清零，可能在一个或多个缓存中分配数据缓存副本
* _预取_ 指令向硬件指示，给定内存位置的数据可能在不久的将来被访问，可能在一个或多个缓存中分配数据缓存副本

本文档介绍了一组基本的 CMO ISA 扩展，这些扩展专门对缓存块或与缓存块对应的内存位置进行操作；这些被称为 _缓存块操作_（或 _CBO_）指令。上述每个指令类别都代表本规范中的一个扩展：

* _Zicbom_ 扩展定义了一组缓存块管理指令：`CBO.INVAL`、`CBO.CLEAN` 和 `CBO.FLUSH`
* _Zicboz_ 扩展定义了一个缓存块清零指令：`CBO.ZERO`
* _Zicbop_ 扩展定义了一组缓存块预取指令：`PREFETCH.R`、`PREFETCH.W` 和 `PREFETCH.I`

上述指令的执行行为也受本规范添加的 CSR 状态修改。

本文档的其余部分提供了 CMO 指令的一般背景信息，并描述了上述每个 ISA 扩展。

[NOTE]
====
_术语 CMO 涵盖了对缓存或与缓存相关的资源的所有操作。术语 CBO 表示 CMO 的一个子集，它仅对缓存块进行操作。第一个 CMO 扩展仅定义 CBO。_
====

[#background,reftext="背景"]
=== 背景

本章提供了所有 CMO 扩展的通用信息。

[#memory-caches,reftext="内存和缓存"]
==== 内存和缓存

_内存位置_ 是系统中由 _物理地址_ 唯一标识的物理资源。_代理_ 是一个逻辑块，例如 RISC-V hart、加速器、I/O 设备等，可以访问给定的内存位置。

[NOTE]
====
_给定代理可能无法访问系统中所有内存位置，并且两个不同的代理可能能够或不能够访问相同的内存位置集。_
====

_加载操作_（或 _存储操作_）由代理执行，以使用（或修改）给定内存位置的数据。加载和存储操作是由于对该内存位置的显式内存访问而执行的。此外，从内存的 _读取传输_ 获取内存位置的数据，而对内存的 _写入传输_ 更新内存位置的数据。

_缓存_ 是一种缓冲数据副本以减少平均内存延迟的结构。任意数量的缓存可以穿插在代理和内存位置之间，并且来自代理的加载和存储操作可以由缓存而不是内存位置满足。

[NOTE]
====
_加载和存储操作与缓存的读取和写入传输是解耦的。例如，加载操作可以由缓存满足，而无需从内存执行读取传输，或者存储操作可以由缓存满足，该缓存首先从内存执行读取传输。_
====

缓存将数据副本组织成 _缓存块_，每个缓存块表示一个连续的、自然对齐的 2 的幂（或 _NAPOT_）内存位置范围。缓存块由与底层内存位置对应的任何物理地址标识。缓存的容量和组织以及缓存块的大小都是 _实现特定_ 的，执行环境为软件提供了一种发现系统中缓存和缓存块信息的方法。在初始的 CMO 扩展集中，缓存块的大小在整个系统中应是统一的。

[NOTE]
====
_在未来的 CMO 扩展中，对统一缓存块大小的要求可能会放宽。_
====

推测执行或硬件预取等实现技术可能导致给定缓存随时分配或释放缓存块的副本，前提是相应的物理地址可根据支持的访问类型 PMA 访问，并且可根据缓存性 PMA 缓存。分配缓存块的副本会导致从另一个缓存或从内存进行读取传输，而释放缓存块的副本可能导致向另一个缓存或向内存进行写入传输，具体取决于副本中的数据是否已通过存储操作修改。更多详细信息将在 <<#coherent-agents-caches>> 中讨论。

==== 缓存块操作

CBO 指令导致对指令标识的缓存块执行一个或多个操作。通常，CBO 指令可以标识一个或多个缓存块；但是，在初始的 CMO 扩展集中，CBO 指令仅标识单个缓存块。

缓存块管理指令执行以下操作之一，相对于给定缓存中分配的给定缓存块的副本：

* _失效操作_ 释放缓存块的副本

* _清理操作_ 如果缓存块副本中的数据已通过存储操作修改，则执行写入传输到另一个缓存或内存

* _刷新操作_ 原子地执行清理操作，然后执行失效操作

更多详细信息，包括给定缓存块管理指令执行的实际操作，将在 <<#Zicbom>> 中描述。

缓存块清零指令执行一组存储操作，将零写入与缓存块对应的字节集。除非另有说明，否则缓存块清零指令生成的存储操作具有与架构中其他存储指令相同的通用属性和行为。实现可以或可以不原子地更新整个字节集，包括单个字节。更多详细信息将在 <<#Zicboz>> 中描述。

缓存块预取指令是向硬件发出的 HINT，指示软件期望在不久的将来执行特定类型的内存访问。更多详细信息将在 <<#Zicbop>> 中描述。

[#coherent-agents-caches,reftext="一致性代理和缓存"]
=== 一致性代理和缓存

对于给定的内存位置，_一组一致性代理_ 由满足以下所有条件的代理组成：

* 来自该集合中所有代理的存储操作相对于彼此看起来是串行化的
* 来自该集合中所有代理的存储操作最终对该集合中所有其他代理可见
* 来自该集合中代理的加载操作返回来自该集合中代理的存储操作的数据（或内存中的初始数据）

该集合中的一致性代理应以相同的物理地址和相同的物理内存属性访问给定的内存位置；但是，如果给定代理的一致性 PMA 指示给定内存位置不一致，则该代理不应成为该内存位置的任何其他代理的一致性代理集合的成员，并且应是仅由其自身组成的一致性代理集合的唯一成员。

作为一组一致性代理成员的代理被称为相对于该集合中的其他代理是 _一致的_。另一方面，_不是_ 成员的代理被称为相对于该集合中的代理是 _非一致的_。

缓存引入了给定缓存块的多个副本可能同时存在于系统中的可能性。_实现特定_ 机制使这些副本相对于一致性代理集合中代理的加载和存储操作保持一致。此外，如果集合中的一致性代理执行指定缓存块的 CBO 指令，则生成的操作应应用于可由一致性代理的加载和存储操作访问的缓存中的任何和所有副本。

[NOTE]
====
_CBO 指令的操作被定义为仅对缓存中缓存的缓存块副本进行操作，这些缓存可由一致性代理执行的显式内存访问访问。这包括缓存中缓存块的副本，这些副本仅通过加载和存储操作间接访问，例如一致性指令缓存。_
====

受上述机制约束的缓存集构成 _一组一致性缓存_，每个一致性缓存具有以下行为，假设所有操作都由一组一致性代理中的代理执行：

* 允许一致性缓存分配和释放缓存块的副本，并执行 <<#memory-caches>> 中描述的读取和写入传输

* 允许一致性缓存执行写入传输到内存，前提是自缓存块上最近的失效、清理或刷新操作以来，存储操作已修改缓存块中的数据

* 至少一个一致性缓存负责在存储操作修改缓存块中的数据后执行写入传输到内存，直到缓存块上的下一次失效、清理或刷新操作，之后没有一致性缓存负责（或允许）执行写入传输到内存，直到下一次存储操作修改缓存块中的数据

* 如果自缓存块上最近的失效、清理或刷新操作以来，存储操作已修改缓存块中的数据，并且如果下一次清理或刷新操作需要写入传输到内存，则要求一致性缓存执行写入传输到内存

[NOTE]
====
_上述限制确保从内存读取传输获取且未被存储操作修改的“干净”缓存块副本，不能在以后覆盖由非一致性代理写入传输到内存的缓存块副本。_
====

非一致性代理可以启动缓存块操作，该操作对一组一致性代理访问的一致性缓存集进行操作。执行此类操作的机制是 _实现特定_ 的。

==== 内存排序

===== 保留程序顺序

保留程序顺序（缩写为 _PPO_）规则由 RVWMO 内存排序模型定义。CMO 指令产生的操作如何符合这些规则将在下面描述。

对于缓存块管理指令，生成的失效、清理和刷新操作在 PPO 规则中表现为存储，但有一个额外的重叠地址规则。具体来说，如果 _a_ 在程序顺序中先于 _b_，则如果满足以下条件，_a_ 将在全局内存顺序中先于 _b_：

* _a_ 是失效、清理或刷新，_b_ 是加载，并且 _a_ 和 _b_ 访问重叠的内存地址

[NOTE]
====
_上述规则确保程序顺序中随后的加载永远不会在全局内存顺序中出现在先前的失效、清理或刷新操作之前，该操作针对重叠地址。_
====

此外，失效、清理和刷新操作在 `FENCE` 指令中被分类为 W 或 O（取决于相应物理地址的物理内存属性），用于前驱和后继集。这些操作不受其他排序存储的指令（例如 `FENCE.I` 和 `SFENCE.VMA`）的排序。

对于缓存块清零指令，生成的存储操作在 PPO 规则中表现为存储，并由其他排序存储的指令排序。

最后，对于缓存块预取指令，生成的操作不受 PPO 规则的排序，也不受任何其他排序指令的排序。

===== 加载值

失效操作可能会改变加载可以返回的值集。特别是，加载值公理中添加了一个附加条件：

* 如果失效操作 _i_ 先于加载 _r_ 并对 _r_ 返回的字节 _x_ 进行操作，并且在程序顺序或全局内存顺序中 _i_ 和 _r_ 之间没有对 _x_ 的存储，则 _r_ 返回 _x_ 的以下任何值：

. 如果在全局内存顺序中没有对 _x_ 的清理或刷新操作先于 _i_，则为 _x_ 的初始值或任何先于 _i_ 的对 _x_ 的存储值

. 如果在全局内存顺序中没有对 _x_ 的存储先于对 _x_ 的清理或刷新操作，并且如果对 _x_ 的清理或刷新操作在全局内存顺序中先于 _i_，则为 _x_ 的初始值或任何先于 _i_ 的对 _x_ 的存储值

. 如果在全局内存顺序中对 _x_ 的存储先于对 _x_ 的清理或刷新操作，并且如果对 _x_ 的清理或刷新操作在全局内存顺序中先于 _i_，则为先于对 _x_ 的最新清理或刷新操作的对 _x_ 的最新存储值，或任何先于 _i_ 且在先于 _i_ 的对 _x_ 的最新清理或刷新操作之后对 _x_ 的存储值

. 无论上述条件如何，非一致性代理对 _x_ 的任何存储值

[NOTE]
====
_前三点描述了相对于清理或刷新操作，在全局内存顺序中不同点上可能的加载值。最后一点意味着加载值可能随时由非一致性代理产生。_
====

==== 陷阱

执行某些 CMO 指令可能会由于 CSR 状态（在 <<#csr_state>> 部分中描述）或由于地址转换和保护机制而导致陷阱。CMO 指令的陷阱行为将在以下部分中描述。

===== 非法指令和虚拟指令异常

缓存块管理指令和缓存块清零指令可能会根据当前特权模式和 <<#csr_state>> 部分中描述的 CMO 控制寄存器的状态引发非法指令异常或虚拟指令异常。

缓存块预取指令既不引发非法指令异常也不引发虚拟指令异常。

===== 页故障、访客页故障和访问故障异常

与加载和存储指令类似，CMO 指令是显式内存访问指令，它们计算有效地址。有效地址最终根据特权模式和启用的转换机制转换为物理地址，CMO 扩展对给定缓存块中的物理地址施加以下约束：

* 缓存块中 _所有_ 物理地址的 PMP 访问控制位应相同，如果 PMP 访问控制位授予写入权限，则也应授予读取权限

* 缓存块中 _所有_ 物理地址的 PMA 应相同，如果支持的访问类型 PMA 授予写入权限，则也应授予读取权限

如果上述约束未满足，则 CBO 指令的行为是未指定的。

[NOTE]
====
_本规范假定上述约束通常会为主内存区域满足，并且可能为某些 I/O 区域满足。_
====

此外，为了 PMP 和 PMA 检查的目的，CMO 指令的访问大小等于指令访问的缓存块的大小。

Zicboz 扩展为缓存块清零指令引入了额外的支持访问类型 PMA。主内存区域需要支持缓存块清零指令的访问；但是，I/O 区域可以指定是否支持缓存块清零指令的访问。

当加载指令或存储指令允许访问相应的物理地址时，允许缓存块管理指令访问指定的缓存块。如果加载指令或存储指令都不允许访问物理地址，但指令获取允许访问物理地址，则缓存块管理指令是否允许访问缓存块是未指定的。如果不允许访问缓存块，则缓存块管理指令会引发存储页故障或存储访客页故障异常（如果地址转换不允许任何访问），否则会引发存储访问故障异常。在地址转换期间，指令还会检查访问位，并可能根据需要引发异常或设置该位。

[NOTE]
====
_缓存块管理指令和指令获取之间的交互将在未来的扩展中指定。_

_如省略所示，缓存块管理指令不检查脏位，也不引发异常或设置该位。_
====

当存储指令允许访问相应的物理地址并且 PMA 指示缓存块清零指令是支持的访问类型时，允许缓存块清零指令访问指定的缓存块。如果不允许访问缓存块，则缓存块清零指令会引发存储页故障或存储访客页故障异常（如果地址转换不允许写入访问），否则会引发存储访问故障异常。在地址转换期间，指令还会检查访问位和脏位，并可能根据需要引发异常或设置这些位。

当加载指令、存储指令或指令获取允许访问相应的物理地址时，允许缓存块预取指令访问指定的缓存块。如果不允许访问缓存块，则缓存块预取指令不引发任何异常，也不应访问任何缓存或内存。在地址转换期间，指令 _不_ 检查访问位和脏位，也不引发异常或设置这些位。

当发生页故障、访客页故障或访问故障异常时，相关的 *tval CSR 会写入故障有效地址（即 _rs1_ 的值）。

[NOTE]
====
_与加载或存储指令一样，CMO 指令可能允许或不允许访问缓存块，具体取决于 `mstatus` 中的 `MPRV`、`MPV` 和 `MPP` 位以及 `mstatus`、`sstatus` 和 `vsstatus` 中的 `SUM` 和 `MXR` 位的状态。_

_本规范期望实现将缓存块管理指令视为存储/AMO 指令，因此存储/AMO 异常适用于这些指令，无论所需的权限如何。_
====

===== 地址未对齐异常

CMO 指令 _不_ 生成地址未对齐异常。

===== 断点异常和调试模式进入

除非调试架构规范另有定义，否则触发模块相对于 CMO 指令的行为是未指定的。

[NOTE]
====
_对于 Zicbom、Zicboz 和 Zicbop 扩展，本规范建议以下常见的触发模块行为：_

* 应支持类型 6 地址匹配触发器，即 `tdata1.type=6` 和 `mcontrol6.select=0`

* 应不支持类型 2 地址/数据匹配触发器，即 `tdata1.type=2`

* 内存访问的大小等于访问的缓存块的大小，并且比较值遵循与包含有效地址的缓存块对应的 NAPOT 内存区域的地址

* 除非将缓存块的编码添加到 `mcontrol6.size` 字段，否则地址触发器应仅在 `mcontrol6.size=0` 时匹配来自 CBO 指令的内存访问

_如果实现了 Zicbom 扩展，本规范建议以下附加触发模块行为：_

* 实现地址匹配触发器应是可选的

* 应不支持类型 6 数据匹配触发器，即 `tdata1.type=6` 和 `mcontrol6.select=1`

* 内存访问被视为存储，即地址触发器仅在 `mcontrol6.store=1` 时匹配

_如果实现了 Zicboz 扩展，本规范建议以下附加触发模块行为：_

* 实现地址匹配触发器应是强制性的

* 应支持类型 6 数据匹配触发器，即 `tdata1.type=6` 和 `mcontrol6.select=1`，并且实现这些触发器应是可选的

* 内存访问被视为存储，即地址触发器仅在 `mcontrol6.store=1` 时匹配

_如果实现了 Zicbop 扩展，本规范建议以下附加触发模块行为：_

* 实现地址匹配触发器应是可选的

* 应不支持类型 6 数据匹配触发器，即 `tdata1.type=6` 和 `mcontrol6.select=1`

* 内存访问可能被视为加载或存储，具体取决于实现，即当 `mcontrol6.load=1` 或 `mcontrol6.store=1` 时，地址触发器是否匹配这些指令是 _实现特定_ 的

_本规范还建议，触发模块相对于 Zicboz 扩展的行为应在调试架构规范的 1.0 版本中定义。触发模块相对于 Zicbom 和 Zicbop 扩展的行为预计将在未来的扩展中定义。_
====

===== 管理程序扩展

为了在陷阱时写入 `mtinst` 或 `htinst` 寄存器，为缓存块管理指令和缓存块清零指令定义了以下标准转换：

[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 'opcode'},
 { bits: 5,  name: 0x0 },
 { bits: 3,  name: 'funct3'},
 { bits: 5,  name: 0x0},
 { bits: 12, name: 'operation'},
]}
....

`operation` 字段对应于陷阱指令的 12 个最高有效位。

[NOTE]
====
_如管理程序扩展中所述，可以将零写入 `mtinst` 或 `htinst`，而不是上面定义的标准转换。_
====

==== 对受限 LR/SC 循环的影响

以下事件已添加到满足受限 LR/SC 循环提供的最终性保证的事件列表中，如 A 扩展中定义：

* 某个其他 hart 对 _H_ 的受限 LR/SC 循环中的 LR 指令的预留集执行缓存块管理指令或缓存块清零指令。

[NOTE]
====
_上述事件已添加，以适应无法区分存储失效和缓存块管理操作失效的缓存一致性协议。_

_除了上述事件，CMO 指令既不改变受限 LR/SC 循环的属性，也不修改它们提供的最终性保证。例如，执行 CMO 指令可能导致任何 hart 上的受限 LR/SC 循环周期性失败，或者可能导致同一 hart 上的不受限 LR/SC 序列始终失败。此外，执行缓存块预取指令不会影响任何 hart 上执行的受限 LR/SC 循环提供的最终性保证。_
====

==== 软件发现

初始的 CMO 扩展要求软件发现以下信息：

* 管理和预取指令的缓存块大小
* 清零指令的缓存块大小
* 每个特权级别的 CBIE 支持

其他通用缓存特性也可以在发现机制中指定。

[#csr_state,reftext="控制和状态寄存器状态"]
=== 控制和状态寄存器状态

三个 CSR 控制 CMO 指令的执行：

* `m{csrname}`
* `s{csrname}`
* `h{csrname}`

`s{csrname}` 寄存器由所有 supervisor 模式使用，包括 VS 模式。管理程序负责在访客上下文切换时保存和恢复 `s{csrname}`。`h{csrname}` 寄存器仅在实现并启用 H 扩展时存在。

每个 `x{csrname}` 寄存器（其中 `x` 是 `m`、`s` 或 `h`）具有以下通用格式：

.x{csrname} CSR 的通用格式
[cols="^10,^10,80a"]
|===
| 位    | 名称     | 描述

| [5:4]   | `CBIE`   | 缓存块失效指令启用。*WARL*。

启用在较低特权模式下执行缓存块失效指令 `CBO.INVAL`：

* `00`：指令引发非法指令或虚拟指令异常
* `01`：指令执行并执行刷新操作
* `10`：_保留_
* `11`：指令执行并执行失效操作

| [6]     | `CBCFE`  | 缓存块清理和刷新指令启用

启用在较低特权模式下执行缓存块清理指令 `CBO.CLEAN` 和缓存块刷新指令 `CBO.FLUSH`：

* `0`：指令引发非法指令或虚拟指令异常
* `1`：指令执行

| [7]     | `CBZE`   | 缓存块清零指令启用

启用在较低特权模式下执行缓存块清零指令 `CBO.ZERO`：

* `0`：指令引发非法指令或虚拟指令异常
* `1`：指令执行

|===

x{csrname} 寄存器根据当前特权模式和适当 CSR 的状态控制 CBO 指令执行，如下所述。

`CBO.INVAL` 指令根据 `x{csrname}.CBIE` 字段的状态执行或引发非法指令异常或虚拟指令异常：

[source,sail,subs="attributes+"]
--

// illegal-instruction exceptions
if (((priv_mode != M) && (m{csrname}.CBIE == 00)) ||
    ((priv_mode == U) && (s{csrname}.CBIE == 00)))
{
  <raise illegal-instruction exception>
}
// virtual-instruction exceptions
else if (((priv_mode == VS) && (h{csrname}.CBIE == 00)) ||
         ((priv_mode == VU) && ((h{csrname}.CBIE == 00) || (s{csrname}.CBIE == 00))))
{
  <raise virtual-instruction exception>
}
// execute instruction
else
{
  if (((priv_mode != M) && (m{csrname}.CBIE == 01)) ||
      ((priv_mode == U) && (s{csrname}.CBIE == 01)) ||
      ((priv_mode == VS) && (h{csrname}.CBIE == 01)) ||
      ((priv_mode == VU) && ((h{csrname}.CBIE == 01) || (s{csrname}.CBIE == 01))))
  {
    <execute CBO.INVAL and perform flush operation>
  }
  else
  {
    <execute CBO.INVAL and perform invalidate operation>
  }
}


--

[NOTE]
====
_在修改后的缓存块更新内存之前，如果 CSR 被编程为执行失效操作，`CBO.INVAL` 指令可能会暴露内存中过时的数据值。如果较低特权级别的软件执行失效操作并访问内存中的敏感信息，则此行为可能导致安全漏洞。_

_为避免此类漏洞，较高特权级别的软件必须在允许较低特权级别的软件对该块执行失效操作之前，对缓存块执行清理或刷新操作。或者，较高特权级别的软件可以编程 CSR，以便 `CBO.INVAL` 在较低特权级别下要么陷阱，要么执行刷新操作。_
====

`CBO.CLEAN` 或 `CBO.FLUSH` 指令根据 `x{csrname}.CBCFE` 位的状态执行或引发非法指令或虚拟指令异常：

[source,sail,subs="attributes+"]
--

// illegal-instruction exceptions
if (((priv_mode != M) && !m{csrname}.CBCFE) ||
    ((priv_mode == U) && !s{csrname}.CBCFE))
{
  <raise illegal-instruction exception>
}
// virtual-instruction exceptions
else if (((priv_mode == VS) && !h{csrname}.CBCFE) ||
         ((priv_mode == VU) && !(h{csrname}.CBCFE && s{csrname}.CBCFE)))
{
  <raise virtual-instruction exception>
}
// execute instruction
else
{
  <execute CBO.CLEAN or CBO.FLUSH>
}

--

最后，`CBO.ZERO` 指令根据 `x{csrname}.CBZE` 位的状态执行或引发非法指令或虚拟指令异常：

[source,sail,subs="attributes+"]
--

// illegal-instruction exceptions
if (((priv_mode != M) && !m{csrname}.CBZE) ||
    ((priv_mode == U) && !s{csrname}.CBZE))
{
  <raise illegal-instruction exception>
}
// virtual-instruction exceptions
else if (((priv_mode == VS) && !h{csrname}.CBZE) ||
         ((priv_mode == VU) && !(h{csrname}.CBZE && s{csrname}.CBZE)))
{
  <raise virtual-instruction exception>
}
// execute instruction
else
{
  <execute CBO.ZERO>
}

--

每个 `x{csrname}` 寄存器都是 WARL；但是，软件应从执行环境发现机制中确定合法值。

[#extensions,reftext="扩展"]
=== 扩展

CMO 指令在以下扩展中定义：

* <<#Zicbom>>
* <<#Zicboz>>
* <<#Zicbop>>

[#Zicbom,reftext="缓存块管理指令"]
==== 缓存块管理指令

缓存块管理指令使在一组一致性代理上运行的软件能够通过执行以下操作之一与一组非一致性代理通信：

* 失效操作使由一组非一致性代理执行的存储操作的数据在对两组都通用的点上对一致性代理集可见，方法是释放所有缓存块的副本，直到该点为止

* 清理操作使由一致性代理集执行的存储操作的数据在对两组都通用的点上对一组非一致性代理可见，方法是将缓存块副本写入传输到该点，前提是一致性代理执行了存储操作，该操作自上次缓存块上的失效、清理或刷新操作以来修改了缓存块中的数据

* 刷新操作原子地执行清理操作，然后执行失效操作

在 Zicbom 扩展中，指令操作到系统中 _所有_ 代理的共同点。换句话说，失效操作确保来自所有非一致性代理的存储操作对一致性代理集中的代理可见，并且清理操作确保来自一致性代理的存储操作对所有非一致性代理可见。

[NOTE]
====
_Zicbom 扩展不禁止超出上述架构定义的代理；但是，软件不能依赖定义的缓存操作对这些代理产生所需的效果。_

_未来的扩展可能会为性能优化目的定义不同的代理集。_
====

这些指令对有效地址在 _rs1_ 中指定的缓存块进行操作。有效地址通过适当的转换机制转换为相应的物理地址。

以下指令构成了 Zicbom 扩展：

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|cbo.clean _base_
|<<#insns-cbo_clean>>

|&#10003;
|&#10003;
|cbo.flush _base_
|<<#insns-cbo_flush>>

|&#10003;
|&#10003;
|cbo.inval _base_
|<<#insns-cbo_inval>>

|===

[#Zicboz,reftext="缓存块清零指令"]
==== 缓存块清零指令

缓存块清零指令将零存储到与缓存块对应的字节集。实现可以以任何顺序和任何粒度以及原子性更新字节，包括单个字节。

[NOTE]
====
_缓存块清零指令独立于底层内存位置的数据是否可缓存而存储零。此外，本规范不限制字节的写入方式。_
====

这些指令对缓存块或与缓存块对应的内存位置进行操作，其有效地址在 _rs1_ 中指定。有效地址通过适当的转换机制转换为相应的物理地址。

以下指令构成了 Zicboz 扩展：

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|cbo.zero _base_
|<<#insns-cbo_zero>>

|===

[#Zicbop,reftext="缓存块预取指令"]
==== 缓存块预取指令

缓存块预取指令是向硬件发出的 HINT，指示软件打算在不久的将来执行特定类型的内存访问。内存访问的类型是指令获取、数据读取（即加载）和数据写入（即存储）。

这些指令对缓存块进行操作，其有效地址是 _rs1_ 中指定的基地址与 _imm[11:0]_ 中编码的符号扩展偏移量之和，其中 _imm[4:0]_ 应等于 `0b00000`。有效地址通过适当的转换机制转换为相应的物理地址。

[NOTE]
====
_缓存块预取指令编码为 ORI 指令，其中 rd 等于 `0b00000`；但是，为了有效地址计算的目的，该字段也被解释为像存储指令一样的 imm[4:0]。_
====

以下指令构成了 Zicbop 扩展：

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|prefetch.i _offset_(_base_)
|<<#insns-prefetch_i>>

|&#10003;
|&#10003;
|prefetch.r _offset_(_base_)
|<<#insns-prefetch_r>>

|&#10003;
|&#10003;
|prefetch.w _offset_(_base_)
|<<#insns-prefetch_w>>

|===

[#insns,reftext="指令"]
=== 指令

[#insns-cbo_clean,reftext="缓存块清理"]
==== cbo.clean

概要::
对缓存块执行清理操作

助记符::
cbo.clean _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0xF,   attr: ['MISC-MEM'] },
 { bits: 5,  name: 0x0 },
 { bits: 3,  name: 0x2,   attr: ['CBO'] },
 { bits: 5,  name: 'rs1', attr: ['base'] },
 { bits: 12, name: 0x001, attr: ['CBO.CLEAN'] },
]}
....

描述::

*cbo.clean* 指令对有效地址为 _rs1_ 中指定的基地址的缓存块执行清理操作。可以省略偏移量操作数；否则，任何计算偏移量的表达式都应评估为零。该指令对执行指令的代理访问的一致性缓存集进行操作。

[NOTE]
====
_执行 *cbo.clean* 指令时，实现可以改为执行刷新操作，因为该操作的结果与在释放一致性缓存集中所有缓存副本之前执行清理操作的序列是无法区分的。_
====

操作::
[source,sail]
--
TODO
--

[#insns-cbo_flush,reftext="缓存块刷新"]
==== cbo.flush

概要::
对缓存块执行刷新操作

助记符::
cbo.flush _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0xF,   attr: ['MISC-MEM'] },
 { bits: 5,  name: 0x0 },
 { bits: 3,  name: 0x2,   attr: ['CBO'] },
 { bits: 5,  name: 'rs1', attr: ['base'] },
 { bits: 12, name: 0x002, attr: ['CBO.FLUSH'] },
]}
....

描述::

*cbo.flush* 指令对包含 _rs1_ 中指定地址的缓存块执行刷新操作。不要求 _rs1_ 与缓存块的大小对齐。在故障时，故障虚拟地址被认为是 rs1 中的值，而不是缓存块的基地址。该指令对执行指令的代理访问的一致性缓存集进行操作。

可以省略汇编 _offset_ 操作数。如果未省略，则任何计算偏移量的表达式都应评估为零。

操作::
[source,sail]
--
TODO
--

[#insns-cbo_inval,reftext="缓存块失效"]
==== cbo.inval

概要::
对缓存块执行失效操作

助记符::
cbo.inval _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0xF,   attr: ['MISC-MEM'] },
 { bits: 5,  name: 0x0 },
 { bits: 3,  name: 0x2,   attr: ['CBO'] },
 { bits: 5,  name: 'rs1', attr: ['base'] },
 { bits: 12, name: 0x000, attr: ['CBO.INVAL'] },
]}
....

描述::

*cbo.inval* 指令对包含 _rs1_ 中指定地址的缓存块执行失效操作。不要求 _rs1_ 与缓存块的大小对齐。在故障时，故障虚拟地址被认为是 rs1 中的值，而不是缓存块的基地址。该指令对执行指令的代理访问的一致性缓存集进行操作。

根据 CSR 编程，指令可能执行刷新操作而不是失效操作。

可以省略汇编 _offset_ 操作数。如果未省略，则任何计算偏移量的表达式都应评估为零。

[NOTE]
====
_执行 *cbo.inval* 指令时，实现可以改为执行刷新操作，因为该操作的结果与在执行失效操作之前执行写入传输到内存的序列是无法区分的。_
====

操作::
[source,sail]
--
TODO
--

[#insns-cbo_zero,reftext="缓存块清零"]
==== cbo.zero

概要::
将零存储到与缓存块对应的完整字节集

助记符::
cbo.zero _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0xF,   attr: ['MISC-MEM'] },
 { bits: 5,  name: 0x0 },
 { bits: 3,  name: 0x2,   attr: ['CBO'] },
 { bits: 5,  name: 'rs1', attr: ['base'] },
 { bits: 12, name: 0x004, attr: ['CBO.ZERO'] },
]}
....

描述::

*cbo.zero* 指令将零存储到包含 _rs1_ 中指定地址的缓存块对应的完整字节集。不要求 _rs1_ 与缓存块的大小对齐。在故障时，故障虚拟地址被认为是 rs1 中的值，而不是缓存块的基地址。实现可以或可以不原子地更新整个字节集。

可以省略汇编 _offset_ 操作数。如果未省略，则任何计算偏移量的表达式都应评估为零。

操作::
[source,sail]
--
TODO
--

[#insns-prefetch_i,reftext="用于指令获取的缓存块预取"]
==== prefetch.i

概要::
向硬件提供 HINT，指示缓存块可能在不久的将来被指令获取访问

助记符::
prefetch.i _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0x13,        attr: ['OP-IMM'] },
 { bits: 5,  name: 0x0,         attr: ['offset[4:0]'] },
 { bits: 3,  name: 0x6,         attr: ['ORI'] },
 { bits: 5,  name: 'rs1',       attr: ['base'] },
 { bits: 5,  name: 0x0,         attr: ['PREFETCH.I'] },
 { bits: 7, name: 'imm[11:5]',  attr: ['offset[11:5]'] },
]}
....

描述::

*prefetch.i* 指令向硬件指示，有效地址是 _rs1_ 中指定的基地址与 _imm[11:0]_ 中编码的符号扩展偏移量之和的缓存块（其中 _imm[4:0]_ 等于 `0b00000`），可能在不久的将来被指令获取访问。

[NOTE]
====
_实现可以选择将缓存块的副本缓存到指令获取访问的缓存中，以提高内存访问延迟，但这不是必需的行为。_
====

操作::
[source,sail]
--
TODO
--

[#insns-prefetch_r,reftext="用于数据读取的缓存块预取"]
==== prefetch.r

概要::
向硬件提供 HINT，指示缓存块可能在不久的将来被数据读取访问

助记符::
prefetch.r _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0x13,        attr: ['OP-IMM'] },
 { bits: 5,  name: 0x0,         attr: ['offset[4:0]'] },
 { bits: 3,  name: 0x6,         attr: ['ORI'] },
 { bits: 5,  name: 'rs1',       attr: ['base'] },
 { bits: 5,  name: 0x1,         attr: ['PREFETCH.R'] },
 { bits: 7, name: 'imm[11:5]',  attr: ['offset[11:5]'] },
]}
....

描述::

*prefetch.r* 指令向硬件指示，有效地址是 _rs1_ 中指定的基地址与 _imm[11:0]_ 中编码的符号扩展偏移量之和的缓存块（其中 _imm[4:0]_ 等于 `0b00000`），可能在不久的将来被数据读取（即加载）访问。

[NOTE]
====
_实现可以选择将缓存块的副本缓存到数据读取访问的缓存中，以提高内存访问延迟，但这不是必需的行为。_
====

操作::
[source,sail]
--
TODO
--

[#insns-prefetch_w,reftext="用于数据写入的缓存块预取"]
==== prefetch.w

概要::
向硬件提供 HINT，指示缓存块可能在不久的将来被数据写入访问

助记符::
prefetch.w _offset_(_base_)

编码::
[wavedrom, , svg]
....
{reg:[
 { bits: 7,  name: 0x13,        attr: ['OP-IMM'] },
 { bits: 5,  name: 0x0,         attr: ['offset[4:0]'] },
 { bits: 3,  name: 0x6,         attr: ['ORI'] },
 { bits: 5,  name: 'rs1',       attr: ['base'] },
 { bits: 5,  name: 0x3,         attr: ['PREFETCH.W'] },
 { bits: 7, name: 'imm[11:5]',  attr: ['offset[11:5]'] },
]}
....

描述::

*prefetch.w* 指令向硬件指示，有效地址是 _rs1_ 中指定的基地址与 _imm[11:0]_ 中编码的符号扩展偏移量之和的缓存块（其中 _imm[4:0]_ 等于 `0b00000`），可能在不久的将来被数据写入（即存储）访问。

[NOTE]
====
_实现可以选择将缓存块的副本缓存到数据写入访问的缓存中，以提高内存访问延迟，但这不是必需的行为。_
====

操作::
[source,sail]
--
TODO
--
