[[counters]]
== "Zicntr"和"Zihpm"扩展：计数器，版本 2.0

RISC-V ISA 提供了一组多达三十二个 64 位性能计数器和计时器，可通过非特权 XLEN 位只读 CSR 寄存器 `0xC00`–`0xC1F` 访问（当 XLEN=32 时，高 32 位通过 CSR 寄存器 `0xC80`–`0xC9F` 访问）。这些计数器分为"Zicntr"和"Zihpm"扩展。

=== "Zicntr"扩展：基本计数器和计时器

Zicntr 标准扩展包括前三个计数器（CYCLE、TIME 和 INSTRET），它们具有专用功能（分别为周期计数、实时时钟和已执行指令数）。Zicntr 扩展依赖于 Zicsr 扩展。

[NOTE]
====
我们建议在实现中提供这些基本计数器，因为它们对于基本性能分析、自适应和动态优化以及允许应用程序与实时流一起工作至关重要。单独的 Zihpm 扩展中的附加计数器可以帮助诊断性能问题，并且这些计数器应该以低开销从用户级应用程序代码访问。

某些执行环境可能会禁止访问计数器，例如，为了阻止时序侧信道攻击。
====

include::images/wavedrom/counters-diag.edn[]


对于 XLEN≥64 的基本 ISA，CSR 指令可以直接访问完整的 64 位 CSR。特别是，RDCYCLE、RDTIME 和 RDINSTRET 伪指令读取 `cycle`、`time` 和 `instret` 计数器的完整 64 位。

[NOTE]
====
计数器伪指令映射到只读 `csrrs rd, counter, x0` 规范形式，但其他只读 CSR 指令形式（基于 CSRRC/CSRRSI/CSRRCI）也是读取这些 CSR 的合法方式。
====

对于 XLEN=32 的基本 ISA，Zicntr 扩展使三个 64 位只读计数器能够以 32 位片段访问。RDCYCLE、RDTIME 和 RDINSTRET 伪指令提供低 32 位，RDCYCLEH、RDTIMEH 和 RDINSTRETH 伪指令提供相应计数器的高 32 位。
[NOTE]
====
我们要求计数器为 64 位宽，即使 XLEN=32，否则软件很难确定值是否溢出。对于低端实现，每个计数器的高 32 位可以通过软件计数器实现，这些计数器由低 32 位溢出触发的陷阱处理程序递增。下面给出的示例代码显示了如何使用单个 32 位宽伪指令安全地读取完整的 64 位宽值。
====

RDCYCLE 伪指令读取 `cycle` CSR 的低 XLEN 位，该 CSR 记录了 hart 运行的处理器核心自过去某个任意起始时间以来执行的时钟周期数。RDCYCLEH 仅在 XLEN=32 时存在，并读取相同周期计数器的位 63-32。底层 64 位计数器在实践中永远不应溢出。周期计数器前进的速率将取决于实现和操作环境。执行环境应提供一种方法来确定周期计数器递增的当前速率（周期/秒）。

[NOTE]
====
RDCYCLE 旨在返回处理器核心执行的周期数，而不是 hart。鉴于某些实现选择（例如 AMD Bulldozer），精确定义什么是"核心"很困难。鉴于实现范围（包括软件仿真），精确定义什么是"时钟周期"也很困难，但其目的是 RDCYCLE 与其他性能计数器一起用于性能监控。特别是，当只有一个 hart/核心时，人们会期望周期计数/已退役指令数来衡量 hart 的 CPI。

核心不必完全暴露给软件，实现者可能选择假装一个物理核心上的多个 hart 在具有一个 hart/核心的单独核心上运行，并为每个 hart 提供单独的周期计数器。这在简单的桶式处理器（例如 CDC 6600 外围处理器）中可能是有意义的，其中 hart 间时序交互不存在或最小。

当有多个 hart/核心和动态多线程时，通常不可能分离每个 hart 的周期（尤其是在 SMT 中）。可能可以定义一个单独的性能计数器来尝试捕获特定 hart 运行的周期数，但这个定义必须非常模糊才能涵盖所有可能的线程实现。例如，我们是否只计算为该 hart 发出任何指令执行的周期，和/或任何指令退役的周期，或者包括该 hart 占用机器资源但由于停顿而无法执行的周期，而其他 hart 进入执行？可能需要"以上所有"才能获得可理解的性能统计数据。定义每个 hart 周期计数的这种复杂性，以及在调整多线程代码时无论如何都需要总的每个核心周期计数，导致只标准化了每个核心周期计数器，这对于常见的单个 hart/核心情况也恰好很有效。

标准化"睡眠"期间发生的事情是不实际的，因为"睡眠"的含义在执行环境之间没有标准化，但如果整个核心暂停（在深度睡眠中完全时钟门控或断电），那么它就没有执行时钟周期，并且根据规范周期计数不应增加。有许多细节，例如，从断电事件唤醒后重置处理器所需的时钟周期是否应计算在内，这些都被认为是执行环境特定的细节。

尽管没有适用于所有平台的精确定义，但这对于大多数平台仍然是一个有用的功能，不精确、通用、"通常正确"的标准在这里比没有标准更好。RDCYCLE 的目的主要是性能监控/调整，规范的编写考虑了这一目标。
====

RDTIME 伪指令读取"time"CSR 的低 XLEN 位，该 CSR 记录了自过去某个任意起始时间以来经过的挂钟实时。RDTIMEH 仅在 XLEN=32 时存在，并读取相同实时计数器的位 63-32。底层 64 位计数器随着实时时钟的每次滴答递增一，并且，对于现实的实时时钟频率，在实践中永远不应溢出。执行环境应提供一种方法来确定计数器滴答的周期（秒/滴答）。周期应在小误差范围内保持恒定。环境应提供一种方法来确定时钟的准确性（即，标称和实际实时时钟周期之间的最大相对误差）。

[NOTE]
====
在某些简单平台上，周期计数可能代表 RDTIME 的有效实现，在这种情况下，RDTIME 和 RDCYCLE 可能返回相同的结果。

鉴于各种可能的实现平台，很难对时钟周期提供严格的规定。最大误差范围应根据平台的要求设置。
====

所有 hart 的实时时钟必须同步到实时时钟的一个滴答之内。

[NOTE]
====
与其他架构规定一样，只要看起来"好像"hart 同步到实时时钟的一个滴答之内就足够了，即软件无法观察到两个 hart 上观察到的实时时钟值之间存在更大的增量。

如果，例如，实时时钟以 1 GHz 的频率递增，那么所有 hart 必须看起来同步到 1 纳秒之内。
但对于此示例实现，只以例如 100 MHz 的频率更新实时时钟，每次递增 10 个滴答也是可以接受的。
只要软件无法观察到这种看似违反上述同步要求的行为，并且软件始终观察到跨 hart 的时间单调不递减，那么此实现就是符合要求的。

平台规范可以，例如，指定一个表观实时时钟滴答频率（例如 1 GHz）以及一个最小更新频率（例如 100 MHz），在该频率下，软件保证能够观察到更新的时间值。
软件可以更频繁地读取时间，但它应该只观察单调不递减的值，并且它应该至少每 10 纳秒（对应于此示例中的 100 MHz 更新频率）观察到一个新值。
====

RDINSTRET 伪指令读取 `instret` CSR 的低 XLEN 位，该 CSR 记录了该 hart 自过去某个任意起始点以来已退役的指令数。RDINSTRETH 仅在 XLEN=32 时存在，并读取相同指令计数器的位 63-32。底层 64 位计数器在实践中永远不应溢出。

[NOTE]
====
导致同步异常的指令，包括 ECALL 和 EBREAK，不被视为退役，因此不递增 `instret` CSR。
====

以下代码序列将有效的 64 位周期计数器值读入 `x3:x2`，即使计数器在读取其高半部分和低半部分之间其低半部分溢出。

[source,asm.]
.当 XLEN=32 时读取 64 位周期计数器的示例代码。
    again:
        rdcycleh     x3
        rdcycle      x2
        rdcycleh     x4
        bne          x3, x4, again


=== "Zihpm"扩展：硬件性能计数器

Zihpm 扩展包括多达 29 个额外的非特权 64 位硬件性能计数器，`hpmcounter3-hpmcounter31`。当 XLEN=32 时，这些性能计数器的高 32 位可通过附加的 CSR `hpmcounter3h-hpmcounter31h` 访问。Zihpm 扩展依赖于 Zicsr 扩展。

[NOTE]
====
在某些应用程序中，能够在同一时刻读取多个计数器很重要。在多任务环境下运行时，用户线程在尝试读取计数器时可能会发生上下文切换。一种解决方案是用户线程在读取其他计数器之前和之后读取实时计数器，以确定序列中间是否发生了上下文切换，在这种情况下可以重试读取。我们考虑添加输出锁存器以允许用户线程原子地快照计数器值，但这会增加用户上下文的大小，特别是对于具有更丰富计数器集的实现。
====

这些附加计数器的实现数量和宽度，以及它们计数的事件集，是平台特定的。访问未实现或配置错误的计数器可能会导致非法指令异常或返回常量值。

执行环境应提供一种方法来确定已实现计数器的数量和宽度，以及配置每个计数器要计数的事件的接口。

[NOTE]
====
对于在 RISC-V 特权平台上实现的执行环境，特权架构手册描述了控制较低特权模式访问这些计数器以及设置要计数事件的特权 CSR。

替代执行环境（例如，仅用户级软件性能模型）可以提供替代机制来配置性能计数器计数的事件。

最终标准化事件设置以计数 ISA 级指标（例如，执行的浮点指令数）以及可能的一些常见微架构指标（例如，"L1 指令缓存未命中"）将是有用的。
====