== “D”扩展：双精度浮点，版本 2.2

本章描述了标准双精度浮点指令集扩展，名为“D”，它添加了符合 IEEE 754-2008 算术标准的双精度浮点计算指令。D 扩展依赖于基本单精度指令子集 F。
(((双精度，浮点)))
(((浮点，双精度)))

=== D 寄存器状态

D 扩展将 32 个浮点寄存器 `f0-f31` 扩展到 64 位（<<fprs>> 中 FLEN=64）。`f` 寄存器现在可以容纳 32 位或 64 位浮点值，如下文 <<nanboxing>> 所述。

[NOTE]
====
FLEN 可以是 32、64 或 128，具体取决于支持的 F、D 和 Q 扩展。最多可以支持四种不同的浮点精度，包括 H、F、D 和 Q。
====
(((浮点，支持的精度)))

[[nanboxing]]
=== 窄值 NaN 装箱

当支持多种浮点精度时，窄 _n_ 位类型（_n_<FLEN）的有效值以 FLEN 位 NaN 值的低 _n_ 位表示，此过程称为 NaN 装箱。有效 NaN 装箱值的上部必须全部为 1。因此，当作为任何更宽的 _m_ 位值（_n_ < _m_ ≤ FLEN）查看时，有效的 NaN 装箱 _n_ 位值显示为负静默 NaN (qNaN)。任何将窄结果写入“f”寄存器的操作都必须将所有 1 写入最上部的 FLEN-_n_ 位，以生成合法的 NaN 装箱值。
(((浮点，要求)))

[NOTE]
====
软件可能不知道浮点寄存器中存储的数据的当前类型，但必须能够保存和恢复寄存器值，因此必须定义使用更宽操作传输更窄值的结果。常见情况是被调用者保存的寄存器，但对于包括可变参数函数、用户级线程库、虚拟机迁移和调试在内的功能，标准约定也是可取的。
====

浮点 _n_ 位传输操作将 IEEE 标准格式中保存的外部值移入和移出 `f` 寄存器，并包括浮点加载和存储 (FL__n__/FS__n__) 以及浮点移动指令 (FMV._n_.X/FMV.X._n_)。将窄 _n_ 位传输（_n_<FLEN）移入 `f` 寄存器将创建有效的 NaN 装箱值。将窄 _n_ 位传输移出浮点寄存器将传输寄存器的低 _n_ 位，忽略高 FLEN-_n_ 位。

除了上一段中描述的传输操作外，所有其他对窄 _n_ 位操作（_n_<FLEN）的浮点操作都会检查输入操作数是否正确 NaN 装箱，即所有高 FLEN-_n_ 位是否为 1。如果是，则使用输入的 _n_ 个最低有效位作为输入值，否则输入值被视为 _n_ 位规范 NaN。

[NOTE]
====
本文档的早期版本没有定义将更窄或更宽操作数的结果输入到操作中的行为，除了要求更宽的保存和恢复将保留更窄操作数的值。新定义消除了这种实现特定的行为，同时仍然适应浮点单元的非重编码和重编码实现。新定义还有助于通过在值使用不正确时传播 NaN 来捕获软件错误。

非重编码实现会在每个浮点操作的输入和输出处解包和打包操作数到 IEEE 标准格式。非重编码实现的 NaN 装箱成本主要在于检查更窄操作的高位是否表示合法的 NaN 装箱值，以及将所有 1 写入结果的高位。

重编码实现使用更方便的内部格式来表示浮点值，并添加了一个额外的指数位以允许所有值保持归一化。重编码实现的成本主要在于跟踪内部类型和符号位所需的额外标记，但这可以通过在指数字段中内部重编码 NaN 来完成，而无需添加新的状态位。需要对用于在重编码格式之间传输值的流水线进行少量修改，但数据路径和延迟成本最小。重编码过程无论如何都必须处理宽操作数的输入次正规值的移位，并且提取 NaN 装箱值与归一化过程类似，只是跳过前导 1 位而不是跳过前导 0 位，从而允许共享数据路径多路复用。_
====

[[fld_fsd]]
=== 双精度加载和存储指令

FLD 指令将双精度浮点值从内存加载到浮点寄存器 _rd_ 中。FSD 将双精度值从浮点寄存器存储到内存中。
(((浮点，加载和存储)))

[NOTE]
====
双精度值可以是 NaN 装箱的单精度值。
====

include::images/wavedrom/double-ls.edn[]
[[double-ls]]
//.双精度加载和存储

FLD 和 FSD 仅在有效地址自然对齐且 XLEN≥64 时才保证原子执行。

FLD 和 FSD 不修改正在传输的位；特别是，非规范 NaN 的有效载荷得以保留。

=== 双精度浮点计算指令

双精度浮点计算指令的定义类似于其单精度对应指令，但对双精度操作数进行操作并产生双精度结果。

include::images/wavedrom/double-fl-compute.edn[]
[[fl-compute]]
//.双精度浮点计算

=== 双精度浮点转换和移动指令

浮点到整数和整数到浮点转换指令编码在 OP-FP 主操作码空间中。FCVT.W.D 或 FCVT.L.D 将浮点寄存器 _rs1_ 中的双精度浮点数分别转换为整数寄存器 _rd_ 中的有符号 32 位或 64 位整数。FCVT.D.W 或 FCVT.D.L 将整数寄存器 _rs1_ 中的 32 位或 64 位有符号整数分别转换为浮点寄存器 _rd_ 中的双精度浮点数。FCVT.WU.D、FCVT.LU.D、FCVT.D.WU 和 FCVT.D.LU 变体转换为或从无符号整数值转换。对于 RV64，FCVT.W[U].D 符号扩展 32 位结果。FCVT.L[U].D 和 FCVT.D.L[U] 是 RV64 独有的指令。FCVT._int_.D 的有效输入范围和无效输入的行为与 FCVT._int_.S 相同。
(((浮点，转换和移动)))

所有浮点到整数和整数到浮点转换指令都根据 _rm_ 字段进行舍入。请注意，FCVT.D.W[U] 总是产生精确结果，不受舍入模式影响。

include::images/wavedrom/double-fl-convert-mv.edn[]
[[fl-convert-mv]]
//.双精度浮点转换和移动

双精度到单精度和单精度到双精度转换指令 FCVT.S.D 和 FCVT.D.S 编码在 OP-FP 主操作码空间中，源和目标都是浮点寄存器。_rs2_ 字段编码源的数据类型，_fmt_ 字段编码目标的数据类型。FCVT.S.D 根据 RM 字段进行舍入；FCVT.D.S 永远不会舍入。
(((双精度，到单精度)))
(((单精度，到双精度)))

include::images/wavedrom/fcvt-sd-ds.edn[]
[[fcvt-sd-ds]]
//.双精度 FCVT.S.D 和 FCVT.D.S

浮点到浮点符号注入指令 FSGNJ.D、FSGNJN.D 和 FSGNJX.D 的定义类似于单精度符号注入指令。
//FSGNJ.D、FSGNJN.D 和 FSGNJX.D

include::images/wavedrom/fsjgnjnx-d.edn[]
//.双精度符号注入

仅当 XLEN≥64 时，才提供指令以在浮点寄存器和整数寄存器之间移动位模式。FMV.X.D 将浮点寄存器 _rs1_ 中的双精度值移动到整数寄存器 _rd_ 中 IEEE 754-2008 标准编码的表示形式。FMV.D.X 将整数寄存器 _rs1_ 中编码为 IEEE 754-2008 标准编码的双精度值移动到浮点寄存器 _rd_ 中。

FMV.X.D 和 FMV.D.X 不修改正在传输的位；特别是，非规范 NaN 的有效载荷得以保留。

include::images/wavedrom/d-xwwx.edn[]
[[fmvxddx]]
//.双精度浮点移动到 _rd_

[NOTE]
====
RISC-V ISA 的早期版本有额外的指令，允许 RV32 系统在 64 位浮点寄存器的上半部分和下半部分以及整数寄存器之间传输。然而，这些将是唯一具有部分寄存器写入的指令，并且会增加具有重编码浮点或寄存器重命名实现的复杂性，需要流水线读-改-写序列。
如果它们遵循这种模式，扩展到处理 RV32 和 RV64 的四精度也将需要额外的指令。ISA 的定义旨在减少显式整数-浮点寄存器移动的数量，通过让转换和比较将结果写入适当的寄存器文件，因此我们预计这些指令的收益将低于其他 ISA。

我们注意到，对于实现 64 位浮点单元（包括融合乘加支持和 64 位浮点加载和存储）的系统，从 32 位整数数据路径移动到 64 位整数数据路径的边际硬件成本很低，并且可以使用支持 32 位宽地址空间和指针的软件 ABI 来避免静态数据和动态内存流量的增长。
====


=== 双精度浮点比较指令

双精度浮点比较指令的定义类似于其单精度对应指令，但对双精度操作数进行操作。
(((浮点，比较)))

include::images/wavedrom/double-fl-compare.edn[]
[[fl-compare]]
//.双精度浮点比较

=== 双精度浮点分类指令

双精度浮点分类指令 FCLASS.D 的定义类似于其单精度对应指令，但对双精度操作数进行操作。
(((浮点，分类)))

include::images/wavedrom/double-fl-class.edn[]
[[fl-class]]
//.双精度浮点分类
