:stem: latexmath

[[single-float]]
== “F”扩展：单精度浮点，版本 2.2

本章描述了单精度浮点标准指令集扩展，名为“F”，它添加了符合 IEEE 754-2008 算术标准 cite:[ieee754-2008] 的单精度浮点计算指令。F 扩展依赖于“Zicsr”扩展以进行控制和状态寄存器访问。

=== F 寄存器状态

F 扩展增加了 32 个浮点寄存器 `f0-f31`，每个寄存器宽 32 位，以及一个浮点控制和状态寄存器 `fcsr`，其中包含浮点单元的操作模式和异常状态。此附加状态如 <<fprs>> 所示。我们使用术语 FLEN 来描述 RISC-V ISA 中浮点寄存器的宽度，对于 F 单精度浮点扩展，FLEN=32。大多数浮点指令对浮点寄存器文件中的值进行操作。浮点加载和存储指令在寄存器和内存之间传输浮点值。还提供了在整数寄存器文件之间传输值的指令。

[NOTE]
====
我们考虑了整数和浮点值的统一寄存器文件，因为这简化了软件寄存器分配和调用约定，并减少了总的用户状态。然而，分离的组织增加了给定指令宽度可访问的寄存器总数，简化了为宽超标量发射提供足够寄存器文件端口，支持解耦浮点单元架构，并简化了内部浮点编码技术的使用。分离寄存器文件架构的编译器支持和调用约定已得到充分理解，并且在浮点寄存器文件状态上使用脏位可以减少上下文切换开销。
====

[[fprs]]
.RISC-V 标准 F 扩展单精度浮点状态
[cols="<,^,>",options="header",width="50%",align="center",grid="rows"]
|===
| [.small]#FLEN-1#| >| [.small]#0#
3+^| [.small]#f0#
3+^| [.small]#f1#
3+^| [.small]#f2#
3+^| [.small]#f3#
3+^| [.small]#f4#
3+^| [.small]#f5#
3+^| [.small]#f6#
3+^| [.small]#f7#
3+^| [.small]#f8#
3+^| [.small]#f9#
3+^| [.small]#f10#
3+^| [.small]#f11#
3+^| [.small]#f12#
3+^| [.small]#f13#
3+^| [.small]#f14#
3+^| [.small]#f15#
3+^| [.small]#f16#
3+^| [.small]#f17#
3+^| [.small]#f18#
3+^| [.small]#f19#
3+^| [.small]#f20#
3+^| [.small]#f21#
3+^| [.small]#f22#
3+^| [.small]#f23#
3+^| [.small]#f24#
3+^| [.small]#f25#
3+^| [.small]#f26#
3+^| [.small]#f27#
3+^| [.small]#f28#
3+^| [.small]#f29#
3+^| [.small]#f30#
3+^| [.small]#f31#
3+^| [.small]#FLEN#
| [.small]#31#| >| [.small]#0#
3+^|  [.small]#fcsr#
3+^| [.small]#32#
|===

=== 浮点控制和状态寄存器

浮点控制和状态寄存器 `fcsr` 是一个 RISC-V 控制和状态寄存器 (CSR)。它是一个 32 位读/写寄存器，用于选择浮点算术运算的动态舍入模式并保存累积的异常标志，如 <<fcsr>> 所示。

[[fcsr, 浮点控制和状态寄存器]]
.浮点控制和状态寄存器
include::images/wavedrom/float-csr.edn[]

`fcsr` 寄存器可以使用 FRCSR 和 FSCSR 指令进行读写，这些指令是基于底层 CSR 访问指令构建的汇编器伪指令。FRCSR 通过将 `fcsr` 复制到整数寄存器 _rd_ 来读取 `fcsr`。FSCSR 通过将原始值复制到整数寄存器 _rd_，然后将从整数寄存器 _rs1_ 获取的新值写入 `fcsr` 来交换 `fcsr` 中的值。

`fcsr` 中的字段也可以通过不同的 CSR 地址单独访问，并为这些访问定义了单独的汇编器伪指令。FRRM 指令读取舍入模式字段 `frm`（`fcsr` 的 7-5 位），并将其复制到整数寄存器 _rd_ 的最低有效三位中，其他所有位为零。FSRM 通过将原始值复制到整数寄存器 _rd_，然后将从整数寄存器 _rs1_ 的最低有效三位获取的新值写入 `frm` 来交换 `frm` 中的值。FRFLAGS 和 FSFLAGS 为累积异常标志字段 `fflags`（`fcsr` 的 4-0 位）类似地定义。

`fcsr` 的 31-8 位保留用于其他标准扩展。如果不存在这些扩展，实现应忽略对这些位的写入，并在读取时提供零值。标准软件应保留这些位的内容。

浮点运算使用指令中编码的静态舍入模式，或 `frm` 中保存的动态舍入模式。舍入模式的编码如 <<rm>> 所示。指令 _rm_ 字段中的值 111 选择 `frm` 中保存的动态舍入模式。当使用保留舍入模式执行时，依赖于舍入模式的浮点指令的行为是 _保留的_，包括静态保留舍入模式 (101-110) 和动态保留舍入模式 (101-111)。某些指令，包括加宽转换，具有 _rm_ 字段，但数学上不受舍入模式影响；软件应将其 _rm_ 字段设置为 RNE (000)，但实现必须像往常一样处理 _rm_ 字段（特别是关于解码合法与保留编码）。

[[rm]]
.舍入模式编码。
[%autowidth,float="center",align="center",cols="^,^,<",options="header"]
|===
|舍入模式 |助记符 |含义
|000 |RNE |四舍五入到最近，偶数优先
|001 |RTZ |向零舍入
|010 |RDN |向下舍入（朝向 latexmath:[$-\infty$]）
|011 |RUP |向上舍入（朝向 latexmath:[$\+\infty$]）
|100 |RMM |四舍五入到最近，最大幅度优先
|101 | |_保留供将来使用。
|110 | |_保留供将来使用。
|111 |DYN |在指令 _rm_ 字段中，选择动态舍入模式；在舍入模式寄存器中，_保留_。
|===

[NOTE]
====
C99 语言标准有效地强制要求提供动态舍入模式寄存器。在典型实现中，对动态舍入模式 CSR 状态的写入将使流水线串行化。静态舍入模式用于实现专门的算术运算，这些运算通常必须频繁地在不同舍入模式之间切换。

F 规范的批准版本规定，当指令以保留的动态舍入模式执行时，会引发非法指令异常。这已弱化为保留，这与静态舍入模式指令的行为相匹配。在遇到保留编码时引发非法指令异常仍然是有效行为，因此与批准规范兼容的实现与弱化规范兼容。
====

累积异常标志指示自上次由软件重置该字段以来，任何浮点算术指令上出现的异常情况，如 <<bitdef>> 所示。基本 RISC-V ISA 不支持在设置浮点异常标志时生成陷阱。
(((浮点，异常标志)))

[[bitdef]]
.累积异常标志编码。
[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
|标志助记符 |标志含义
|NV |无效操作
|DZ |除以零
|OF |溢出
|UF |下溢
|NX |不精确
|===

[NOTE]
====
根据标准允许，我们不支持 F 扩展中的浮点异常陷阱，而是要求软件中显式检查标志。我们考虑过添加直接由浮点累积异常标志内容控制的分支，但最终选择省略这些指令以保持 ISA 简单。
====

=== NaN 生成和传播

除非另有说明，如果浮点运算的结果是 NaN，则它是规范 NaN。规范 NaN 具有正号，并且除了 MSB（也称为静默位）之外，所有有效数字位都清除。对于单精度浮点，这对应于模式 `0x7fc00000`。
(((NaN，生成)))
(((NaN，传播)))

[NOTE]
====
我们考虑过传播 NaN 有效载荷，正如标准所建议的那样，但这个决定会增加硬件成本。
此外，由于此功能在标准中是可选的，因此不能在可移植代码中使用。

实现者可以自由地提供 NaN 有效载荷传播方案作为非标准扩展，通过非标准操作模式启用。但是，上面描述的规范 NaN 方案必须始终受支持，并且应该是默认模式。
====
'''
[NOTE]
====
我们要求实现在异常情况下返回标准规定的默认值，而无需用户级软件的进一步干预（与 Alpha ISA 浮点陷阱屏障不同）。我们相信硬件对异常情况的全面处理将变得更加普遍，因此希望避免使用户级 ISA 复杂化以优化其他方法。
实现总是可以陷阱到机器模式软件处理程序以提供异常默认值。
====

=== 次正规算术

次正规数上的操作按照 IEEE 754-2008 标准处理。
(((操作，次正规)))

用 IEEE 标准的说法，微小性是在舍入后检测到的。
(((微小性，处理)))

[NOTE]
====
在舍入后检测微小性会减少虚假的下溢信号。
====

=== 单精度加载和存储指令

浮点加载和存储使用与整数基本 ISA 相同的基址+偏移寻址模式，其中寄存器 _rs1_ 中有一个基址和一个 12 位有符号字节偏移量。FLW 指令将单精度浮点值从内存加载到浮点寄存器 _rd_ 中。FSW 将单精度值从浮点寄存器 _rs2_ 存储到内存中。

include::images/wavedrom/sp-load-store-2.edn[]
[[sp-ldst]]
//.SP 加载和存储

FLW 和 FSW 仅在有效地址自然对齐时才保证原子执行。

FLW 和 FSW 不修改正在传输的位；特别是，非规范 NaN 的有效载荷得以保留。

如 <<ldst>> 中所述，执行环境定义了未对齐浮点加载和存储是隐式处理还是引发包含或致命陷阱。

[[single-float-compute]]
=== 单精度浮点计算指令

具有一个或两个源操作数的浮点算术指令使用 R 类型格式和 OP-FP 主操作码。FADD.S 和 FMUL.S 分别在 _rs1_ 和 _rs2_ 之间执行单精度浮点加法和乘法。FSUB.S 执行 _rs1_ 减去 _rs2_ 的单精度浮点减法。FDIV.S 执行 _rs1_ 除以 _rs2_ 的单精度浮点除法。FSQRT.S 计算 _rs1_ 的平方根。在每种情况下，结果都写入 _rd_。

2 位浮点格式字段 _fmt_ 的编码如 <<fmt>> 所示。对于 F 扩展中的所有指令，它都设置为 _S_ (00)。

[[fmt]]
.格式字段编码
[%autowidth,float="center",align="center",cols="^,^,<",options="header",]
|===
|_fmt_ 字段 |助记符 |含义
|00 |S |32 位单精度
|01 |D |64 位双精度
|10 |H |16 位半精度
|11 |Q |128 位四精度
|===

所有执行舍入的浮点操作都可以使用 _rm_ 字段选择舍入模式，编码如 <<rm>> 所示。

浮点最小数和最大数指令 FMIN.S 和 FMAX.S 分别将 _rs1_ 和 _rs2_ 中较小或较大的值写入 _rd_。对于这些指令，值 latexmath:[$-0.0$] 被认为小于值 latexmath:[$+0.0$]。如果两个输入都是 NaN，则结果是规范 NaN。如果只有一个操作数是 NaN，则结果是非 NaN 操作数。
信令 NaN 输入会设置无效操作异常标志，即使结果不是 NaN。

[NOTE]
====
请注意，在 F 扩展的 2.2 版本中，FMIN.S 和 FMAX.S 指令已修改为实现提议的 IEEE 754-201x `minimumNumber` 和 `maximumNumber` 操作，而不是 IEEE 754-2008 minNum 和 maxNum 操作。这些操作在处理信令 NaN 方面有所不同。
====

include::images/wavedrom/spfloat.edn[]
[[spfloat]]
//.单精度浮点计算指令
(((浮点，融合乘加)))

浮点融合乘加指令需要新的标准指令格式。R4 类型指令指定三个源寄存器（_rs1_、_rs2_ 和 _rs3_）和一个目标寄存器（_rd_）。此格式仅用于浮点融合乘加指令。

FMADD.S 将 _rs1_ 和 _rs2_ 中的值相乘，加上 _rs3_ 中的值，并将最终结果写入 _rd_。FMADD.S 计算 _(rs1latexmath:[$\times$]rs2)latexmath:[$\+$]rs3_。

FMSUB.S 将 _rs1_ 和 _rs2_ 中的值相乘，减去 _rs3_ 中的值，并将最终结果写入 _rd_。FMSUB.S 计算 _(rs1latexmath:[$\times$]rs2)latexmath:[$\-$]rs3_。

FNMSUB.S 将 _rs1_ 和 _rs2_ 中的值相乘，对乘积取反，加上 _rs3_ 中的值，并将最终结果写入 _rd_。FNMSUB.S 计算 _-(rs1latexmath:[$\times$]rs2)latexmath:[$\+$]rs3_。

FNMADD.S 将 _rs1_ 和 _rs2_ 中的值相乘，对乘积取反，减去 _rs3_ 中的值，并将最终结果写入 _rd_。FNMADD.S 计算 _-(rs1latexmath:[$\times$]rs2)latexmath:[$\-$]rs3_。

[NOTE]
====
FNMSUB 和 FNMADD 指令的命名有些反直觉，这归因于 MIPS-IV 中相应指令的命名。MIPS 指令被定义为对和取反，而不是像 RISC-V 指令那样对乘积取反，因此当时的命名方案更合理。这两个定义在有符号零结果方面有所不同。RISC-V 的定义与 x86 和 ARM 融合乘加指令的行为相匹配，但不幸的是，RISC-V 的 FNMSUB 和 FNMADD 指令名称与 x86 相比是交换的，而 RISC-V 的 FMSUB 和 FNMADD 指令名称与 ARM 相比是交换的。
====

include::images/wavedrom/spfloat2.edn[]
[[fnmaddsub]]
//.F[N]MADD/F[N]MSUB 指令

[NOTE]
====
融合乘加 (FMA) 指令占据了 32 位指令编码空间的很大一部分。考虑的一些替代方案是将 FMA 限制为仅使用动态舍入模式，但静态舍入模式在利用缺乏乘积舍入的代码中很有用。另一个替代方案是使用 rd 提供 rs3，但这在某些常见序列中需要额外的移动指令。当前的设计仍然保留了 32 位编码空间的很大一部分，同时避免了 FMA 的非正交性。
====

当乘数是 latexmath:[$\infty$] 和零时，即使加数是静默 NaN，融合乘加指令也必须设置无效操作异常标志。

[NOTE]
====
IEEE 754-2008 标准允许但不要求对操作 latexmath:[$\infty\times 0\ +$]qNaN 引发无效异常。
====

=== 单精度浮点转换和移动指令

浮点到整数和整数到浮点转换指令编码在 OP-FP 主操作码空间中。FCVT.W.S 或 FCVT.L.S 将浮点寄存器 _rs1_ 中的浮点数分别转换为整数寄存器 _rd_ 中的有符号 32 位或 64 位整数。FCVT.S.W 或 FCVT.S.L 将整数寄存器 _rs1_ 中的 32 位或 64 位有符号整数分别转换为浮点寄存器 _rd_ 中的浮点数。FCVT.WU.S、FCVT.LU.S、FCVT.S.WU 和 FCVT.S.LU 变体转换为或从无符号整数值转换。对于 XLENlatexmath:[$>32$]，FCVT.W[U].S 将 32 位结果符号扩展到目标寄存器宽度。FCVT.L[U].S 和 FCVT.S.L[U] 是 RV64 独有的指令。如果舍入结果无法在目标格式中表示，则将其截断为最近的值并设置无效标志。<<int_conv>> 给出了 FCVT._int_.S 的有效输入范围和无效输入的行为。
(((浮点，转换)))

所有浮点到整数和整数到浮点转换指令都根据 _rm_ 字段进行舍入。浮点寄存器可以使用 FCVT.S.W _rd_, `x0` 初始化为浮点正零，这永远不会设置任何异常标志。

[[int_conv]]
.浮点到整数转换的域和无效输入的行为
[%autowidth,float="center",align="center",cols="<,>,>,>,>",options="header",]
|===
| |FCVT.W.S |FCVT.WU.S |FCVT.L.S |FCVT.LU.S
|最小有效输入（舍入后） |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|最大有效输入（舍入后） |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]

|超出范围负输入的输出 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|latexmath:[$-\infty$] 的输出 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|超出范围正输入的输出 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]

|latexmath:[$\+\infty$] 或 NaN 的输出 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]
|===

所有浮点转换指令如果舍入结果与操作数值不同且无效标志未设置，则设置不精确异常标志。

include::images/wavedrom/spfloat-cn-cmp.edn[]
[[fcvt]]
//.SP 浮点转换和移动

浮点到浮点符号注入指令 FSGNJ.S、FSGNJN.S 和 FSGNJX.S 产生一个结果，该结果从 _rs1_ 获取除符号位之外的所有位。对于 FSGNJ，结果的符号位是 _rs2_ 的符号位；对于 FSGNJN，结果的符号位与 _rs2_ 的符号位相反；对于 FSGNJX，符号位是 _rs1_ 和 _rs2_ 符号位的异或。符号注入指令不设置浮点异常标志，也不规范化 NaN。注意，FSGNJ.S _rx, ry, ry_ 将 _ry_ 移动到 _rx_（汇编器伪指令 FMV.S _rx, ry_）；FSGNJN.S _rx, ry, ry_ 将 _ry_ 的负值移动到 _rx_（汇编器伪指令 FNEG.S _rx, ry_）；FSGNJX.S _rx, ry, ry_ 将 _ry_ 的绝对值移动到 _rx_（汇编器伪指令 FABS.S _rx, ry_）。

include::images/wavedrom/spfloat-sign-inj.edn[]
[[inj]]

[NOTE]
====
符号注入指令提供了浮点 MV、ABS 和 NEG，以及支持其他一些操作，包括 IEEE `copySign` 操作和超越数学函数库中的符号操作。尽管 MV、ABS 和 NEG 只需要一个寄存器操作数，而 FSGNJ 指令需要两个，但大多数微架构不太可能添加优化以从这些相对不频繁的指令的减少的寄存器读取中受益。即使在这种情况下，微架构也可以简单地检测 FSGNJ 指令的两个源寄存器何时相同，并且只读取一个副本。
====

提供了在浮点寄存器和整数寄存器之间移动位模式的指令。FMV.X.W 将浮点寄存器 _rs1_ 中以 IEEE 754-2008 编码表示的单精度值移动到整数寄存器 _rd_ 的低 32 位。传输中不修改位，特别是，非规范 NaN 的有效载荷得以保留。对于 RV64，目标寄存器的高 32 位填充浮点数的符号位副本。

FMV.W.X 将整数寄存器 _rs1_ 的低 32 位中以 IEEE 754-2008 标准编码的单精度值移动到浮点寄存器 _rd_。传输中不修改位，特别是，非规范 NaN 的有效载荷得以保留。

[NOTE]
====
FMV.W.X 和 FMV.X.W 指令以前称为 FMV.S.X 和 FMV.X.S。使用 W 更符合其语义，即作为不解释地移动 32 位的指令。在定义 NaN 装箱后，这一点变得更加清晰。为了避免干扰现有代码，工具将支持 W 和 S 版本。
====

include::images/wavedrom/spfloat-mv.edn[]
[[spfloat-mv]]
//.SP 浮点移动

[NOTE]
====
基本浮点 ISA 的定义允许实现采用寄存器中浮点格式的内部重编码，以简化次正规值的处理，并可能减少功能单元延迟。为此，F 扩展通过定义直接读取和写入整数寄存器文件的转换和比较操作，避免在浮点寄存器中表示整数值。这还消除了许多常见情况下需要整数和浮点寄存器之间显式移动的情况，从而减少了常见混合格式代码序列的指令计数和关键路径。
====

=== 单精度浮点比较指令

浮点比较指令 (FEQ.S, FLT.S, FLE.S) 执行浮点寄存器之间的指定比较（latexmath:[$\mbox{\em rs1}
= \mbox{\em rs2}$]、latexmath:[$\mbox{\em rs1} < \mbox{\em rs2}$]、latexmath:[$\mbox{\em rs1} \leq
\mbox{\em rs2}$]），如果条件成立，则将 1 写入整数寄存器 _rd_，否则写入 0。

FLT.S 和 FLE.S 执行 IEEE 754-2008 标准中所谓的 _信令_ 比较：即，如果任一输入是 NaN，它们会设置无效操作异常标志。FEQ.S 执行 _静默_ 比较：它仅在任一输入是信令 NaN 时才设置无效操作异常标志。对于所有三个指令，如果任一操作数是 NaN，则结果为 0。

include::images/wavedrom/spfloat-comp.edn[]
[[spfloat-comp]]
//.SP 浮点比较

[NOTE]
====
F 扩展提供了 latexmath:[$\leq$] 比较，而基本 ISA 提供了 latexmath:[$\geq$] 分支比较。因为 latexmath:[$\leq$] 可以从 latexmath:[$\geq$] 合成，反之亦然，所以这种不一致性没有性能影响，但它仍然是 ISA 中一个不幸的不协调之处。
====

=== 单精度浮点分类指令

FCLASS.S 指令检查浮点寄存器 _rs1_ 中的值，并将一个 10 位掩码写入整数寄存器 _rd_，该掩码指示浮点数的类别。掩码的格式如 <<fclass>> 所示。如果属性为真，则 _rd_ 中相应的位将被设置，否则清除。_rd_ 中的所有其他位都清除。请注意，_rd_ 中恰好有一个位将被设置。
FCLASS.S 不设置浮点异常标志。
(((浮点，分类)))

include::images/wavedrom/spfloat-classify.edn[]
[[spfloat-classify]]
//.SP 浮点分类

[[fclass]]
.FCLASS 指令结果的格式。
[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
|_rd_ 位 |含义
|0 |_rs1_ 是 latexmath:[$-\infty$]。
|1 |_rs1_ 是负正规数。
|2 |_rs1_ 是负次正规数。
|3 |_rs1_ 是 latexmath:[$-0$]。
|4 |_rs1_ 是 latexmath:[$\+0$]。
|5 |_rs1_ 是正次正规数。
|6 |_rs1_ 是正正规数。
|7 |_rs1_ 是 latexmath:[$\+\infty$]。
|8 |_rs1_ 是信令 NaN。
|9 |_rs1_ 是静默 NaN。
|===