== 引言

RISC-V（发音为“risk-five”）是一种新的指令集架构（ISA），最初旨在支持计算机架构研究和教育，但我们现在希望它也能成为工业实现的标准自由开放架构。我们定义 RISC-V 的目标包括：

* 一个完全 _开放_ 的 ISA，可供学术界和工业界免费使用。
* 一个 _真实_ 的 ISA，适用于直接原生硬件实现，而不仅仅是仿真或二进制转换。
* 一个避免为特定微架构风格（例如，微代码、顺序执行、解耦、乱序执行）或实现技术（例如，全定制、ASIC、FPGA）“过度设计”的 ISA，但允许在其中任何一种中高效实现。
* 一个分为 _小型_ 基本整数 ISA 的 ISA，可单独用作定制加速器或教育目的的基础，以及可选的标准扩展，以支持通用软件开发。
* 支持修订后的 2008 IEEE-754 浮点标准。 cite:[ieee754-2008]
* 一个支持广泛 ISA 扩展和专用变体的 ISA。
* 应用程序、操作系统内核和硬件实现都支持 32 位和 64 位地址空间变体。
* 一个支持高度并行多核或众核实现（包括异构多处理器）的 ISA。
* 可选的 _可变长度指令_，既可以扩展可用指令编码空间，又可以支持可选的 _密集指令编码_，以提高性能、静态代码大小和能效。
* 一个完全可虚拟化的 ISA，以简化管理程序开发。
* 一个简化新特权架构设计实验的 ISA。

[NOTE]
====
我们设计决策的评论格式与本段落相同。如果读者只对规范本身感兴趣，可以跳过此非规范性文本。
====

[NOTE]
====
RISC-V 这个名称是为了代表加州大学伯克利分校的第五个主要 RISC ISA 设计（RISC-I cite:[riscI-isca1981]、RISC-II cite:[Katevenis:1983]、SOAR cite:[Ungar:1984] 和 SPUR cite:[spur-jsscc1989] 是前四个）。我们还双关语地使用罗马数字“V”来表示“变体”和“向量”，因为支持一系列架构研究（包括各种数据并行加速器）是 ISA 设计的明确目标。
====
(((ISA，定义)))
RISC-V ISA 的定义尽可能避免实现细节（尽管包含了对实现驱动决策的评论），应将其视为各种实现的软件可见接口，而不是特定硬件工件的设计。RISC-V 手册分为两卷。本卷涵盖了基本 _非特权_ 指令的设计，包括可选的非特权 ISA 扩展。非特权指令是指通常可在所有特权架构的所有特权模式下使用的指令，尽管行为可能因特权模式和特权架构而异。第二卷提供了第一个（“经典”）特权架构的设计。手册使用 IEC 80000-13:2008 约定，字节为 8 位。

[NOTE]
====
在非特权 ISA 设计中，我们试图消除对特定微架构特性（例如缓存行大小）或特权架构细节（例如页面转换）的任何依赖。这既是为了简单起见，也是为了最大限度地提高替代微架构或替代特权架构的灵活性。
====

=== RISC-V 硬件平台术语


RISC-V 硬件平台可以包含一个或多个 RISC-V 兼容的处理核心以及其他非 RISC-V 兼容的核心、固定功能加速器、各种物理内存结构、I/O 设备和互连结构，以允许组件进行通信。
(((核心，组件)))

如果一个组件包含一个独立的指令获取单元，则称其为 _核心_。一个 RISC-V 兼容的核心可能通过多线程支持多个 RISC-V 兼容的硬件线程，或 _hart_。
(((核心，扩展，协处理器)))

一个 RISC-V 核心可能具有额外的专用指令集扩展或附加的 _协处理器_。我们使用术语 _协处理器_ 来指代连接到 RISC-V 核心的单元，主要由 RISC-V 指令流进行排序，但包含额外的架构状态和指令集扩展，并且可能相对于主 RISC-V 指令流具有一定的有限自主性。

我们使用术语 _加速器_ 来指代不可编程的固定功能单元或可以自主操作但专门用于某些任务的核心。在 RISC-V 系统中，我们预计许多可编程加速器将是基于 RISC-V 的核心，具有专用指令集扩展和/或定制协处理器。RISC-V 加速器的一个重要类别是 I/O 加速器，它们将 I/O 处理任务从主应用程序核心卸载。
(((核心，加速器)))

RISC-V 硬件平台的系统级组织可以从单核微控制器到数千个共享内存众核服务器节点的集群。即使是小型片上系统也可能被构建为多计算机和/或多处理器的层次结构，以模块化开发工作或在子系统之间提供安全隔离。
(((核心，集群，多处理器)))

=== RISC-V 软件执行环境和 Hart


RISC-V 程序的行为取决于其运行的执行环境。RISC-V 执行环境接口 (EEI) 定义了程序的初始状态、环境中 hart 的数量和类型（包括 hart 支持的特权模式）、内存和 I/O 区域的可访问性和属性、每个 hart 上执行的所有合法指令的行为（即 ISA 是 EEI 的一个组成部分），以及执行期间引发的任何中断或异常（包括环境调用）的处理。EEI 的示例包括 Linux 应用程序二进制接口 (ABI) 或 RISC-V supervisor 二进制接口 (SBI)。RISC-V 执行环境的实现可以是纯硬件、纯软件或硬件和软件的组合。例如，操作码陷阱和软件仿真可用于实现硬件中未提供的功能。执行环境实现的示例包括：

* “裸机”硬件平台，其中 hart 由物理处理器线程直接实现，指令可以完全访问物理地址空间。硬件平台定义了一个在上电复位时开始的执行环境。
* RISC-V 操作系统，通过将用户级 hart 多路复用到可用的物理处理器线程并控制通过虚拟内存访问内存来提供多个用户级执行环境。
* RISC-V 管理程序，为客户操作系统提供多个 supervisor 级执行环境。
* RISC-V 模拟器，例如 Spike、QEMU 或 rv8，它们在底层 x86 系统上模拟 RISC-V hart，并且可以提供用户级或 supervisor 级执行环境。

[NOTE]
====
裸硬件平台可以被视为定义了一个 EEI，其中可访问的 hart、内存和其他设备填充了环境，初始状态是上电复位时的状态。通常，大多数软件都设计为使用更抽象的硬件接口，因为更抽象的 EEI 提供了跨不同硬件平台的更大可移植性。EEI 通常是分层的，其中一个更高级别的 EEI 使用另一个更低级别的 EEI。
====
(((hart，执行环境)))
从在给定执行环境中运行的软件的角度来看，hart 是一种资源，它在该执行环境中自主获取和执行 RISC-V 指令。在这方面，hart 的行为类似于硬件线程资源，即使它由执行环境在真实硬件上进行时间多路复用。一些 EEI 支持创建和销毁额外的 hart，例如，通过环境调用来 fork 新的 hart。

执行环境负责确保其每个 hart 的最终前进。对于给定的 hart，当 hart 正在执行明确等待事件的机制时（例如本规范第二卷中定义的等待中断指令），该责任暂停；如果 hart 终止，则该责任终止。以下事件构成前进：

* 指令的退役。
* 陷阱，如 <<trap-defn>> 中定义。
* 扩展定义的任何其他构成前进的事件。

[NOTE]
====
hart 这个术语是在 Lithe cite:[lithe-pan-hotpar09] 和 cite:[lithe-pan-pldi10] 的工作中引入的，旨在提供一个术语来表示抽象执行资源，而不是软件线程编程抽象。

硬件线程 (hart) 和软件线程上下文之间的重要区别在于，在执行环境内部运行的软件不负责使其每个 hart 前进；这是外部执行环境的责任。因此，环境的 hart 从执行环境内部软件的角度来看，就像硬件线程一样运行。

执行环境实现可以将一组客户 hart 时间多路复用到较少的主机 hart 上，这些主机 hart 由其自身的执行环境提供，但必须以客户 hart 像独立的硬件线程一样运行的方式进行。特别是，如果客户 hart 数量多于主机 hart 数量，则执行环境必须能够抢占客户 hart，并且不得无限期地等待客户 hart 上的客户软件“让出”客户 hart 的控制权。
====

=== RISC-V ISA 概述


RISC-V ISA 被定义为基本整数 ISA，任何实现中都必须存在，以及基本 ISA 的可选扩展。基本整数 ISA 与早期 RISC 处理器非常相似，只是没有分支延迟槽，并支持可选的可变长度指令编码。基本 ISA 被仔细限制为最小指令集，足以提供编译器、汇编器、链接器和操作系统（具有附加特权操作）的合理目标，因此提供了一个方便的 ISA 和软件工具链“骨架”，在此基础上可以构建更定制的处理器 ISA。

尽管谈论 _RISC-V ISA_ 很方便，但 RISC-V 实际上是一个相关 ISA 系列，目前有四个基本 ISA。每个基本整数指令集都以整数寄存器的宽度和相应的地址空间大小以及整数寄存器的数量为特征。有两个主要的基本整数变体，RV32I 和 RV64I，分别在 <<rv32>> 和 <<rv64>> 中描述，它们分别提供 32 位或 64 位地址空间。我们使用术语 XLEN 来指代整数寄存器的位宽（32 或 64）。<<rv32e>> 描述了 RV32I 或 RV64I 基本指令集的 RV32E 和 RV64E 子集变体，它们是为了支持小型微控制器而添加的，并且整数寄存器数量减半。基本整数指令集使用补码表示有符号整数值。


[NOTE]
====
尽管 64 位地址空间是大型系统的要求，但我们认为 32 位地址空间在未来几十年内仍将足以满足许多嵌入式和客户端设备的需求，并且将有助于降低内存流量和能耗。此外，32 位地址空间足以满足教育目的。最终可能需要更大的平面 128 位地址空间，并且可以在现有 RISC-V ISA 框架内通过新的 RV128I 基本 ISA 来实现。
====

[NOTE]
====
RISC-V 中的四个基本 ISA 被视为不同的基本 ISA。一个常见的问题是为什么没有一个单一的 ISA，特别是为什么 RV32I 不是 RV64I 的严格子集？一些早期的 ISA 设计（SPARC、MIPS）在增加地址空间大小时采用了严格的超集策略，以支持在新的 64 位硬件上运行现有的 32 位二进制文件。

明确分离基本 ISA 的主要优点是，每个基本 ISA 都可以针对其需求进行优化，而无需支持其他基本 ISA 所需的所有操作。例如，RV64I 可以省略仅用于处理 RV32I 中较窄寄存器的指令和 CSR。RV32I 变体可以使用否则保留用于更宽地址空间变体所需的指令的编码空间。

不将设计视为单一 ISA 的主要缺点是它使在一个基本 ISA 上模拟另一个基本 ISA 所需的硬件复杂化（例如，在 RV64I 上模拟 RV32I）。然而，寻址和非法指令陷阱的差异通常意味着无论如何都需要在硬件中进行某种模式切换，即使是完整的超集指令编码，并且不同的 RISC-V 基本 ISA 足够相似，以至于支持多个版本成本相对较低。尽管有人提出严格的超集设计将允许 32 位旧库与 64 位代码链接，但这在实践中是不切实际的，即使编码兼容，由于软件调用约定和系统调用接口的差异。

RISC-V 特权架构在 `misa` 中提供了字段来控制每个级别的非特权 ISA，以支持在相同硬件上模拟不同的基本 ISA。我们注意到，较新的 SPARC 和 MIPS ISA 修订版已弃用对在 64 位系统上运行未更改的 32 位代码的支持。

一个相关的问题是为什么 RV32I (ADD) 和 RV64I (ADDW) 中的 32 位加法有不同的编码？ADDW 操作码可以用于 RV32I 中的 32 位加法，ADDIW 用于 RV64I 中的 64 位加法，而不是现有设计中 RV32I 中的 32 位加法和 RV64I 中的 64 位加法使用相同的操作码 ADD，而 RV64I 中的 32 位加法使用不同的操作码 ADDW。这与 RV32I 和 RV64I 中 32 位加载使用相同的 LW 操作码更一致。RISC-V ISA 的最初版本确实有这种替代设计的变体，但 RISC-V 设计在 2011 年 1 月更改为当前选择。我们的重点是在 64 位 ISA 中支持 32 位整数，而不是提供与 32 位 ISA 的兼容性，动机是消除 RV32I 中并非所有操作码都带有 *W 后缀（例如 ADDW，但 AND 而不是 ANDW）所产生的不对称性。事后看来，这可能没有充分的理由，并且是同时设计两个 ISA 而不是稍后添加一个以叠加在另一个之上的结果，也源于我们认为必须将平台要求纳入 ISA 规范的信念，这意味着 RV32I 的所有指令都将被要求在 RV64I 中。现在更改编码为时已晚，但由于上述原因，这实际上也没有什么影响。

有人指出，我们可以将 *W 变体作为 RV32I 系统的扩展，以在 RV64I 和未来的 RV32 变体之间提供通用编码。
====

RISC-V 的设计旨在支持广泛的定制和专业化。每个基本整数 ISA 都可以通过一个或多个可选指令集扩展进行扩展。扩展可以分为标准、自定义或不符合。为此，我们将每个 RISC-V 指令集编码空间（以及相关的编码空间，例如 CSR）分为三个不相交的类别：_标准_、_保留_ 和 _自定义_。标准扩展和编码由 RISC-V International 定义；任何未由 RISC-V International 定义的扩展都是 _非标准_。每个基本 ISA 及其标准扩展仅使用标准编码，并且在使用这些编码时不得相互冲突。保留编码目前未定义，但保留用于未来的标准扩展；一旦使用，它们就成为标准编码。自定义编码永远不得用于标准扩展，并可用于供应商特定的非标准扩展。非标准扩展要么是自定义扩展（仅使用自定义编码），要么是 _不符合_ 扩展（使用任何标准或保留编码）。指令集扩展通常是共享的，但根据基本 ISA 可能提供略有不同的功能。<<extending>> 描述了扩展 RISC-V ISA 的各种方法。我们还为 RISC-V 基本指令和指令集扩展开发了命名约定，详见 <<naming>>。

为了支持更通用的软件开发，定义了一组标准扩展，以提供整数乘法/除法、原子操作以及单精度和双精度浮点算术。基本整数 ISA 命名为“I”（根据整数寄存器宽度前缀为 RV32 或 RV64），包含整数计算指令、整数加载、整数存储和控制流指令。标准整数乘法和除法扩展命名为“M”，并添加了用于整数寄存器中值乘法和除法的指令。标准原子指令扩展，表示为“A”，添加了原子读取、修改和写入内存以进行处理器间同步的指令。标准单精度浮点扩展，表示为“F”，添加了浮点寄存器、单精度计算指令以及单精度加载和存储。标准双精度浮点扩展，表示为“D”，扩展了浮点寄存器，并添加了双精度计算指令、加载和存储。标准“C”压缩指令扩展提供了更窄的 16 位常见指令形式。

除了基本整数 ISA 和这些标准扩展之外，我们认为新指令很少能为所有应用程序带来显著好处，尽管它可能对特定领域非常有益。由于能效问题迫使更大的专业化，我们认为简化 ISA 规范的所需部分非常重要。虽然其他架构通常将其 ISA 视为一个单一实体，随着时间的推移添加指令而更改为新版本，但 RISC-V 将努力使基本和每个标准扩展随着时间的推移保持不变，而是将新指令作为进一步的可选扩展分层。例如，基本整数 ISA 将继续作为完全支持的独立 ISA，无论后续有任何扩展。

=== 内存


RISC-V hart 具有一个字节可寻址的地址空间，大小为 latexmath:[$2^{\text{XLEN}}$] 字节，用于所有内存访问。内存的 _字_ 定义为 32{nbsp}位（4{nbsp}字节）。相应地，_半字_ 为 16{nbsp}位（2{nbsp}字节），_双字_ 为 64{nbsp}位（8{nbsp}字节），_四字_ 为 128{nbsp}位（16{nbsp}字节）。内存地址空间是循环的，因此地址 latexmath:[$2^{\text{XLEN}}-1$] 处的字节与地址零处的字节相邻。因此，硬件执行的内存地址计算会忽略溢出，而是模 latexmath:[$2^{\text{XLEN}}$] 环绕。

执行环境决定了硬件资源到 hart 地址空间的映射。hart 地址空间的不同地址范围可能 (1) 包含 _主内存_，或 (2) 包含一个或多个 _I/O 设备_。I/O 设备的读写可能具有可见的副作用，但对主内存的访问不能。空闲地址范围不是一个单独的类别，但可以表示为不可访问的主内存或 I/O 区域。
尽管执行环境可以将 hart 地址空间中的所有内容都称为 I/O 设备，但通常期望其中一部分将被指定为主内存。

当 RISC-V 平台具有多个 hart 时，任何两个 hart 的地址空间可能完全相同，或完全不同，或可能部分不同但共享某些资源子集，映射到相同或不同的地址范围。

[NOTE]
====
对于纯粹的“裸机”环境，所有 hart 可能会看到相同的地址空间，完全通过物理地址访问。然而，当执行环境包含使用地址转换的操作系统时，通常每个 hart 都被赋予一个大部分或完全属于自己的虚拟地址空间。
====
(((内存访问，隐式和显式)))

执行每个 RISC-V 机器指令都涉及一次或多次内存访问，细分为 _隐式_ 和 _显式_ 访问。对于执行的每个指令，都会进行一次 _隐式_ 内存读取（指令获取）以获取要执行的编码指令。许多 RISC-V 指令除了指令获取之外不再执行其他内存访问。特定的加载和存储指令在指令确定的地址处执行内存的 _显式_ 读取或写入。执行环境可能规定指令执行除了非特权 ISA 文档中记录的之外，还会执行其他 _隐式_ 内存访问（例如实现地址转换）。

执行环境决定了地址空间的哪些部分可用于每种内存访问。例如，可用于指令获取的隐式读取位置集可能与加载指令可显式读取的位置集有重叠，也可能没有；存储指令可显式写入的位置集可能只是可读取位置集的子集。通常，如果指令尝试访问不可访问地址处的内存，则会为该指令引发异常。

除非另有规定，否则不会引发异常且没有副作用的隐式读取可以任意早地推测性发生，甚至在机器可能证明需要读取之前。例如，一个有效的实现可以尝试在最早的机会读取所有主内存，尽可能多地缓存可获取（可执行）字节以供后续指令获取，并避免再次读取主内存以进行指令获取。为了确保某些隐式读取仅在写入相同内存位置之后才进行排序，软件必须执行为此目的定义的特定栅栏或缓存控制指令（例如 <<zifencei>> 中定义的 FENCE.I 指令）。
(((内存访问，隐式和显式)))

hart 执行的内存访问（隐式或显式）在另一个 hart 或任何其他可以访问相同内存的代理看来可能以不同的顺序发生。然而，这种感知到的内存访问重新排序始终受到适用内存一致性模型的约束。RISC-V 的默认内存一致性模型是 RISC-V 弱内存排序 (RVWMO)，在 <<memorymodel>> 和附录中定义。可选地，实现可以采用更强的全存储排序模型，如 <<ztso>> 中定义。执行环境还可以添加约束，进一步限制感知到的内存访问重新排序。由于 RVWMO 模型是任何 RISC-V 实现允许的最弱模型，因此为该模型编写的软件与所有 RISC-V 实现的实际内存一致性规则兼容。与隐式读取一样，软件必须执行栅栏或缓存控制指令，以确保内存访问的特定排序超出假定内存一致性模型和执行环境的要求。

=== 基本指令长度编码

基本 RISC-V ISA 具有固定长度的 32 位指令，必须自然对齐到 32 位边界。然而，标准 RISC-V 编码方案旨在支持具有可变长度指令的 ISA 扩展，其中每个指令可以是任意数量的 16 位指令 _包_，并且包自然对齐到 16 位边界。<<compressed>> 中描述的标准压缩 ISA 扩展通过提供压缩的 16 位指令来减少代码大小，并放宽对齐约束，以允许所有指令（16 位和 32 位）对齐到任何 16 位边界，以提高代码密度。

我们使用术语 IALIGN（以位为单位）来指代实现强制执行的指令地址对齐约束。IALIGN 在基本 ISA 中是 32 位，但某些 ISA 扩展（包括压缩 ISA 扩展）将 IALIGN 放宽到 16 位。IALIGN 不能取除 16 或 32 之外的任何值。
(((ILEN)))

我们使用术语 ILEN（以位为单位）来指代实现支持的最大指令长度，并且它始终是 IALIGN 的倍数。对于仅支持基本指令集的实现，ILEN 为 32 位。支持更长指令的实现具有更大的 ILEN 值。

基本 ISA 中的所有 32 位指令的最低两位都设置为 `11`。可选的压缩 16 位指令集扩展的最低两位等于 `00`、`01` 或 `10`。

[NOTE]
====
鉴于压缩格式的代码大小和能效节省，我们希望在 ISA 编码方案中内置对压缩格式的支持，而不是事后添加，但为了允许更简单的实现，我们不想强制要求压缩格式。我们还希望可选地允许更长的指令以支持实验和更大的指令集扩展。尽管我们的编码约定要求更紧凑地编码核心 RISC-V ISA，但这具有几个有益的效果。
(((IMAFD)))

标准 IMAFD ISA 的实现只需要在指令缓存中保存最高有效 30 位（节省 6.25%）。在指令缓存填充时，任何遇到的低位清除的指令都应在存储到缓存之前重新编码为非法 30 位指令，以保留非法指令异常行为。

也许更重要的是，通过将我们的基本 ISA 压缩到 32 位指令字的一个子集中，我们为非标准和自定义扩展留下了更多可用空间。特别是，基本 RV32I ISA 使用的 32 位指令字编码空间不到 1/8。如 <<extending>> 中所述，不需要支持标准压缩指令扩展的实现可以将 3 个额外的非符合 30 位指令空间映射到 32 位固定宽度格式中，同时保留对标准 ≥32 位指令集扩展的支持。
====

所有位 [15:0] 都为零的编码被定义为非法指令。这些指令被认为是最小长度：如果存在任何 16 位指令集扩展，则为 16 位，否则为 32 位。所有位 [ILEN-1:0] 都为一的编码也是非法的；此指令被认为是 ILEN 位长。

[NOTE]
====
我们认为任何包含所有零位的指令长度都不合法是一个特性，因为这可以快速捕获错误跳转到零内存区域。同样，我们还将包含所有一的指令编码保留为非法指令，以捕获未编程的非易失性存储设备、断开连接的内存总线或损坏的内存设备中观察到的其他常见模式。

软件可以依赖包含零的自然对齐的 32 位字在所有 RISC-V 实现上作为非法指令，供软件在明确需要非法指令时使用。为所有一的相应已知非法值定义更困难，因为可变长度编码。软件通常不能使用 ILEN 位全为 1 的非法值，因为软件可能不知道最终目标机器的 ILEN（例如，如果软件编译成许多不同机器使用的标准二进制库）。将全为一的 32 位字定义为非法也曾被考虑，因为所有机器都必须支持 32 位指令大小，但这要求具有 ILEN >32 的机器上的指令获取单元在遇到此类指令时报告非法指令异常而不是访问故障异常，从而使可变指令长度获取和解码复杂化。
====
(((字节序，小端和大端)))
RISC-V 基本 ISA 具有小端或大端内存系统，特权架构进一步定义了双端操作。指令在内存中存储为一系列 16 位小端包，无论内存系统字节序如何。构成一个指令的包存储在递增的半字地址处，最低地址的包保存指令规范中编号最低的位。
(((双端)))
(((字节序，双端)))

[NOTE]
====
我们最初选择 RISC-V 内存系统的小端字节序，因为小端系统目前在商业上占主导地位（所有 x86 系统；ARM 的 iOS、Android 和 Windows）。一个次要点是，我们还发现小端内存系统对硬件设计人员来说更自然。然而，某些应用领域，例如 IP 网络，操作大端数据结构，并且某些旧代码库是假设大端处理器构建的，因此我们定义了 RISC-V 的大端和双端变体。

我们必须固定指令包在内存中的存储顺序，独立于内存系统字节序，以确保长度编码位始终首先出现在半字地址顺序中。这允许指令获取单元通过仅检查第一个 16 位指令包的前几位来快速确定可变长度指令的长度。

我们进一步使指令包本身为小端，以完全解耦指令编码与内存系统字节序。这种设计有利于软件工具和双端硬件。否则，例如，RISC-V 汇编器或反汇编器将始终需要知道预期的活动字节序，尽管在双端系统中，字节序模式可能在执行期间动态更改。相比之下，通过为指令提供固定字节序，有时精心编写的软件即使在二进制形式下也可以是字节序无关的，就像位置无关代码一样。

选择指令仅为小端确实会带来一些后果，对于编码或解码机器指令的 RISC-V 软件而言。例如，大端 JIT 编译器在存储到指令内存时必须交换字节顺序。

一旦我们决定固定小端指令编码，这自然导致将长度编码位放置在指令格式的 LSB 位置，以避免破坏操作码字段。
====

[[trap-defn]]
=== 异常、陷阱和中断

我们使用术语 _异常_ 来指代当前 RISC-V hart 中与指令相关的运行时发生的异常情况。
我们使用术语 _中断_ 来指代可能导致 RISC-V hart 经历意外控制转移的外部异步事件。
我们使用术语 _陷阱_ 来指代由异常或中断引起的控制转移到陷阱处理程序。
(((异常)))
(((陷阱)))
(((中断)))

以下章节中的指令描述了执行期间可能引发异常的条件。大多数 RISC-V EEI 的一般行为是，当指令上发出异常信号时（浮点异常除外，在标准浮点扩展中，它们不会导致陷阱），会发生陷阱到某个处理程序。中断的生成、路由和由 hart 启用方式取决于 EEI。

[NOTE]
====
我们对“异常”和“陷阱”的使用与 IEEE-754 浮点标准中的使用兼容。
====

陷阱如何处理并对在 hart 上运行的软件可见，取决于封闭的执行环境。从在执行环境内部运行的软件的角度来看，hart 在运行时遇到的陷阱可以有四种不同的效果：

包含陷阱:::
  陷阱对在执行环境内部运行的软件可见并由其处理。例如，在提供 hart 上的 supervisor 和用户模式的 EEI 中，用户模式 hart 的 ECALL 通常会导致控制转移到在同一 hart 上运行的 supervisor 模式处理程序。同样，在相同的环境中，当 hart 被中断时，中断处理程序将在 hart 上的 supervisor 模式下运行。
请求陷阱:::
  陷阱是同步异常，它是对执行环境的显式调用，请求代表执行环境内部的软件执行操作。一个例子是系统调用。在这种情况下，在执行环境执行请求的操作后，执行可能在 hart 上恢复，也可能不恢复。例如，系统调用可以移除 hart 或导致整个执行环境的有序终止。
不可见陷阱:::
  陷阱由执行环境透明地处理，并且在处理陷阱后执行正常恢复。示例包括模拟缺失指令、处理按需分页虚拟内存系统中的非驻留页故障，或在多程序机器中处理不同作业的设备中断。在这些情况下，在执行环境内部运行的软件不知道陷阱（我们在这些定义中忽略时间效应）。
致命陷阱:::
  陷阱表示致命故障，并导致执行环境终止执行。示例包括未能通过虚拟内存页保护检查或允许看门狗计时器过期。每个 EEI 都应定义如何终止执行并向外部环境报告。

<<trapcharacteristics>> 显示了每种陷阱的特征。

[[trapcharacteristics]]
.陷阱的特征
[%autowidth,float="center",align="center",cols="<,^,^,^,^",options="header",]
|===
| |包含 |请求 |不可见 |致命
|执行终止 |否 |否^1^|否 |是
|软件不知情 |否 |否 |是 |是^2^|由环境处理 |否 |是 |是 |是
|===

^1^ 可能请求终止 +
^2^ 不精确的致命陷阱可能被软件观察到

EEI 定义了每个陷阱是否精确处理，但建议尽可能保持精确。包含陷阱和请求陷阱可以被执行环境内部的软件观察到不精确。不可见陷阱，根据定义，不能被在执行环境内部运行的软件观察到精确或不精确。致命陷阱可以被在执行环境内部运行的软件观察到不精确，如果已知错误的指令不会导致立即终止。

由于本文档描述的是非特权指令，因此很少提及陷阱。处理包含陷阱的架构方法在特权架构手册中定义，以及支持更丰富 EEI 的其他功能。此处记录了仅用于引起请求陷阱的非特权指令。不可见陷阱，就其性质而言，不在本文档的范围之内。此处未定义且未通过其他方式定义的指令编码可能会导致致命陷阱。

=== 未指定行为和值
架构充分描述了实现必须做什么以及它们可能做什么的任何约束。在架构有意不约束实现的情况下，明确使用术语 UNSPECIFIED。
(((未指定，行为)))
(((未指定，值)))

术语 UNSPECIFIED 指的是有意不受约束的行为或值。这些行为或值的定义开放给扩展、平台标准或实现。扩展、平台标准或实现文档可以提供规范性内容，以进一步约束基本架构定义为 UNSPECIFIED 的情况。

与基本架构一样，扩展应充分描述允许的行为和值，并对有意不受约束的情况使用术语 UNSPECIFIED。这些情况可以由其他扩展、平台标准或实现约束或定义。
