[[rv32-64g]]
== RV32/64G 指令集列表

RISC-V 项目的一个目标是将其用作稳定的软件开发目标。为此，我们将基本 ISA（RV32I 或 RV64I）加上选定的标准扩展（IMAFD、Zicsr、Zifencei）的组合定义为“通用”ISA，我们使用缩写 G 表示 IMAFDZicsr_Zifencei 指令集扩展的组合。本章介绍了 RV32G 和 RV64G 的操作码映射和指令集列表。

// note: &#8805; 是 >= 的 Unicode 字符
[[opcodemap]]
.RISC-V 基本操作码映射，inst[1:0]=11
[%autowidth.stretch,float="center",align="center",cols=  ">.^4m,  ^.^4m,    ^.^4m,      ^.^4m,    ^.^4m,  ^.^4m,      ^.^4m,           ^.^6m, ^.^4h"]
|===
|inst[4:2] .2+|000 .2+|001   .2+|010     .2+|011   .2+|100 .2+|101     .2+|110          .2+|111 (>32b)
|inst[6:5]
|00           |加载   |加载-FP  |_自定义-0_ |杂项-内存 |OP-立即数 |AUIPC      |OP-立即数-32       |_保留_
|01           |存储  |存储-FP |_自定义-1_ |AMO      |OP     |LUI        |OP-32           |_保留_
|10           |MADD   |MSUB     |NMSUB      |NMADD    |OP-FP  |OP-V       |_自定义-2_      |_保留_
|11           |分支 |JALR     |_保留_ |JAL      |SYSTEM |OP-VE      |_自定义-3_      |_保留_
|===

<<opcodemap>> 显示了 RVG 的主要操作码映射。标记为 _保留_ 的操作码应避免用于自定义指令集扩展，因为它们可能被未来的标准扩展使用。标记为 _自定义-0_ 到 _自定义-3_ 的主要操作码将避免被未来的标准扩展使用，并建议用于基本 32 位指令格式中的自定义指令集扩展。

我们相信 RV32G 和 RV64G 为广泛的通用计算提供了简单但完整的指令集。<<compressed>> 中描述的可选压缩指令集可以添加（形成 RV32GC 和 RV64GC）以提高性能、代码大小和能效，尽管会增加一些额外的硬件复杂性。

随着我们超越 IMAFDC 进入更远的指令集扩展，添加的指令往往更具领域特定性，并且仅为受限的应用程序类别提供好处，例如，用于多媒体或安全性。与大多数商业 ISA 不同，RISC-V ISA 设计明确将基本 ISA 和广泛适用的标准扩展与这些更专业的添加分开。<<extending>> 更广泛地讨论了向 RISC-V ISA 添加扩展的方法。

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |   0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R-type
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I-type
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S-type
 4+^|imm[12\|10:5]  2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:1\|11] 2+^|opcode  <|B-type
10+^|imm[31:12]                                    2+^|rd           2+^|opcode  <|U-type
10+^|imm[20\|10:1\|11\|19:12]                      2+^|rd           2+^|opcode  <|J-type
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32I 基本指令集*
10+^|imm[31:12]                                    2+^|rd           2+^|0110111 <|LUI
10+^|imm[31:12]                                    2+^|rd           2+^|0010111 <|AUIPC
10+^|imm[20\|10:1\|11\|19:12]                      2+^|rd           2+^|1101111 <|JAL
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|1100111 <|JALR
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|000    2+^|imm[4:1\|11] 2+^|1100011 <|BEQ
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|001    2+^|imm[4:1\|11] 2+^|1100011 <|BNE
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|100    2+^|imm[4:1\|11] 2+^|1100011 <|BLT
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|101    2+^|imm[4:1\|11] 2+^|1100011 <|BGE
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|110    2+^|imm[4:1\|11] 2+^|1100011 <|BLTU
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|111    2+^|imm[4:1\|11] 2+^|1100011 <|BGEU
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|0000011 <|LB
 6+^|imm[11:0]                2+^|rs1   2+^|001    2+^|rd           2+^|0000011 <|LH
 6+^|imm[11:0]                2+^|rs1   2+^|010    2+^|rd           2+^|0000011 <|LW
 6+^|imm[11:0]                2+^|rs1   2+^|100    2+^|rd           2+^|0000011 <|LBU
 6+^|imm[11:0]                2+^|rs1   2+^|101    2+^|rd           2+^|0000011 <|LHU
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|000    2+^|imm[4:0]     2+^|0100011 <|SB
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|001    2+^|imm[4:0]     2+^|0100011 <|SH
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|010    2+^|imm[4:0]     2+^|0100011 <|SW
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|0010011 <|ADDI
 6+^|imm[11:0]                2+^|rs1   2+^|010    2+^|rd           2+^|0010011 <|SLTI
 6+^|imm[11:0]                2+^|rs1   2+^|011    2+^|rd           2+^|0010011 <|SLTIU
 6+^|imm[11:0]                2+^|rs1   2+^|100    2+^|rd           2+^|0010011 <|XORI
 6+^|imm[11:0]                2+^|rs1   2+^|110    2+^|rd           2+^|0010011 <|ORI
 6+^|imm[11:0]                2+^|rs1   2+^|111    2+^|rd           2+^|0010011 <|ANDI
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|001    2+^|rd           2+^|0010011 <|SLLI
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRLI
 4+^|0100000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRAI
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0110011 <|ADD
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0110011 <|SUB
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|001    2+^|rd           2+^|0110011 <|SLL
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|010    2+^|rd           2+^|0110011 <|SLT
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0110011 <|SLTU
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|100    2+^|rd           2+^|0110011 <|XOR
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0110011 <|SRL
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0110011 <|SRA
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|110    2+^|rd           2+^|0110011 <|OR
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|111    2+^|rd           2+^|0110011 <|AND
 3+^|fm   2+^|pred  1+^|succ  2+^|rs1   2+^|000    2+^|rd           2+^|0001111 <|FENCE
 3+^|1000 2+^|0011  1+^|0011  2+^|00000 2+^|000    2+^|00000        2+^|0001111 <|FENCE.TSO
 3+^|0000 2+^|0001  1+^|0000  2+^|00000 2+^|000    2+^|00000        2+^|0001111 <|PAUSE
 6+^|000000000000             2+^|00000 2+^|000    2+^|00000        2+^|1110011 <|ECALL
 6+^|000000000001             2+^|00000 2+^|000    2+^|00000        2+^|1110011 <|EBREAK
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R-type
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4-type
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I-type
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S-type
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64I 基本指令集（RV32I 之外）*
 6+^|imm[11:0]                2+^|rs1   2+^|110    2+^|rd           2+^|0000011 <|LWU
 6+^|imm[11:0]                2+^|rs1   2+^|011    2+^|rd           2+^|0000011 <|LD
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|011    2+^|imm[4:0]     2+^|0100011 <|SD
 3+^|000000         3+^|shamt 2+^|rs1   2+^|001    2+^|rd           2+^|0010011 <|SLLI
 3+^|000000         3+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRLI
 3+^|010000         3+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRAI
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|0011011 <|ADDIW
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|001    2+^|rd           2+^|0011011 <|SLLIW
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0011011 <|SRLIW
 4+^|0100000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0011011 <|SRAIW
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0111011 <|ADDW
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0111011 <|SUBW
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|001    2+^|rd           2+^|0111011 <|SLLW
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0111011 <|SRLW
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0111011 <|SRAW
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32/RV64 _Zifencei_ 标准扩展*
 6+^|imm[11:0]                2+^|rs1   2+^|001    2+^|rd           2+^|0001111 <|FENCE.I
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32/RV64 _Zicsr_ 标准扩展*
 6+^|csr                      2+^|rs1   2+^|001    2+^|rd           2+^|1110011 <|CSRRW
 6+^|csr                      2+^|rs1   2+^|010    2+^|rd           2+^|1110011 <|CSRRS
 6+^|csr                      2+^|rs1   2+^|011    2+^|rd           2+^|1110011 <|CSRRC
 6+^|csr                      2+^|uimm  2+^|101    2+^|rd           2+^|1110011 <|CSRRWI
 6+^|csr                      2+^|uimm  2+^|110    2+^|rd           2+^|1110011 <|CSRRSI
 6+^|csr                      2+^|uimm  2+^|111    2+^|rd           2+^|1110011 <|CSRRCI
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32M 标准扩展*
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0110011 <|MUL
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|001    2+^|rd           2+^|0110011 <|MULH
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|010    2+^|rd           2+^|0110011 <|MULHSU
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0110011 <|MULHU
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|100    2+^|rd           2+^|0110011 <|DIV
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0110011 <|DIVU
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|110    2+^|rd           2+^|0110011 <|REM
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|111    2+^|rd           2+^|0110011 <|REMU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64M 标准扩展（RV32M 之外）*
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0111011 <|MULW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|100    2+^|rd           2+^|0111011 <|DIVW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0111011 <|DIVUW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|110    2+^|rd           2+^|0111011 <|REMW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|111    2+^|rd           2+^|0111011 <|REMUW
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R-type
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32A 标准扩展*
 2+^|00010 ^|aq ^|rl 2+^|00000 2+^|rs1  2+^|010    2+^|rd           2+^|0101111 <|LR.W
 2+^|00011 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|SC.W
 2+^|00001 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOSWAP.W
 2+^|00000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOADD.W
 2+^|00100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOXOR.W
 2+^|01100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOAND.W
 2+^|01000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOOR.W
 2+^|10000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMIN.W
 2+^|10100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMAX.W
 2+^|11000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMINU.W
 2+^|11100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMAXU.W
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64A 标准扩展（RV32A 之外）*
 2+^|00010 ^|aq ^|rl 2+^|00000 2+^|rs1  2+^|011    2+^|rd           2+^|0101111 <|LR.D
 2+^|00011 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|SC.D
 2+^|00001 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOSWAP.D
 2+^|00000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOADD.D
 2+^|00100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOXOR.D
 2+^|01100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOAND.D
 2+^|01000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOOR.D
 2+^|10000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMIN.D
 2+^|10100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMAX.D
 2+^|11000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMINU.D
 2+^|11100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMAXU.D
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R-type
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4-type
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I-type
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S-type
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32F 标准扩展*
 6+^|imm[11:0]               2+^|rs1    2+^|010    2+^|rd           2+^|0000111 <|FLW
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|010    2+^|imm[4:0]     2+^|0100111 <|FSW
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.S
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.S
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.S
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.S
 4+^|0000000        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.S
 4+^|0000100        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.S
 4+^|0001000        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.S
 4+^|0001100        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.S
 4+^|0101100        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.S
 4+^|0010000        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.S
 4+^|0010000        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.S
 4+^|0010000        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.S
 4+^|0010100        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.S
 4+^|0010100        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.S
 4+^|1100000        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.S
 4+^|1100000        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.S
 4+^|1110000        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.X.W
 4+^|1010000        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.S
 4+^|1010000        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.S
 4+^|1010000        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.S
 4+^|1110000        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.S
 4+^|1101000        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.W
 4+^|1101000        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.WU
 4+^|1111000        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.W.X
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64F 标准扩展（RV32F 之外）*
 4+^|1100000        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.L.S
 4+^|1100000        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.LU.S
 4+^|1101000        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.L
 4+^|1101000        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.LU
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R-type
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4-type
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I-type
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S-type
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+|*RV32D 标准扩展*
 6+^|imm[11:0]               2+^|rs1    2+^|011    2+^|rd           2+^|0000111 <|FLD
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|011    2+^|imm[4:0]     2+^|0100111 <|FSD
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.D
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.D
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.D
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.D
 4+^|0000001        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.D
 4+^|0000101        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.D
 4+^|0001001        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.D
 4+^|0001101        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.D
 4+^|0101101        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.D
 4+^|0010001        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.D
 4+^|0010001        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.D
 4+^|0010001        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.D
 4+^|0010101        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.D
 4+^|0010101        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.D
 4+^|0100000        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.D
 4+^|0100001        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.S
 4+^|1010001        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.D
 4+^|1010001        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.D
 4+^|1010001        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.D
 4+^|1110001        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.D
 4+^|1100001        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.D
 4+^|1100001        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.D
 4+^|1101001        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.W
 4+^|1101001        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.WU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64D 标准扩展（RV32D 之外）*
 4+^|1100001        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.L.D
 4+^|1100001        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.LU.D
 4+^|1110001        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.X.D
 4+^|1101001        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.L
 4+^|1101001        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.LU
 4+^|1111001        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.D.X
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R-type
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4-type
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I-type
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S-type
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32Q 标准扩展*
 4+^|imm[11:0]      2+^|     2+^|rs1    2+^|100    2+^|rd           2+^|0000111 <|FLQ
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|100    2+^|imm[4:0]     2+^|0100111 <|FSQ
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.Q
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.Q
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.Q
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.Q
 4+^|0000011        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.Q
 4+^|0000111        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.Q
 4+^|0001011        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.Q
 4+^|0001111        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.Q
 4+^|0101111        2+^|00000  2+^|rs1  2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.Q
 4+^|0010011        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.Q
 4+^|0010011        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.Q
 4+^|0010011        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.Q
 4+^|0010111        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.Q
 4+^|0010111        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.Q
 4+^|0100000        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.Q
 4+^|0100011        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.S
 4+^|0100001        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.Q
 4+^|0100011        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.D
 4+^|1010011        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.Q
 4+^|1010011        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.Q
 4+^|1010011        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.Q
 4+^|1110011        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.Q
 4+^|1100011        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.Q
 4+^|1100011        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.Q
 4+^|1101011        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.W
 4+^|1101011        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.WU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64Q 标准扩展（RV32Q 之外）*
 4+^|1100011        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.L.Q
 4+^|1100011        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.LU.Q
 4+^|1101011        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.L
 4+^|1101011        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.LU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32Zfh 标准扩展*
 3+^|imm[11:0]      2+^|     2+^|rs1    2+^|001    2+^|rd           2+^|0000111 <|FLH
 2+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|001    2+^|imm[4:0]     2+^|0100111 <|FSH
 2+^|rs3 2+^|10     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.H
 2+^|rs3 2+^|10     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.H
 2+^|rs3 2+^|10     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.H
 2+^|rs3 2+^|10     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.H
 4+^|0000010        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.H
 4+^|0000110        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.H
 4+^|0001010        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.H
 4+^|0001110        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.H
 4+^|0101110        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.H
 4+^|0010010        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.H
 4+^|0010010        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.H
 4+^|0010010        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.H
 4+^|0010110        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.H
 4+^|0010110        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.H
 4+^|0100000        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.H
 4+^|0100010        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.H.S
 4+^|0100001        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.H
 4+^|0100010        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.H.D
 4+^|0100011        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.H
 4+^|0100010        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.H.Q
 4+^|1010010        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.H
 4+^|1010010        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.H
 4+^|1010010        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.H
 4+^|1110010        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.H
 4+^|1100010        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.H
 4+^|1100010        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.H
 4+^|1110010        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.X.H
 4+^|1101010        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.H.W
 4+^|1101010        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.H.WU
 4+^|1111010        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.H.X
|===

[%autowidth.stretch,float="center",align="center",cols="^m,^m,^m,^m,^m,^m,^m,<m",options="header"]
|===
8+|RV64Zfh 标准扩展（RV32Zfh 之外）
2+|1100010 |00010 |rs1 |rm |rd |1010011 |FCVT.L.H
2+|1100010 |00011 |rs1 |rm |rd |1010011 |FCVT.LU.H
2+|1101010 |00010 |rs1 |rm |rd |1010011 |FCVT.H.L
2+|1101010 |00011 |rs1 |rm |rd |1010011 |FCVT.H.LU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|Zawrs 标准扩展

6+^|000000001101 2+^|00000 2+^|000 2+^|00000 2+^|1110011 <|WRS.NTO
6+^|000000011101 2+^|00000 2+^|000 2+^|00000 2+^|1110011 <|WRS.STO
|===


<<rvgcsrnames>> 列出了当前已分配 CSR 地址的 CSR。计时器、计数器和浮点 CSR 是本规范中定义的唯一 CSR。

[[rvgcsrnames]]
.RISC-V 控制和状态寄存器 (CSR) 地址映射。
[%autowidth,float="center",align="center",cols="<m,<,<m,<",options="header"]
|===
|编号|特权|名称|描述
4+^|浮点控制和状态寄存器
|0x001|读写|fflags|浮点累积异常。
|0x002|读写|frm|浮点动态舍入模式。
|0x003|读写|fcsr|浮点控制和状态寄存器（`frm` + `fflags`）。
4+^|计数器和计时器
|0xC00|只读|cycle|RDCYCLE 指令的周期计数器。
|0x001|只读|time|RDTIME 指令的计时器。
|0x002|只读|instret|RDINSTRET 指令的已执行指令计数器。
|0xC80|只读|cycleh|`cycle` 的高 32 位，仅 RV32I。
|0xC81|只读|timeh|`time` 的高 32 位，仅 RV32I。
|0xC82|只读|instreth|`instret` 的高 32 位，仅 RV32I。
|===
