[[rv32]]
== RV32I 基本整数指令集，版本 2.1

本章描述了 RV32I 基本整数指令集。

[NOTE]
====
RV32I 旨在足以形成编译器目标并支持现代操作系统环境。ISA 的设计还旨在减少最小实现所需的硬件。RV32I 包含 40 条独特的指令，但一个简单的实现可能会用一个始终捕获的 SYSTEM 硬件指令来覆盖 ECALL/EBREAK 指令，并且可能能够将 FENCE 指令实现为 NOP，从而将基本指令计数减少到总共 38 条。RV32I 几乎可以模拟任何其他 ISA 扩展（除了 A 扩展，它需要额外的硬件支持原子性）。

实际上，包含机器模式特权架构的硬件实现还需要 6 条 CSR 指令。

基本整数 ISA 的子集可能对教学目的有用，但基本 ISA 的定义使得除了省略对未对齐内存访问的支持并将所有 SYSTEM 指令视为单个陷阱之外，几乎没有动力去子集化实际的硬件实现。
====

[NOTE]
====
标准 RISC-V 汇编语言语法记录在汇编程序员手册 cite:[riscv-asm-manual] 中。
====

[NOTE]
====
RV32I 的大部分注释也适用于 RV64I 基本指令集。
====

=== 基本整数 ISA 的程序员模型

<<gprs>> 显示了基本整数 ISA 的非特权状态。对于 RV32I，32 个 `x` 寄存器每个宽 32 位，即 `XLEN=32`。寄存器 `x0` 硬连线为所有位都为 0。通用寄存器 `x1-x31` 保存各种指令解释为布尔值集合、补码有符号二进制整数或无符号二进制整数的值。

还有一个额外的非特权寄存器：程序计数器 `pc` 保存当前指令的地址。

[[gprs]]
.RISC-V 基本非特权整数寄存器状态。
[cols="<,^,>",options="header",width="50%",align="center",grid="rows"]
|===
<| [.small]#XLEN-1#| >| [.small]#0#
3+^| [.small]#x0/zero#
3+^| [.small]#x1#
3+^| [.small]#x2#
3+^| [.small]#x3#
3+^| [.small]#x4#
3+^| [.small]#x5#
3+^| [.small]#x6#
3+^| [.small]#x7#
3+^| [.small]#x8#
3+^| [.small]#x9#
3+^| [.small]#x10#
3+^| [.small]#x11#
3+^| [.small]#x12#
3+^| [.small]#x13#
3+^| [.small]#x14#
3+^| [.small]#x15#
3+^| [.small]#x16#
3+^| [.small]#x17#
3+^| [.small]#x18#
3+^| [.small]#x19#
3+^| [.small]#x20#
3+^| [.small]#x21#
3+^| [.small]#x22#
3+^| [.small]#x23#
3+^| [.small]#x24#
3+^| [.small]#x25#
3+^| [.small]#x26#
3+^| [.small]#x27#
3+^| [.small]#x28#
3+^| [.small]#x29#
3+^| [.small]#x30#
3+^| [.small]#x31#
3+^| [.small]#pc#
|===
[NOTE]
====
基本整数 ISA 中没有专用的栈指针或子例程返回地址链接寄存器；指令编码允许任何 `x` 寄存器用于这些目的。然而，标准软件调用约定使用寄存器 `x1` 保存调用的返回地址，寄存器 `x5` 可用作备用链接寄存器。标准调用约定使用寄存器 `x2` 作为栈指针。

硬件可以选择加速使用 `x1` 或 `x5` 的函数调用和返回。请参阅 JAL 和 JALR 指令的描述。

可选的 16 位压缩指令格式是围绕 `x1` 是返回地址寄存器且 `x2` 是栈指针的假设设计的。使用其他约定的软件将正确运行，但代码大小可能更大。

可用架构寄存器的数量对代码大小、性能和能耗有很大影响。尽管 16 个寄存器对于运行编译代码的整数 ISA 来说可能足够，但不可能在 16 位指令中使用 3 地址格式编码完整的 ISA。尽管 2 地址格式是可能的，但它会增加指令计数并降低效率。我们希望避免中间指令大小（例如 Xtensa 的 24 位指令）以简化基本硬件实现，一旦采用 32 位指令大小，支持 32 个整数寄存器就很简单了。更多的整数寄存器还有助于提高高性能代码的性能，在这些代码中，可以广泛使用循环展开、软件流水线和缓存平铺。

由于这些原因，我们为 RV32I 选择了 32 个整数寄存器的常规大小。动态寄存器使用倾向于由少数频繁访问的寄存器主导，并且寄存器文件实现可以优化以减少频繁访问寄存器的访问能耗 cite:[jtseng:sbbci]。可选的 16 位压缩指令格式主要只访问 8 个寄存器，因此可以提供密集的指令编码，而附加指令集扩展如果需要，可以支持更大的寄存器空间（平面或分层）。

对于资源受限的嵌入式应用程序，我们定义了 RV32E 子集，它只有 16 个寄存器（<<rv32e>>）。
====
=== 基本指令格式
在基本 RV32I ISA 中，有四种核心指令格式（R/I/S/U），如 <<base_instr>> 所示。所有指令长度固定为 32 位。基本 ISA 的 `IALIGN=32`，这意味着指令必须在内存中对齐到四字节边界。如果目标地址未对齐 `IALIGN-bit`，则在执行分支或无条件跳转时会生成指令地址未对齐异常。此异常在分支或跳转指令上报告，而不是在目标指令上。未执行的条件分支不会生成指令地址未对齐异常。

[NOTE]
====
当添加具有 16 位长度或其他 16 位长度奇数倍的指令扩展时（即 IALIGN=16），基本 ISA 指令的对齐约束放宽到两字节边界。

指令地址未对齐异常在可能导致指令未对齐的分支或跳转上报告，以帮助调试，并简化 IALIGN=32 系统的硬件设计，因为这些是唯一可能发生未对齐的地方。
====

解码保留指令时的行为是未指定的。

[NOTE]
====
某些平台可能要求为标准用途保留的操作码引发非法指令异常。其他平台可能允许保留的操作码空间用于不符合的扩展。
====

RISC-V ISA 将源寄存器（_rs1_ 和 _rs2_）和目标寄存器（_rd_）保持在所有格式中的相同位置，以简化解码。除了 CSR 指令中使用的 5 位立即数（<<csrinsts>>）之外，立即数总是符号扩展的，并且通常打包到指令中最左侧可用的位，并已分配以降低硬件复杂性。特别是，所有立即数的符号位始终位于指令的第 31 位，以加快符号扩展电路的速度。

include::images/wavedrom/instruction-formats.edn[]
[[base_instr,基本指令格式]]
RISC-V 基本指令格式。每个立即数字段都标有其生成的立即数值中的位位置 (imm[x])，而不是像通常那样标有指令立即数字段中的位位置。

[NOTE]
====
解码寄存器说明符通常是实现中的关键路径，因此选择指令格式是为了将所有寄存器说明符保持在所有格式中的相同位置，代价是必须在格式之间移动立即数位（这是 RISC-IV，即 SPUR cite:[spur-jsscc1989] 共享的属性）。

实际上，大多数立即数要么很小，要么需要所有 XLEN 位。我们选择不对称的立即数拆分（常规指令中 12 位，加上一个特殊的加载高位立即数指令，具有 20 位）以增加常规指令可用的操作码空间。

立即数是符号扩展的，因为我们没有观察到像 MIPS ISA 那样对某些立即数使用零扩展的好处，并且希望保持 ISA 尽可能简单。
====

=== 立即数编码变体

指令格式还有另外两种变体（B/J），基于立即数的处理方式，如 <<baseinstformatsimm>> 所示。

include::images/wavedrom/immediate-variants.edn[]
[[baseinstformatsimm,基本指令格式立即数变体。]]
//.RISC-V 基本指令格式显示立即数变体。


S 和 B 格式之间唯一的区别是，12 位立即数字段用于在 B 格式中编码 2 字节倍数的分支偏移量。与传统上在硬件中将指令编码的立即数中的所有位左移一位不同，中间位 (imm[10:1]) 和符号位保持固定位置，而 S 格式中的最低位 (inst[7]) 编码 B 格式中的高位。

同样，U 和 J 格式之间唯一的区别是，20 位立即数左移 12 位形成 U 立即数，左移 1 位形成 J 立即数。U 和 J 格式立即数中指令位的位置选择是为了最大化与其他格式和彼此之间的重叠。

<<immtypes>> 显示了每种基本指令格式生成的立即数，并标明了哪个指令位 (inst[_y_]) 生成立即数值的每个位。

[[immtypes, 立即数类型]]
include::images/wavedrom/i-immediate.edn[]

include::images/wavedrom/s-immediate.edn[]

include::images/wavedrom/b-immediate.edn[]

include::images/wavedrom/u-immediate.edn[]

.RISC-V 指令生成的立即数类型。
include::images/wavedrom/j-immediate.edn[]


字段标有用于构造其值的指令位。符号扩展始终使用 inst[31]。

[NOTE]
====
符号扩展是立即数最关键的操作之一（特别是对于 XLEN>32），在 RISC-V 中，所有立即数的符号位始终位于指令的第 31 位，以允许符号扩展与指令解码并行进行。

尽管更复杂的实现可能对分支和跳转计算有单独的加法器，因此不会受益于保持立即数位位置在指令类型之间不变，但我们希望降低最简单实现的硬件成本。通过在 B 和 J 立即数的指令编码中旋转位，而不是使用动态硬件多路复用器将立即数乘以 2，我们将指令信号扇出和立即数多路复用器成本降低了大约 2 倍。打乱的立即数编码将对静态或预先编译增加可忽略的时间。对于指令的动态生成，会增加一些小的额外开销，但最常见的短前向分支具有简单的立即数编码。
====

=== 整数计算指令

大多数整数计算指令对整数寄存器文件中保存的 `XLEN` 位值进行操作。整数计算指令要么使用 I 型格式编码为寄存器-立即数操作，要么使用 R 型格式编码为寄存器-寄存器操作。目标是寄存器 _rd_，适用于寄存器-立即数和寄存器-寄存器指令。没有整数计算指令会导致算术异常。

[NOTE]
====
我们没有在基本指令集中包含对整数算术运算的溢出检查的特殊指令集支持，因为许多溢出检查可以使用 RISC-V 分支廉价地实现。
无符号加法的溢出检查只需要在加法后添加一条额外的分支指令：
`add t0, t1, t2; bltu t0, t1, overflow`。

对于有符号加法，如果已知一个操作数的符号，则溢出检查只需要在加法后添加一条额外的分支指令：
`addi t0, t1, +imm; blt t0, t1, overflow`。这涵盖了带立即数操作数的加法的常见情况。

对于通用有符号加法，在加法后需要三条额外的指令，利用了以下观察：当且仅当另一个操作数为负数时，和才应小于其中一个操作数。

[source,text]
....
         add t0, t1, t2
         slti t3, t2, 0
         slt t4, t0, t1
         bne t3, t4, overflow
....

在 RV64I 中，可以通过比较操作数上的 ADD 和 ADDW 的结果来进一步优化 32 位有符号加法的检查。
====

==== 整数寄存器-立即数指令

include::images/wavedrom/integer-computational.edn[]
//.整数计算指令

ADDI 将符号扩展的 12 位立即数添加到寄存器 _rs1_。算术溢出被忽略，结果只是结果的低 XLEN 位。ADDI _rd, rs1, 0_ 用于实现 MV _rd, rs1_ 汇编器伪指令。

SLTI（小于立即数设置）将值 1 放入寄存器 _rd_，如果寄存器 _rs1_ 小于符号扩展的立即数（两者都视为有符号数），否则将 0 写入 _rd_。SLTIU 类似，但将值视为无符号数进行比较（即，立即数首先符号扩展到 XLEN 位，然后视为无符号数）。注意，SLTIU _rd, rs1, 1_ 将 _rd_ 设置为 1，如果 _rs1_ 等于零，否则将 _rd_ 设置为 0（汇编器伪指令 SEQZ _rd, rs_）。

ANDI、ORI、XORI 是逻辑运算，对寄存器 _rs1_ 和符号扩展的 12 位立即数执行按位 AND、OR 和 XOR，并将结果放入 _rd_。注意，XORI _rd, rs1, -1_ 执行寄存器 _rs1_ 的按位逻辑反转（汇编器伪指令 NOT _rd, rs_）。

include::images/wavedrom/int-comp-slli-srli-srai.edn[]
[[int-comp-slli-srli-srai]]
//.整数寄存器-立即数，SLLI，SRLI，SRAI

常量移位编码为 I 型格式的特化。要移位的操作数在 _rs1_ 中，移位量编码在 I 立即数字段的低 5 位中。右移类型编码在第 30 位。SLLI 是逻辑左移（零移入低位）；SRLI 是逻辑右移（零移入高位）；SRAI 是算术右移（原始符号位复制到空出的高位）。

include::images/wavedrom/int-comp-lui-aiupc.edn[]
[[int-comp-lui-aiupc]]
//.整数寄存器-立即数，U-立即数

LUI（加载高位立即数）用于构建 32 位常量，并使用 U 型格式。LUI 将 32 位 U 立即数值放入目标寄存器 _rd_，将最低 12 位填充为零。

AUIPC（将高位立即数添加到 `pc`）用于构建 `pc` 相对地址，并使用 U 型格式。AUIPC 从 U 立即数形成 32 位偏移量，将最低 12 位填充为零，将此偏移量添加到 AUIPC 指令的地址，然后将结果放入寄存器 _rd_。

[NOTE]
====
`lui` 和 `auipc` 的汇编语法不表示 U 立即数的低 12 位，这些位始终为零。

AUIPC 指令支持两指令序列，用于访问 PC 的任意偏移量，用于控制流转移和数据访问。AUIPC 和 JALR 中 12 位立即数的组合可以将控制转移到任何 32 位 PC 相对地址，而 AUIPC 加上常规加载或存储指令中 12 位立即数偏移量可以访问任何 32 位 PC 相对数据地址。

当前 PC 可以通过将 U 立即数设置为 0 来获取。尽管 JAL +4 指令也可以用于获取本地 PC（JAL 之后指令的 PC），但它可能会在更简单的微架构中导致流水线中断，或者在更复杂的微架构中污染 BTB 结构。
====

==== 整数寄存器-寄存器操作

RV32I 定义了几个算术 R 型操作。所有操作都将 _rs1_ 和 _rs2_ 寄存器作为源操作数读取，并将结果写入寄存器 _rd_。_funct7_ 和 _funct3_ 字段选择操作类型。

include::images/wavedrom/int-reg-reg.edn[]
[[int-reg-reg]]
//.整数寄存器-寄存器

ADD 执行 _rs1_ 和 _rs2_ 的加法。SUB 执行 _rs1_ 减去 _rs2_ 的减法。溢出被忽略，结果的低 XLEN 位写入目标 _rd_。SLT 和 SLTU 分别执行有符号和无符号比较，如果 _rs1_ < _rs2_，则将 1 写入 _rd_，否则写入 0。注意，SLTU _rd_, _x0_, _rs2_ 将 _rd_ 设置为 1，如果 _rs2_ 不等于零，否则将 _rd_ 设置为零（汇编器伪指令 SNEZ _rd, rs_）。AND、OR 和 XOR 执行按位逻辑运算。

SLL、SRL 和 SRA 对寄存器 _rs1_ 中的值执行逻辑左移、逻辑右移和算术右移，移位量在寄存器 _rs2_ 的低 5 位中。

==== NOP 指令

include::images/wavedrom/nop.edn[]
[[nop]]
//.NOP 指令

NOP 指令不改变任何架构可见状态，除了推进 `pc` 和增加任何适用的性能计数器。NOP 编码为 ADDI _x0, x0, 0_。

[NOTE]
====
NOP 可用于将代码段对齐到微架构上重要的地址边界，或为内联代码修改留出空间。尽管有许多可能的方式来编码 NOP，但我们定义了一个规范的 NOP 编码，以允许微架构优化以及更可读的反汇编输出。其他 NOP 编码可用于 <<rv32i-hints>>。

选择 ADDI 作为 NOP 编码是因为它在各种系统上执行所需资源最少（如果未在解码中优化掉）。特别是，该指令只读取一个寄存器。此外，ADDI 功能单元在超标量设计中更可能可用，因为加法是最常见的操作。特别是，地址生成功能单元可以使用与基址+偏移地址计算所需的相同硬件执行 ADDI，而寄存器-寄存器 ADD 或逻辑/移位操作需要额外的硬件。
====

=== 控制转移指令
RV32I 提供两种类型的控制转移指令：无条件跳转和条件分支。RV32I 中的控制转移指令 _不_ 具有架构可见的延迟槽。

如果指令访问故障或指令页故障异常发生在跳转或已执行分支的目标上，则异常在目标指令上报告，而不是在跳转或分支指令上。

==== 无条件跳转
跳转和链接 (JAL) 指令使用 J 型格式，其中 J 立即数编码以 2 字节倍数表示的有符号偏移量。偏移量进行符号扩展并添加到跳转指令的地址以形成跳转目标地址。因此，跳转可以指向 ±1 MiB 范围。JAL 将跳转后指令的地址 (`pc`+4) 存储到寄存器 _rd_ 中。标准软件调用约定使用 `x1` 作为返回地址寄存器，`x5` 作为备用链接寄存器。

[NOTE]
====
备用链接寄存器支持调用微代码例程（例如，压缩代码中保存和恢复寄存器的例程），同时保留常规返回地址寄存器。选择寄存器 `x5` 作为备用链接寄存器，因为它在标准调用约定中映射到临时寄存器，并且其编码与常规链接寄存器仅相差一位。
====

普通无条件跳转（汇编器伪指令 J）编码为 _rd_=`x0` 的 JAL。

include::images/wavedrom/ct-unconditional.edn[]
[[ct-unconditional]]
//.无条件跳转指令 JAL

间接跳转指令 JALR（跳转和链接寄存器）使用 I 型编码。目标地址通过将符号扩展的 12 位 I 立即数添加到寄存器 _rs1_，然后将结果的最低有效位设置为零来获得。跳转后指令的地址 (`pc`+4) 写入寄存器 _rd_。如果不需要结果，可以将寄存器 `x0` 用作目标。

普通无条件间接跳转（汇编器伪指令 JR）编码为 _rd_=`x0` 的 JALR。
标准调用约定中的过程返回（汇编器伪指令 RET）编码为 _rd_=`x0`、_rs1_=`x1` 和 _imm_=0 的 JALR。

include::images/wavedrom/ct-unconditional-2.edn[]
[[ct-unconditional-2]]
//.间接无条件跳转指令 JALR

[NOTE]
====
所有无条件跳转指令都使用 PC 相对寻址，以帮助支持位置无关代码。JALR 指令的定义旨在实现两指令序列，以跳转到 32 位绝对地址范围内的任何位置。LUI 指令可以首先将目标地址的高 20 位加载到 _rs1_ 中，然后 JALR 可以添加低位。
同样，AUIPC 然后 JALR 可以跳转到 32 位 `pc` 相对地址范围内的任何位置。

请注意，JALR 指令不像条件分支指令那样将 12 位立即数视为 2 字节的倍数。这避免了硬件中多一个立即数格式。实际上，JALR 的大多数用法要么是零立即数，要么与 LUI 或 AUIPC 配对，因此范围的轻微减小并不显著。

在计算 JALR 目标地址时清除最低有效位既简化了硬件，又允许函数指针的最低位用于存储辅助信息。尽管在这种情况下可能存在轻微的错误检查损失，但实际上跳转到不正确的指令地址通常会很快引发异常。

当与基址 _rs1_=`x0` 一起使用时，JALR 可用于实现单个指令子例程调用到地址空间中最低或最高地址区域的任何位置，这可用于实现对小型运行时库的快速调用。或者，ABI 可以将通用寄存器专用于指向地址空间中其他位置的库。
====

JAL 和 JALR 指令如果目标地址未对齐到四字节边界，将生成指令地址未对齐异常。

[NOTE]
====
在支持 16 位对齐指令的机器上，例如压缩指令集扩展 C，指令地址未对齐异常是不可能的。
====

返回地址预测栈是高性能指令获取单元的常见功能，但需要准确检测用于过程调用和返回的指令才能有效。对于 RISC-V，关于指令用法的提示通过使用的寄存器编号隐式编码。JAL 指令应仅在 _rd_ 为 `x1` 或 `x5` 时将返回地址推送到返回地址栈 (RAS) 上。JALR 指令应按 <<rashints>> 所示推入/弹出 RAS。

[[rashints]]
.JALR 指令寄存器操作数中编码的返回地址栈预测提示。
[%autowidth,float="center",align="center",cols="^,^,^,<",options="header"]
|===
|_rd_ 是 _x1/x5_ |_rs1_ 是 _x1/x5_ |_rd_=_rs1_ |RAS 操作

|否 |否 |-- |无

|否 |是 |-- |弹出

|是 |否 |-- |推入

|是 |是 |否 |弹出，然后推入

|是 |是 |是 |推入
|===


[NOTE]
====
其他一些 ISA 在其间接跳转指令中添加了显式提示位，以指导返回地址栈操作。我们使用与寄存器编号和调用约定绑定的隐式提示，以减少这些提示使用的编码空间。

当两个不同的链接寄存器（`x1` 和 `x5`）作为 _rs1_ 和 _rd_ 给出时，RAS 会同时弹出和推入以支持协程。如果 _rs1_ 和 _rd_ 是相同的链接寄存器（`x1` 或 `x5`），则 RAS 只会推入，以实现序列的宏操作融合：`lui ra, imm20; jalr ra, imm12(ra)` 和 `auipc ra, imm20; jalr ra, imm12(ra)`。
====

==== 条件分支

所有分支指令都使用 B 型指令格式。12 位 B 立即数编码以 2 字节倍数表示的有符号偏移量。偏移量进行符号扩展并添加到分支指令的地址以给出目标地址。条件分支范围为 ±4 KiB。

include::images/wavedrom/ct-conditional.edn[]
[[ct-conditional]]
//.条件分支

分支指令比较两个寄存器。BEQ 和 BNE 在寄存器 _rs1_ 和 _rs2_ 分别相等或不相等时执行分支。BLT 和 BLTU 在 _rs1_ 小于 _rs2_ 时执行分支，分别使用有符号和无符号比较。BGE 和 BGEU 在 _rs1_ 大于或等于 _rs2_ 时执行分支，分别使用有符号和无符号比较。注意，BGT、BGTU、BLE 和 BLEU 可以通过分别反转 BLT、BLTU、BGE 和 BGEU 的操作数来合成。

[NOTE]
====
有符号数组边界可以用单个 BLTU 指令检查，因为任何负索引都将大于任何非负边界。
====

软件应进行优化，使顺序代码路径是最常见的路径，而较少执行的代码路径则放置在行外。软件还应假定向后分支将被预测为执行，而向前分支将被预测为不执行，至少在它们首次遇到时是这样。动态预测器应快速学习任何可预测的分支行为。

与某些其他架构不同，RISC-V 跳转（_rd_=`x0` 的 JAL）指令应始终用于无条件分支，而不是使用始终为真的条件分支指令。RISC-V 跳转也是 PC 相对的，并支持比分支更宽的偏移范围，并且不会污染条件分支预测表。

[NOTE]
====
条件分支的设计旨在包含两个寄存器之间的算术比较操作（如 PA-RISC、Xtensa 和 MIPS R6 中所做），而不是使用条件码（x86、ARM、SPARC、PowerPC），或者只比较一个寄存器与零（Alpha、MIPS），或者只比较两个寄存器是否相等（MIPS）。这种设计是基于以下观察：组合的比较和分支指令适合常规流水线，避免了额外的条件码状态或使用临时寄存器，并减少了静态代码大小和动态指令获取流量。另一点是，与零的比较需要非平凡的电路延迟（尤其是在高级工艺中转向静态逻辑之后），因此几乎与算术幅度比较一样昂贵。融合比较和分支指令的另一个优点是，分支在前端指令流中更早被观察到，因此可以更早地预测。在基于相同条件码可以进行多个分支的情况下，具有条件码的设计可能具有优势，但我们认为这种情况相对罕见。

我们考虑过但未在指令编码中包含静态分支提示。这些可以减少动态预测器的压力，但需要更多的指令编码空间和软件分析才能获得最佳结果，并且如果生产运行与分析运行不匹配，可能会导致性能不佳。

我们考虑过但未包含条件移动或谓词指令，它们可以有效地替代不可预测的短前向分支。条件移动是两者中较简单的一种，但难以与可能导致异常的条件代码（内存访问和浮点运算）一起使用。谓词向系统添加了额外的标志状态，用于设置和清除标志的额外指令，以及每个指令的额外编码开销。条件移动和谓词指令都增加了乱序微架构的复杂性，由于需要将目标架构寄存器的原始值复制到重命名的目标物理寄存器（如果谓词为假），因此增加了隐式第三个源操作数。此外，编译时静态决策使用谓词而不是分支可能会导致在编译器训练集中未包含的输入上性能降低，特别是考虑到不可预测的分支很少见，并且随着分支预测技术的改进而变得越来越少。
====

条件分支指令如果目标地址未对齐到四字节边界且分支条件评估为真，将生成指令地址未对齐异常。如果分支条件评估为假，则不会引发指令地址未对齐异常。

[NOTE]
====
在支持 16 位对齐指令的机器上，例如压缩指令集扩展 C，指令地址未对齐异常是不可能的。
====

[[ldst]]
=== 加载和存储指令
RV32I 是一种加载-存储架构，其中只有加载和存储指令访问内存，算术指令只对 CPU 寄存器进行操作。RV32I 提供 32 位地址空间，按字节寻址。EEI 将定义哪些地址空间部分可以使用哪些指令合法访问（例如，某些地址可能只读，或只支持字访问）。目标为 `x0` 的加载即使加载值被丢弃，也必须引发任何异常并导致任何其他副作用。

EEI 将定义内存系统是小端序还是大端序。在 RISC-V 中，字节序是字节地址不变的。

[NOTE]
====
在字节序不变的系统中，以下属性成立：如果一个字节以某种字节序存储到内存中的某个地址，则从该地址以任何字节序进行的字节大小加载都会返回存储的值。

在小端序配置中，多字节存储将最低有效寄存器字节写入最低内存字节地址，然后是按其重要性升序排列的其他寄存器字节。加载类似地将较低内存字节地址的内容传输到较低有效寄存器字节。

在大端序配置中，多字节存储将最高有效寄存器字节写入最低内存字节地址，然后是按其重要性降序排列的其他寄存器字节。加载类似地将较高内存字节地址的内容传输到较低有效寄存器字节。
====

include::images/wavedrom/load-store.edn[]
[[load-store,加载和存储]]
//.加载和存储指令

加载和存储指令在寄存器和内存之间传输值。加载以 I 型格式编码，存储以 S 型格式编码。有效地址通过将寄存器 _rs1_ 与符号扩展的 12 位偏移量相加获得。加载将值从内存复制到寄存器 _rd_。存储将寄存器 _rs2_ 中的值复制到内存。

LW 指令将 32 位值从内存加载到 _rd_ 中。LH 从内存加载 16 位值，然后符号扩展到 32 位，再存储到 _rd_ 中。LHU 从内存加载 16 位值，但零扩展到 32 位，再存储到 _rd_ 中。LB 和 LBU 对 8 位值进行类似定义。SW、SH 和 SB 指令将寄存器 _rs2_ 的低位中的 32 位、16 位和 8 位值存储到内存中。

无论 EEI 如何，有效地址自然对齐的加载和存储都不应引发地址未对齐异常。有效地址未自然对齐到引用数据类型（即，有效地址不能被访问大小（以字节为单位）整除）的加载和存储的行为取决于 EEI。

EEI 可以保证未对齐的加载和存储得到完全支持，因此在执行环境内部运行的软件永远不会遇到包含或致命的地址未对齐陷阱。在这种情况下，未对齐的加载和存储可以在硬件中处理，或者通过不可见的陷阱进入执行环境实现，或者可能是硬件和不可见陷阱的组合，具体取决于地址。

EEI 可能不保证未对齐的加载和存储得到隐式处理。在这种情况下，未自然对齐的加载和存储可能成功完成执行或引发异常。引发的异常可以是地址未对齐异常或访问故障异常。对于除了未对齐之外本可以完成的内存访问，如果未对齐访问不应被模拟，例如，如果对内存区域的访问具有副作用，则可以引发访问故障异常而不是地址未对齐异常。当 EEI 不保证未对齐的加载和存储得到隐式处理时，EEI 必须定义由地址未对齐引起的异常是否导致包含陷阱（允许在执行环境内部运行的软件处理陷阱）或致命陷阱（终止执行）。

[NOTE]
====
移植旧代码时偶尔需要未对齐访问，并且在使用任何形式的打包 SIMD 扩展或处理外部打包数据结构时有助于提高应用程序的性能。我们允许 EEI 选择通过常规加载和存储指令支持未对齐访问的理由是简化未对齐硬件支持的添加。一种选择是禁止基本 ISA 中的未对齐访问，然后为未对齐访问提供一些单独的 ISA 支持，要么是帮助软件处理未对齐访问的特殊指令，要么是用于未对齐访问的新硬件寻址模式。特殊指令难以使用，使 ISA 复杂化，并且通常会添加新的处理器状态（例如，SPARC VIS 对齐地址偏移寄存器）或使访问现有处理器状态复杂化（例如，MIPS LWL/LWR 部分寄存器写入）。此外，对于面向循环的打包 SIMD 代码，当操作数未对齐时，额外的开销促使软件根据操作数对齐提供多种形式的循环，这使代码生成复杂化并增加了循环启动开销。新的未对齐硬件寻址模式在指令编码中占用大量空间，或者需要非常简化的寻址模式（例如，仅寄存器间接）。
====

即使未对齐的加载和存储成功完成，这些访问也可能运行得非常慢，具体取决于实现（例如，通过不可见的陷阱实现时）。此外，虽然自然对齐的加载和存储保证原子执行，但未对齐的加载和存储可能不原子执行，因此需要额外的同步以确保原子性。

[NOTE]
====
我们不强制要求未对齐访问的原子性，因此执行环境实现可以使用不可见的机器陷阱和软件处理程序来处理部分或全部未对齐访问。如果提供了硬件未对齐支持，软件可以通过简单地使用常规加载和存储指令来利用这一点。然后硬件可以根据运行时地址是否对齐来自动优化访问。
====

[[fence]]
=== 内存排序指令

include::images/wavedrom/mem-order.edn[]
[[mem-order]]
//.内存排序指令

FENCE 指令用于排序设备 I/O 和内存访问，从其他 RISC-V hart 和外部设备或协处理器的角度来看。任何设备输入 (I)、设备输出 (O)、内存读取 (R) 和内存写入 (W) 的组合都可以相互排序。非正式地，在 FENCE 之后，任何其他 RISC-V hart 或外部设备都不能在 FENCE 之前观察到 _后继_ 集中的任何操作，除非在 FENCE 之前 _前驱_ 集中的任何操作。
<<memorymodel>> 提供了 RISC-V 内存一致性模型的精确描述。

FENCE 指令还排序 hart 进行的内存读取和写入，从外部设备观察到的内存读取和写入。然而，FENCE 指令不排序使用任何其他信令机制的外部设备观察到的事件。

[NOTE]
====
设备可能通过某种外部通信机制观察对内存位置的访问，例如，驱动中断信号到中断控制器的内存映射控制寄存器。此通信超出了 FENCE 排序机制的范围，因此 FENCE 指令无法保证中断信号何时对中断控制器可见。特定设备可能提供额外的排序保证以减少软件开销，但这些超出了 RISC-V 内存模型的范围。
====

EEI 将定义哪些 I/O 操作是可能的，特别是，当加载和存储指令访问哪些内存地址时，它们将被视为设备输入和设备输出操作，而不是内存读取和写入。例如，内存映射 I/O 设备通常将通过未缓存的加载和存储访问，这些加载和存储使用 I 和 O 位而不是 R 和 W 位进行排序。指令集扩展也可能描述新的 I/O 指令，这些指令也将使用 FENCE 指令中的 I 和 O 位进行排序。

[[fm]]
[float="center",align="center",cols="^1,^1,<3",options="header"]
.栅栏模式编码
|===
|_fm_ 字段 |助记符后缀|含义
|0000 |_无_ |普通栅栏
|1000 |.TSO |与 `FENCE RW,RW`：排除写-读排序；否则：_保留供将来使用。_
|_其他_|_其他_ |_保留供将来使用。_
|===

FENCE 模式字段 _fm_ 定义了 FENCE 指令的语义。`FENCE`（_fm_=`0000`）将其前驱集中的所有内存操作排序在其后继集中的所有内存操作之前。

`FENCE.TSO` 指令编码为 FENCE 指令，其中 _fm_=`1000`，_predecessor_=`RW`，_successor_=`RW`。`FENCE.TSO` 将其前驱集中的所有加载操作排序在其后继集中的所有内存操作之前，并将其前驱集中的所有存储操作排序在其后继集中的所有存储操作之前。这使得 `FENCE.TSO` 前驱集中的 `非 AMO` 存储操作与其后继集中的 `非 AMO` 加载操作无序。

[NOTE]
====
因为 `FENCE RW,RW` 施加的排序是 `FENCE.TSO` 施加的排序的超集，所以忽略 _fm_ 字段并将 `FENCE.TSO` 实现为 `FENCE RW,RW` 是正确的。
====

FENCE 指令中未使用的字段——_rs1_ 和 _rd_——保留用于未来扩展中更细粒度的栅栏。为了向前兼容，基本实现应忽略这些字段，标准软件应将这些字段清零。同样，许多 _fm_ 和前驱/后继集设置也保留供将来使用。
基本实现应将所有此类保留配置视为 `FENCE` 指令（_fm_=`0000`），标准软件应仅使用非保留配置。

[NOTE]
====
我们选择了一种宽松的内存模型，以允许简单的机器实现以及未来可能的协处理器或加速器扩展实现高性能。我们将 I/O 排序与内存 R/W 排序分开，以避免设备驱动程序 hart 中不必要的串行化，并支持控制附加协处理器或 I/O 设备的替代非内存路径。简单的实现还可以忽略 _predecessor_ 和 _successor_ 字段，并始终对所有操作执行保守的 FENCE。
====

[[ecall-ebreak]]
=== 环境调用和断点
`SYSTEM` 指令用于访问可能需要特权访问的系统功能，并使用 I 型指令格式编码。这些指令可分为两大类：原子读-改-写控制和状态寄存器 (CSR) 的指令，以及所有其他潜在的特权指令。CSR 指令在 <<csrinsts>> 中描述，基本非特权指令在以下部分中描述。


[NOTE]
====
SYSTEM 指令的定义允许更简单的实现始终捕获到单个软件陷阱处理程序。更复杂的实现可能会在硬件中执行更多每个系统指令。
====

include::images/wavedrom/env-call-breakpoint.edn[]
[[env-call]]
//.环境调用和断点指令

这两个指令会导致对支持执行环境的精确请求陷阱。

`ECALL` 指令用于向执行环境发出服务请求。EEI 将定义服务请求的参数如何传递，但通常这些参数将位于整数寄存器文件中的定义位置。

`EBREAK` 指令用于将控制权返回给调试环境。

[NOTE]
====
ECALL 和 EBREAK 以前分别命名为 SCALL 和 SBREAK。这些指令具有相同的功能和编码，但已重命名以反映它们可以更广泛地使用，而不仅仅是调用 supervisor 级操作系统或调试器。
====

[NOTE]
====
EBREAK 主要设计用于调试器，以使执行停止并回退到调试器。EBREAK 也被标准 GCC 编译器用于标记不应执行的代码路径。

EBREAK 的另一个用途是支持“半主机”，其中执行环境包括一个调试器，该调试器可以通过围绕 EBREAK 指令构建的替代系统调用接口提供服务。由于 RISC-V 基本 ISA 不提供多于一个 EBREAK 指令，因此 RISC-V 半主机使用特殊的指令序列来区分半主机 EBREAK 和调试器插入的 EBREAK。

[source,asm]
....
    slli x0, x0, 0x1f   # 入口 NOP
    ebreak              # 中断到调试器
    srai x0, x0, 7      # 出口 NOP
....

请注意，这三条指令必须是 32 位宽的指令，即它们不能是 <<compressed>> 中描述的 16 位压缩指令。

移位 NOP 指令仍被视为可用于 HINT。

半主机是一种服务调用形式，更自然地编码为使用现有 ABI 的 ECALL，但这将要求调试器能够拦截 ECALL，这是调试标准中较新的添加。我们打算转向使用带有标准 ABI 的 ECALL，在这种情况下，半主机可以与现有标准共享服务 ABI。

我们注意到 ARM 处理器在较新的设计中也已转向使用 SVC 而不是 BKPT 进行半主机调用。
====

=== HINT 指令
//[#rv32i-hints,HINT 指令]

[[rv32i-hints,HINT 指令]]

RV32I 为 HINT 指令保留了大量的编码空间，这些指令通常用于向微架构传递性能提示。与 NOP 指令一样，HINT 不改变任何架构可见状态，除了推进 `pc` 和增加任何适用的性能计数器。实现始终允许忽略编码的提示。

大多数 RV32I HINT 编码为整数计算指令，其中 _rd_=`x0`。其他 RV32I HINT 编码为 FENCE 指令，其前驱或后继集为空，且 _fm_=0。

[NOTE]
====
选择这些 HINT 编码是为了让简单的实现可以完全忽略 HINT，而是将 HINT 作为常规指令执行，该指令恰好不改变架构状态。例如，如果目标寄存器是 `x0`，则 ADD 是 HINT；五位 _rs1_ 和 _rs2_ 字段编码 HINT 的参数。然而，一个简单的实现可以简单地将 HINT 作为 _rs1_ 和 _rs2_ 的 ADD 执行，该 ADD 写入 `x0`，这没有架构可见的效果。

作为另一个示例，_pred_ 字段为零且 _fm_ 字段为零的 FENCE 指令是 HINT；_succ_、_rs1_ 和 _rd_ 字段编码 HINT 的参数。一个简单的实现可以简单地将 HINT 作为 FENCE 执行，该 FENCE 将空集的前置内存访问排序在 _succ_ 字段中编码的任何后续内存访问之前。由于前驱和后继集的交集为空，因此该指令不施加任何内存排序，因此它没有架构可见的效果。
====

<<t-rv32i-hints>> 列出了所有 RV32I HINT 代码点。91% 的 HINT 空间保留用于标准 HINT。HINT 空间的其余部分指定用于自定义 HINT：在此子空间中永远不会定义标准 HINT。

[NOTE]
====
我们预计标准提示最终将包括内存系统空间和时间局部性提示、分支预测提示、线程调度提示、安全标签以及用于仿真/模拟的仪器化标志。
====

// this table might still have some problems--some rows might not have landed properly. It needs to be checked cell-by cell.

[[t-rv32i-hints]]
.RV32I HINT 指令。
[float="center",align="center",cols="<,<,^,<",options="header"]
|===
|指令 |约束 |代码点 |目的

|LUI |_rd_=`x0` |latexmath:[$2^{20}$] .8+<.^m|_指定用于未来的标准用途_

|AUIPC |_rd_=`x0` |latexmath:[$2^{20}$]

|ADDI |_rd_=`x0`，且 _rs1_≠`x0` 或 _imm_≠0 |latexmath:[$2^{17}-1$]

|ANDI |_rd_=`x0` |latexmath:[$2^{17}$]

|ORI |_rd_=`x0` |latexmath:[$2^{17}$]

|XORI |_rd_=`x0` |latexmath:[$2^{17}$]

|ADD |_rd_=`x0`，_rs1_≠`x0` |latexmath:[$2^{10}-32$]

|ADD |_rd_=`x0`，_rs1_=`x0`，_rs2_≠`x2-x5` | 28

|ADD |_rd_=`x0`，_rs1_=`x0`，_rs2_=`x2-x5` |4|（_rs2_=`x2`）NTL.P1 +
（_rs2_=`x3`）NTL.PALL +
（_rs2_=`x4`）NTL.S1 +
（_rs2_=`x5`）NTL.ALL

|SLLI |_rd_=`x0`，_rs1_=`x0`，_shamt_=31 |1|半主机入口标记

|SRAI |_rd_=`x0`，_rs1_=`x0`，_shamt_=7 |1|半主机出口标记

|SUB |_rd_=`x0` |latexmath:[$2^{10}$] .11+<.^m|_指定用于未来的标准用途_

|AND |_rd_=`x0` |latexmath:[$2^{10}$]

|OR |_rd_=`x0` |latexmath:[$2^{10}$]

|XOR |_rd_=`x0` |latexmath:[$2^{10}$]

|SLL |_rd_=`x0` |latexmath:[$2^{10}$]

|SRL |_rd_=`x0` |latexmath:[$2^{10}$]

|SRA |_rd_=`x0` |latexmath:[$2^{10}$]

|FENCE|_rd_=`x0`，_rs1_≠`x0`，_fm_=0，且 _pred_=0 或 _succ_=0| latexmath:[$2^{10}-63$]

|FENCE|_rd_≠`x0`，_rs1_=`x0`，_fm_=0，且 _pred_=0 或 _succ_=0| latexmath:[$2^{10}-63$]

|FENCE |_rd_=_rs1_=`x0`，_fm_=0，_pred_=0，_succ_≠0 |15

|FENCE |_rd_=_rs1_=`x0`，_fm_=0，_pred_≠W，_succ_=0 |15

|FENCE |_rd_=_rs1_=`x0`，_fm_=0，_pred_=W，_succ_=0 |1|PAUSE

4+|

|SLTI |_rd_=`x0` |latexmath:[$2^{17}$] .7+<.^m|_指定用于自定义用途_

|SLTIU|_rd_=`x0` |latexmath:[$2^{17}$]

|SLLI |_rd_=`x0`，且 _rs1_≠`x0` 或 _shamt_≠31 |latexmath:[$2^{10}-1$]

|SRLI |_rd_=`x0` |latexmath:[$2^{10}$]

|SRAI |_rd_=`x0`，且 _rs1_≠`x0` 或 _shamt_≠7 |latexmath:[$2^{10}-1$]

|SLT |_rd_=`x0` |latexmath:[$2^{10}$]

|SLTU |_rd_=`x0` |latexmath:[$2^{10}$]
|===

NOTE: `slli x0, x0, 0x1f` 和 `srai x0, x0, 7` 以前被指定为自定义 HINT，但它们已被用于半主机调用，如 <<ecall-ebreak>> 中所述。
为了反映它们在实践中的用法，基本 ISA 规范已更改为将它们指定为标准 HINT。
