[[smcntrpmf]]

== “Smcntrpmf”周期和指令退役特权模式过滤，版本 1.0

=== 引言

周期和指令退役计数器旨在支持用户模式自分析用途，用户可以读取计数器两次并计算增量以评估用户软件性能和行为。默认情况下，这些计数器不受特权模式过滤，因此它们在处理更特权代码的陷阱（例如，页故障或中断）时会继续递增。这导致两个问题：

* 它给用户观察到的计数器值引入了不可预测的噪声。
* 它将特权软件执行的信息泄露给用户模式。

Smcntrpmf 通过为周期和指令退役计数器引入特权模式过滤来解决这些问题。

=== CSR

==== 机器计数器配置 (`mcyclecfg`, `minstretcfg`) 寄存器

mcyclecfg 和 minstretcfg 是 64 位寄存器，分别配置周期和指令退役计数器的特权模式过滤。

[cols="^1,^1,^1,^1,^1,^1,^5",stripes=even,options="header"]
|====
|63 |62 |61 |60 |59 |58 |57:0
|0 |MINH |SINH |UINH |VSINH |VUINH |_WPRI_
|====

[cols="15%,85%",options="header"]
|====
| 字段 | 描述
| MINH | 如果设置，则禁止在 M 模式下计数事件
| SINH | 如果设置，则禁止在 S/HS 模式下计数事件
| UINH | 如果设置，则禁止在 U 模式下计数事件
| VSINH | 如果设置，则禁止在 VS 模式下计数事件
| VUINH | 如果设置，则禁止在 VU 模式下计数事件
|====

当所有 __x__INH 位都为零时，所有模式都启用事件计数。

对于 61:58 中的每个位，如果关联的特权模式未实现，则该位为只读零。

对于 RV32，mcyclecfg 的 63:32 位可以通过 mcyclecfgh CSR 访问，minstretcfg 的 63:32 位可以通过 minstretcfgh CSR 访问。

如果实现了 Smcdeleg/Ssccfg 扩展，则这些寄存器的内容可以从 Supervisor 级别访问。

[NOTE]
====
mcyclecfg 更自然的 CSR 编号是 0x320，但该编号已分配给 mcountinhibit。

此寄存器格式与 Sscofpmf 为可编程计数器指定的格式匹配。OF 位的位位置（位 63）是只读 0，因为这些计数器在溢出时不会生成本地计数器溢出中断。
====

=== 计数器行为

周期和指令退役的基本行为被修改为在抑制特权模式下执行时不进行计数。此外，以下定义了非抑制特权模式和抑制特权模式之间的转换如何计数。

周期计数器将简单地在 CPU 处于非抑制特权模式时计数 CPU 周期。模式转换操作（陷阱和陷阱返回）可能需要多个时钟周期，并且特权模式的更改可能在这些周期中的任何一个中报告（对于每次陷阱或陷阱返回的发生可能不同）。

[NOTE]
====
RISC-V ISA 没有要求陷阱或陷阱返回的周期数在所有发生时都相同。实现可以自由决定此数字的一致性和可预测性（或不一致和不可预测性），对于特权模式更改发生的特定周期也是如此。
====

对于指令退役计数器，大多数指令不影响模式转换，因此对于这些指令，行为是明确的：在非抑制模式下退役的指令会增加指令退役计数，而在抑制模式下退役的指令则不会。有两种类型的指令可以影响特权模式更改：导致同步异常到更特权模式的指令，以及返回到较低特权模式的 xRET 指令。前者不被视为退役，因此不增加指令退役计数。后者会退役，并且只有在原始特权模式未被抑制时才应增加指令退役计数。

[NOTE]
====
上述指令退役定义旨在确保计数器以可预测的方式递增。例如，考虑一个场景，其中 minstretcfg 配置为除 U 模式之外的所有模式都被抑制。用户模式加载应该只递增一次，即使它发生页故障或其他异常。根据此定义，加载的故障执行不会递增（它不会退役），处理程序指令不会递增（它们在抑制模式下执行），包括 xRET（它可能在非抑制模式下退役，但它源于抑制模式）。只有当加载重新执行并退役时，它才会增加指令退役计数。

在指令被软件模拟的情况下，如果软件在 minstretcfg 中被抑制的特权模式下运行，则模拟例程必须模拟指令退役计数。
====
