[[Sscofpmf]]
== “Sscofpmf”扩展：计数溢出和基于模式的过滤，版本 1.0

当前的特权规范定义了 mhpmevent CSR 来选择和控制关联的 hpmcounter CSR 的事件计数，但没有标准化这些 CSR 中的任何字段。对于至少 Linux 类的富操作系统系统，标准化某些广泛需要的基本功能是可取的（并且在过去一年多的 RISC-V 列表中出现过，并且一直是过去提案的主题）。这使得可以有标准的上游软件支持，从而消除了实现提供自己的自定义软件支持的需要。

此扩展旨在在现有 mhpmevent CSR 中实现这一点（并相应地避免不必要地创建全新的 CSR 集——除了一个新 CSR）。

此扩展坚持解决两个基本且广为人知的需求，这些需求已由各种人员提出。为了便于理解与当前 Priv 1.11/1.12 规范的差异，本文以对 Priv 规范文本现有段落的实际精确更改（或现有文本中的附加段落）的形式编写。

扩展名称是“Sscofpmf”（“Ss”表示特权架构和 Supervisor 级扩展，“cofpmf”表示计数溢出和特权模式过滤）。

请注意，新的计数溢出中断将被视为标准本地中断，分配给 mip/mie/sip/sie 寄存器中的位 13。

=== 计数溢出控制

以下位已添加到 `mhpmevent`：

[cols="^1,^1,^1,^1,^1,^1,^1,^1",stripes=even,options="header"]
|====
|63 |62 |61 |60 |59 |58 |57 |56
|OF |MINH |SINH |UINH |VSINH |VUINH |_WPRI_ |_WPRI_
|====

[cols="15%,85%",options="header"]
|====
| 字段 | 描述
| OF | 计数器溢出时设置的溢出状态和中断禁用位
| MINH | 如果设置，则禁止在 M 模式下计数事件
| SINH | 如果设置，则禁止在 S/HS 模式下计数事件
| UINH | 如果设置，则禁止在 U 模式下计数事件
| VSINH | 如果设置，则禁止在 VS 模式下计数事件
| VUINH | 如果设置，则禁止在 VU 模式下计数事件
| _WPRI_ | 保留
| _WPRI_ | 保留
|====

对于每个 `x`INH 位，如果关联的特权模式未实现，则该位为只读零。

五个 `x`INH 位中的每个位，当设置时，禁止在特权模式 `x` 中计数事件。这些位全为零会导致在所有模式下计数事件。

当相应的 hpmcounter 溢出时，OF 位被设置，并保持设置状态直到软件写入。由于 hpmcounter 值是无符号值，因此溢出定义为已实现计数器位的无符号溢出。请注意，溢出后没有信息丢失，因为计数器会回绕并继续计数，同时粘性 OF 位保持设置状态。

如果实现了 supervisor 模式，则 32 位 scountovf 寄存器包含所有 32 个 mhpmevent 寄存器中 OF 位的只读影子副本。

如果 hpmcounter 溢出而关联的 OF 位为零，则会生成“计数溢出中断请求”。如果 OF 位为一，则不生成中断请求。因此，OF 位也充当关联 hpmcounter 的计数溢出中断禁用。

计数溢出永远不会由写入 mhpmcounter__n__ 或 mhpmevent__n__ 寄存器引起，仅由计数器寄存器的硬件递增引起。

此计数溢出中断请求信号被视为标准本地中断，对应于 `mip`/`mie`/`sip`/`sie` 寄存器中的位 13。
`mip`/`sip` LCOFIP 和 `mie`/`sie` LCOFIE 位分别是此中断的中断待处理和中断使能位。
（“LCOFI”表示“本地计数溢出中断”。）

由 `hpmcounter` 生成的计数溢出中断请求会设置关联的 OF 位。
当 OF 位被设置时，它最终（但不一定立即）设置 `mip`/`sip` 寄存器中的 LCOFIP 位。
LCOFIP 位在处理一个或多个计数溢出导致计数溢出中断之前由软件清除。
`mideleg` 寄存器控制此中断委托给 S 模式还是 M 模式。

[NOTE]
====
没有单独的溢出状态和溢出中断使能位。实际上，启用溢出中断生成（通过清除 OF 位）与将计数器初始化为起始值同时进行。一旦计数器溢出，它和 OF 位必须重新初始化，然后才能生成另一个溢出中断。
====

[NOTE]
====
软件可以通过维护一个位掩码来区分新溢出的计数器（尚未由溢出中断处理程序处理）和已处理或配置为不生成溢出中断的溢出计数器，该位掩码反映了哪些计数器处于活动状态并最终会溢出。
====

=== Supervisor 计数溢出 (`scountovf`) 寄存器

此扩展添加了 `scountovf` CSR，一个 32 位只读寄存器，包含 29 个 mhpmevent CSR（mhpmevent__3__ - mhpmevent__31__）中 OF 位的影子副本——其中 scountovf 位 _X_ 对应于 mhpmevent__X__。

此寄存器使 supervisor 级溢出中断处理程序软件能够快速轻松地确定哪些计数器已溢出（无需进行执行环境调用或一系列调用最终到 M 模式）。

对位 _X_ 的读取受相同的 mcounteren（或 mcounteren 和 hcounteren）CSR 的限制，这些 CSR 介导 S 模式（或 VS 模式）对 hpmcounter CSR 的访问。在 M 模式下，scountovf 位 _X_ 始终可读。在 S/HS 模式下，当 mcounteren 位 _X_ 设置时，scountovf 位 _X_ 可读，否则读取为零。同样，在 VS 模式下，当 mcounteren 位 _X_ 和 hcounteren 位 _X_ 都设置时，scountovf 位 _X_ 可读，否则读取为零。
