[[Zicond]]
== “Zicond”整数条件运算扩展，版本 1.0.0

[[intro]]
=== 引言
Zicond 扩展定义了一个简单的解决方案，它提供了人们期望的用于支持条件算术和条件选择/移动运算的大部分好处和全部灵活性，同时忠于 RISC-V 的设计理念。
这些指令遵循具有 3 个操作数（即 2 个源操作数和 1 个目标操作数）的 R 型指令格式。
使用这些指令，可以实现无分支序列（通常在两条指令的序列中），而无需指令融合、在架构指令解码期间的特殊规定或其他微架构规定。

与竞争的指令集架构相比，RISC-V 的缺点之一是缺少用于支持无分支代码生成的条件运算：这包括条件算术、条件选择和条件移动运算。
RISC-V 的设计原则（例如，缺少支持 3 个源寄存器和一个输出寄存器的指令格式）使得不太可能引入与竞争指令直接等效的指令。

然而，低成本的条件指令是一个理想的功能，因为它们允许在各种合适的情况下替换分支（无论分支是不可预测的还是可预测的），从而减少对 BTB 和分支预测器的容量和别名压力，并允许更长的基本块（供硬件和编译器使用）。

=== Zicond 规范

“条件”运算扩展提供了一个简单的解决方案，它提供了人们期望的用于支持条件算术和条件选择/移动运算的大部分好处和全部灵活性，同时忠于 RISC-V 的设计理念。
这些指令遵循具有 3 个操作数（即 2 个源操作数和 1 个目标操作数）的 R 型指令格式。
使用这些指令，可以实现无分支序列（通常在两条指令的序列中），而无需指令融合、在架构指令解码期间的特殊规定或其他微架构规定。

Zicond 扩展包含以下指令：

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|czero.eqz _rd_, _rs1_, _rs2_
|<<#insns-czero-eqz>>

|&#10003;
|&#10003;
|czero.nez _rd_, _rs1_, _rs2_
|<<#insns-czero-nez>>

|===

[NOTE]
====
架构评论：除了等于零和不等于零之外，定义额外的比较并没有提供好处，因为缺少进行比较的立即数或额外的寄存器操作数。
====

基于这两条指令，支持以下*条件算术*运算的合成指令（即短指令序列）：

* 如果为零，则条件加法
* 如果非零，则条件加法
* 如果为零，则条件减法
* 如果非零，则条件减法
* 如果为零，则条件按位与
* 如果非零，则条件按位与
* 如果为零，则条件按位或
* 如果非零，则条件按位或
* 如果为零，则条件按位异或
* 如果非零，则条件按位异或

此外，还支持以下*条件选择*指令：

* 如果为零，则条件选择
* 如果非零，则条件选择

更复杂的条件，例如与立即数、寄存器、单位测试、与范围的比较等，可以通过将这些新指令与现有指令组合来实现。

=== 指令（按字母顺序）

[#insns-czero-eqz,reftext="条件零，如果条件等于零"]
==== czero.eqz

概要：
如果条件 _rs2_ 等于零，则将零移动到寄存器 _rd_，否则将 _rs1_ 移动到 _rd_。

助记符：
czero.eqz _rd_, _rs1_, _rs2_

编码：
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x5, attr: ['CZERO.EQZ']},
    { bits:  5, name: 'rs1', attr: ['value'] },
    { bits:  5, name: 'rs2', attr: ['condition'] },
    { bits:  7, name: 0x7, attr: ['CZERO'] },
]}
....

描述：
如果 _rs2_ 包含值零，则此指令将值零写入 _rd_。否则，此指令将 _rs1_ 的内容复制到 _rd_。

此指令带有从 _rs1_ 和 _rs2_ 到 _rd_ 的语法依赖性。
此外，如果实现了 Zkt 扩展，则此指令的时间与 _rs1_ 和 _rs2_ 中的数据值无关。

SAIL 代码：
[source,sail]
--
  let condition = X(rs2);
  result : xlenbits = if (condition == zeros()) then zeros()
                                                else X(rs1);
  X(rd) = result;
--

<<<

[#insns-czero-nez,reftext="条件零，如果条件非零"]
==== czero.nez

概要：
如果条件 _rs2_ 非零，则将零移动到寄存器 _rd_，否则将 _rs1_ 移动到 _rd_。

助记符：
czero.nez _rd_, _rs1_, _rs2_

编码：
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x7, attr: ['CZERO.NEZ']},
    { bits:  5, name: 'rs1', attr: ['value'] },
    { bits:  5, name: 'rs2', attr: ['condition'] },
    { bits:  7, name: 0x7, attr: ['CZERO'] },
]}
....

描述：
如果 _rs2_ 包含非零值，则此指令将值零写入 _rd_。否则，此指令将 _rs1_ 的内容复制到 _rd_。

此指令带有从 _rs1_ 和 _rs2_ 到 _rd_ 的语法依赖性。
此外，如果实现了 Zkt 扩展，则此指令的时间与 _rs1_ 和 _rs2_ 中的数据值无关。

SAIL 代码：
[source,sail]
--
  let condition = X(rs2);
  result : xlenbits = if (condition != zeros()) then zeros()
                                                else X(rs1);
  X(rd) = result;
--

=== 用法示例

此扩展中的指令可用于构建执行条件算术、条件按位逻辑和条件选择运算的序列。

==== 指令序列

[%header,cols="4,.^3l,^2"]
|===
|运算
|指令序列
|长度

|*如果为零，则条件加法* +
`rd = (rc == 0) ? (rs1 + rs2) : rs1`
|czero.nez  rd, rs2, rc
add        rd, rs1, rd
.8+.^|2 条指令

|*如果非零，则条件加法* +
`rd = (rc != 0) ? (rs1 + rs2) : rs1`
|czero.eqz  rd, rs2, rc
add        rd, rs1, rd

|*如果为零，则条件减法* +
`rd = (rc == 0) ? (rs1 - rs2) : rs1`
|czero.nez  rd, rs2, rc
sub        rd, rs1, rd

|*如果非零，则条件减法* +
`rd = (rc != 0) ? (rs1 - rs2) : rs1`
|czero.eqz  rd, rs2, rc
sub        rd, rs1, rd

|*如果为零，则条件按位或* +
`rd = (rc == 0) ? (rs1 \| rs2) : rs1`
|czero.nez  rd, rs2, rc
or         rd, rs1, rd

|*如果非零，则条件按位或* +
`rd = (rc != 0) ? (rs1 \| rs2) : rs1`
|czero.eqz  rd, rs2, rc
or         rd, rs1, rd

|*如果为零，则条件按位异或* +
`rd = (rc == 0) ? (rs1 ^ rs2) : rs1`
|czero.nez  rd, rs2, rc
xor        rd, rs1, rd

|*如果非零，则条件按位异或* +
`rd = (rc != 0) ? (rs1 ^ rs2) : rs1`
|czero.eqz  rd, rs2, rc
xor        rd, rs1, rd

|*如果为零，则条件按位与* +
`rd = (rc == 0) ? (rs1 & rs2) : rs1`
|and        rd, rs1, rs2
czero.eqz  rtmp, rs1, rc
or         rd, rd, rtmp
.4+.^|3 条指令 +
（需要 1 个临时寄存器）

|*如果非零，则条件按位与* +
`rd = (rc != 0) ? (rs1 & rs2) : rs1`
|and        rd, rs1, rs2
czero.nez  rtmp, rs1, rc
or         rd, rd, rtmp

|*如果为零，则条件选择* +
`rd = (rc == 0) ? rs1 : rs2`
|czero.nez  rd, rs1, rc
czero.eqz  rtmp, rs2, rc
or         rd, rd, rtmp

|*如果非零，则条件选择* +
`rd = (rc != 0) ? rs1 : rs2`
|czero.eqz  rd, rs1, rc
czero.nez  rtmp, rs2, rc
or         rd, rd, rtmp

|===
