[[csrinsts]]
== “Zicsr”，控制和状态寄存器 (CSR) 指令扩展，版本 2.0

RISC-V 为每个 hart 定义了一个包含 4096 个控制和状态寄存器的独立地址空间。本章定义了操作这些 CSR 的完整 CSR 指令集。

[NOTE]
====
虽然 CSR 主要由特权架构使用，但在非特权代码中也有多种用途，包括用于计数器和定时器，以及用于浮点状态。

计数器和定时器不再被视为标准基础 ISA 的强制性部分，因此访问它们所需的 CSR 指令已从 <<rv32>> 移至本独立章节。
====

=== CSR 指令

所有 CSR 指令都原子地读-修改-写一个 CSR，其 CSR 说明符编码在指令的 12 位 _csr_ 字段中，位于位 31-20。立即数形式使用一个 5 位零扩展的立即数，编码在 _rs1_ 字段中。

include::images/wavedrom/csr-instr.edn[]

CSRRW（原子读/写 CSR）指令原子地交换 CSR 和整数寄存器中的值。CSRRW 读取 CSR 的旧值，将该值零扩展到 XLEN 位，然后将其写入整数寄存器 _rd_。_rs1_ 中的初始值被写入 CSR。如果 _rd_=`x0`，则该指令不得读取 CSR，也不得引起 CSR 读取可能发生的任何副作用。

CSRRS（原子读并设置 CSR 中的位）指令读取 CSR 的值，将该值零扩展到 XLEN 位，并将其写入整数寄存器 _rd_。整数寄存器 _rs1_ 中的初始值被视为一个位掩码，用于指定要在 CSR 中设置的位位置。如果 _rs1_ 中的任何位为高，则如果该 CSR 位是可写的，则会导致 CSR 中的相应位被设置。

CSRRC（原子读并清除 CSR 中的位）指令读取 CSR 的值，将该值零扩展到 XLEN 位，并将其写入整数寄存-器 _rd_。整数寄存器 _rs1_ 中的初始值被视为一个位掩码，用于指定要在 CSR 中清除的位位置。如果 _rs1_ 中的任何位为高，则如果该 CSR 位是可写的，则会导致 CSR 中的相应位被清除。

对于 CSRRS 和 CSRRC，如果 _rs1_=`x0`，则该指令根本不会写入 CSR，因此不会引起 CSR 写入可能发生的任何副作用，也不会在访问只读 CSR 时引发非法指令异常。无论 _rs1_ 和 _rd_ 字段如何，CSRRS 和 CSRRC 始终读取所寻址的 CSR 并引起任何读取副作用。
请注意，如果 _rs1_ 指定的寄存器不是 `x0`，并且该寄存器保存一个零值，则该指令不会对任何伴随的每个字段的副作用采取行动，但会对因写入整个 CSR 而引起的任何副作用采取行动。

_rs1_=`x0` 的 CSRRW 将尝试向目标 CSR 写入零。

CSRRWI、CSRRSI 和 CSRRCI 变体分别与 CSRRW、CSRRS 和 CSRRC 类似，只是它们使用通过零扩展编码在 _rs1_ 字段中的 5 位无符号立即数 (uimm[4:0]) 获得的 XLEN 位值来更新 CSR，而不是使用来自整数寄存器的值。对于 CSRRSI 和 CSRRCI，如果 uimm[4:0] 字段为零，则这些指令不会写入 CSR，并且不会引起 CSR 写入可能发生的任何副作用，也不会在访问只读 CSR 时引发非法指令异常。对于 CSRRWI，如果 _rd_=`x0`，则该指令不得读取 CSR，也不得引起 CSR 读取可能发生的任何副作用。无论 _rd_ 和 _rs1_ 字段如何，CSRRSI 和 CSRRCI 都将始终读取 CSR 并引起任何读取副作用。

[[csrsideeffects]]
.确定 CSR 指令是读取还是写入指定 CSR 的条件。
[%autowidth,float="center",align="center",cols="<,^,^,^,^",options="header",]
|===
5+^|*寄存器操作数*
|指令 |_rd_ 是 `x0` |_rs1_ 是 `x0` |读取 CSR |写入 CSR

|CSRRW |是 |- |否 |是

|CSRRW |否 |- |是 |是

|CSRRS/CSRRC |- |是 |是 |否

|CSRRS/CSRRC |- |否 |是 |是

5+^|*立即数操作数*

|指令 |_rd_ 是 `x0` |__uimm__latexmath:[$=$]0 |读取 CSR |写入
CSR

|CSRRWI |是 |- |否 |是

|CSRRWI |否 |- |是 |是

|CSRRSI/CSRRCI |- |是 |是 |否

|CSRRSI/CSRRCI |- |否 |是 |是
|===

<<csrsideeffects>> 总结了 CSR 指令在读取和/或写入 CSR 方面的行为。

除了因读取或写入 CSR 而发生的副作用外，CSR 中的各个字段在写入时也可能产生副作用。CSRRW[I] 指令对所写 CSR 中的所有此类字段都产生副作用。CSRRS[I] 和 CSRRC[I] 指令仅对 _rs1_ 或 _uimm_ 参数中至少有一个位设置对应于该字段的字段产生副作用。
[NOTE]
====
在撰写本文时，没有标准 CSR 在字段写入时具有副作用。因此，标准 CSR 访问是否具有任何副作用可以仅从操作码确定。

不建议定义在字段写入时具有副作用的 CSR。
====

对于因 CSR 具有特定值而发生的任何事件或后果，如果对 CSR 的写入使其具有该值，则所产生的事件或后果被称为写入的_间接影响_。RISC-V ISA 不认为 CSR 写入的间接影响是该写入的副作用。

[NOTE]
====
CSR 访问副作用的一个例子是，如果从特定 CSR 读取会导致灯泡打开，而向同一 CSR 写入奇数值会导致灯泡关闭。假设写入偶数值没有效果。在这种情况下，读取和写入都具有控制灯泡是否点亮的副作用，因为此条件并非仅由 CSR 值确定。（请注意，在向 CSR 写入奇数值以关闭灯泡后，然后读取以打开灯泡，再次写入相同的奇数值会导致灯泡再次关闭。因此，在最后一次写入时，关闭灯泡的不是 CSR 值的变化。）

另一方面，如果一个灯泡被设置为在特定 CSR 的值为奇数时点亮，那么打开和关闭灯泡不被视为写入 CSR 的副作用，而仅仅是此类写入的间接影响。

更具体地说，第二卷中定义的 RISC-V 特权架构规定，某些 CSR 值的组合会导致发生陷阱。当对 CSR 的显式写入创建触发陷阱的条件时，该陷阱不被视为写入的副作用，而仅仅是间接影响。

标准 CSR 在读取时没有任何副作用。标准 CSR 在写入时可能具有副作用。自定义扩展可能会添加在读取或写入时具有副作用的 CSR。
====
一些 CSR，例如指令退役计数器 `instret`，可能会作为指令执行的副作用而被修改。在这些情况下，如果 CSR 访问指令读取一个 CSR，它会读取指令执行之前的值。如果 CSR 访问指令写入这样一个 CSR，则会执行显式写入，而不是来自副作用的更新。特别是，一条指令写入 `instret` 的值将是下一条指令读取的值。

用于读取 CSR 的汇编器伪指令 CSRR _rd, csr_ 被编码为 CSRRS _rd, csr, x0_。用于写入 CSR 的汇编器伪指令 CSRW _csr, rs1_ 被编码为 CSRRW _x0, csr, rs1_，而 CSRWI _csr, uimm_ 被编码为 CSRRWI _x0, csr, uimm_。

还定义了进一步的汇编器伪指令，用于在不需要旧值时设置和清除 CSR 中的位：CSRS/CSRC _csr, rs1_；CSRSI/CSRCI _csr, uimm_。

==== CSR 访问排序

每个 RISC-V hart 通常按照程序顺序观察自己的 CSR 访问，包括其隐式 CSR 访问。特别是，除非另有规定，否则 CSR 访问是在执行程序顺序中任何其行为修改或被 CSR 状态修改的先前指令之后，以及在执行程序顺序中任何其行为修改或被 CSR 状态修改的后续指令之前执行的。此外，显式 CSR 读取返回指令执行之前的 CSR 状态，而显式 CSR 写入则抑制并覆盖同一指令对同一 CSR 的任何隐式写入或修改。

同样，来自显式 CSR 访问的任何副作用通常被观察为在程序顺序中同步发生。除非另有规定，否则任何此类副作用的全部后果都可由紧邻的下一条指令观察到，并且前面的指令不得乱序观察到任何后果。（请注意前面在 CSR 写入的副作用和间接影响之间所做的区分。）

对于 RVWMO 内存一致性模型 (<<memorymodel>>)，CSR 访问默认是弱序的，因此其他 hart 或设备可能会以不同于程序顺序的顺序观察 CSR 访问。此外，CSR 访问与显式内存访问之间没有排序，除非 CSR 访问修改了执行显式内存访问的指令的执行行为，或者除非 CSR 访问和显式内存访问由内存模型定义的语法依赖性或本手册第二卷中内存排序 PMA 部分定义的排序要求进行排序。为了在所有其他情况下强制排序，软件应在相关访问之间执行 FENCE 指令。就 FENCE 指令而言，CSR 读取访问被归类为设备输入 (I)，CSR 写入访问被归类为设备输出 (O)。

[NOTE]
====
非正式地，CSR 空间充当弱序内存映射 I/O 区域，如本手册第二卷中内存排序 PMA 部分所定义。因此，CSR 访问相对于所有其他访问的顺序受制于约束对此类区域的内存映射 I/O 访问顺序的相同机制。

施加这些 CSR 排序约束是为了支持相对于对设备或其他 hart 可见或受其影响的 CSR 访问来排序主内存和内存映射 I/O 访问。示例包括 `time`、`cycle` 和 `mcycle` CSR，以及反映挂起中断的 CSR，如 `mip` 和 `sip`。请注意，对此类 CSR 的隐式读取（例如，由于 `mip` 的变化而发生中断）也被排序为设备输入。

大多数 CSR（包括，例如，`fcsr`）对其他 hart 不可见；它们的访问可以在全局内存顺序中相对于 FENCE 指令自由重新排序，而不会违反本规范。
====

硬件平台可以定义对某些 CSR 的访问是强序的，如本手册第二卷中内存排序 PMA 部分所定义。对强序 CSR 的访问相对于对弱序 CSR 的访问和对内存映射 I/O 区域的访问具有更强的排序约束。

[NOTE]
====
全局内存顺序中 CSR 访问重新排序的规则可能应该移至 <<memorymodel>> 中关于 RVWMO 内存一致性模型的部分。
====
