[[zihintpause]]
== “Zihintpause”暂停提示扩展，版本 2.0
PAUSE 指令是一个 HINT，表示当前 hart 的指令退役速率应暂时降低或暂停。其效果的持续时间必须是有限的，并且可以为零。
(((PAUSE, HINT)))
(((HINT, PAUSE)))

[NOTE]
====
软件可以使用 PAUSE 指令在执行自旋等待代码序列时降低能耗。当执行 PAUSE 时，多线程核心可能会暂时将执行资源让给其他 hart。建议在自旋等待循环的代码序列中通常包含一条 PAUSE 指令。
(((PAUSE, 能耗)))

未来的扩展可能会添加类似于 x86 MONITOR/MWAIT 指令的原语，这些原语提供了更有效的机制来等待对特定内存位置的写入。然而，这些指令不会取代 PAUSE。当轮询非内存事件、轮询多个事件或软件不确切知道它正在轮询哪些事件时，PAUSE 更为合适。

PAUSE 指令效果的持续时间在实现内部和实现之间可能会有很大差异。在典型的实现中，此持续时间应远小于执行上下文切换的时间，可能大致相当于片上缓存未命中延迟或无缓存访问主内存的时间。
(((PAUSE, 持续时间)))

一系列 PAUSE 指令可用于创建与 PAUSE 指令数量大致成比例的累积延迟。然而，在可移植代码的自旋等待循环中，在重新评估循环条件之前只应使用一条 PAUSE 指令，否则在某些实现上，hart 可能会停顿超过最佳时间，从而降低系统性能。
====

PAUSE 被编码为 FENCE 指令，其中 _pred_=`W`，_succ_=`0`，_fm_=`0`，_rd_=`x0`，_rs1_=`x0`。

//include::images/wavedrom/zihintpause-hint.edn[]
//[zihintpause-hint]
//.Zihintpause 栅栏指令

[NOTE]
====
PAUSE 被编码为 FENCE 操作码中的一个提示，因为某些实现预计会故意暂停 PAUSE 指令，直到未完成的内存事务完成。然而，由于后继集为空，PAUSE 并未_强制_任何特定的内存排序——因此，它确实是一个 HINT。
(((PAUSE, 编码)))

与其他 FENCE 指令一样，PAUSE 不能在 LR/SC 序列中使用，否则会使前向进度保证无效。
(((PAUSE, LR/RC 序列)))

选择 W 的前驱集是任意的，因为后继集为空。其他类似于 PAUSE 的 HINT 可能会用其他前驱集进行编码。
====
