[[Zpm]]
== 指针屏蔽扩展，版本 1.0.0

=== 引言

RISC-V 指针屏蔽 (PM) 是一项功能，启用后，CPU 会忽略有效地址的高位（这些术语将在背景部分更精确地定义）。这允许应用程序以任何方式使用这些位。此处描述的扩展版本专门针对**标签检查**：当访问地址时，可以将存储在屏蔽位中的标签与基于范围的标签进行比较。这用于动态安全检查器，例如 HWASAN cite:[HWASAN]。此类工具可以应用于所有特权模式（U、S 和 M）。

HWASAN 利用地址高位中的标签来识别内存错误，例如释放后使用或缓冲区溢出错误。通过在地址的高位中存储一个*指针标签*并将其与存储在旁表中的*内存标签*进行检查，它可以识别指针是否指向有效位置。在没有硬件支持的情况下执行此操作会引入显着的开销，因为每次常规内存操作都需要手动删除指针标签。指针屏蔽支持减少了这些开销。

指针屏蔽仅增加了在常规内存访问期间忽略指针标签的能力。标签检查本身可以在软件或硬件中实现。如果在软件中实现，指针屏蔽仍然可以提供性能优势，因为未经检查的访问不需要在每次内存访问之前转换地址。由于带外执行标签检查并加强从这些检查中获得的安全保证，预计硬件实现将提供更大的优势。我们预计未来的扩展可能会在指针屏蔽的基础上构建，以在硬件中支持此功能。

值得一提的是，虽然 HWASAN 是当前指针屏蔽扩展的主要用例，但可以利用指针屏蔽实现许多其他硬件/软件功能。其中一些用例包括沙箱、对象类型检查和运行时系统中的垃圾收集位。请注意，当前版本的规范并未明确解决这些用例，但未来的扩展可能会在此基础上进行构建。

虽然我们将指针屏蔽的高级概念描述为单个扩展，但实际上，它是一个扩展系列，实现或配置文件可以选择单独包含或排除（请参阅 <<_pointer_masking_extensions>>）。

=== 背景

==== 定义

我们现在定义基本术语。请注意，这些术语依赖于“忽略”转换的定义，该定义在 <<sec-ignore-transform>> 中定义。

* **有效地址（在 RISC-V 基本 ISA 中定义）：** 发送到内存子系统的加载/存储有效地址（例如，在执行加载/存储指令期间生成的）。这不包括与隐式访问相对应的地址，例如页表遍历。

* **屏蔽位：** 地址的高 PMLEN 位，其中 PMLEN 是一个可配置的参数。在本文档中，我们将始终使用 PMLEN 来指代此参数。

* **转换后的地址：** 应用忽略转换后的有效地址。

* **地址转换模式：** RISC-V 特权规范中定义的当前活动地址转换方案的模式。例如，这可以指 Bare、Sv39、Sv48 和 Sv57。根据特权规范，非 Bare 转换模式被称为虚拟内存方案。就本规范而言，M 模式转换被视为等同于 Bare。

* **地址有效性：** RISC-V 特权规范根据当前使用的地址转换模式（例如，Sv57、Sv48、Sv39 等）定义地址的有效性。对于虚拟地址要有效，地址未使用部分中的所有位必须与已使用部分的最高有效位 (MSB) 相同。例如，当使用基于页的 48 位虚拟内存 (Sv48) 时，加载/存储有效地址（64 位）的位 63-48 必须全部设置为位 47，否则将发生页错误异常。对于物理地址，有效性意味着位 XLEN-1 到 PABITS 为零，其中 PABITS 是处理器支持的物理地址位数。

* **NVBITS：** 虚拟地址中对寻址内存没有影响且仅用于有效性检查的高位。这些位取决于当前活动的地址转换模式。例如，在 Sv48 中，这些是位 63-48。

* **VBITS：** 虚拟地址中影响寻址哪个内存的位。这些是用于索引页表的地址位。

[[sec-ignore-transform]]
==== “忽略”转换

忽略转换根据其应用于虚拟地址还是物理地址而有所不同。对于虚拟地址，它用 PMLEN+1 位的符号扩展替换高 PMLEN 位。

[source]
.“忽略”虚拟地址的转换，用 Verilog 代码表示。
----
transformed_effective_address =
  {{PMLEN{effective_address[XLEN-PMLEN-1]}}, effective_address[XLEN-PMLEN-1:0]}
----

[NOTE]
====
如果对于给定架构上支持的最大地址转换模式，PMLEN 小于或等于 NVBITS，则这等效于忽略 NVBITS 的一个子集。这使得廉价的实现可以通过修改 CPU 中的有效性检查而不是执行符号扩展来实现。
====

当应用于物理地址时，包括客户机物理地址（即，除活动 satp 寄存器的 MODE 字段 != Bare 之外的所有情况），忽略转换用 0 替换高 PMLEN 位。这包括在 M 模式下运行和在其他特权模式下使用 Bare 地址转换模式运行的情况。

[source]
.“忽略”物理地址的转换，用 Verilog 代码表示。
----
transformed_effective_address =
  {{PMLEN{0}}, effective_address[XLEN-PMLEN-1:0]}
----

[NOTE]
====
此定义与 RISC-V 已经以不同方式处理物理和虚拟地址的方式一致。虽然虚拟地址的未使用高位是已使用位的符号扩展（请参阅 <<_definitions>> 中“地址有效性”的定义），但物理地址中的等效位是零扩展的。由于它们与物理内存保护 (PMP) 等其他机制的交互，这是必要的。
====

启用指针屏蔽后，忽略转换将应用于每个显式内存访问（例如，加载/存储、原子操作和浮点加载/存储）。该转换*不*适用于隐式访问，例如页表遍历或指令提取。指针屏蔽适用的访问集在 <<_memory_accesses_subject_to_pointer_masking>> 中描述。

[WARNING]
====
指针屏蔽不会改变底层的地址生成逻辑或权限检查。在固定的地址转换模式下，它在语义上等效于用一个指令序列替换一个指令子集（例如，加载和存储），该指令序列将忽略操作应用于此指令的目标地址，然后将该指令应用于转换后的地址。文本中对地址转换和其他实现细节的引用主要是为了解释设计决策和常见的实现模式。
====

请注意，指针屏蔽纯粹是对地址的算术运算，对其应用的地址的含义不做任何假设。具有相同 PMLEN 值的指针屏蔽对于相同类型的地址（虚拟或物理）始终具有相同的效果。这确保了依赖指针屏蔽的代码一旦启用指针屏蔽就不需要了解其运行的环境，只要 PMLEN 的值是已知的，以及地址是虚拟的还是物理的。例如，相同的应用程序或库代码可以在用户模式、监控模式或 M 模式（具有不同的地址转换模式）下运行而无需修改。

[NOTE]
====
此类代码的一个常见场景是地址由 mmap 系统调用生成。这从应用程序代码中抽象出底层地址转换模式的细节。因此，软件需要了解 PMLEN 的值，以确保支持其最低要求的标签位数。<<_determining_the_value_of_pmlen>> 介绍了如何派生此值。
====

==== 示例

表 1 显示了在 Sv57 (PMLEN=7) 下为 RV64 启用 PM 时对虚拟地址进行指针屏蔽转换的示例。

[%header, cols="25%,75%", options="header"]
.RV64 在 Sv57 下的 PM 地址转换示例
|===
|基于页的配置文件|RV64 上的 Sv57
|有效地址 |0xABFFFFFF12345678 +
NVBITS[1010101]  VBITS[11111111111111111111111110001...000]
|PMLEN|7
|掩码|0x01FFFFFFFFFFFFFF +
NVBITS[0000000]  VBITS[11111111111111111111111111111...111]
|从顶部开始的 PMLEN+1 位（即位 XLEN-PMLEN-1）|1
|转换后的有效地址 |0xFFFFFFFF12345678 +
NVBITS[1111111]  VBITS[11111111111111111111111110001...000]

|===

如果地址是物理地址而不是具有 Sv57 的虚拟地址，则 PMLEN=7 的转换后地址将为 0x1FFFFFF12345678。

==== 确定 PMLEN 的值

从实现的角度来看，忽略位与处理器支持的最大虚拟和物理地址空间（例如，Bare、Sv48、Sv57）密切相关。特别是，如果应用上述转换仅涵盖**任何**支持的地址转换模式都不使用的位，则应用该转换是廉价的（因为它等效于关闭有效性检查）。屏蔽超出这些位的 NVBITS 更昂贵，因为它需要忽略 TLB 标签中的它们，如果屏蔽的位扩展到地址的 VBITS 部分，则更昂贵（因为它需要执行实际的符号扩展）。同样，在 Bare 或 M 模式下运行时，实现通常不使用物理地址范围顶部的特定数量的位并将它们固定为零。对这些位应用忽略转换也很廉价，因为它将导致一个有效物理地址，其所有高位都固定为 0。

当前标准仅支持 PMLEN=XLEN-48（即 RV64 中的 PMLEN=16）和 PMLEN=XLEN-57（即 RV64 中的 PMLEN=7）。已保留一个设置，以便在未来的标准中可能支持 PMLEN 的其他值。在此类未来的标准中，可以为每个特权模式（U/VU、S/HS 和 M）定义不同的支持的 PMLEN 值。

[NOTE]
====
未来版本的指针屏蔽扩展可能会引入自由配置 PMLEN 值的能力。当前扩展未定义如果 PMLEN 与上述值不同时的行为。特别是，不能保证未来的指针屏蔽扩展会以相同的方式为这些 PMLEN 值定义忽略操作。
====

==== 指针屏蔽和特权模式

指针屏蔽是针对不同特权模式单独控制的。支持的特权模式的子集由支持的指针屏蔽扩展集确定。不同的特权模式可以同时激活不同的指针屏蔽设置，硬件将自动应用当前活动特权模式的指针屏蔽设置。特权模式的指针屏蔽设置由下一级更高特权模式的配置寄存器中的位配置。

请注意，应用的指针屏蔽设置仅取决于活动特权模式，而不取决于被屏蔽的地址。某些操作系统（例如 Linux）可能会使用地址中的某些位来消除不同类型地址（例如，内核和用户模式地址）之间的歧义。指针屏蔽_不_考虑这些语义，纯粹是对其给定的地址进行算术运算。

[NOTE]
====
Linux 将内核地址放在地址空间的上半部分，将用户地址放在地址空间的下半部分。因此，MSB 通常用于识别特定地址的类型。启用指针屏蔽后，此角色现在由位 XLEN-PMLEN-1 扮演，检查指针是内核地址还是用户地址的代码需要检查此位。为了向后兼容，可能希望 MSB 仍然指示地址是用户地址还是内核地址。操作系统的 ABI 可能会强制要求这一点，但这不会影响指针屏蔽机制本身。例如，Linux ABI 可能会选择强制要求 MSB 不用于标记并复制位 XLEN-PMLEN-1 位（请注意，为了使此类机制安全，内核需要在使用任何用户模式提供的地址之前检查其 MSB 并确保此不变量成立；或者，它可以应用清单 1 或 2 中的转换来确保 MSB 设置为正确的值）。
====

==== 受指针屏蔽影响的内存访问

指针屏蔽适用于所有显式内存访问。目前，在基本和特权 ISA 中，这些是：

* **基本指令集**：LB、LH、LW、LBU、LHU、LWU、LD、SB、SH、SW、SD。
* **原子操作**：RV32A 和 RV64A 中的所有指令。
* **浮点**：FLW、FLD、FLQ、FSW、FSD、FSQ。
* **压缩**：映射到上述任何指令的所有指令，以及 C.LWSP、C.LDSP、C.LQSP、C.FLWSP、C.FLDSP、C.SWSP、C.SDSP、C.SQSP、C.FSWSP、C.FSDSP。
* **虚拟机管理程序扩展**：HLV.\*、HSV.*（在某些情况下；请参阅 <<_ssnpm>>）。
* **缓存管理操作**：Zicbom、Zicbop 和 Zicboz 中的所有指令。
* **向量扩展**：已批准的 RVV 1.0 规范中的所有向量加载和存储指令。
* **Zicfiss 扩展**：SSPUSH、C.SSPUSH、SSPOPCHK、C.SSPOPCHK、SSAMOSWAP.W/D。
* **杂项**：FENCE、FENCE.I（如果当前未使用的地址字段在将来启用）。

[NOTE]
====
随着新扩展引入执行显式内存访问的新指令，此列表将随着时间的推移而增长。
====

对于其他扩展，指针屏蔽默认适用于所有显式内存访问。未来的扩展可能会添加特定的语言来指示特定访问是否包含在指针屏蔽中。

[NOTE]
====
值得注意的是，指针屏蔽不适用于 `SFENCE.\*`、`HFENCE.*`、`SINVAL.\*` 或 `HINVAL.*`。调用此类操作时，软件有责任提供正确的地址。
====

MPRV 和 SPVP 也会影响指针屏蔽，导致应用有效特权模式的指针屏蔽设置。当在执行显式内存访问的有效特权模式下 MXR 生效时，指针屏蔽不适用。

[NOTE]
====
请注意，这包括未启用基于页的虚拟内存的情况；即，虽然在未启用基于页的虚拟内存时 MXR 对权限检查没有影响，但它仍用于确定是否应应用指针屏蔽。
====

[NOTE]
====
缓存管理操作 (CMO) 必须遵守并考虑指针屏蔽。否则，可能会出现一些严重的安全问题，包括：

* CBO.ZERO 可以作为 STORE 操作。如果不遵守指针屏蔽，则可以绕过掩码强制写入内存。
* 如果 CMO 不遵守指针屏蔽，则可以在旁道攻击中将其武器化。例如，U 模式将能够刷新它不应被允许的物理地址（不带屏蔽）。
====

指针屏蔽仅适用于 CPU 上的指令生成的访问（包括 FPU 等 CPU 扩展）。例如，它不适用于页表遍历、IOMMU 或设备生成的访问。

[NOTE]
====
指针屏蔽不适用于 DMA 控制器和其他设备。因此，软件有责任手动取消这些地址的标记。
====

支持未对齐的访问，但受与没有指针屏蔽时相同的限制。其行为与将指针屏蔽转换应用于每个组成对齐内存访问相同。换句话说，访问的字节应与在没有指针屏蔽的情况下将指针屏蔽转换单独应用于访问的每个字节时访问的字节相同。这确保了硬件实现和 M 模式下未对齐访问的仿真的行为相同，并且无论是否启用指针屏蔽，M 模式实现都相同（例如，此类实现可以利用 MPRV 来应用正确的特权模式的指针屏蔽设置）。

当软件读/写 CSR 时，不应用任何指针屏蔽操作，包括那些旨在保存地址的 CSR。如果软件将标记的地址存储到此类 CSR 中，则基于这些地址的数据加载或数据存储操作仅在它们是显式的 (<<_memory_accesses_subject_to_pointer_masking>>) 并且为执行访问的特权模式启用了指针屏蔽时才受指针屏蔽的影响。CSR 的已实现 WARL 宽度不受指针屏蔽的影响（例如，如果 CSR 支持 52 位有效地址并且支持 PMLEN=16 的指针屏蔽，则所需的 WARL 位数保持为 52，而与是否启用或禁用指针屏蔽无关）。

与软件写入相反，指针屏蔽**会应用于**硬件对 CSR 的写入（例如，当硬件在发生异常时将转换后的地址写入 `stval` 时）。当在调试中匹配地址触发器时，指针屏蔽也应用于内存访问地址。

例如，软件可以自由地将标记或未标记的地址写入 `stvec`，但在陷阱传递时（例如，由于异常或中断），指针屏蔽**不会应用于**陷阱处理程序的地址。但是，当传递异常时，硬件**会应用于**写入 `stval` 的任何地址。

[NOTE]
====
此选择的理由是，在某些硬件实现中，传递额外的位可能会增加开销。此外，指针屏蔽是按特权模式配置的，因此监控模式下的所有陷阱处理程序都需要小心地以与用户模式相同的方式配置指针屏蔽或手动取消屏蔽（这很昂贵）。
====

==== 指针屏蔽扩展

指针屏蔽是指许多独立的扩展，所有这些扩展都是特权的。使用此方法来捕获指针屏蔽功能的可选性。配置文件和实现可以选择支持这些扩展的任意子集，并且必须为其对应的 PMLEN 值定义有效范围。

**扩展**：

* **Ssnpm**：一个监控级扩展，为下一个较低的特权模式（U 模式）以及在存在 H 扩展时为 VS 和 VU 模式提供指针屏蔽。
* **Smnpm**：一个机器级扩展，为下一个较低的特权模式（如果实现了 S 模式，则为 S/HS，否则为 U 模式）提供指针屏蔽。
* **Smmpm**：一个机器级扩展，为 M 模式提供指针屏蔽。

有关如何配置这些扩展的详细信息，请参阅 <<_isa_extensions>>。

此外，指针屏蔽标准定义了两个描述执行环境但与硬件实现无关的扩展。这些扩展旨在用于配置文件规范，其中用户配置文件或监控配置文件只能引用用户级或监控级指针屏蔽功能，而不能引用存在于更高特权级别（即在执行环境中）的关联 CSR 控件。

* **Sspm**：一个扩展，指示在监控模式下有可用的指针屏蔽支持，并在监控执行环境中提供了一些用于控制指针屏蔽的设施。
* **Supm**：一个扩展，指示在用户模式下有可用的指针屏蔽支持，并在应用程序执行环境中提供了一些用于控制指针屏蔽的设施。

这些设施的确切性质留给各自的执行环境。

指针屏蔽仅适用于 RV64。在 RV32 中，尝试启用指针屏蔽将导致非法的 WARL 写入，并且不会更新指针屏蔽配置位（有关详细信息，请参阅 <<_isa_extensions>>）。在 RV64 或更大的系统上，当为相应的特权模式将 UXL/SXL/MXL 设置为 1 时，情况也是如此。请注意，在 RV32 中，指针屏蔽引入的 CSR 位仍然存在，以便在 UXL/SXL/MXL 设置为 1 的 RV32 和更大的系统之间兼容。将 UXL/SXL/MXL 设置为 1 将清除相应的指针屏蔽配置位。

[NOTE]
====
请注意，将 UXL/SXL/MXL 设置为 1 然后再设置回 0 不会保留 PMM 位的先前值。这包括从 RV64 虚拟机管理程序进入 RV32 虚拟机然后返回的情况。
====

=== ISA 扩展

本节描述指针屏蔽扩展 `Smmpm`、`Smnpm` 和 `Ssnpm`。所有这些扩展都是特权 ISA 扩展，不添加任何新的 CSR。有关 `Sspm` 和 `Supm` 的定义，请参阅 <<_pointer_masking_extensions>>。

[NOTE]
====
未来的扩展可能会引入额外的 CSR，以允许不同的特权模式修改自己的指针屏蔽设置。这对于当前未作为此扩展一部分解决的托管运行时系统中的未来用例可能是必需的。
====

每个扩展都引入了一个 2 位 WARL 字段 (`PMM`)，该字段可以采用以下值来为特定特权模式设置指针屏蔽设置。

[%header, cols="25%,75%", options="header"]
.`PMM` WARL 字段的可能值。
|===
|值|描述
|00|指针屏蔽已禁用 (PMLEN=0)
|01|保留
|10|指针屏蔽已启用，PMLEN=XLEN-57（RV64 上为 PMLEN=7）
|11|指针屏蔽已启用，PMLEN=XLEN-48（RV64 上为 PMLEN=16）
|===

在 RV32 系统上，所有这些字段都是只读 0。

==== Ssnpm

`Ssnpm` 在 `senvcfg` 的位 33:32 中添加了一个新的 2 位 WARL 字段 (`PMM`)。根据表 2 中的值，设置 `PMM` 可以为下一个较低的特权模式（U/VU 模式）启用或禁用指针屏蔽。

在存在 H 扩展的系统中，`Ssnpm` 还在 `henvcfg` 的位 33:32 中添加了一个新的 2 位 WARL 字段 (`PMM`)。根据表 2 中的值，设置 `PMM` 可以为 VS 模式启用或禁用指针屏蔽。此外，在 `hstatus` 的位 49:48 中添加了一个 2 位 WARL 字段 (`HUPMM`)。根据表 2 中的值，当在 U 模式下执行 `HLV.\*` 和 `HSV.*` 指令时，设置 `hstatus.HUPMM` 可以为它们的显式内存访问启用或禁用指针屏蔽，就好像在 VU 模式下执行一样。在 HS 和 M 模式下，当这些指令的显式内存访问就好像在 VU 模式下执行时，`senvcfg.PMM` 可以为它们启用或禁用指针屏蔽。当 `HLV.\*` 和 `HSV.*` 的显式内存访问就好像在 VS 模式下执行时，设置 `henvcfg.PMM` 可以为它们启用或禁用指针屏蔽。

[NOTE]
====
在 U 模式下调用 `HLV.\*` 或 `HSV.*` 指令之前，虚拟机管理程序应将客户机写入 `senvcfg.PMM` 的值复制到 `hstatus.HUPMM` 字段。
====

`HLVX.*` 指令执行的内存访问不受指针屏蔽的影响。

[NOTE]
====
`HLVX.*` 指令旨在模拟从客户机内存中获取指令的隐式访问，其执行的内存访问不受指针屏蔽的影响，以方便此模拟。出于同样的原因，当设置 MXR 时，指针屏蔽不适用。
====

==== Smnpm

`Smnpm` 在 `menvcfg` 的位 33:32 中添加了一个新的 2 位 WARL 字段 (`PMM`)。根据表 2 中的值，设置 `PMM` 可以为下一个较低的特权模式（如果实现了 S 模式，则为 S-/HS-模式，否则为 U 模式）启用或禁用指针屏蔽。

[NOTE]
====
地址的类型决定了应用哪种类型的指针屏蔽。例如，当在 VS/VU 模式下使用 `vsatp.MODE` = Bare 运行虚拟化时，将应用物理地址指针屏蔽（零扩展）。
====

==== Smmpm

`Smmpm` 在 `mseccfg` 的位 33:32 中添加了一个新的 2 位 WARL 字段 (`PMM`)。`Smmpm` 的存在意味着 `mseccfg` 寄存器的存在，即使它本来不存在。根据表 2 中的值，设置 `PMM` 可以为 M 模式启用或禁用指针屏蔽。

==== 与 SFENCE.VMA 的交互

由于指针屏蔽仅适用于有效地址，并且不影响任何内存管理数据结构，因此在启用/禁用指针屏蔽后不需要 SFENCE.VMA。

==== 与两阶段地址转换的交互

客户机物理地址 (GPA) 比相应的虚拟地址转换模式宽 2 位，从而导致用于将客户机物理地址转换为监控物理地址的附加地址转换方案 Sv32x4、Sv39x4、Sv48x4 和 Sv57x4。当在 VS/VU 模式下使用 `vsatp.MODE` = Bare 运行虚拟化时，这意味着这两个位可能会受到指针屏蔽的影响，具体取决于 `hgatp.MODE` 和 `senvcfg.PMM`/`henvcfg.PMM`（对于 VU/VS 模式）。如果 `vsatp.MODE` != BARE，则此问题*不*适用。

[NOTE]
====
实现可以在 TLB 访问路径上屏蔽这两个位，但这可能会产生显着的时序影响。或者，实现可以选择通过为每个页面设置多达 4 个重复条目来“浪费”TLB 容量。在这种情况下，指针屏蔽操作可以在 TLB 重新填充路径上应用，在该路径上它不太可能影响时序。为了支持此方法，当 PMLEN 以可能影响这些重复条目的方式更改时，需要刷新一些 TLB 条目。
====

为了支持 (XLEN-PMLEN) 可能小于 `hgatp.MODE` 支持的 GPA 宽度的实现，如果 `henvcfg.PMM` 从或更改为 (XLEN-PMLEN) 小于该客户机的 `hgatp` 转换模式支持的 GPA 宽度的值，则虚拟机管理程序应执行 `HFENCE.GVMA`，其中 _rs1_=`x0`。具体来说，这些情况是：

* `PMLEN=7` 和 `hgatp.MODE=sv57x4`
* `PMLEN=16` 和 `hgatp.MODE=sv57x4`
* `PMLEN=16` 和 `hgatp.MODE=sv48x4`

[NOTE]
====
`Smmpm` 实现需要满足 max(支持的最大虚拟地址大小，支持的最大监控物理地址大小) <= (XLEN - PMLEN) 位，以避免 TLB 访问路径上的任何屏蔽逻辑。
====

地址特定的 `HFENCE.GVMA` 的实现应要么忽略地址参数，要么在比较地址匹配时忽略条目的顶部屏蔽 GPA 位。

==== 屏蔽位数

如 <<_determining_the_value_of_pmlen>> 中所述，支持的 PMLEN 值可能取决于有效的特权模式。当前标准仅定义 PMLEN=XLEN-48 和 PMLEN=XLEN-57，但此假设可能会在未来的扩展和配置文件中放宽。在不支持的场景中尝试启用指针屏蔽表示对相应的指针屏蔽启用位的非法写入，并遵循 WARL 语义。未来的配置文件可能会选择将特权模式和支持的 PMLEN 值的某些组合定义为强制性的。

[NOTE]
====
考虑过但放弃的一个选项是允许实现根据活动的寻址模式设置 PMLEN。例如，对于 Sv48，PMLEN 可以设置为 16，对于 Sv39，可以设置为 25。然而，具有单个 PMLEN 值（例如，对于 Sv39 和 Sv48 都将 PMLEN 设置为 16 而不是 25）有助于在支持 Sv39 和 Sv48 但不支持 Sv57 的设计中实现 TLB。16 位足以满足当前的指针屏蔽用例，但允许 TLB 实现与相同数量的虚拟标签位匹配，而与它是使用 Sv39 还是 Sv48 运行无关。但是，如果支持 Sv57，则标签匹配可能需要以当前地址转换模式为条件。
====
