[[bf16]]
== “BF16”扩展：BFloat16 精度浮点，版本 1.0

[[BF16_introduction]]
=== 引言

当 FP16（官方称为 binary16）首次由 IEEE-754 标准引入时，它只是一种交换格式。它旨在作为一种节省空间/带宽的有效编码，用于传输信息。这与 Zfhmin 扩展一致。

然而，有一些应用（特别是图形学）发现，较小的精度和动态范围足以满足其空间需求。因此，FP16 开始作为一种算术格式得到广泛采用。这与 Zfh 扩展一致。

虽然 '754 的初衷并非让 FP16 成为一种算术格式，但标准支持它。尽管 '754 委员会认识到 FP16 日益普及，但委员会决定在 2019 年的版本中暂不将其作为基本格式。这意味着，一个符合 '754 标准的二进制浮点实现，需要支持至少一种基本格式，不能只支持 FP16——它需要支持 binary32、binary64 和 binary128 中的至少一种。

从事机器学习的专家注意到，FP16 是一种更紧凑的存储操作数的方式，并且通常能为他们提供足够的精度。然而，他们也发现，当累积到更高精度时，中间值要好得多。最终的计算结果通常会转换回更紧凑的 FP16 编码。这种方法在机器学习（ML）推理中变得非常普遍，其中权重和激活以 FP16 编码存储。还有一个额外的好处是，可以为 FP16 较少的有效位数创建更小的乘法块。此时，加宽乘法累加指令变得更加普遍。此外，更复杂的点积指令也开始出现，包括那些将两个 FP16 数打包到一个 32 位寄存器中，将它们与另一个寄存器中的另一对 FP16 数相乘，将这两个乘积加到一个第三个寄存器中的 FP32 累加值，并返回一个 FP32 结果的指令。

在谷歌从事机器学习并继续使用 FP32 值的专家注意到，即使在训练中，其尾数的最低有效 16 位也并非总是需要获得良好结果。他们提出了一种 FP32 的截断版本，即 FP32 编码的最高有效 16 位。该格式被命名为 BFloat16（或 BF16）。BF16 中的 B 代表 Brain，因为它最初是由 Google Brain 团队引入的。他们不仅发现 BF16 中的有效位数往往足以满足他们的工作需求（尽管比 FP16 少），而且他们重用现有数据也非常容易；FP32 数可以很容易地以最少的工作量四舍五入到 BF16。此外，BF16 有效位数的减少使得可以构建更小的乘法块。与 FP16 类似，BF16 乘法累加加宽和点积指令也开始激增。

// include::riscv-bfloat16-audience.adoc[]
[[BF16_audience]]
=== 目标受众
浮点运算是一个专门的学科，需要许多不同背景的人合作才能正确有效地实现。
在可能的情况下，我们编写本规范时力求让所有人都能理解，尽管我们认识到，对于非领域专家来说，动机以及对算法或其他规范和标准的引用可能不熟悉。

本规范预计将被具有不同背景的各种人士阅读和采纳。
我们试图在此处捕捉这些背景，并简要说明我们期望他们了解什么，以及这与规范的关系。
我们希望这有助于人们理解规范的哪些方面与他们特别相关，以及他们可以（安全地！）忽略或交给同事的方面。

软件开发人员::
我们期望这些人使用本规范中的指令编写代码。
他们应该理解我们包含的指令的动机，并熟悉我们引用的大多数算法和外部标准。

计算机架构师::
我们期望架构师具有一些基本的浮点背景。
此外，我们期望架构师能够检查我们的指令是否存在实现问题，了解指令将在上下文中如何使用，并就如何最好地适应功能提出建议。

数字设计工程师和微架构师::
这些人将在核心内部实现规范。假定具备浮点专业知识，因为规范中并未指出所有极端情况。

验证工程师::
负责确保在硬件中正确实现扩展。
这些人应具备一些浮点专业知识，以便他们能够识别和生成浮点架构和实现中常见的有趣的极端情况——包括异常。


这些人绝不是唯一关注本规范的人，但他们在我们撰写本规范时是我们考虑最多的人。

[[BF16_format]]
=== 数字格式

==== BF16 操作数格式

BF16 位::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'frac'},
{bits: 8, name: 'expo'},
{bits: 1, name: 'S'},
]}
....

IEEE 合规性：虽然 BF16（也称为 BFloat16）不是 IEEE-754 _标准_ 格式，但它是 IEEE-754 定义的有效浮点格式。
指定格式的三个参数是：基数 (b)、有效数中的位数 (p) 和最大指数 (emax)。
对于 BF16，这些值为：

[%autowidth]
.BF16 参数
[cols = "2,1"]
|===
| 参数 | 值
|基数 (b)|2
|有效数 (p)|8
|emax|127
|===


[%autowidth]
.强制性浮点格式表
[cols = "1,1,1,1,1,1,1,1"]
|===
|格式|符号位|指数位|小数位|填充 0|编码位|指数最大值/偏移量|指数最小值

|FP16    |1| 5|10| 0|16|  15| -14
|BF16|1| 8| 7| 0|16| 127|-126
|TF32    |1| 8|10|13|32| 127|-126
|FP32    |1| 8|23| 0|32| 127|-126
|FP64    |1|11|52| 0|64|1023|-1022
|FP128   |1|15|112|0|128|16,383|-16,382
|===

==== BF16 行为

对于这些 BF16 扩展，BF16 操作数上的指令行为与 RISC-V ISA 中的其他浮点指令相同。为便于参考，此处重复了部分行为。

===== 次正规数：
浮点值太小而无法表示为正规数，但仍可通过格式的最小指数值、“0”整数位和尾随小数位中至少一个“1”位来表示，称为次正规数。基本上，这个想法是通过牺牲精度来支持 _渐进下溢_。

本规范中定义的所有 BF16 指令（即 Zfbfmin、Zvfbfmin 和 Zvfbfwma）都完全支持次正规数。也就是说，指令能够接受次正规值作为输入，并且可以产生次正规结果。


[NOTE]
====
未来的浮点扩展，包括那些操作 BF16 值的扩展，可能会选择不支持次正规数。
关于支持次正规 BF16 值的评论仅限于本规范中定义的那些指令。
====

=====  无穷大：
无穷大用于表示太大而无法用目标格式表示的值。
这些通常是溢出的结果（取决于舍入模式），但也可以作为输入提供。无穷大有与之关联的符号：有正无穷大和负无穷大。

无穷大对于防止对无意义的结果进行操作很重要。

===== NaNs

NaN 代表非数字。

NaN 有两种类型：信令 (sNaN) 和静默 (qNaN)。任何计算指令都不会产生 sNaN；这些仅作为输入数据提供。对 sNaN 进行操作将导致无效操作异常。对静默 NaN 进行操作通常不会导致异常。

当操作结果无法表示为数字或无穷大时，会提供 QNaN。例如，对 -1 执行平方根将导致 qNaN，因为没有实数可以表示结果。NaN 也可以用作输入。

NaN 包括一个符号位，但该位没有意义。

NaN 对于防止对无意义的结果进行操作很重要。

除非另有明确说明，否则当浮点运算的结果为 qNaN 时，它就是 RISC-V 规范 NaN。对于 BF16，RISC-V 规范 NaN 对应于 _0x7fc0_ 的模式，这是 RISC-V 单精度规范 NaN 的最高有效 16 位。

===== 标量 NaN 装箱

RISC-V 将 NaN 装箱应用于标量结果，并在浮点运算（甚至是向量-标量运算）从标量浮点寄存器中消耗值时检查 NaN 装箱。
如果该值已正确进行 NaN 装箱，则其最低有效位将用作操作数，否则将其视为规范 QNaN。

NaN 装箱只不过是将较小的编码放在寄存器的最低有效位中，并将所有更重要的位设置为“1”。这与较大精度中 qNaN 的编码（尽管不是规范 NaN）相匹配。

NaN 装箱永远不会影响操作数本身的值，它只改变寄存器中比操作数最高有效位更重要的位。


=====  舍入模式：

与其他浮点指令一样，
BF16 指令支持所有 5 种 RISC-V 浮点舍入模式。
这些模式可以在标量指令的 `rm` 字段中指定，也可以在 `frm` CSR 中指定。

[%autowidth]
.RISC-V 浮点舍入模式
[cols = "1,1,1"]
|===
|舍入模式 | 助记符 | 含义
|000 | RNE | 四舍五入到最近，偶数优先
|001 | RTZ | 向零舍入
|010 | RDN | 向下舍入（朝向 −∞）
|011 | RUP | 向上舍入（朝向 +∞）
|100 | RMM | 四舍五入到最近，最大幅度优先
|===

与其他标量浮点指令一样，舍入模式字段
`rm` 也可以采用
`DYN` 编码，表示该指令使用 `frm` CSR 中指定的舍入模式。

[%autowidth]
.标量指令 `rm` 字段的附加编码
[cols = "1,1,1"]
|===
|舍入模式 | 助记符 | 含义
|111 | DYN | 选择动态舍入模式
|===

在实践中，通常使用默认的 IEEE 舍入模式（四舍五入到最近，偶数优先）进行算术运算。

===== 处理异常
RISC-V 支持 IEEE 定义的默认异常处理。BF16 也不例外。

IEEE 定义的默认异常处理是在异常情况下产生结果的一种简单有效的方法。为了让编码人员能够看到发生了什么，并在需要时采取进一步的行动，
BF16 指令以与 RISC-V 中所有其他浮点指令相同的方式设置浮点异常标志。

====== 下溢

IEEE 定义的下溢异常要求结果不精确且微小，其中微小可以在舍入之前或之后检测到。在 RISC-V 中，微小是在舍入之后检测到的。

需要注意的是，舍入后检测微小需要其自身的舍入，这与最终结果舍入不同。这种微小检测需要像指数是无界的那样进行舍入。
这意味着舍入器的输入始终是正规数。
这与最终结果舍入不同，在最终结果舍入中，当值太小而无法在目标格式中表示为正规数时，舍入器的输入是次正规数。
这两种不同的舍入可能导致为舍入回正规范围的结果发出下溢信号。

如 '754 中所定义，在默认异常处理下，仅当结果微小且不精确时才发出下溢信号。在这种情况下，下溢和不精确标志都会被置位。

<<<

[[BF16_extensions]]
=== 扩展

此处列出了 BF16 指令集扩展引入的扩展组。

单个 BF16 扩展的检测使用统一的基于软件的 RISC-V 发现方法。

[NOTE]
====
在撰写本文时，这些发现机制仍在开发中。
====

本规范中定义的 BF16 扩展（即 `Zfbfmin`、`Zvfbfmin` 和 `Zvfbfwma`）依赖于单精度浮点扩展 `F`。此外，向量 BF16 扩展（即 `Zvfbfmin` 和 `Zvfbfwma`）依赖于 `"V"` 应用处理器向量扩展或 `Zve32f` 嵌入式处理器向量扩展。

如本规范稍后所述，新定义的扩展之间存在依赖关系：`Zvfbfwma` 依赖于 `Zfbfmin` 和 `Zvfbfmin`。

这组初始的 BF16 扩展提供了非常基本的功能，包括 BF16 和单精度值之间的标量和向量转换，以及向量加宽乘法累加指令。


// include::riscv-bfloat16-zfbfmin.adoc[]
[[zfbfmin, Zfbfmin]]
==== `Zfbfmin` - 标量 BF16 转换

该扩展提供了启用 BF16 格式标量支持所需的最少指令集。它通过提供 BF16 值和 FP32 值之间的转换，使 BF16 成为一种交换格式。

该扩展依赖于单精度浮点扩展 `F`，以及 `Zfh` 扩展中定义的 `FLH`、`FSH`、`FMV.X.H` 和 `FMV.H.X` 指令。

[NOTE]
====
虽然转换指令倾向于包含所有支持的格式，但在这些扩展中，我们只支持 BF16 和 FP32 之间的转换，因为我们针对的是一个特殊的用例。
这些扩展旨在支持将 BF16 值用作 FP32 值的降精度版本的情况，其中使用 BF16 在存储、带宽和计算方面提供了双重优势。在这种用例中，BF16 值通常相互相乘并累加到 FP32 和中。
这些和通常会转换为 BF16，然后用作后续输入。对 BF16 值的操作可以在 CPU 或松散耦合的协处理器上执行。

后续扩展可能会提供对原生 BF16 算术的支持。此类扩展可以添加额外的转换指令，以允许所有支持的格式与 BF16 之间进行转换。
====

[NOTE]
====
BF16 加法、减法、乘法、除法和平方根运算可以通过将 BF16 操作数转换为单精度，使用单精度算术执行运算，然后转换回 BF16 来忠实地模拟。使用此方法执行 BF16 融合乘加运算可能会在某些输入上对 RNE 和 RMM 舍入模式产生 1-ulp 的差异。


BF16 与大于 FP32 的格式之间的转换可以被模拟。
从 BF16 进行的精确加宽转换可以通过先转换为 FP32，然后从 FP32 转换为目标精度来合成。
缩小到 BF16 的转换可以通过先通过一系列减半步骤转换为 FP32，然后从 FP32 转换为 BF16 来合成。
与上面描述的融合乘加指令一样，这种将值转换为 BF16 的方法在某些输入上对 RNE 和 RMM 舍入模式可能会有 1-ulp 的偏差。
====

[%autowidth]
[%header,cols="2,4"]
|===
|助记符
|指令
|FCVT.BF16.S    | <<insns-fcvt.bf16.s>>
|FCVT.S.BF16    | <<insns-fcvt.s.bf16>>
|FLH            |
|FSH            |
|FMV.H.X        |
|FMV.X.H        |
|===

// include::riscv-bfloat16-zvfbfmin.adoc[]
[[zvfbfmin,Zvfbfmin]]
==== `Zvfbfmin` - 向量 BF16 转换

该扩展提供了启用 BF16 格式向量支持所需的最少指令集。它通过提供 BF16 值和 FP32 值之间的转换，使 BF16 成为一种交换格式。

该扩展依赖于 `Zve32f` 向量扩展。

[NOTE]
====
虽然转换指令倾向于包含所有支持的格式，但在这些扩展中，我们只支持 BF16 和 FP32 之间的转换，因为我们针对的是一个特殊的用例。
这些扩展旨在支持将 BF16 值用作 FP32 值的降精度版本的情况，其中使用 BF16 在存储、带宽和计算方面提供了双重优势。在这种用例中，BF16 值通常相互相乘并累加到 FP32 和中。
这些和通常会转换为 BF16，然后用作后续输入。对 BF16 值的操作可以在 CPU 或松散耦合的协处理器上执行。

后续扩展可能会提供对原生 BF16 算术的支持。此类扩展可以添加额外的转换指令，以允许所有支持的格式与 BF16 之间进行转换。
====

[NOTE]
====
BF16 加法、减法、乘法、除法和平方根运算可以通过将 BF16 操作数转换为单精度，使用单精度算术执行运算，然后转换回 BF16 来忠实地模拟。使用此方法执行 BF16 融合乘加运算可能会在某些输入上对 RNE 和 RMM 舍入模式产生 1-ulp 的差异。

BF16 与大于 FP32 的格式之间的转换可以忠实地模拟。
从 BF16 进行的精确加宽转换可以通过先转换为 FP32，然后从 FP32 转换为目标精度来合成。缩小到 BF16 的转换可以通过先使用向量向奇数舍入的窄化转换指令（_vfncvt.rod.f.f.w_）通过一系列减半步骤转换为 FP32 来合成。最终从 FP32 到 BF16 的转换将使用所需的舍入模式。

====

[%autowidth]
[%header,cols="^2,4"]
|===
|助记符
|指令
| vfncvtbf16.f.f.w   | <<insns-vfncvtbf16.f.f.w>>
| vfwcvtbf16.f.f.v   | <<insns-vfwcvtbf16.f.f.v>>
|===

// include::riscv-bfloat16-zvfbfwma.adoc[]
[[zvfbfwma,Zvfbfwma]]
==== `Zvfbfwma` - 向量 BF16 加宽乘加

该扩展提供了一个向量加宽 BF16 乘加指令，该指令累加到 FP32 中。

该扩展依赖于 `Zvfbfmin` 扩展和 `Zfbfmin` 扩展。

[%autowidth]
[%header,cols="2,4"]
|===
|助记符
|指令

|VFWMACCBF16 | <<insns-vfwmaccbf16>>
|===


[[BF16_insns, reftext="BF16 指令"]]
=== 指令

// include::insns/fcvt_BF16_S.adoc[]
// <<<
[[insns-fcvt.bf16.s, 将 FP32 转换为 BF16]]

==== fcvt.bf16.s

概要::
将 FP32 值转换为 BF16 值

助记符::
fcvt.bf16.s rd, rs1

编码::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '01000', attr: ['bf16.s']},
{bits: 2, name: '10', attr: ['h']},
{bits: 5, name: '01000', attr: 'fcvt'},
]}
....


[NOTE]
====
.编码
虽然该指令的助记符与其他 RISC-V 浮点转换指令的助记符一致，但在第 24:20 位使用了新的编码。

`BF16.S` 和 `H` 用于表示源是 FP32，目标是 BF16。
====


描述::
将 FP32 值窄化转换为 BF16 值。根据 RM 字段进行舍入。

该指令类似于其他窄化浮点到浮点转换指令。


异常： 上溢、下溢、不精确、无效

包含于： <<zfbfmin>>

<<<
// include::insns/fcvt_S_BF16.adoc[]
// <<<
[[insns-fcvt.s.bf16, 将 BF16 转换为 FP32]]
==== fcvt.s.bf16

概要::
将 BF16 值转换为 FP32 值

助记符::
fcvt.s.bf16 rd, rs1

编码::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '00110', attr: ['bf16']},
{bits: 2, name: '00', attr: ['s']},
{bits: 5, name: '01000', attr: 'fcvt'},
]}
....

[NOTE]
====
.编码
虽然该指令的助记符与其他 RISC-V 浮点转换指令的助记符一致，但在第 24:20 位使用了新的编码来表示源是 BF16。
====


描述::
将 BF16 值转换为 FP32 值。转换是精确的。

该指令类似于其他加宽浮点到浮点转换指令。

[NOTE]
====
如果输入是正规数或无穷大，则 BF16 编码值向左移动 16 位，最低有效 16 位用 0 填充。

结果通过将最高有效 `FLEN`-32 位用 1 填充来进行 NaN 装箱。
====



异常： 无效

包含于： <<zfbfmin>>

<<<

// include::insns/vfncvtbf16_f_f_w.adoc[]
// <<<
[[insns-vfncvtbf16.f.f.w, 向量将 FP32 转换为 BF16]]
==== vfncvtbf16.f.f.w

概要::
向量将 FP32 转换为 BF16

助记符::
vfncvtbf16.f.f.w vd, vs2, vm

编码::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '001', attr:['OPFVV']},
{bits: 5, name: '11101', attr:['vfncvtbf16']},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '010010', attr:['VFUNARY0']},
]}
....

保留编码::
* `SEW` 是除 16 以外的任何值

参数::

[%autowidth]
[%header,cols="4,2,2,2"]
|===
|寄存器
|方向
|EEW
|定义

| Vs2 | 输入  | 32  | FP32 源
| Vd  | 输出 | 16  | BF16 结果
|===



描述::
从 FP32 到 BF16 的窄化转换。根据 _frm_ 寄存器进行舍入。

该指令类似于 `vfncvt.f.f.w`，它将 2*SEW 宽度格式的浮点值转换为 SEW 宽度格式。
但是，此处的 SEW 宽度格式仅限于 BF16。

异常： 上溢、下溢、不精确、无效

包含于： <<zvfbfmin>>

<<<

// include::insns/vfwcvtbf16_f_f_v.adoc[]
// <<<
[[insns-vfwcvtbf16.f.f.v, 向量将 BF16 转换为 FP32]]
==== vfwcvtbf16.f.f.v

概要::
向量将 BF16 转换为 FP32

助记符::
vfwcvtbf16.f.f.v vd, vs2, vm

编码::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '001', attr:['OPFVV']},
{bits: 5, name: '01101', attr:['vfwcvtbf16']},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '010010', attr:['VFUNARY0']},
]}
....

保留编码::
* `SEW` 是除 16 以外的任何值

参数::
[%autowidth]
[%header,cols="4,2,2,2"]
|===
|寄存器
|方向
|EEW
|定义

| Vs2 | 输入  | 16  | BF16 源
| Vd  | 输出 | 32  | FP32 结果
|===

描述::
从 BF16 到 FP32 的加宽转换。转换是精确的。

该指令类似于 `vfwcvt.f.f.v`，它将 SEW 宽度格式的浮点值转换为 2*SEW 宽度格式。
但是，此处的 SEW 宽度格式仅限于 BF16。

[NOTE]
====
如果输入是正规数或无穷大，则 BF16 编码值向左移动 16 位，最低有效 16 位用 0 填充。
====

异常： 无效

包含于： <<zvfbfmin>>

<<<

// include::insns/vfwmaccbf16.adoc[]
// <<<
[#insns-vfwmaccbf16, reftext="向量 BF16 加宽乘法累加"]
==== vfwmaccbf16

概要::
向量 BF16 加宽乘法累加

助记符::
vfwmaccbf16.vv vd, vs1, vs2, vm +
vfwmaccbf16.vf vd, rs1, vs2, vm +

编码 (向量-向量)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '001', attr:['OPFVV']},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '111011', attr:['vfwmaccbf16']},
]}
....

编码 (向量-标量)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '101', attr:['OPFVF']},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '111011', attr:['vfwmaccbf16']},
]}
....

保留编码::
* `SEW` 是除 16 以外的任何值

参数::
[%autowidth]
[%header,cols="4,2,2,2"]
|===
|寄存器
|方向
|EEW
|定义

| Vd      | 输入  | 32  | FP32 累加
| Vs1/rs1 | 输入  | 16  | BF16 源
| Vs2     | 输入  | 16  | BF16 源
| Vd      | 输出 | 32  | FP32 结果
|===

描述::

该指令执行加宽融合乘法累加运算，其中每对 BF16 值相乘，其未舍入的乘积加到相应的 FP32 累加值上。
和根据 _frm_ 寄存器进行舍入。


在向量-向量版本中，BF16 元素从 `vs1` 和 `vs2` 读取，FP32 累加值从 `vd` 读取。FP32 结果写入目标寄存器 `vd`。

向量-标量版本类似，但不是从 `vs1` 读取元素，而是从 FPU 寄存器 `rs1` 读取标量 BF16 值。


异常： 上溢、下溢、不精确、无效

操作::

`vfwmaccbf16.vv` 指令等效于将每个 BF16 输入加宽到 FP32，然后执行 FMACC，如以下指令序列所示：

[source,asm]
--
vfwcvtbf16.f.f.v T1, vs1, vm
vfwcvtbf16.f.f.v T2, vs2, vm
vfmacc.vv        vd, T1, T2, vm
--

同样，`vfwmaccbf16.vf` 等效于以下指令序列：

[source,asm]
--
fcvt.s.bf16      T1, rs1
vfwcvtbf16.f.f.v T2, vs2, vm
vfmacc.vf        vd, T1, T2, vm
--

包含于： <<zvfbfwma>>


// include::../bibliography.adoc[ieee]
[bibliography]
=== 参考书目

// bibliography::[]

https://ieeexplore.ieee.org/document/8766229[754-2019 - IEEE Standard for Floating-Point Arithmetic] +
https://ieeexplore.ieee.org/document/4610935[754-2008 - IEEE Standard for Floating-Point Arithmetic]
