== 介绍


RISC-V（发音为"risk-five"）是一种新的指令集架构（ISA），最初设计用于支持计算机架构研究和教育，但我们现在也希望它能成为工业实现的标准自由开放架构。我们在定义 RISC-V 时的目标包括：

* 一个完全 _开放_ 的 ISA，可供学术界和工业界自由使用。
* 一个适合直接本地硬件实现的 _真实_ ISA，而不仅仅是仿真或二进制转换。
* 一个避免为特定微架构风格（例如，微编码、顺序、解耦、乱序）或实现技术（例如，全定制、ASIC、FPGA）"过度架构"的 ISA，但允许在其中任何一种中高效实现。
* 一个分离为 _小型_ 基本整数 ISA 的 ISA，可单独用作定制加速器的基础或用于教育目的，以及可选的标准扩展，以支持通用软件开发。
* 支持修订的 2008 IEEE-754 浮点标准。cite:[ieee754-2008]
* 支持广泛的 ISA 扩展和专门变体的 ISA。
* 应用程序、操作系统内核和硬件实现的 32 位和 64 位地址空间变体。
* 支持高度并行多核或众核实现的 ISA，包括异构多处理器。
* 可选的 _变长指令_ 既可以扩展可用的指令编码空间，也可以支持可选的 _密集指令编码_，以提高性能、静态代码大小和能效。
* 完全可虚拟化的 ISA，以简化管理程序开发。
* 简化新特权架构设计实验的 ISA。

[NOTE]
====
对我们设计决策的评论格式如本段所示。如果读者只对规范本身感兴趣，可以跳过这些非规范性文本。
====

[NOTE]
====
选择 RISC-V 这个名称是为了代表来自 UC Berkeley 的第五个主要 RISC ISA 设计（RISC-I cite:[riscI-isca1981]、RISC-II cite:[Katevenis:1983]、SOAR cite:[Ungar:1984] 和 SPUR cite:[spur-jsscc1989] 是前四个）。我们还巧妙地使用罗马数字"V"来表示"变化"和"向量"，因为对一系列架构研究的支持，包括各种数据并行加速器，是 ISA 设计的明确目标。
====
(((ISA，定义)))
RISC-V ISA 的定义尽可能避免实现细节（尽管包含了对实现驱动决策的评论），应该被理解为各种实现的软件可见接口，而不是特定硬件工件的设计。RISC-V 手册分为两卷。本卷涵盖基本 _非特权_ 指令的设计，包括可选的非特权 ISA 扩展。非特权指令是那些在所有特权架构的所有特权模式中通常可用的指令，尽管行为可能因特权模式和特权架构而异。第二卷提供第一个（"经典"）特权架构的设计。手册使用 IEC 80000-13:2008 约定，字节为 8 位。

[NOTE]
====
在非特权 ISA 设计中，我们试图消除对特定微架构特性（例如缓存行大小）或特权架构细节（例如页面转换）的任何依赖。这既是为了简单起见，也是为了最大限度地提高替代微架构或替代特权架构的灵活性。
====

=== RISC-V 硬件平台术语


RISC-V 硬件平台可以包含一个或多个 RISC-V 兼容的处理核心以及其他非 RISC-V 兼容的核心、固定功能加速器、各种物理内存结构、I/O 设备和互连结构，以允许组件进行通信。
(((核心，组件)))

如果一个组件包含一个独立的指令获取单元，则称其为 _核心_。一个 RISC-V 兼容的核心可能通过多线程支持多个 RISC-V 兼容的硬件线程，或 _hart_。
(((核心，扩展，协处理器)))

一个 RISC-V 核心可能具有额外的专用指令集扩展或附加的 _协处理器_。我们使用术语 _协处理器_ 来指代连接到 RISC-V 核心的单元，主要由 RISC-V 指令流进行排序，但包含额外的架构状态和指令集扩展，并且可能相对于主 RISC-V 指令流具有一定的有限自主性。

我们使用术语 _加速器_ 来指代不可编程的固定功能单元或可以自主操作但专门用于某些任务的核心。在 RISC-V 系统中，我们预计许多可编程加速器将是基于 RISC-V 的核心，具有专用指令集扩展和/或定制协处理器。RISC-V 加速器的一个重要类别是 I/O 加速器，它们将 I/O 处理任务从主应用程序核心卸载。
(((核心，加速器)))

RISC-V 硬件平台的系统级组织可以从单核微控制器到数千个共享内存众核服务器节点的集群。即使是小型片上系统也可能被构建为多计算机和/或多处理器的层次结构，以模块化开发工作或在子系统之间提供安全隔离。
(((核心，集群，多处理器)))

=== RISC-V 软件执行环境和 Hart


RISC-V 程序的行为取决于其运行的执行环境。RISC-V 执行环境接口 (EEI) 定义了程序的初始状态、环境中 hart 的数量和类型（包括 hart 支持的特权模式）、内存和 I/O 区域的可访问性和属性、每个 hart 上执行的所有合法指令的行为（即 ISA 是 EEI 的一个组成部分），以及执行期间引发的任何中断或异常（包括环境调用）的处理。EEI 的示例包括 Linux 应用程序二进制接口 (ABI) 或 RISC-V supervisor 二进制接口 (SBI)。RISC-V 执行环境的实现可以是纯硬件、纯软件或硬件和软件的组合。例如，操作码陷阱和软件仿真可用于实现硬件中未提供的功能。执行环境实现的示例包括：

* "裸机"硬件平台，其中 hart 由物理处理器线程直接实现，指令可以完全访问物理地址空间。硬件平台定义了一个在上电复位时开始的执行环境。
* RISC-V 操作系统，通过将用户级 hart 多路复用到可用的物理处理器线程并控制通过虚拟内存访问内存来提供多个用户级执行环境。
* RISC-V 管理程序，为客户操作系统提供多个 supervisor 级执行环境。
* RISC-V 模拟器，例如 Spike、QEMU 或 rv8，它们在底层 x86 系统上模拟 RISC-V hart，并且可以提供用户级或 supervisor 级执行环境。

[NOTE]
====
裸硬件平台可以被视为定义了一个 EEI，其中可访问的 hart、内存和其他设备填充了环境，初始状态是上电复位时的状态。通常，大多数软件都设计为使用更抽象的硬件接口，因为更抽象的 EEI 提供了跨不同硬件平台的更大可移植性。EEI 通常是分层的，其中一个更高级别的 EEI 使用另一个更低级别的 EEI。
====
(((hart，执行环境)))
从在给定执行环境中运行的软件的角度来看，hart 是一种资源，它在该执行环境中自主获取和执行 RISC-V 指令。在这方面，hart 的行为类似于硬件线程资源，即使它由执行环境在真实硬件上进行时间多路复用。一些 EEI 支持创建和销毁额外的 hart，例如，通过环境调用来 fork 新的 hart。

执行环境负责确保其每个 hart 的最终前进。对于给定的 hart，当 hart 正在执行明确等待事件的机制时（例如本规范第二卷中定义的等待中断指令），该责任暂停；如果 hart 终止，则该责任终止。以下事件构成前进：

* 指令的退役。
* 陷阱，如 <<trap-defn>> 中定义。
* 扩展定义的任何其他构成前进的事件。

[NOTE]
====
hart 这个术语是在 Lithe cite:[lithe-pan-hotpar09] 和 cite:[lithe-pan-pldi10] 的工作中引入的，旨在提供一个术语来表示抽象执行资源，而不是软件线程编程抽象。

硬件线程 (hart) 和软件线程上下文之间的重要区别在于，在执行环境内部运行的软件不负责使其每个 hart 前进；这是外部执行环境的责任。因此，环境的 hart 从执行环境内部软件的角度来看，就像硬件线程一样运行。

执行环境实现可以将一组客户 hart 时间多路复用到较少的主机 hart 上，这些主机 hart 由其自身的执行环境提供，但必须以客户 hart 像独立的硬件线程一样运行的方式进行。特别是，如果客户 hart 数量多于主机 hart 数量，则执行环境必须能够抢占客户 hart，并且不得无限期地等待客户 hart 上的客户软件"让出"客户 hart 的控制权。
====

=== RISC-V ISA 概述


RISC-V ISA 被定义为基本整数 ISA，任何实现中都必须存在，以及基本 ISA 的可选扩展。基本整数 ISA 与早期 RISC 处理器非常相似，只是没有分支延迟槽，并支持可选的可变长度指令编码。基本 ISA 被仔细限制为最小指令集，足以提供编译器、汇编器、链接器和操作系统（具有附加特权操作）的合理目标，因此提供了一个方便的 ISA 和软件工具链"骨架"，在此基础上可以构建更定制的处理器 ISA。

虽然方便地说 _the_ RISC-V ISA，但 RISC-V 实际上是一系列相关的 ISA，目前有四个基本 ISA。每个基本整数指令集由整数寄存器的宽度和相应的地址空间大小以及整数寄存器的数量来表征。有两个主要的基本整数变体，RV32I 和 RV64I，在 <<rv32>> 和 <<rv64>> 中描述，分别提供 32 位或 64 位地址空间。我们使用术语 XLEN 来指代整数寄存器的位宽（32 或 64）。<<rv32e>> 描述了 RV32I 或 RV64I 基本指令集的 RV32E 和 RV64E 子集变体，它们为支持小型微控制器而添加，具有一半数量的整数寄存器。基本整数指令集使用有符号整数值的二进制补码表示。


[NOTE]
====
虽然 64 位地址空间是较大系统的要求，但我们相信 32 位地址空间在未来几十年内对许多嵌入式和客户端设备仍然足够，并且有望降低内存流量和能耗。此外，32 位地址空间足以满足教育目的。更大的平坦 128 位地址空间最终可能是必需的，可以在现有的 RISC-V ISA 框架内通过新的 RV128I 基本 ISA 来适应。
====

[NOTE]
====
RISC-V 中的四个基本 ISA 被视为不同的基本 ISA。一个常见的问题是为什么没有单一的 ISA，特别是为什么 RV32I 不是 RV64I 的严格子集？一些早期的 ISA 设计（SPARC、MIPS）在增加地址空间大小时采用了严格的超集策略，以支持在新的 64 位硬件上运行现有的 32 位二进制文件。

显式分离基本 ISA 的主要优势在于，每个基本 ISA 都可以针对其需求进行优化，而不需要支持其他基本 ISA 所需的所有操作。例如，RV64I 可以省略仅为应对 RV32I 中较窄寄存器而需要的指令和 CSR。RV32I 变体可以使用原本为仅宽地址空间变体所需的指令保留的编码空间。

不将设计视为单个 ISA 的主要缺点是，它使在另一个基本 ISA 上模拟一个基本 ISA 所需的硬件复杂化（例如，在 RV64I 上模拟 RV32I）。然而，寻址差异和非法指令陷阱通常意味着即使具有完整的超集指令编码，在任何情况下都需要某种模式切换，而且不同的 RISC-V 基本 ISA 足够相似，支持多个版本的成本相对较低。尽管有些人建议严格的超集设计将允许传统的 32 位库与 64 位代码链接，但由于软件调用约定和系统调用接口的差异，即使具有兼容的编码，这在实践中也是不切实际的。

RISC-V 特权架构在 `misa` 中提供字段，以控制每个级别的非特权 ISA，以支持在相同硬件上模拟不同的基本 ISA。我们注意到，较新的 SPARC 和 MIPS ISA 修订版本已经弃用了在 64 位系统上不变地运行 32 位代码的支持。

一个相关的问题是为什么在 RV32I (ADD) 和 RV64I (ADDW) 中 32 位加法有不同的编码？ADDW 操作码可以用于 RV32I 中的 32 位加法，ADDD 用于 RV64I 中的 64 位加法，而不是现有的设计，它在 RV32I 中为 32 位加法使用相同的操作码 ADD，在 RV64I 中为 64 位加法使用相同的操作码 ADD，并为 RV64I 中的 32 位加法使用不同的操作码 ADDW。这也将与 RV32I 和 RV64I 中 32 位加载使用相同的 LW 操作码更一致。RISC-V ISA 的最初版本确实有这种替代设计的变体，但 RISC-V 设计在 2011 年 1 月更改为当前选择。我们的重点是在 64 位 ISA 中支持 32 位整数，而不是提供与 32 位 ISA 的兼容性，动机是消除由于 RV32I 中不是所有操作码都有 *W 后缀（例如，ADDW，但 AND 不是 ANDW）而产生的不对称性。事后看来，这可能不是很有道理，这是同时设计两个 ISA 而不是稍后添加一个坐在另一个之上的结果，也是由于我们认为必须将平台要求折叠到 ISA 规范中，这意味着所有 RV32I 指令都需要在 RV64I 中。现在更改编码已经太晚了，但由于上述原因，这也没有什么实际后果。

已经注意到我们可以启用 *W 变体作为 RV32I 系统的扩展，以在 RV64I 和未来的 RV32 变体之间提供通用编码。
====

RISC-V 已被设计为支持广泛的定制和专业化。每个基本整数 ISA 都可以通过一个或多个可选的指令集扩展进行扩展。扩展可以被分类为标准、定制或不符合规范。为此，我们将每个 RISC-V 指令集编码空间（以及相关的编码空间，如 CSR）分为三个不相交的类别：_standard_、_reserved_ 和 _custom_。标准扩展和编码由 RISC-V International 定义；任何未由 RISC-V International 定义的扩展都是 _non-standard_。每个基本 ISA 及其标准扩展仅使用标准编码，并且不得在使用这些编码时相互冲突。保留编码目前未定义，但为未来的标准扩展保存；一旦如此使用，它们就成为标准编码。定制编码永远不得用于标准扩展，并可供供应商特定的非标准扩展使用。非标准扩展要么是定制扩展（仅使用定制编码），要么是 _不符合规范_ 的扩展（使用任何标准或保留编码）。指令集扩展通常是共享的，但可能根据基本 ISA 提供稍有不同的功能。<<extending>> 描述了扩展 RISC-V ISA 的各种方法。我们还为 RISC-V 基本指令和指令集扩展开发了命名约定，在 <<naming>> 中详细描述。

为了支持更通用的软件开发，定义了一组标准扩展来提供整数乘法/除法、原子操作以及单精度和双精度浮点运算。基本整数 ISA 命名为"I"（根据整数寄存器宽度以 RV32 或 RV64 为前缀），包含整数计算指令、整数加载、整数存储和控制流指令。标准整数乘法和除法扩展命名为"M"，并添加指令来乘除整数寄存器中保存的值。标准原子指令扩展，用"A"表示，添加指令以原子地读取、修改和写入内存，用于处理器间同步。标准单精度浮点扩展，用"F"表示，添加浮点寄存器、单精度计算指令以及单精度加载和存储。标准双精度浮点扩展，用"D"表示，扩展浮点寄存器，并添加双精度计算指令、加载和存储。标准"C"压缩指令扩展提供常见指令的较窄 16 位形式。

超出基本整数 ISA 和这些标准扩展，我们相信很少有新指令能为所有应用程序提供显著好处，尽管它可能对某个特定领域非常有益。由于能效关注正在迫使更大的专业化，我们相信简化 ISA 规范的必需部分是重要的。其他架构通常将其 ISA 视为单个实体，随着时间的推移添加指令时更改为新版本，而 RISC-V 将努力保持基本和每个标准扩展随时间不变，而是将新指令分层为进一步的可选扩展。例如，基本整数 ISA 将继续作为完全支持的独立 ISA，无论任何后续扩展如何。

=== 内存


RISC-V hart 具有单个字节可寻址的地址空间，包含 latexmath:[$2^{\text{XLEN}}$] 字节，用于所有内存访问。内存的 _字_ 定义为 32{nbsp}位（4{nbsp}字节）。相应地，_半字_ 是 16{nbsp}位（2{nbsp}字节），_双字_ 是 64{nbsp}位（8{nbsp}字节），_四字_ 是 128{nbsp}位（16{nbsp}字节）。内存地址空间是循环的，因此地址 latexmath:[$2^{\text{XLEN}}-1$] 处的字节与地址零处的字节相邻。因此，硬件执行的内存地址计算忽略溢出，而是围绕 latexmath:[$2^{\text{XLEN}}$] 取模回绕。

执行环境确定硬件资源到 hart 地址空间的映射。hart 地址空间的不同地址范围可能（1）包含 _主内存_，或（2）包含一个或多个 _I/O 设备_。I/O 设备的读写可能具有可见的副作用，但对主内存的访问不能。空闲地址范围不是单独的类别，但可以表示为不可访问的主内存或 I/O 区域。尽管执行环境可能将 hart 地址空间中的所有内容都称为 I/O 设备，但通常期望将某些部分指定为主内存。

当 RISC-V 平台具有多个 hart 时，任何两个 hart 的地址空间可能完全相同，或完全不同，或可能部分不同但共享某些资源子集，映射到相同或不同的地址范围。

[NOTE]
====
对于纯"裸机"环境，所有 hart 可能看到相同的地址空间，完全通过物理地址访问。然而，当执行环境包括使用地址转换的操作系统时，通常为每个 hart 提供很大程度上或完全属于自己的虚拟地址空间。
====
(((内存访问，隐式和显式)))

执行每个 RISC-V 机器指令都需要一次或多次内存访问，细分为 _隐式_ 和 _显式_ 访问。对于执行的每条指令，执行 _隐式_ 内存读取（指令获取）以获得要执行的编码指令。许多 RISC-V 指令除了指令获取之外不执行进一步的内存访问。特定的加载和存储指令在由指令确定的地址处执行内存的 _显式_ 读取或写入。执行环境可能规定指令执行除了为非特权 ISA 记录的那些之外还执行其他 _隐式_ 内存访问（例如实现地址转换）。

执行环境确定地址空间的哪些部分可访问用于每种内存访问。例如，可以为指令获取隐式读取的位置集合可能与可以由加载指令显式读取的位置集合有重叠或没有重叠；可以由存储指令显式写入的位置集合可能只是可以读取的位置的子集。通常，如果指令尝试在不可访问的地址访问内存，则为该指令引发异常。

除非另有规定，否则不引发异常且没有副作用的隐式读取可能任意早地和推测性地发生，甚至在机器可能证明需要读取之前。例如，有效的实现可能尝试在最早的机会读取所有主内存，缓存尽可能多的可获取（可执行）字节以供以后的指令获取，并避免再次为指令获取读取主内存。为了确保某些隐式读取仅在对相同内存位置的写入之后排序，软件必须执行为此目的定义的特定栅栏或缓存控制指令（例如 <<zifencei>> 中定义的 FENCE.I 指令）。
(((内存访问，隐式和显式)))

hart 执行的内存访问（隐式或显式）可能看起来以不同的顺序发生，正如另一个 hart 或可以访问相同内存的任何其他代理所感知的那样。然而，这种内存访问的感知重新排序总是受到适用的内存一致性模型的约束。RISC-V 的默认内存一致性模型是 RISC-V 弱内存排序（RVWMO），在 <<memorymodel>> 和附录中定义。可选地，实现可以采用更强的全存储排序模型，如 <<ztso>> 中定义的。执行环境还可以添加约束，进一步限制内存访问的感知重新排序。由于 RVWMO 模型是任何 RISC-V 实现允许的最弱模型，为此模型编写的软件与所有 RISC-V 实现的实际内存一致性规则兼容。与隐式读取一样，软件必须执行栅栏或缓存控制指令，以确保超出假定的内存一致性模型和执行环境要求的内存访问的特定排序。

=== 基本指令长度编码

基本 RISC-V ISA 具有固定长度的 32 位指令，必须在 32 位边界上自然对齐。然而，标准 RISC-V 编码方案设计为支持具有变长指令的 ISA 扩展，其中每条指令可以是任意数量的 16 位指令 _包_ 的长度，包在 16 位边界上自然对齐。<<compressed>> 中描述的标准压缩 ISA 扩展通过提供压缩的 16 位指令来减少代码大小，并放宽对齐约束以允许所有指令（16 位和 32 位）在任何 16 位边界上对齐以改善代码密度。

我们使用术语 IALIGN（以位测量）来指代实现强制执行的指令地址对齐约束。IALIGN 在基本 ISA 中是 32 位，但一些 ISA 扩展，包括压缩 ISA 扩展，将 IALIGN 放松到 16 位。IALIGN 不得取除 16 或 32 之外的任何值。
(((ILEN)))

我们使用术语 ILEN（以位测量）来指代实现支持的最大指令长度，它总是 IALIGN 的倍数。对于仅支持基本指令集的实现，ILEN 是 32 位。支持更长指令的实现具有更大的 ILEN 值。

基本 ISA 中的所有 32 位指令的最低两位都设置为 `11`。可选的压缩 16 位指令集扩展的最低两位等于 `00`、`01` 或 `10`。

[NOTE]
====
考虑到压缩格式的代码大小和能源节省，我们希望在 ISA 编码方案中内置对压缩格式的支持，而不是将其作为事后考虑添加，但为了允许更简单的实现，我们不想使压缩格式成为强制性的。我们还希望可选择地允许更长的指令来支持实验和更大的指令集扩展。尽管我们的编码约定需要更紧密地编码核心 RISC-V ISA，但这有几个有益的效果。
(((IMAFD)))

标准 IMAFD ISA 的实现只需要在指令缓存中保存最高有效 30 位（节省 6.25%）。在指令缓存重填时，遇到的任何低位清零的指令都应重新编码为非法的 30 位指令，然后存储在缓存中以保持非法指令异常行为。

也许更重要的是，通过将我们的基本 ISA 压缩到 32 位指令字的子集中，我们为非标准和定制扩展留下了更多可用空间。特别是，基本 RV32I ISA 使用 32 位指令字中编码空间的不到 1/8。如 <<extending>> 中所述，不需要支持标准压缩指令扩展的实现可以将 3 个额外的不符合规范的 30 位指令空间映射到 32 位固定宽度格式中，同时保持对标准 ≥32 位指令集扩展的支持。
====

位 [15:0] 全为零的编码被定义为非法指令。这些指令被认为是最小长度：如果存在任何 16 位指令集扩展，则为 16 位，否则为 32 位。位 [ILEN-1:0] 全为一的编码也是非法的；此指令被认为是 ILEN 位长。

[NOTE]
====
我们认为包含全零位的任何长度的指令都不合法是一个特性，因为这会快速捕获到零化内存区域的错误跳转。同样，我们还保留包含全一的指令编码为非法指令，以捕获未编程的非易失性内存设备、断开的内存总线或损坏的内存设备观察到的其他常见模式。

软件可以依赖包含零的自然对齐 32 位字在所有 RISC-V 实现上作为非法指令，供软件在明确需要非法指令的地方使用。由于变长编码，为全一定义相应的已知非法值更困难。软件通常不能使用 ILEN 位全为 1 的非法值，因为软件可能不知道最终目标机器的 ILEN（例如，如果软件被编译为许多不同机器使用的标准二进制库）。也考虑了将全一的 32 位字定义为非法，因为所有机器都必须支持 32 位指令大小，但这需要 ILEN >32 的机器上的指令获取单元在这样的指令跨越保护边界时报告非法指令异常而不是访问故障异常，这使变长指令获取和解码复杂化。
====
(((字节序，小端和大端)))
RISC-V 基本 ISA 具有小端或大端内存系统，特权架构进一步定义了双端操作。指令在内存中存储为 16 位小端包的序列，无论内存系统字节序如何。形成一条指令的包存储在递增的半字地址处，最低地址的包保存指令规范中编号最低的位。
(((双端)))
(((字节序，双)))

[NOTE]
====
我们最初为 RISC-V 内存系统选择了小端字节排序，因为小端系统目前在商业上占主导地位（所有 x86 系统；ARM 的 iOS、Android 和 Windows）。一个次要点是，我们也发现小端内存系统对硬件设计者来说更自然。然而，某些应用领域，如 IP 网络，操作大端数据结构，某些传统代码库已经构建为假设大端处理器，因此我们定义了 RISC-V 的大端和双端变体。

我们必须固定指令包在内存中的存储顺序，独立于内存系统字节序，以确保长度编码位总是首先出现在半字地址顺序中。这允许变长指令的长度由指令获取单元通过仅检查第一个 16 位指令包的前几位来快速确定。

我们进一步使指令包本身为小端，以将指令编码与内存系统字节序完全解耦。这种设计对软件工具和双端硬件都有好处。否则，例如，RISC-V 汇编器或反汇编器将始终需要知道预期的活动字节序，尽管在双端系统中，字节序模式可能在执行期间动态更改。相比之下，通过给指令固定的字节序，有时可能让仔细编写的软件在二进制形式下保持字节序无关，就像位置无关代码一样。

选择指令只为小端确实对编码或解码机器指令的 RISC-V 软件有后果。例如，大端 JIT 编译器在存储到指令内存时必须交换字节顺序。

一旦我们决定固定小端指令编码，这自然导致将长度编码位放在指令格式的 LSB 位置，以避免打破操作码字段。
====

[[trap-defn]]
=== 异常、陷阱和中断

我们使用术语 _异常_ 来指代在运行时发生的与当前 RISC-V hart 中的指令相关的异常条件。我们使用术语 _中断_ 来指代可能导致 RISC-V hart 经历意外控制转移的外部异步事件。我们使用术语 _陷阱_ 来指代由异常或中断引起的向陷阱处理程序的控制转移。
(((异常)))
(((陷阱)))
(((中断)))

以下章节中的指令描述描述了在执行期间可能引发异常的条件。大多数 RISC-V EEI 的一般行为是，当在指令上发出异常信号时，会发生到某个处理程序的陷阱（除了浮点异常，在标准浮点扩展中，它们不会导致陷阱）。中断的生成、路由到 hart 以及由 hart 启用的方式取决于 EEI。

[NOTE]
====
我们对"异常"和"陷阱"的使用与 IEEE-754 浮点标准兼容。
====

陷阱如何处理以及如何对在 hart 上运行的软件可见取决于封闭的执行环境。从在执行环境内运行的软件的角度来看，hart 在运行时遇到的陷阱可能有四种不同的效果：

包含陷阱:::
  陷阱对在执行环境内运行的软件可见并由其处理。例如，在为 hart 提供 supervisor 和用户模式的 EEI 中，用户模式 hart 的 ECALL 通常会导致控制转移到在同一 hart 上运行的 supervisor 模式处理程序。同样，在同一环境中，当 hart 被中断时，中断处理程序将在 hart 上以 supervisor 模式运行。
请求陷阱:::
  陷阱是一个同步异常，它是对执行环境的显式调用，请求代表执行环境内的软件采取行动。一个例子是系统调用。在这种情况下，在执行环境采取请求的行动后，执行可能会也可能不会在 hart 上恢复。例如，系统调用可能移除 hart 或导致整个执行环境的有序终止。
不可见陷阱:::
  陷阱由执行环境透明地处理，处理陷阱后正常恢复执行。示例包括模拟缺失的指令、在按需分页虚拟内存系统中处理非驻留页面故障，或处理多程序机器中不同作业的设备中断。在这些情况下，在执行环境内运行的软件不知道陷阱（我们在这些定义中忽略时间效应）。
致命陷阱:::
  陷阱表示致命故障并导致执行环境终止执行。示例包括未通过虚拟内存页面保护检查或允许看门狗定时器过期。每个 EEI 应定义如何终止执行并报告给外部环境。

<<trapcharacteristics>> 显示了每种陷阱的特性。

[[trapcharacteristics]]
.陷阱特性
[%autowidth,float="center",align="center",cols="<,^,^,^,^",options="header",]
|===
| |包含 |请求 |不可见 |致命
|执行终止 |否 |否^1^|否 |是
|软件不知情 |否 |否 |是 |是^2^
|由环境处理 |否 |是 |是 |是
|===

^1^ 可能请求终止 +
^2^ 不精确的致命陷阱可能被软件观察到

EEI 为每个陷阱定义它是否被精确处理，尽管建议在可能的情况下保持精确性。包含和请求的陷阱可以被执行环境内的软件观察为不精确。根据定义，不可见陷阱不能被执行环境内运行的软件观察为精确或不精确。如果已知错误的指令不会导致立即终止，则致命陷阱可以被执行环境内运行的软件观察为不精确。

由于本文档描述的是非特权指令，因此很少提及陷阱。处理包含陷阱的架构方法在特权架构手册中定义，以及支持更丰富 EEI 的其他功能。此处记录了仅用于引起请求陷阱的非特权指令。不可见陷阱，就其性质而言，不在本文档的范围之内。此处未定义且未通过其他方式定义的指令编码可能会导致致命陷阱。

=== 未指定行为和值
架构充分描述了实现必须做什么以及它们可能做什么的任何约束。在架构有意不约束实现的情况下，明确使用术语 UNSPECIFIED。
(((未指定，行为)))
(((未指定，值)))

术语 UNSPECIFIED 指的是有意不受约束的行为或值。这些行为或值的定义开放给扩展、平台标准或实现。扩展、平台标准或实现文档可以提供规范性内容，以进一步约束基本架构定义为 UNSPECIFIED 的情况。

与基本架构一样，扩展应充分描述允许的行为和值，并对有意不受约束的情况使用术语 UNSPECIFIED。这些情况可以由其他扩展、平台标准或实现约束或定义。

[NOTE]
====
RISC-V 中的四个基本 ISA 被视为不同的基本 ISA。一个常见的问题是为什么没有单一的 ISA，特别是为什么 RV32I 不是 RV64I 的严格子集？一些较早的 ISA 设计（SPARC、MIPS）在增加地址空间大小以支持在新的 64 位硬件上运行现有 32 位二进制文件时采用了严格的超集政策。

明确分离基本 ISA 的主要优点是每个基本 ISA 都可以根据其需要进行优化，而无需支持其他基本 ISA 所需的所有操作。例如，RV64I 可以省略仅需要处理 RV32I 中较窄寄存器的指令和 CSR。RV32I 变体可以使用否则为仅需要更宽地址空间变体的指令保留的编码空间。

不将设计视为单一 ISA 的主要缺点是它使在另一个基本 ISA 上模拟一个基本 ISA 所需的硬件复杂化（例如，在 RV64I 上模拟 RV32I）。然而，寻址和非法指令陷阱的差异通常意味着即使使用完整的超集指令编码，在任何情况下硬件都需要某种模式切换，并且不同的 RISC-V 基本 ISA 足够相似，支持多个版本的成本相对较低。尽管有些人建议严格的超集设计将允许遗留的 32 位库与 64 位代码链接，但这在实践中是不现实的，即使使用兼容的编码，由于软件调用约定和系统调用接口的差异。

RISC-V 特权架构在 `misa` 中提供字段来控制每个级别的非特权 ISA，以支持在同一硬件上模拟不同的基本 ISA。我们注意到较新的 SPARC 和 MIPS ISA 修订版已经弃用对在 64 位系统上不变地运行 32 位代码的支持。

一个相关的问题是为什么在 RV32I（ADD）和 RV64I（ADDW）中 32 位加法有不同的编码？ADDW 操作码可以用于 RV32I 中的 32 位加法，ADDD 用于 RV64I 中的 64 位加法，而不是现有的设计，它在 RV32I 中使用相同的操作码 ADD 进行 32 位加法，在 RV64I 中进行 64 位加法，并使用不同的操作码 ADDW 在 RV64I 中进行 32 位加法。这也与在 RV32I 和 RV64I 中都使用相同的 LW 操作码进行 32 位加载更一致。RISC-V ISA 的最初版本确实有这种替代设计的变体，但 RISC-V 设计在 2011 年 1 月更改为当前的选择。我们的重点是在 64 位 ISA 中支持 32 位整数，而不是提供与 32 位 ISA 的兼容性，动机是消除由于 RV32I 中并非所有操作码都有 *W 后缀而产生的不对称性（例如，ADDW，但 AND 而不是 ANDW）。事后看来，这也许没有很好的理由，这是同时设计两个 ISA 的结果，而不是稍后添加一个坐在另一个之上的结果，但现在更改它会破坏软件兼容性。
====

=== 基本指令格式

RISC-V ISA 基于小端字节序存储系统，尽管某些实现将具有双端字节序模式，支持大端字节序存储访问。

指令长度编码在每个指令的低阶位中。在基本 RISC-V ISA 中，指令的长度为 32 位，并且必须在 32 位边界上自然对齐。然而，指令长度编码方案被设计为支持可变长度指令的 ISA 扩展。

<<ilen-encode>> 显示了标准指令长度编码约定，该约定同时考虑了压缩指令（当前定义为 16 位）和可能的未来扩展。该编码被设计为扩展现有标准软件工具以处理新的指令长度变体，并且不要求软件确定指令的确切长度（例如，用于陷阱处理程序），仅确定指令的大小类别。

[[ilen-encode]]
.RISC-V 指令长度编码
[float="center",align="center",cols=">,>,>,>",options="header",]
|===
|`xxxxxxxxxxxxxxaa`|低 2 位|指令长度|描述
|`xxxxxxxxxxxx00` |00 |16 位 |压缩指令（≠11）
|`xxxxxxxxxxxx01` |01 |16 位 |压缩指令（≠11）
|`xxxxxxxxxxxx10` |10 |16 位 |压缩指令（≠11）
|`xxxxxxxxxxxx11` |11 |32 位 |未压缩指令
|`xxxxxxxxxxxnnn11` |nnn≠111 |32 位 |标准未压缩指令
|`xxx{8,12,16}x1111111` |111 |48, 64, 80 位等 |保留用于未来标准扩展
|`x{14,30,62,...}x011111111` |011...111 |16×(nnn+1) 位 |保留用于非标准扩展
|===

指令可以包含零个或多个指令字。指令字的概念源于 RISC-V 在 32 位指令字上的历史起源，并且在指令编码中可以观察到（例如，主要和次要操作码分布）。

[NOTE]
====
RISC-V 从一开始就被设计为可变长度指令扩展。虽然主要的 32 位指令格式为大多数代码提供了良好的密度和性能，但更短的 16 位压缩指令格式对嵌入式代码很重要，而我们预计更长的指令格式对高端设计很重要。
====

=== 异常、陷阱和中断

我们使用术语_异常_来指代执行期间的异常控制流变化，以及术语_中断_来指代由外部异步事件引起的异常控制流变化。术语_陷阱_指代同步异常。

(((陷阱)))
(((异常)))
(((中断)))

在本文档中，我们使用陷阱这一术语来指代将控制转移到陷阱处理程序的任何情况，无论是由于同步异常、异步中断还是显式异常指令（如系统调用）。我们使用"致命陷阱"这一术语来指代导致执行环境终止执行的陷阱。

=== RISC-V 特权软件栈术语

本节描述了 RISC-V 特权软件栈的术语，这有助于解释某些设计选择的动机。

((应用程序执行环境))
_应用程序执行环境_（AEE）是为用户级软件提供的执行环境。从 AEE 的角度来看，有三种类型的 RISC-V 系统：

1. AEE 直接在硬件上实现，即系统只运行单一的用户级应用程序。
2. AEE 由某种简单的库或监督程序在较低级的执行环境上实现。
3. AEE 是传统操作系统的用户模式。

((supervisor执行环境))
_Supervisor 执行环境_（SEE）是为 supervisor 级软件提供的执行环境。supervisor 执行环境通常代表传统的操作系统。

((管理程序执行环境))
_管理程序执行环境_（HEE）是为管理程序级软件提供的执行环境。

我们使用术语_执行环境接口_（EEI）来指代给定执行环境与级别上方的软件之间的接口。

((执行环境))
嵌入式系统通常只使用 AEE，而传统的桌面或服务器系统通常只使用前三个级别中的两个：AEE 和 SEE，或者在虚拟化环境中，AEE、SEE 和 HEE。

复杂的嵌入式系统可能对不同的应用程序类使用多个执行环境。例如，安全的嵌入式系统可能具有一个小型的可信任监督程序，该监督程序为安全关键控制代码提供 SEE，并为以传统方式操作的不太关键的代码提供单独的 AEE。

尽管传统的机器级架构（如 x86）已经被 supervisor/kernel 级架构支配，但其历史的 RISC-V 设计方法保留了机器级架构的明确规范。此方法有几个优点。首先，它将责任明确分为机器级实现（例如，平台特定的启动和配置、实时功能、多种权限级别之间的切换），以及可移植的 supervisor 级软件。其次，它允许RISC-V 设计师为不需要某些 supervisor 级功能的应用程序开发高度专门化且相对简单的机器级实现，而不需要支持完整的虚拟化环境。

=== 调试模式

大多数RISC-V系统会提供一些对软件调试的支持。有关软件调试支持的详细信息，请参阅RISC-V调试规范cite:[RISC-V-DEBUG]。

此处我们仅定义调试模式作为一种特殊的操作模式，某些实现可能包含这种模式以支持离片调试。在调试模式下运行的代码在实现定义的调试地址空间中运行，并且能够访问常规RISC-V机器级和非特权功能以及额外的调试功能。调试模式以及任何代码的执行在调试模式下运行的存在，对于在常规模式下运行的软件不是架构可见的，除了定义了诸如调试陷阱信息CSR之类的调试CSR以提供基本的调试支持，甚至没有调试模式的系统。

一些执行环境将提供对其他形式的调试支持，如执行跟踪。

[NOTE]
====
_调试模式_操作是不需要虚拟化的可选功能，实际上对于大多数可能具有的低成本实现来说是不切实际的。许多系统将依赖其他调试机制，如联合测试行动组（JTAG）或简单的打印语句。
====

=== 符号约定

我们采用以下符号约定来描述指令语义：

=== 指令格式图

指令格式以两种方式显示：作为一个 32 位字格式和作为一个寄存器传输符号。

<<riscvencoding>> 给出了使用的 32 位字约定，格式为：

[[riscvencoding]]
.RISC-V指令编码约定
[cols="1,1,1,1,1",options="header",]
|===
|31 |30-25 |24-20 |19-15 |14-12 |11-7 |6-0
|imm[31] |imm[30:25] |imm[24:20] |rs1 |funct3 |rd |opcode
|===

这种格式显示立即数，源寄存器和目标寄存器字段，以及任何固定的用于区分不同类型指令的位字段。

=== 指令类别

我们使用一致的指令类别来避免在类似的指令类型之间重复信息。

((（计算，指令类别)))
_计算指令_对源操作数执行某种功能以产生结果，该结果写入目标寄存器。

((（系统，指令类别)))
_系统指令_提供对系统的访问功能。

((（控制流，指令类别)))
_控制流指令_改变下一指令的程序计数器值。

((（存储器，指令类别)))
_存储器指令_传输值在寄存器和存储器之间。

=== 描述语言

我们使用简化的Haskell风格的符号来描述指令的行为，其中纯函数用于读取和更新系统状态。表示符号我们直接从<<user-spec>> 采用。

我们使用 RISC-V架构测试框架的约定 cite:[riscv-arch-test]，它们本身大多来自 Sail语言 cite:[sail-language]。

我们定义了 XLEN 为硬件中基本整数寄存器的宽度，这可能与软件中的 XLEN 不同，称为 VSXLEN（虚拟化 XLEN）。术语 XLEN 的一般使用是指硬件设置，VSXLEN 只在特定上下文中使用。

XLEN 可以为 32 或 64，对应于 RV32* 和 RV64*。我们为 Zfinx 变体使用 FLEN 来表示 F 寄存器的宽度，VLEN 来表示每个向量寄存器的宽度（以位为单位），ELEN 来表示每个向量元素的最大宽度（以位为单位）。

对于 RV32，XLEN=32，对于 RV64，XLEN=64。

我们使用数学函数 SEXT(x, n) 来表示值 x 的符号扩展，从 n 位到 XLEN 位。

我们还使用 ZEXT(x, n) 来表示值 x 的零扩展，从 n 位到 XLEN 位。

我们使用符号 FENCE(predecessor, successor) 来表示适当类型的栅栏操作。

我们使用 `+` 来表示连接，如 rs2 的位 31:20 和 rs1 的位 11:0 被写为 rs2[31:20] + rs1[11:0]。我们使用一种更简洁的符号 {a,b,c} 来表示 a + b + c，其中 a、b 和 c 是从寄存器、立即数或常量提取的位字段。

我们使用符号 repeat(n, pattern) 来表示模式的 n 个副本的连接。

=== 支持非对齐访问

RISC-V 指令集要求通常对齐的地址支持非对齐存储器访问。不支持非对齐访问的实现将把非对齐的加载和存储的访问-故障异常传递给软件进行模拟。实现使用地址不匹配异常的详细信息在特权架构手册中提供。

软件编写者可以通过避免生成非对齐访问来避免陷阱到软件的性能和代码大小开销。所有当前提出的标准RISC-V扩展都避免了需要非对齐访问。但是，一些支持非对齐访问的快速实现可能会受益于使用非对齐访问，特别是对字符串操作的库例程。

[NOTE]
====
我们要求执行环境能够处理非对齐访问，以与软件中其他ISA的标准二进制接口兼容，并简化遗留代码的移植。

大多数现代指令集都要求对象的地址自然对齐到其大小，但支持非对齐访问（为了大多数处理器可以快速处理）或通过软件陷阱（为了小型处理器）或通过硬件陷阱（为了专业处理器）。通过利用现代互连和存储器系统的较大的传输大小，可以以相对低的成本支持非对齐访问。
====

常见的不对齐操作包括：

- 跨越高速缓存行边界的多字访问。
- 字符串操作中的非对齐加载和存储。
- 访问打包的数据结构。
- 在运行时只能确定其对齐的指针间接访问。

实现可能会针对某些情况提供快速的非对齐访问，同时对其他情况进行软件陷阱。

[NOTE]
====
非对齐访问的性能将取决于底层缓存和存储器系统设计，实现在原理上可以提供比对齐访问更快的非对齐访问，尽管这在实践中可能是一个疑问。
====

大多数RISC-V EEI的共同特征是当指令上发出异常信号时（除了浮点异常，在标准浮点扩展中，它们不会导致陷阱），对某个处理程序发生陷阱。中断如何生成、路由到和由hart启用取决于EEI。

[NOTE]
====
我们对"异常"和"陷阱"的使用与IEEE-754浮点标准中的兼容。
====

软件如何处理陷阱并使其对在hart上运行的软件可见取决于封闭的执行环境。从在执行环境内运行的软件的角度来看，hart在运行时遇到的陷阱可能有四种不同的效果：

包含陷阱:::
  陷阱对在执行环境内运行的软件可见并由其处理。例如，在为hart提供supervisor和用户模式的EEI中，用户模式hart的ECALL通常会导致控制权转移到在同一hart上运行的supervisor模式处理程序。类似地，在同一环境中，当hart被中断时，中断处理程序将在hart上以supervisor模式运行。

请求陷阱:::
  陷阱是一个同步异常，是对执行环境的显式调用，请求代表执行环境内的软件采取行动。一个例子是系统调用。在这种情况下，在执行环境采取请求的行动后，执行可能会或可能不会在hart上恢复。例如，系统调用可能删除hart或导致整个执行环境的有序终止。

不可见陷阱:::
  陷阱由执行环境透明处理，在处理陷阱后执行正常恢复。示例包括模拟缺失的指令、在需求分页虚拟存储器系统中处理非驻留页故障，或为多程序机器中的不同作业处理设备中断。在这些情况下，在执行环境内运行的软件不知道陷阱（我们在这些定义中忽略时序效应）。

致命陷阱:::
  陷阱代表致命故障并导致执行环境终止执行。示例包括未能通过虚拟存储器页保护检查或允许看门狗定时器到期。每个EEI应该定义如何终止和报告执行到外部环境。

<<trapcharacteristics>> 显示了每种陷阱的特征。

[[trapcharacteristics]]
.陷阱的特征
[%autowidth,float="center",align="center",cols="<,^,^,^,^",options="header",]
|===
| |包含 |请求 |不可见 |致命
|执行终止 |否 |否^1^|否 |是
|软件不知情 |否 |否 |是 |是^2^
|由环境处理 |否 |是 |是 |是
|===

^1^ 可能请求终止 +
^2^ 不精确的致命陷阱可能被软件观察到

EEI为每个陷阱定义它是否被精确处理，尽管建议在可能的情况下保持精确性。包含和请求的陷阱可以被执行环境内的软件观察为不精确。根据定义，不可见陷阱不能被执行环境内运行的软件观察为精确或不精确。如果已知错误的指令不会导致立即终止，则致命陷阱可以被执行环境内运行的软件观察为不精确。

由于本文档描述的是非特权指令，因此很少提及陷阱。处理包含陷阱的架构方法在特权架构手册中定义，以及支持更丰富EEI的其他功能。此处记录了仅用于引起请求陷阱的非特权指令。不可见陷阱，就其性质而言，不在本文档的范围之内。此处未定义且未通过其他方式定义的指令编码可能会导致致命陷阱。

基本RISC-V ISA被固定为32位指令长度，与32位和64位地址空间变体相匹配。编码方案被设计为支持可变长度指令的ISA扩展，其中每个指令可以是任意数量的16位指令_包_的长度，并且包在16位边界上自然对齐。<<compressed>>中描述的标准压缩ISA扩展通过提供压缩的16位指令减少代码大小，并放宽对齐约束以允许所有指令（16位和32位）在任何16位边界上对齐以改善代码密度。

我们使用术语IALIGN（以位衡量）来指代实现强制执行的指令地址对齐约束。在基本ISA中IALIGN是32位，但一些ISA扩展，包括压缩ISA扩展，将IALIGN放宽到16位。IALIGN不能取除16或32之外的任何值。

(((ILEN)))

我们使用术语ILEN（以位衡量）来指代实现支持的最大指令长度，它总是IALIGN的倍数。对于仅支持基本指令集的实现，ILEN是32位。支持更长指令的实现具有更大的ILEN值。

基本ISA中的所有32位指令都将其最低的两位设置为`11`。可选的压缩16位指令集扩展的最低两位等于`00`、`01`或`10`。

[NOTE]
====
考虑到压缩格式的代码大小和能耗节省，我们希望将对压缩格式的支持内置到ISA编码方案中，而不是将其作为事后考虑添加，但为了允许更简单的实现，我们不想使压缩格式成为强制性的。我们还希望可选地允许更长的指令来支持实验和更大的指令集扩展。尽管我们的编码约定需要对核心RISC-V ISA进行更紧密的编码，但这有几个有益的效果。

(((IMAFD)))

标准IMAFD ISA的实现只需在指令缓存中保存最高有效的30位（节省6.25％）。在指令缓存重填时，遇到任何低位清零的指令都应在存储到缓存之前重新编码为非法的30位指令，以保持非法指令异常行为。

也许更重要的是，通过将我们的基本ISA压缩到32位指令字的子集中，我们为非标准和自定义扩展留下了更多可用空间。特别是，基本RV32I ISA使用32位指令字中的编码空间不到1/8。如<<extending>>中所述，不需要支持标准压缩指令扩展的实现可以将3个额外的不符合要求的30位指令空间映射到基本ISA的30位空间的每一位。

ISA编码方案还有助于将来扩展，因为较短的压缩指令在最初的16位编码空间内很容易识别和扩展。
====

我们注意到，在<<ilen-encode>>中选择的指令长度编码将禁止由多个较短指令形成的更长指令，例如具有两个16位部分的一个32位指令。我们认为这种结构太复杂而不值得支持，特别是因为具有更明确的格式更容易支持。

[NOTE]
====
指令获取现在基于2字节获取数据包，仅识别指令边界以将单个指令传递给执行单元。这在表现更单纯的指令获取的处理器机器中更简单，并且能够更简单地处理在内存或缓存访问边界上跨越的指令。
====

=== RISC-V指令语法

在RISC-V汇编语法中，大多数指令具有如下格式：

    opcode rd, rs1, rs2

其中opcode是指令的名称，rd是目标寄存器，rs1和rs2是源寄存器。这种语法源于约定，即目标寄存器在指令操作中首先出现。立即值使用十进制表示法编写，并且立即值包含在汇编代码中，如下所示：

    opcode rd, rs1, immediate

更复杂的指令也遵循这种语法，以可能不同的源和目的寄存器列表为开始，然后跟着其他参数（通常是立即值）。

=== 存储器类型

RISC-V架构是围绕小端字节序内存设计的，尽管某些实现在执行环境接口级别提供双端字节序支持。

对于基本存储器指令，有效地址是通过将第一个源寄存器的值与符号扩展的12位立即数相加获得的。加载将值从内存复制到目标寄存器。存储将源寄存器的值复制到内存。

存储器被字节寻址，并且没有对齐约束for基本存储器访问（在某些实现中，某些标量指令可能要求自然对齐）。可以加载和存储8位字节、16位半字、32位字、以及在RV64中的64位双字。字节存储只需要8位有效地址。

[NOTE]
====
尽管存储器没有对齐约束，但可能针对对齐访问优化实现，或可能为非对齐访问生成软件陷阱，因此程序员应该被鼓励对齐数据以避免可能的性能或功能性惩罚。
====

其他RISC-V指令集扩展可能对特定指令提供其他寻址模式和内存访问宽度，或可能不支持非对齐访问。

=== 未指定行为和值

架构充分描述了实现必须做什么以及它们可能做什么的任何约束。在架构有意不约束实现的情况下，明确使用术语 UNSPECIFIED。

(((未指定，行为)))
(((未指定，值)))

术语 UNSPECIFIED 指的是有意不受约束的行为或值。这些行为或值的定义开放给扩展、平台标准或实现。扩展、平台标准或实现文档可以提供规范性内容，以进一步约束基本架构定义为 UNSPECIFIED 的情况。

与基本架构一样，扩展应充分描述允许的行为和值，并对有意不受约束的情况使用术语 UNSPECIFIED。这些情况可以由其他扩展、平台标准或实现约束或定义。

与基本架构一样，扩展应充分描述允许的行为和值，并对有意不受约束的情况使用术语 UNSPECIFIED。这些情况可以由其他扩展、平台标准或实现约束或定义。