[[mstandard]]
== `M` 扩展：整数乘法和除法，版本 2.0

本章描述了标准整数乘法和除法指令扩展，名为 `M`，包含对两个整数寄存器中的值进行乘法或除法的指令。

[NOTE]
====
我们将整数乘法和除法从基本指令集中分离出来，以简化低端实现，或用于整数乘法和除法操作不频繁或在附加加速器中处理得更好的应用程序。
====

=== 乘法操作

include::images/wavedrom/m-st-ext-for-int-mult.edn[]
[[m-st-ext-for-int-mult]]
//.乘法操作指令
(((MUL, MULH)))
(((MUL, MULHU)))
(((MUL, MULHSU)))

MUL 执行 `rs1` 乘以 `rs2` 的 XLEN 位 × XLEN 位乘法，并将结果的低 XLEN 位放入目标寄存器。MULH、MULHU 和 MULHSU 执行相同的乘法，但返回完整 2 × XLEN 位乘积的高 XLEN 位，分别用于有符号 × 有符号、无符号 × 无符号和 `rs1` × 无符号 `rs2` 乘法。
如果需要同一乘积的高位和低位，则推荐的代码序列是：`MULH[[S]U] rdh, rs1, rs2; MUL rdl, rs1, rs2`（源寄存器说明符必须按相同顺序，且 `rdh` 不能与 `rs1` 或 `rs2` 相同）。微架构可以将这些融合为一个乘法操作，而不是执行两个单独的乘法。

[NOTE]
====
MULHSU 用于多字有符号乘法中，将乘数的最高有效字（包含符号位）与乘数的较低有效字（无符号）相乘。
====

MULW 是 RV64 指令，它将源寄存器的低 32 位相乘，并将结果的低 32 位的符号扩展放入目标寄存器。

[NOTE]
====
在 RV64 中，MUL 可用于获取 64 位乘积的高 32 位，但有符号参数必须是正确的 32 位有符号值，而无符号参数必须将其高 32 位清零。如果参数已知为符号扩展或零扩展，则另一种方法是将两个参数左移 32 位，然后使用 MULH[[S]U]。
====

=== 除法操作

include::images/wavedrom/division-op.edn[]
[[division-op]]
//.除法操作指令
(((MUL, DIV)))
(((MUL, DIVU)))

DIV 和 DIVU 执行 XLEN 位除以 XLEN 位有符号和无符号整数除法，`rs1` 除以 `rs2`，向零舍入。REM 和 REMU 提供相应除法操作的余数。对于 REM，非零结果的符号等于被除数的符号。

[NOTE]
====
对于有符号和无符号除法，除了溢出情况外，都满足
latexmath:[$\textrm{被除数} = \textrm{除数} \times \textrm{商} + \textrm{余数}$]。
====

如果需要同一除法的商和余数，则推荐的代码序列是：`DIV[U] rdq, rs1, rs2; REM[U] rdr,`
`rs1, rs2`（`rdq` 不能与 `rs1` 或 `rs2` 相同）。微架构可以将这些融合为一个除法操作，而不是执行两个单独的除法。

DIVW 和 DIVUW 是 RV64 指令，它们将 `rs1` 的低 32 位除以 `rs2` 的低 32 位，将它们视为有符号和无符号整数，将 32 位商放入 `rd`，并符号扩展到 64 位。REMW 和 REMUW 是 RV64 指令，它们提供相应的有符号和无符号余数操作。REMW 和 REMUW 都总是将 32 位结果符号扩展到 64 位，包括除以零时。
(((MUL, 除以零)))

除以零和除法溢出的语义总结在 <<divby0>> 中。除以零的商所有位都设置为 1，除以零的余数等于被除数。有符号除法溢出仅在最负整数除以 latexmath:[$-1$] 时发生。有符号除法溢出的商等于被除数，余数为零。无符号除法不会溢出。

[[divby0]]
.除以零和除法溢出的语义。L 是操作的位宽：DIV[U] 和 REM[U] 为 XLEN，或 DIV[U]W 和 REM[U]W 为 32。
[cols="<2,^,^,^,^,^,^",options="header",]
|===
|条件 |被除数 |除数 |DIVU[W] |REMU[W] |DIV[W] |REM[W]

|除以零 +
溢出（仅有符号） |latexmath:[$x$] +
latexmath:[$-2^{L-1}$] |0 +
latexmath:[$-1$] |latexmath:[$2^{L}-1$] +
 - |latexmath:[$x$] +
 - |latexmath:[$-1$] +
 latexmath:[$-2^{L-1}$] +
  |latexmath:[$x$] +
  0
|===

//|溢出（仅有符号） |latexmath:[$-2^{L-1}$] |latexmath:[$-1$] |– |– |latexmath:[$-2^{L-1}$] |0
//|===

[NOTE]
====
我们考虑过在整数除以零时引发异常，这些异常在大多数执行环境中会导致陷阱。然而，这将是标准 ISA 中唯一的算术陷阱（浮点异常设置标志并写入默认值，但不会导致陷阱），并且需要语言实现者在这种情况下与执行环境的陷阱处理程序交互。此外，如果语言标准要求除以零异常必须导致立即控制流更改，则每个除法操作只需添加一个分支指令，并且该分支指令可以在除法之后插入，并且通常非常可预测地不会被执行，从而增加很少的运行时开销。

为了简化除法器电路，对于无符号和有符号除以零，都返回所有位都设置为 1 的值。所有位都设置为 1 的值既是无符号除法返回的自然值，表示最大的无符号数，也是简单无符号除法器实现的自然结果。有符号除法通常使用无符号除法电路实现，并且指定相同的溢出结果简化了硬件。
====

=== `Zmmul` 扩展，版本 1.0

`Zmmul` 扩展实现了 M 扩展的乘法子集。它添加了 <<Multiplication Operations>> 中定义的所有指令，即：MUL、MULH、MULHU、MULHSU 和（仅适用于 RV64）MULW。编码与相应的 M 扩展指令相同。`M` 隐含 `Zmmul`。
(((MUL, Zmmul)))

[NOTE]
====
`Zmmul` 扩展支持需要乘法操作但不需要除法的低成本实现。对于许多微控制器应用程序，除法操作过于不频繁，无法证明除法器硬件的成本是合理的。相比之下，乘法操作更频繁，使得乘法器硬件的成本更合理。简单的 FPGA 软核特别受益于消除除法但保留乘法，因为许多 FPGA 提供硬连线乘法器，但要求除法器在软逻辑中实现。
====
