== "Zawrs"——等待预留集指令扩展，版本 1.01

Zawrs 扩展定义了一对用于轮询循环的指令，允许核心进入低功耗状态并等待对内存位置的存储。等待内存位置被更新是许多用例中的常见模式，例如：

. 锁的竞争者等待锁变量被更新。

. 消费者在空队列的尾部等待生产者将工作/数据入队。生产者可以是正在 RISC-V hart 上执行的代码、加速器设备或外部 I/O 代理。

. 代码等待内存中设置一个标志，以指示事件发生。例如，RISC-V hart 上的软件可能会等待加速器设备在内存中设置一个"完成"标志，以指示先前提交给该设备的作业已完成。

此类用例涉及轮询内存位置，而这种繁忙的循环可能会浪费能源。为了减少此类用法中浪费的循环，提供了 `WRS.NTO`（无超时的 WRS）指令。软件不是轮询对特定内存位置的存储，而是使用 `LR` 指令注册一个包含该内存位置所有字节的预留集。然后，随后的 `WRS.NTO` 指令将导致 hart 暂时停止执行并进入低功耗状态，直到发生对预留集的存储或观察到中断。

有时，等待内存更新的程序可能还需要在将来的某个时间执行任务，或者以其他方式为等待设置一个上限。为了支持此类用例，提供了第二条指令 `WRS.STO`（具有短超时的 WRS），其工作方式类似于 `WRS.NTO`，但将暂停持续时间限制为实现定义的短超时，以便在没有其他条件发生以终止暂停的情况下，暂停在超时时终止。然后，使用此指令的程序可以确定其最后期限是否已到。

[NOTE]
====
Zawrs 扩展中的指令只有与 A 扩展的 Zalrsc 组件提供的 LR 指令结合使用才有用。
====
[[Zawrs]]
=== 等待预留集指令

只要预留集有效并且没有观察到挂起的中断（即使已禁用），`WRS.NTO` 和 `WRS.STO` 指令就会导致 hart 暂时停止执行并进入低功耗状态。对于 `WRS.STO`，暂停持续时间受实现定义的短超时限制。这些指令在所有特权模式下都可用。

[wavedrom, ,svg]
....
{reg: [
  {bits: 7, name: 'opcode', attr: ['SYSTEM(0x73)'] },
  {bits: 5, name: 'rd', attr: ['0'] },
  {bits: 3,  name: 'funct3', attr: ['0'] },
  {bits: 5,  name: 'rs1', attr: ['0'] },
  {bits: 12,  name: 'funct12', attr:['WRS.NTO(0x0d)', 'WRS.STO(0x1d)'] },
], config:{lanes: 1, hspace:1024}}
....

<<<

在以下所有条件都满足的情况下，Hart 执行可能会暂停：
[loweralpha]
    . 预留集有效
    . 如果是 `WRS.STO`，则自暂停开始以来的"短"持续时间尚未过去
    . 没有观察到挂起的中断（请参阅下面的规则）

在暂停期间，允许实现出于任何原因偶尔终止暂停并完成执行。

`WRS.NTO` 和 `WRS.STO` 指令遵循 `WFI` 指令的规则，以便在挂起中断时恢复执行。

当 `mstatus` 中的 `TW`（超时等待）位置 1 并且在除 M 模式之外的任何特权模式下执行 `WRS.NTO`，并且它在实现特定的有界时间限制内未完成时，`WRS.NTO` 指令将导致非法指令异常。

在 VS 或 VU 模式下执行时，如果 `hstatus` 中的 `VTW` 位置 1，`mstatus` 中的 `TW` 位为 0，并且 `WRS.NTO` 在实现特定的有界时间限制内未完成，则 `WRS.NTO` 指令将导致虚拟指令异常。

[NOTE]
====
由于 `WRS.STO` 和 `WRS.NTO` 指令可以出于除对预留集的存储之外的原因完成执行，因此软件可能需要一种循环方式，直到发生所需的存储。

`WRS.STO` 指令的超时持续时间在实现内部和实现之间可能会有很大差异。在典型的实现中，此持续时间应大致在片上缓存未命中延迟或无缓存访问主内存的 10 到 100 倍范围内。

与 `WFI` 不同，当控制 `TW` 位为 0 时，在 U 模式下执行 `WRS.NTO` 不会指定导致非法指令异常。`WFI` 通常不希望在 U 模式下使用，并且在许多系统上，如果在 U 模式下使用，可能会立即导致非法指令异常。与 `WFI` 不同，当在 U 模式下等待内存但没有该等待的最后期限时，软件有望使用 `WRS.NTO`。
====