[[sec:zfinx]]
== "Zfinx"、"Zdinx"、"Zhinx"、"Zhinxmin"——整数寄存器中的浮点扩展，版本 1.0

本章定义了"Zfinx"扩展（发音为"z-f-in-x"），它提供了与标准浮点 F 扩展中的单精度浮点指令类似的指令，但这些指令操作于 `x` 寄存器而不是 `f` 寄存器。本章还定义了"Zdinx"、"Zhinx"和"Zhinxmin"扩展，它们为其他浮点精度提供了类似的指令。

[NOTE]
====
F 扩展使用单独的 `f` 寄存器进行浮点计算，以减少寄存器压力并简化为宽超标量提供寄存器文件端口。然而，额外的体系结构状态增加了最小实现成本。通过消除 `f` 寄存器，Zfinx 扩展大大降低了具有浮点指令集支持的简单 RISC-V 实现的成本。Zfinx 还降低了上下文切换成本。

通常，假设存在 F 扩展的软件与假设存在 Zfinx 扩展的软件不兼容，反之亦然。
====

Zfinx 扩展添加了 F 扩展添加的所有指令，_除了_传输指令 FLW、FSW、FMV.W.X、FMV.X.W、C.FLW[SP] 和 C.FSW[SP]。

[NOTE]
====
Zfinx 软件使用整数加载和存储来从内存中传输浮点值。寄存器之间的传输使用整数算术或浮点符号注入指令。
====
这些 F 扩展指令的 Zfinx 变体具有相同的语义，只是每当这样的指令访问 `f` 寄存器时，它会改为访问具有相同编号的 `x` 寄存器。

Zfinx 扩展依赖于"Zicsr"扩展来进行控制和状态寄存器访问。

=== 较窄值的处理

宽度为 _w_ latexmath:[$<$] XLEN 位的浮点操作数占据 `x` 寄存器的位 _w_-1:0。对 _w_ 位操作数进行的浮点运算会忽略操作数位 XLEN-1: _w_。

产生 _w_ latexmath:[$<$] XLEN 位结果的浮点运算会用位 _w_-1（符号位）的副本填充位 XLEN-1: _w_。

[NOTE]
====
`f` 寄存器中采用的 NaN-boxing 方案旨在有效支持重编码的浮点格式。然而，对于 Zfinx 来说，重编码不太实用，因为相同的寄存器同时保存浮点和整数操作数。因此，对 NaN-boxing 的需求减少了。

在 RV64 `x` 寄存器中保存 32 位浮点数时对其进行符号扩展与现有的 RV64 调用约定兼容，该约定在 `x` 寄存器中传递 32 位浮点值时未定义位 63-32。为了保持体系结构的规律性，我们将此模式扩展到 RV32 和 RV64 中的 16 位浮点数。
====
=== Zdinx

Zdinx 扩展提供了类似的双精度浮点指令。Zdinx 扩展依赖于 Zfinx 扩展。

Zdinx 扩展添加了 D 扩展添加的所有指令，_除了_传输指令 FLD、FSD、FMV.D.X、FMV.X.D、C.FLD[SP] 和 C.FSD[SP]。

这些 D 扩展指令的 Zdinx 变体具有相同的语义，只是每当这样的指令访问 `f` 寄存器时，它会改为访问具有相同编号的 `x` 寄存器。

=== 较宽值的处理

RV32Zdinx 中的双精度操作数保存在对齐的 `x` 寄存器对中，即寄存器号必须是偶数。对双宽度浮点操作数使用未对齐（奇数编号）的寄存器是_保留_的。

无论字节序如何，编号较低的寄存器保存低位，编号较高的寄存器保存高位：例如，RV32Zdinx 中双精度操作数的位 31:0 可能保存在寄存器 `x14` 中，该操作数的位 63:32 保存在 `x15` 中。

当将双宽度浮点结果写入 `x0` 时，整个写入无效：例如，对于 RV32Zdinx，将双精度结果写入 `x0` 不会导致写入 `x1`。

当 `x0` 用作双宽度浮点操作数时，整个操作数为零，即不访问 `x1`。

[NOTE]
====
加载对和存储对指令包含在一个单独的扩展中（请参阅 <<sec:zilsd,RV32 的加载/存储对扩展>>）。如果此扩展不可用，则在 RV32Zdinx 中从内存传输或向内存传输双精度操作数需要两次加载或存储。然而，寄存器移动只需要一个 FSGNJ.D 指令。
====
=== Zhinx

Zhinx 扩展提供了类似的半精度浮点指令。Zhinx 扩展依赖于 Zfinx 扩展。

Zhinx 扩展添加了 Zfh 扩展添加的所有指令，_除了_传输指令 FLH、FSH、FMV.H.X 和 FMV.X.H。

这些 Zfh 扩展指令的 Zhinx 变体具有相同的语义，只是每当这样的指令访问 `f` 寄存器时，它会改为访问具有相同编号的 `x` 寄存器。

=== Zhinxmin

Zhinxmin 扩展为在 `x` 寄存器上操作的 16 位半精度浮点指令提供了最小支持。Zhinxmin 扩展依赖于 Zfinx 扩展。

Zhinxmin 扩展包括 Zhinx 扩展中的以下指令：FCVT.S.H 和 FCVT.H.S。如果存在 Zdinx 扩展，则还包括 FCVT.D.H 和 FCVT.H.D 指令。
[NOTE]
====
将来，可以类似于 RV32Zdinx 定义 RV64Zqinx 四精度扩展。也可以定义 RV32Zqinx 扩展，但这需要四寄存器组。
====
=== 特权体系结构影响

在第二卷中定义的标准特权体系结构中，如果实现了 Zfinx 扩展，则 `mstatus` 字段 FS 将硬连线为 0，并且 FS 不再影响浮点指令或 `fcsr` 访问的陷阱行为。

当实现 Zfinx 扩展时，`misa` 位 F、D 和 Q 将硬连线为 0。
[NOTE]
====
将来可能会使用一种可发现性机制来探测 Zfinx、Zhinx 和 Zdinx 扩展的存在。
====