[[zifencei]]
== "Zifencei"指令获取栅栏扩展，版本 2.0
本章定义了"Zifencei"扩展，其中包括 FENCE.I 指令，该指令在对指令内存的写入和同一 hart 上的指令获取之间提供显式同步。目前，该指令是确保对 hart 可见的存储也将对其指令获取可见的唯一标准机制。
(((存储指令字，未包括在内)))

[NOTE]
====
我们考虑过但未包括像 cite:[majc] 中那样的"存储指令字"指令。JIT 编译器可以在单个 FENCE.I 之前生成大量的指令轨迹，并通过将翻译后的指令写入已知不在 I-cache 中的内存区域来分摊任何指令缓存窥探/无效开销。
====
'''''
[NOTE]
====
FENCE.I 指令旨在支持各种各样的实现。一个简单的实现可以在执行 FENCE.I 时刷新本地指令缓存和指令流水线。一个更复杂的实现可能在每次数据（指令）缓存未命中时窥探指令（数据）缓存，或者使用一个包容性的统一私有 L2 缓存，在本地存储指令正在写入主指令缓存中的行时使其无效。如果指令和数据缓存以这种方式保持一致，或者如果内存系统仅由非缓存 RAM 组成，那么在 FENCE.I 处只需要刷新获取流水线。

FENCE.I 指令以前是基本 I 指令集的一部分。尽管在撰写本文时，它仍然是维护指令获取一致性的唯一标准方法，但有两个主要问题促使将其移出强制性基础。

首先，人们已经认识到，在某些系统上，FENCE.I 的实现成本会很高，并且内存模型任务组正在讨论替代机制。特别是，对于具有非一致性指令缓存和非一致性数据缓存的设计，或者指令缓存重新填充不窥探一致性数据缓存的设计，在遇到 FENCE.I 指令时必须完全刷新两个缓存。当在统一缓存或外部内存系统前面有多级 I 和 D 缓存时，这个问题会更加严重。

其次，该指令的功能不足以在类 Unix 操作系统环境中的用户级别使用。FENCE.I 仅同步本地 hart，并且操作系统可以在 FENCE.I 之后将用户 hart 重新调度到不同的物理 hart。这将要求操作系统在每次上下文迁移中执行一个额外的 FENCE.I。因此，标准 Linux ABI 已从用户级别中删除了 FENCE.I，现在需要一个系统调用来维护指令获取一致性，这使得操作系统可以最大限度地减少当前系统上所需的 FENCE.I 执行次数，并为未来改进的指令获取一致性机制提供前向兼容性。

正在讨论的未来指令获取一致性方法包括提供更受限制的 FENCE.I 版本，该版本仅针对 _rs1_ 中指定的给定地址，和/或允许软件使用依赖于机器模式缓存维护操作的 ABI。
====

include::images/wavedrom/zifencei-ff.edn[]
[[zifencei-ff]]
//.FENCE.I 指令
(((FENCE.I, 同步)))

FENCE.I 指令用于同步指令和数据流。RISC-V 不保证对指令内存的存储将对 RISC-V hart 上的指令获取可见，直到该 hart 执行 FENCE.I 指令。FENCE.I 指令确保 RISC-V hart 上的后续指令获取将看到对同一 RISC-V hart 已经可见的任何先前数据存储。FENCE.I _不_确保其他 RISC-V hart 的指令获取将观察到多处理器系统中本地 hart 的存储。为了使对指令内存的存储对所有 RISC-V hart 可见，写入 hart 还必须在请求所有远程 RISC-V hart 执行 FENCE.I 之前执行数据 FENCE。

FENCE.I 指令中的未使用字段 _funct12_、_rs1_ 和 _rd_ 保留用于未来扩展中的更细粒度的栅栏。为了前向兼容性，基本实现应忽略这些字段，标准软件应将这些字段置零。
(((FENCE.I, 更细粒度)))
(((FENCE.I, 前向兼容性)))

[NOTE]
====
因为 FENCE.I 仅对 hart 自己的指令获取进行排序，所以应用程序代码只有在应用程序线程不会迁移到不同 hart 的情况下才应依赖 FENCE.I。EEI 可以为高效的多处理器指令流同步提供机制。
====