[[chap:zihintntl]]
== "Zihintntl"非临时局部性提示扩展，版本 1.0

NTL 指令是 HINT，表示紧随其后的指令（以下称为"目标指令"）的显式内存访问表现出较差的时间局部性。NTL 指令不会改变体系结构状态，也不会改变目标指令的体系结构可见效果。提供了四种变体：

NTL.P1 指令表示目标指令在内存层次结构中最内层私有缓存的容量内不表现出时间局部性。NTL.P1 编码为 ADD _x0, x0, x2_。

NTL.PALL 指令表示目标指令在内存层次结构中任何级别的私有缓存的容量内都不表现出时间局部性。NTL.PALL 编码为 ADD _x0, x0, x3_。

NTL.S1 指令表示目标指令在内存层次结构中最内层共享缓存的容量内不表现出时间局部性。NTL.S1 编码为 ADD _x0, x0, x4_。

NTL.ALL 指令表示目标指令在内存层次结构中任何级别的缓存的容量内都不表现出时间局部性。NTL.ALL 编码为 ADD _x0, x0, x5_。

[NOTE]
====
NTL 指令可用于在流式传输数据或遍历大型数据结构时避免缓存污染，或减少生产者-消费者交互中的延迟。

微体系结构可以使用 NTL 指令来通知缓存替换策略，或决定分配到哪个缓存，或完全避免缓存分配。例如，NTL.P1 可能表示实现不应在私有 L1 缓存中分配行，而应在 L2（无论是私有还是共享）中分配。在另一个实现中，NTL.P1 可能会在 L1 中分配行，但处于最近最少使用的状态。

NTL.ALL 通常会通知实现不要在缓存层次结构中的任何位置进行分配。程序员应将 NTL.ALL 用于没有可利用的时间局部性的访问。

与任何 HINT 一样，这些指令可以被自由忽略。因此，尽管它们是根据基于缓存的内存层次结构来描述的，但它们并不强制要求提供缓存。

某些实现可能会对某些内存访问遵守这些 HINT，而对其他内存访问则不遵守：例如，通过在 L1 中以独占状态获取缓存行来实现 LR/SC 的实现可能会忽略 LR 和 SC 上的 NTL 指令，但可能会遵守 AMO 和常规加载和存储的 NTL 指令。
====

<<ntl-portable>> 列出了几个软件用例以及_可移植_软件（即未针对任何特定实现的内存层次结构进行调整的软件）在每种情况下应使用的推荐 NTL 变体。

[[ntl-portable]]
.可移植软件在各种场景中使用的推荐 NTL 变体。
[%autowidth,float="center",align="center",cols="<,<",options="header",]
|===
|场景 |推荐的 NTL 变体
|访问大小介于 和 之间的工作集 |NTL.P1
|访问大小介于 和 之间的工作集 |NTL.PALL
|访问大小大于 的工作集 |NTL.S1
|没有可利用的时间局部性的访问（例如，流式传输） |NTL.ALL
|访问有争议的同步变量 |NTL.PALL
|===

[NOTE]
====
<<ntl-portable>> 中列出的工作集大小并非旨在限制实现者的缓存大小决策。
缓存大小在不同实现之间显然会有所不同，因此软件编写者只应将这些工作集大小作为粗略的指导方针。
====

<<ntl>> 列出了几个示例内存层次结构，并建议每个 NTL 变体如何映射到每个缓存级别。该表还建议了实现调整的软件应使用哪个 NTL 变体来避免在特定缓存级别进行分配。例如，对于具有私有 L1 和共享 L2 的系统，建议 NTL.P1 和 NTL.PALL 表示 L1 无法利用时间局部性，而 NTL.S1 和 NTL.ALL 表示 L2 无法利用时间局部性。此外，为此类系统调整的软件应使用 NTL.P1 来表示 L1 无法利用的时间局部性，或应使用 NTL.ALL 来表示 L2 无法利用的时间局部性。

如果提供了 C 扩展，则还提供了这些 HINT 的压缩变体：C.NTL.P1 编码为 C.ADD _x0, x2_；C.NTL.PALL 编码为 C.ADD _x0, x3_；C.NTL.S1 编码为 C.ADD _x0, x4_；C.NTL.ALL 编码为 C.ADD _x0, x5_。

NTL 指令影响除 Zicbom 扩展中的缓存管理指令之外的所有内存访问指令。

[NOTE]
====
在撰写本文时，此规则没有其他例外，因此 NTL 指令影响基本 ISA 和 A、F、D、Q、C 和 V 标准扩展中定义的所有内存访问指令，以及第二卷中虚拟机管理程序扩展中定义的那些指令。

NTL 指令可以影响除 Zicbom 扩展中的缓存管理操作之外的缓存管理操作。例如，NTL.PALL 后跟 CBO.ZERO 可能表示该行应在 L3 中分配并清零，但不在 L1 或 L2 中分配。
====

<<<

[[ntl]]
[%autowidth,float="center",align="center",cols="<,^,^,^,^,^,^,^,^",options="header"]
.NTL 变体到各种内存层次结构的映射。
|===
| 内存层次结构 4+| NTL 变体到实际缓存级别的推荐映射 4+| 用于显式缓存管理的推荐 NTL 变体
|
|P1 |PALL |S1 |ALL
|L1 |L2 |L3 |L4/L5
 9+^| 常见场景
| 无缓存 4+|-- 4+|无
|仅私有 L1 |L1 |L1 |L1 |L1| ALL |--- |--- |---
|私有 L1；共享 L2 |L1  |L1  |L2  |L2 |P1|ALL|---|---
|私有 L1；共享 L2/L3 |L1 | L1 | L2 | L3 |P1  |S1   |ALL |---
|私有 L1/L2 |L1  |L2  |L2  |L2 | P1  |ALL  |--- |---
|私有 L1/L2；共享 L3 |L1 | L2 | L3 | L3 | P1 | PALL| ALL |---
|私有 L1/L2；共享 L3/L4 | L1 | L2|  L3 | L4 | P1 | PALL | S1 | ALL
 9+^| 不常见场景
|私有 L1/L2/L3；共享 L4 | L1 | L3 |L4 |L4 |P1 |P1 |PALL |ALL
|私有 L1；共享 L2/L3/L4 |L1 | L1 |L2 |L4 |P1 |S1 |ALL |ALL
|私有 L1/L2；共享 L3/L4/L5  |L1 | L2 | L3 | L5 |P1 | PALL |S1 |ALL
|私有 L1/L2/L3；共享 L4/L5  |L1 |L3 |L4 |L5 |P1 |P1 |PALL |ALL
|===

当 NTL 指令应用于 Zicbop 扩展中的预取提示时，它表示应将缓存行预取到比 NTL 指定的级别更_外层_的缓存中。

[NOTE]
====
例如，在具有私有 L1 和共享 L2 的系统中，NTL.P1 后跟 PREFETCH.R 可能会以读取意图预取到 L2 中。

要预取到最内层的缓存中，请不要在预取指令前加上 NTL 指令。

在某些系统中，NTL.ALL 后跟预取指令可能会预取到内存控制器内部的缓存或预取缓冲区中。
====

不鼓励软件在 NTL 指令后跟不显式访问内存的指令。不遵守此建议可能会降低性能，但不会产生其他体系结构可见的影响。

如果在目标指令上发生陷阱，则不鼓励实现将 NTL 应用于陷阱处理程序中的第一条指令。相反，建议实现在这种情况下忽略 HINT。

[NOTE]
====
如果在 NTL 指令及其目标指令的执行之间发生中断，则执行通常将在目标指令处恢复。NTL 指令未重新执行不会改变程序的语义。

某些实现可能更愿意在看到目标指令之前不处理 NTL 指令（例如，以便 NTL 可以与其修改的内存访问融合）。此类实现可能更愿意在 NTL 之前而不是在 NTL 和内存访问之间接受中断。
====
'''''
[NOTE]
====
由于 NTL 指令被编码为 ADD，因此它们可以在 LR/SC 循环中使用而不会使前向进度保证无效。但是，由于在 LR/SC 循环中使用其他加载和存储_确实_会使前向进度保证无效，因此在此类循环中使用 NTL 的唯一原因是修改 LR 或 SC。
====