[[zimop]]
== “Zimop”——可能操作扩展，版本 1.0

本章定义了“Zimop”扩展，它引入了_可能操作_（MOP）指令的概念。MOP 最初被定义为简单地将零写入 `x[rd]`，但被设计为可由后续扩展重新定义以执行其他操作。
Zimop 扩展为 40 个 MOP 定义了一个编码空间。

[NOTE]
====
有时需要定义指令集扩展，其指令在未实现该扩展时不会引发非法指令异常，而是不执行任何有用的操作（除了写入 `x[rd]`）。
例如，具有控制流完整性检查的程序可以在没有相应扩展的实现上正确执行，前提是这些检查被简单地忽略。将这些检查实现为 MOP 允许相同的程序在有或没有相应扩展的实现上运行。

尽管在某些方面与 HINT 类似，但 MOP 不能编码为 HINT，因为与 HINT 不同，MOP 允许改变体系结构状态。

由于 MOP 可能被后续扩展重新定义，因此标准软件不应执行 MOP，除非它有意针对已重新定义该 MOP 的扩展。
====

Zimop 扩展定义了 32 个名为 MOP.R.__n__ 的 MOP 指令，其中 __n__ 是一个介于 0 和 31 之间的整数（含）。
除非被另一个扩展重新定义，否则这些指令只是将 0 写入 `x[rd]`。它们的编码允许未来的扩展将它们定义为读取 `x[rs1]` 以及写入 `x[rd]`。

include::images/wavedrom/mop-r.edn[]
[[mop-r]]

Zimop 扩展还定义了 8 个名为 MOP.RR.__n__ 的 MOP 指令，其中 __n__ 是一个介于 0 和 7 之间的整数（含）。
除非被另一个扩展重新定义，否则这些指令只是将 0 写入 `x[rd]`。它们的编码允许未来的扩展将它们定义为读取 `x[rs1]` 和 `x[rs2]` 以及写入 `x[rd]`。

include::images/wavedrom/mop-rr.edn[]
[[mop-rr]]

注意：MOP.R.__n__ 的推荐汇编语法是 MOP.R.__n__ rd, rs1，任何 `x` 寄存器说明符对任一参数都有效。同样，对于 MOP.RR.__n__，推荐的语法是 MOP.RR.__n__ rd, rs1, rs2。
重新定义 MOP 的扩展可以定义备用汇编助记符。

注意：这些 MOP 部分编码在 SYSTEM 主操作码中，因为预计它们的行为将由特权 CSR 状态调节。

注意：这些 MOP 被定义为将零写入 `x[rd]`，而不是不执行任何操作，以简化指令解码并允许通过对结果的零性进行分支来测试功能的存在。

Zimop 扩展中定义的 MOP 不带有从 `x[rs1]` 或 `x[rs2]` 到 `x[rd]` 的语法依赖性，尽管重新定义 MOP 的扩展可能会施加这样的要求。

注意：不带有语法依赖性可以减轻直接实现读取 `x[rs1]` 和 `x[rs2]` 的负担。

=== “Zcmop”压缩可能操作扩展，版本 1.0

本节定义了“Zcmop”扩展，它定义了八个名为 C.MOP.__n__ 的 16 位 MOP 指令，其中 __n__ 是一个介于 1 和 15 之间的奇数（含）。C.MOP.__n__ 编码在对应于 C.LUI x__n__, 0 的保留编码空间中，如 <<tab:c-mop>> 所示。
与 Zimop 扩展中定义的 MOP 不同，C.MOP.__n__ 指令被定义为_不_写入任何寄存器。
它们的编码允许未来的扩展将它们定义为读取寄存器 `x[__n__]`。

Zcmop 扩展依赖于 Zca 扩展。

include::images/wavedrom/c-mop.edn[]
[[c-mop]]

注意：合适的 16 位编码空间非常少。选择此空间是因为它在 `rd`/`rs1` 字段方面已经具有不寻常的行为——当该字段包含 `x2` 时，它编码 `c.addi16sp`——因此对于大多数目的来说价值较低。

[[tab:c-mop]]
.C.MOP.__n__ 指令编码。

|===
|助记符 | 编码           | 可重新定义以读取寄存器

|C.MOP.1  | `0110000010000001` | `x1`
|C.MOP.3  | `0110000110000001` | `x3`
|C.MOP.5  | `0110001010000001` | `x5`
|C.MOP.7  | `0110001110000001` | `x7`
|C.MOP.9  | `0110010010000001` | `x9`
|C.MOP.11 | `0110010110000001` | `x11`
|C.MOP.13 | `0110011010000001` | `x13`
|C.MOP.15 | `0110011110000001` | `x15`
|===

注意：C.MOP.__n__ 的推荐汇编语法只是空元 C.MOP.__n__。可能访问的寄存器隐式地是 `x__n__`。

注意：期望每个 Zcmop 指令都等效于某个 Zimop 指令，但扩展的选择（如果有）留给重新定义 MOP 的扩展。
注意，不写入值的 Zcmop 指令可以扩展为对 `x0` 的写入。
